force-app/main/default/objects/Filter_Set__c/Filter_Set__c.object-meta.xml
<CustomObject>
    <description>Used with the Undergrad and Graduate Advisor Portal; this object stores the filters created by users.</description>
    <label>Filter Set</label>
    <nameField>
        <label>Filter Set Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filter Sets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Set_User_Association__c/Filter_Set_User_Association__c.object-meta.xml
<CustomObject>
    <description>Used with Filter_Set__c for the Undergrad and Graduate Advisor Portal; This object stores the many-to-many mapping of which users have access to which filter sets.</description>
    <label>Filter Set User Association</label>
    <nameField>
        <label>Filter Set User Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filter Set User Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Filter_Set_User_Association__c/fields/Filter_Set__c.field-meta.xml
<CustomField>
    <fullName>Filter_Set__c</fullName>
    <description>Parent filter set.</description>
    <inlineHelpText>Parent filter set.</inlineHelpText>
    <label>Filter Set</label>
    <referenceTo>Filter_Set__c</referenceTo>
    <relationshipLabel>Filter Set User Associations</relationshipLabel>
    <relationshipName>Filter_Set_User_Associations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Filter_Set_User_Association__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Which user is this association for?</description>
    <inlineHelpText>Which user is this association for?</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Filter_Set_User_Associations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FilterSetService.cls
public inherited sharing class FilterSetService {
    public static void checkOwnerBeforeRename(List<Filter_Set__c> newList, Map<Id, Filter_Set__c> oldMap) {
        for (Filter_Set__c filterSet : newList) {
            Filter_Set__c oldFilterSet = oldMap.get(filterSet.Id);

            if (RecordHelper.hasNewOrChangedField(filterSet, oldFilterSet, Filter_Set__c.Name)) {
                // Only allowed to rename if you own it or are a system admin
                if (
                    filterSet.OwnerId != UserInfo.getUserId() &&
                    !ProfileHelper.currentUserHasProfile('System Administrator')
                ) {
                    filterSet.addError('You do not own this filter set and are not allowed to rename it');
                }
            }
        }
    }

    public static void checkUniqueName(List<Filter_Set__c> newList) {
        Map<Id, Set<String>> userIdToNames = new Map<Id, Set<String>>();

        Set<Id> ownerIds = new Set<Id>();
        Set<Id> filterSetIds = new Set<Id>();
        for (Filter_Set__c fs : newList) {
            ownerIds.add(fs.OwnerId);
            filterSetIds.add(fs.Id);
        }

        // Get list of names per user
        for (Filter_Set__c fs : [
            SELECT Id, Name, OwnerId
            FROM Filter_Set__c
            WHERE OwnerId IN :ownerIds AND Id NOT IN :filterSetIds
        ]) {
            if (!userIdToNames.containsKey(fs.OwnerId))
                userIdToNames.put(fs.OwnerId, new Set<String>());
            userIdToNames.get(fs.OwnerId).add(fs.Name);
        }

        // Check for duplicates
        for (Filter_Set__c fs : newList) {
            Set<String> existingNames = userIdToNames.get(fs.OwnerId);
            if (existingNames != null && existingNames.contains(fs.Name))
                fs.addError('Filter Names must be unique. This name matches an existing filter set that you own.');
        }
    }

    public static void createFSUAForOwners(List<Filter_Set__c> newList) {
        List<Filter_Set_User_Association__c> fsuas = new List<Filter_Set_User_Association__c>();
        for (Filter_Set__c fs : newList)
            fsuas.add(new Filter_Set_User_Association__c(User__c = fs.OwnerId, Filter_Set__c = fs.Id));
        insert fsuas;
    }
}