force-app/main/default/objects/Contact_Tag__c/Contact_Tag__c.object-meta.xml
<CustomObject>
    <description>The object provides information on the tags that are associated with contact.</description>
    <label>Contact Tag</label>
    <nameField>
        <label>Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact_Tag__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is a Look-up to Tag object.</description>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Contact Tags</relationshipLabel>
    <relationshipName>Contact_Tags</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>[Alteryx/Manual] - Provides list on the tag that are available to apply to Contacts and other objects.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/ObjectTaggingService.cls
public with sharing class ObjectTaggingService {

    private Map<Id, Contact> contactNameMap {
        get {
            if (contactNameMap == null) {
                contactNameMap = new Map<Id, Contact>();
                
                if (!contactTagId.isEmpty()) {
                    for (Contact ct : [
                        SELECT Id, FirstName, LastName
                        FROM Contact
                        WHERE Id IN :contactTagId
                    ]) {
                        contactNameMap.put(ct.Id, ct);
                    }
                }
            }
            
            return contactNameMap;
        }
        
        set;
    }

    private Map<Id, Tag__c> tagMap {
        get {
            if (tagMap == null) {
                tagMap = new Map<Id, Tag__c>();
                
                if (!contactTagId.isEmpty()) {
                    for (Tag__c t : [
                        SELECT Id,Name
                        FROM Tag__c
                        WHERE Id IN :tagId
                    ]) {
                        tagMap.put(t.Id, t);
                    }
                }
            }
            
            return tagMap;
        }
        
        set;
    }


    public ObjectTaggingService() {

    }


    private void updateName(Contact_Tag__c con) {
        
        String contactTagName = ((!contactNameMap.isEmpty() && (!String.isBlank(con.Contact__c) && contactNameMap.containsKey(con.Contact__c) && !String.isBlank(contactNameMap.get(con.Contact__c).FirstName))? contactNameMap.get(con.Contact__c).FirstName : '')
                +''
                +(!contactNameMap.isEmpty() && (!String.isBlank(con.Contact__c) && contactNameMap.containsKey(con.Contact__c) && !String.isBlank(contactNameMap.get(con.Contact__c).LastName)) ? contactNameMap.get(con.Contact__c).LastName : '')
                +' - '
                +(!tagMap.isEmpty() && (!String.isBlank(con.Tag__c) && tagMap.containsKey(con.Tag__c))? tagMap.get(con.Tag__c).Name: '')
                +' - '
                +datetime.now());
        
        if(con != null)
        {
            con.Name = contactTagName.length() >= 80 ? contactTagName.substring(0,80):contactTagName;
        }
        
    }
}