force-app/main/default/objects/AKB_Article_Feedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Author__c</fullName>
        <description>The user who created the article.</description>
        <label>Article Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Id__c</fullName>
        <description>The ID of the article the feedback is coming in on.</description>
        <label>Article Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Number__c</fullName>
        <description>The article number.</description>
        <label>Article Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Article_Title__c</fullName>
        <description>The title of the article.</description>
        <label>Article Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comments on ways to improve article.</description>
        <label>Comments</label>
        <length>7000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The contact that rated the article.</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AKB Article Feedback</relationshipLabel>
        <relationshipName>AKB_Article_Feedback</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Functional_Group__c</fullName>
        <description>The Functional Group for the Article</description>
        <label>Functional Group</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Helpful__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Was the article helpful?</description>
        <label>Helpful?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Session_ID__c</fullName>
        <description>The session id for the current user.</description>
        <label>Session ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>The Article Type (FAQ, How To, Informational, CAP)</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>Custom Object to provide feedback on an AKB Article.</description>
    <label>AKB Article Feedback</label>
    <nameField>
        <displayFormat>AKB-{000000}</displayFormat>
        <label>AKB Article Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AKB Article Feedback</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Functional_Group__c</fullName>
        <description>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.</description>
        <inlineHelpText>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.</inlineHelpText>
        <label>Functional Group</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Status</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Academic Partnerships</fullName>
                </value>
                <value>
                    <fullName>Academic Transfer Credit Solutions</fullName>
                </value>
                <value>
                    <fullName>Access ASU Outreach</fullName>
                </value>
                <value>
                    <fullName>Admission Services</fullName>
                </value>
                <value>
                    <fullName>American Indian Student Support Services</fullName>
                </value>
                <value>
                    <fullName>ASU Advisor Outreach</fullName>
                </value>
                <value>
                    <fullName>ASU Coach Outreach</fullName>
                </value>
                <value>
                    <fullName>ASU Colleges at Lake Havasu</fullName>
                </value>
                <value>
                    <fullName>ASU Online</fullName>
                </value>
                <value>
                    <fullName>ASU Salesforce Support</fullName>
                </value>
                <value>
                    <fullName>ASU-USA Pathways</fullName>
                </value>
                <value>
                    <fullName>ASU Wellness</fullName>
                </value>
                <value>
                    <fullName>Biosafety</fullName>
                </value>
                <value>
                    <fullName>Blackboard UTO</fullName>
                </value>
                <value>
                    <fullName>Business</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Changemaker Central</fullName>
                </value>
                <value>
                    <fullName>CISA - UC Community Outreach</fullName>
                </value>
                <value>
                    <fullName>CLAS - Air Force ROTC</fullName>
                </value>
                <value>
                    <fullName>CLAS - AIS</fullName>
                </value>
                <value>
                    <fullName>CLAS - Army ROTC</fullName>
                </value>
                <value>
                    <fullName>CLAS - English</fullName>
                </value>
                <value>
                    <fullName>CLAS - HDSHC</fullName>
                </value>
                <value>
                    <fullName>CLAS - ISSR</fullName>
                </value>
                <value>
                    <fullName>CLAS - Navy ROTC</fullName>
                </value>
                <value>
                    <fullName>CLAS - Physics</fullName>
                </value>
                <value>
                    <fullName>CLAS - Psychology</fullName>
                </value>
                <value>
                    <fullName>CLAS - SCETL</fullName>
                </value>
                <value>
                    <fullName>CLAS - SESE</fullName>
                </value>
                <value>
                    <fullName>CLAS - SGSUP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/FAQ__kav.object
<CustomObject>
    <fields>
        <fullName>Answer__c</fullName>
        <description>Article Answer Content</description>
        <label>Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Functional_Group__c</fullName>
        <description>Group which owns and maintains the article.</description>
        <inlineHelpText>Group which owns and maintains the article.</inlineHelpText>
        <label>Functional Group</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Academic Technologies</fullName>
                </value>
                <value>
                    <fullName>Academic Transfer Credit Solutions</fullName>
                </value>
                <value>
                    <fullName>Admission Services</fullName>
                </value>
                <value>
                    <fullName>ASU Bookstore</fullName>
                </value>
                <value>
                    <fullName>ASU Online</fullName>
                </value>
                <value>
                    <fullName>Barrett Honors College</fullName>
                </value>
                <value>
                    <fullName>Career Services</fullName>
                </value>
                <value>
                    <fullName>Changemaker Central</fullName>
                </value>
                <value>
                    <fullName>Clubs &amp; Organizations</fullName>
                </value>
                <value>
                    <fullName>College of Health Solutions</fullName>
                </value>
                <value>
                    <fullName>College of Integrative Sciences and Arts</fullName>
                </value>
                <value>
                    <fullName>College of Liberal Arts and Sciences</fullName>
                </value>
                <value>
                    <fullName>College of Nursing and Health Innovation</fullName>
                </value>
                <value>
                    <fullName>College of Public Service and Community Solutions</fullName>
                </value>
                <value>
                    <fullName>Counseling Services</fullName>
                </value>
                <value>
                    <fullName>Cronkite</fullName>
                </value>
                <value>
                    <fullName>Disability Resource Center</fullName>
                </value>
                <value>
                    <fullName>EdPlus Open Scale</fullName>
                </value>
                <value>
                    <fullName>Financial Aid</fullName>
                </value>
                <value>
                    <fullName>First Year Success</fullName>
                </value>
                <value>
                    <fullName>Fraternity &amp; Sorority Life</fullName>
                </value>
                <value>
                    <fullName>Fulton Schools of Engineering</fullName>
                </value>
                <value>
                    <fullName>Graduate College</fullName>
                </value>
                <value>
                    <fullName>Health Services</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute</fullName>
                </value>
                <value>
                    <fullName>Housing</fullName>
                </value>
                <value>
                    <fullName>Int'l Students and Scholars Center</fullName>
                </value>
                <value>
                    <fullName>Internal Knowledge</fullName>
                </value>
                <value>
                    <fullName>Internal Knowledge (Finances)</fullName>
                </value>
                <value>
                    <fullName>Library Resources</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>Articles containing lists of questions and answers.</description>
    <label>FAQ</label>
    <pluralLabel>FAQ</pluralLabel>
</CustomObject>

force-app/main/default/objects/FAQ__kav/recordTypes/FAQ.recordType-meta.xml
<RecordType>
    <fullName>FAQ</fullName>
    <active>true</active>
    <label>FAQ</label>
</RecordType>

force-app/main/default/classes/AKBController.cls
/**
 * The AKBController class manages the operations related to article feedback and suggestions within the MyASUHelpController context.
 */
public without sharing class AKBController {
    private MyASUHelpController myASUHelp;
    public AKB_Article_Feedback__c feedbackHelpful { get; set; }
    public AKB_Article_Feedback__c[] feedbackGiven;
    public Case suggestAnArticle { get; set; }
    public FAQ__kav article { get; set; }
    public Contact userContact { get; set; }
    public Id articleId;
    public List<String> fixedLinks;
    public String titleKeyword;
    public String urlsJSON { get; set; }
    public String fixedLinksJSON { get; set; }
    public String articleWasHelpful { get; set; }

    /**
     * Constructor to initialize AKBController with MyASUHelpController.
     * Queries the article based on the current page's ID parameter.
     *
     * @param myASUHelp An instance of MyASUHelpController
     */
    public AKBController(MyASUHelpController myASUHelp) {
        this.myASUHelp = myASUHelp;
        userContact = myASUHelp.userContact;

        for (FAQ__kav matchedArticle : [
            SELECT
                Id,
                KnowledgeArticleId,
                Title,
                RecordTypeId,
                RecordType.Name,
                RecordType.DeveloperName,
                ArticleNumber,
                CreatedBy.Name,
                UrlName,
                IsVisibleInPkb,
                IsVisibleInApp,
                LastModifiedDate,
                Functional_Group__c,
                Answer__c
            FROM FAQ__kav
            WHERE
                KnowledgeArticleId = :ApexPages.currentPage().getParameters().get('id')
                AND RecordType.Name = 'FAQ'
                AND PublishStatus = 'Online'
                AND ValidationStatus = 'Published'
                AND IsDeleted = FALSE
                AND IsLatestVersion = TRUE
            LIMIT 1
        ]) {
            article = matchedArticle;
        }

        articleWasHelpful = '';
        feedbackHelpful = new AKB_Article_Feedback__c();
        suggestAnArticle = new Case();
    }

    /**
     * Retrieves the title keyword of the article.
     * Truncates the title to 99 characters if necessary.
     *
     * @return the title keyword
     */
    public String getTitleKeyword() {
        if (article.RecordType.Name == 'FAQ') {
            titleKeyword = article.Title;
        }
        if (titleKeyword.length() > 99) {
            titleKeyword = titleKeyword.substring(0, 99);
        }
        return titleKeyword;
    }

    /**
     * Marks the article as helpful and inserts feedback.
     * Redirects to the confirmation page.
     *
     * @return the PageReference to the confirmation page
     */
    public PageReference helpfulYes() {
        if (myASUHelp.viewingAs) {
            PageReference go = new PageReference(ApexPages.currentPage().getUrl());
            go.getParameters().put('masqScopeIdCookie', myASUHelp.masqScopeIdCookie);
            go.setRedirect(true);
            return go;
        }
        articleWasHelpful = 'yes';
        feedbackHelpful.Article_Id__c = ApexPages.currentPage().getParameters().get('id');
        feedbackHelpful.Article_Number__c = article.ArticleNumber;
        feedbackHelpful.Article_Title__c = article.Title;
        feedbackHelpful.Contact__c = userContact.Id;
        feedbackHelpful.Helpful__c = true;
        feedbackHelpful.Session_ID__c = UserInfo.getSessionId();
        feedbackHelpful.Article_Author__c = article.CreatedBy.Name;
        if (article.RecordType.Name == 'FAQ') {
            feedbackHelpful.Functional_Group__c = article.Functional_Group__c;
            feedbackHelpful.Type__c = article.RecordType.Name;
        }
        insert feedbackHelpful;
        PageReference confirmPage = new PageReference(
            '/authkb?id=' + ApexPages.currentPage().getParameters().get('id') + '&Feedback=yes'
        );
        confirmPage.setRedirect(true);
        return confirmPage;
    }

    /**
     * Marks the article as not helpful and inserts feedback.
     * Redirects to the confirmation page.
     *
     * @return the PageReference to the confirmation page
     */
    public PageReference helpfulNo() {
        if (myASUHelp.viewingAs) {
            PageReference go = new PageReference(ApexPages.currentPage().getUrl());
            go.getParameters().put('masqScopeIdCookie', myASUHelp.masqScopeIdCookie);
            go.setRedirect(true);
            return go;
        }
        feedbackHelpful.Article_Id__c = ApexPages.currentPage().getParameters().get('id');
        feedbackHelpful.Article_Number__c = article.ArticleNumber;
        feedbackHelpful.Article_Title__c = article.Title;
        feedbackHelpful.Contact__c = userContact.Id;
        feedbackHelpful.Helpful__c = false;
        feedbackHelpful.Session_ID__c = UserInfo.getSessionId();
        feedbackHelpful.Comments__c = feedbackHelpful.Comments__c;
        feedbackHelpful.Article_Author__c = article.CreatedBy.Name;
        if (article.RecordType.Name == 'FAQ') {
            feedbackHelpful.Functional_Group__c = article.Functional_Group__c;
            feedbackHelpful.Type__c = article.RecordType.Name;
        }
        insert feedbackHelpful;
        PageReference confirmPage = new PageReference(
            '/authkb?id=' + ApexPages.currentPage().getParameters().get('id') + '&Feedback=yes'
        );
        confirmPage.setRedirect(true);
        return confirmPage;
    }

    /**
     * Resets the article helpfulness status to null.
     */
    public void setArticleHelpfulNull() {
        articleWasHelpful = '';
    }

    /**
     * Sets the article helpfulness status to 'no'.
     */
    public void setArticleHelpfulNo() {
        articleWasHelpful = 'no';
    }

    /**
     * Checks if feedback is visible for the current article.
     *
     * @return true if feedback is not given yet, otherwise false
     */
    public Boolean getFeedbackVisible() {
        feedbackGiven = [
            SELECT Article_Id__c
            FROM AKB_Article_Feedback__c
            WHERE Article_Id__c = :ApexPages.currentPage().getParameters().get('id') AND Contact__c = :userContact.Id
        ];
        return (feedbackGiven.size() > 0) ? false : true;
    }

    /**
     * Changes the article links based on the provided JSON of URLs.
     * Updates the fixedLinksJSON with new links.
     */
    public void changeLink() {
        fixedLinks = new List<String>();
        List<String> urls = (List<String>) JSON.deserialize(urlsJSON, List<String>.class);
        for (String url : urls) {
            try {
                articleId = [
                    SELECT KnowledgeArticleId
                    FROM FAQ__kav
                    WHERE
                        UrlName = :url
                        AND Language = 'en_US'
                        AND RecordType.Name = 'FAQ'
                        AND ValidationStatus = 'Published'
                        AND PublishStatus = 'Online'
                        AND IsDeleted = FALSE
                        AND IsLatestVersion = TRUE
                ]
                .KnowledgeArticleId;
            } catch (Exception e) {
                articleId = null;
            }
            String newLink = '/authkb?id=' + articleId;
            fixedLinks.add(newLink);
        }
        fixedLinksJSON = JSON.serialize(fixedLinks);
    }
}