force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Is_Functional_Group_Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Functional Group Private</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Classification__c/fields/Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Queue_Id__c</fullName>
    <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
    <description>If a case with this Private functional group is assigned to a user, and that user is then deprovisioned, set the owner of the case to this Id post-deprovision.</description>
    <inlineHelpText>This is the default 18 digits queue id used by the user deprovision process when the case owner is deprovisioned and case Functional Group is Private.</inlineHelpText>
    <label>Queue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Processing_Notes__c</fullName>
        <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
        <description>Notes about the deprovision process - steps taken and errors encountered.</description>
        <inlineHelpText>Notes from the deprovision process that is triggered by checking the checkbox Deprovision_User__c.</inlineHelpText>
        <label>Processing Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BatchDeprovisionUserCase.cls
public class BatchDeprovisionUserCase implements Database.Batchable<SObject>, Database.Stateful {
    private List<Id> userToDeprovisionIds;
    private Integer totalCasesTransferred;
    private Map<Id, Integer> countTransferredPerUser;
    private Boolean errorOccurred = false;

    public BatchDeprovisionUserCase(List<Id> userToDeprovisionIds) {
        this.userToDeprovisionIds = userToDeprovisionIds;
        this.totalCasesTransferred = 0;
        this.countTransferredPerUser = new Map<Id, Integer>();
    }

    public Database.Querylocator start(Database.BatchableContext context) {
        String query = 'SELECT Id, OwnerId, CC_Functional_Group__c, CC_Functional_Group__r.Name, CC_Functional_Group__r.Queue_Id__c, CC_Functional_Group__r.Is_Functional_Group_Private__c FROM Case WHERE OwnerId IN :userToDeprovisionIds';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Case> scope) {
        List<Case> casesToUpdate = new List<Case>();

        for(Case userCase : scope) {

            if(!countTransferredPerUser.keySet().contains(userCase.OwnerId)){
                countTransferredPerUser.put(userCase.OwnerId, 0);
            }

            String deprovisionedUserId = userCase.OwnerId;
            try{
                if(userCase!= null) {
                    if(userCase.CC_Functional_Group__r.Is_Functional_Group_Private__c) {
                        userCase.OwnerId = userCase.CC_Functional_Group__r.Queue_Id__c;

                        casesToUpdate.add(userCase);

                        totalCasesTransferred++;
                        
                        countTransferredPerUser.put(deprovisionedUserId, countTransferredPerUser.get(deprovisionedUserId) + 1);
                    }
                }
            } catch (Exception e) {
                System.debug(e);
                this.errorOccurred = true;
                throw new DeprovisionUserException('Could not transfer cases. QueueId on case\'s functional group may be invalid.');
            }
        }
        update casesToUpdate;
    }

    public void finish(Database.BatchableContext context) {
        if(errorOccurred == false){
            System.debug('Successfully transferred ' + totalCasesTransferred + ' cases.');
            for(Id userId : countTransferredPerUser.keySet()){
                Integer countTransferred = countTransferredPerUser.get(userId);

                String message = 'Successfully transferred ' + countTransferred + ' cases.';
                updateProcessingNotes(userId, message);
            }
        }
    }

    private void updateProcessingNotes(Id userId, String message) {
        User deprovisionedUser = [SELECT Id, Processing_Notes__c FROM User WHERE Id = :userId];
        String processingNotes = deprovisionedUser.Processing_Notes__c + message + '\n';
        deprovisionedUser.Processing_Notes__c = processingNotes;
        update deprovisionedUser;
    }

    public class DeprovisionUserException extends Exception {
    }
}