force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Category.</description>
        <label>Case Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.CC_Functional_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Category)</relationshipLabel>
        <relationshipName>Cases_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Queue__c</fullName>
        <label>Most Recent Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web</description>
        <inlineHelpText>Where was this Case initiated?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advising Community</fullName>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>BBSS</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                    <default>true</default>
                    <label>Email</label>
                </value>
                <value>
                    <fullName>Error Logger</fullName>
                </value>
                <value>
                    <fullName>ESM</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>FC DPC</fullName>
                </value>
                <value>
                    <fullName>FC Poly</fullName>
                </value>
                <value>
                    <fullName>FC Tempe</fullName>
                </value>
                <value>
                    <fullName>FC West</fullName>
                </value>
                <value>
                    <fullName>Help Desk</fullName>
                </value>
                <value>
                    <fullName>Incoming Call</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>My ASU</fullName>
                </value>
                <value>
                    <fullName>Orientation</fullName>
                </value>
                <value>
                    <fullName>Outgoing Call</fullName>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
                <value>
                    <fullName>Resource</fullName>
                </value>
                <value>
                    <fullName>Student Profile</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>U.S. Mail</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>ASU_Advisor_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Advisor Outreach</businessProcess>
        <description>used for cases created for the Student Success Portal</description>
        <label>(Admin Only) ASU Advisor Outreach</label>
    </recordTypes>
    <recordTypes>
        <fullName>ASU_Coach_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Coach Outreach</businessProcess>
        <description>Case Record type for Cases in the Success Portal</description>
        <label>ASU Coach Outreach</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</description>
        <inlineHelpText>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to determine if an active record should be visible in the lookup fields for case.</description>
        <inlineHelpText>Used to determine if an active record should be visible in the lookup fields for case.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <label>Category</label>
    </recordTypes>
    <recordTypes>
        <fullName>Functional_Group</fullName>
        <active>true</active>
        <label>Functional Group</label>
    </recordTypes>
</CustomObject>

src/objects/Success_Pod__c.object
<CustomObject>
    <fields>
        <fullName>Committee__c</fullName>
        <description>for import of Advising Committee</description>
        <label>Committee</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:Queue.QueueName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
    <recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <description>This is a coach record type.</description>
        <label>Coach</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Recruiter_Email__c</fullName>
        <description>[??] - Recruiter Email</description>
        <label>Recruiter Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/QADefaultHandlerTest.cls
@isTest
public class QADefaultHandlerTest {
    private static final String userAlias = 'testusr';
    private static final String groupName = 'TestGroupName1';

    @TestSetup
    public static void setup() {
        User runAsUser = new User(Id = UserInfo.getUserId());

        User testUser = new User(
            FirstName = 'Test',
            LastName = 'User',
            Username = 'test.user.Emperor.Of.Byzantium@test.test',
            Email = 'test.user@test.test',
            Recruiter_Email__c = 'recruit.email@test.test',
            Alias = userAlias,
            TimeZoneSidKey = 'America/Phoenix',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            ProfileId = IDHelper.getProfileID('System Administrator'),
            LanguageLocaleKey = 'en_US'
        );
        insert testUser;

        Case_Classification__c testAdvFuncGroup = new Case_Classification__c(
            Name = 'ASU Advisor Outreach',
            RecordTypeId = IDHelper.getRecordTypeId('Case_Classification__c', 'Functional_Group'),
            Active__c = true,
            Visible__c = true
        );
        Case_Classification__c testCoachFuncGroup = new Case_Classification__c(
            Name = 'ASU Coach Outreach',
            RecordTypeId = IDHelper.getRecordTypeId('Case_Classification__c', 'Functional_Group'),
            Active__c = true,
            Visible__c = true
        );
        insert new List<Case_Classification__c>{ testAdvFuncGroup, testCoachFuncGroup };

        Case_Classification__c testAdvCategory = new Case_Classification__c(
            Name = 'Test Outreach Category',
            Parent__c = testAdvFuncGroup.Id,
            RecordTypeId = IDHelper.getRecordTypeId('Case_Classification__c', 'Category'),
            Active__c = true,
            Visible__c = true
        );
        Case_Classification__c testCoachCategory = new Case_Classification__c(
            Name = 'Test Outreach Category',
            Parent__c = testCoachFuncGroup.Id,
            RecordTypeId = IDHelper.getRecordTypeId('Case_Classification__c', 'Category'),
            Active__c = true,
            Visible__c = true
        );
        insert new List<Case_Classification__c>{ testAdvCategory, testCoachCategory };

        Group testGroup = new Group(Name = groupName, Type = 'Queue');
        insert testGroup;

        List<QueueSobject> testQueues = new List<QueueSobject>{
            new QueueSobject(QueueId = testGroup.Id, SobjectType = 'Success_Pod__c'),
            new QueueSobject(QueueId = testGroup.Id, SobjectType = 'Case')
        };
        System.runAs(runAsUser) {
            // Separate transaction to avoid mixed DML
            insert testQueues;
        }

        Success_Pod__c testPod = new Success_Pod__c(
            OwnerId = testGroup.Id,
            RecordTypeId = IDHelper.getRTID('Success_Pod__c', 'Advisor'),
            Primary_Email__c = testGroup.Name + '@test.asu.edu',
            Name = 'Test Pod 1',
            Committee__c = 'tp1'
        );
        insert testPod;

        List<Contact> testContacts = new List<Contact>();
        for (Integer i = 0; i < 5; i++) {
            testContacts.add(
                new contact(
                    FirstName = 'TestContact' + i,
                    LastName = testPod.Name,
                    Email = 'test.contact.' + i + '@email.test'
                )
            );
        }
        insert testContacts;

        Id advisorOutReachId = IDHelper.getRTID('Case', 'ASU_Advisor_Outreach');
        Id coachOutReachId = IDHelper.getRTID('Case', 'ASU_Coach_Outreach');
        List<Case> testCases = new List<Case>();
        // Advisor Case, Group owned
        testCases.add(
            new Case(
                OwnerId = testGroup.Id,
                RecordTypeId = advisorOutReachId,
                Status = 'Outreach Required',
                CC_Functional_Group__c = testAdvFuncGroup.Id,
                CC_Category__c = testAdvCategory.Id,
                Origin__c = 'Outreach',
                Subject = 'Case Bloat 1',
                Description = 'Case Bloat',
                ContactId = testContacts[0].Id
            )
        );
        // Advisor Case, User owned
        testCases.add(
            new Case(
                OwnerId = testUser.Id,
                RecordTypeId = advisorOutReachId,
                Status = 'Outreach Required',
                CC_Functional_Group__c = testAdvFuncGroup.Id,
                CC_Category__c = testAdvCategory.Id,
                Origin__c = 'Outreach',
                Subject = 'Case Bloat 2',
                Description = 'Case Bloat',
                ContactId = testContacts[1].Id,
                Most_Recent_Queue__c = testGroup.Name
            )
        );
        // Coach Case, User owned
        testCases.add(
            new Case(
                OwnerId = testUser.Id,
                RecordTypeId = coachOutReachId,
                Status = 'Outreach Required',
                CC_Functional_Group__c = testCoachFuncGroup.Id,
                CC_Category__c = testCoachCategory.Id,
                Origin__c = 'Outreach',
                Subject = 'Case Bloat 2',
                Description = 'Case Bloat',
                ContactId = testContacts[2].Id
            )
        );

        insert testCases;
    }

    @isTest
    private static void testOnInitDefaultsForCaseEmail() {
        QADefaultHandler qadh = new QADefaultHandler();
        User testUser = [SELECT Recruiter_Email__c FROM User WHERE Alias = :userAlias];
        Case testCase = [
            SELECT Id, OwnerId
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Coach_Outreach')
        ];

        // Must store as map and then use serialize/deserialize because
        // normally can't set attributes of this object
        Map<String, Object> caseEmailDefaults = new Map<String, Object>{
            'targetSObject' => new EmailMessage(),
            'contextId' => testCase.Id,
            'actionType' => 'Email',
            'actionName' => 'Case.Email',
            'fromAddressList' => new List<String>{ 'salesforce@test.com' }
        };
        QuickAction.SendEmailQuickActionDefaults defaultsSettingEmail = (QuickAction.SendEmailQuickActionDefaults) JSON.deserialize(
            JSON.serialize(caseEmailDefaults),
            QuickAction.SendEmailQuickActionDefaults.class
        );

        System.runAs(testUser) {
            Test.startTest();
            qadh.onInitDefaults(new List<QuickAction.SendEmailQuickActionDefaults>{ defaultsSettingEmail });
            Test.stopTest();
        }

        System.assertEquals(
            testUser.Recruiter_Email__c,
            ((EmailMessage) defaultsSettingEmail.getTargetSObject()).FromAddress
        );
    }

    @isTest
    private static void testOnInitDefaultsForCaseSendEmail() {
        QADefaultHandler qadh = new QADefaultHandler();
        User testUser = [SELECT Recruiter_Email__c FROM User WHERE Alias = :userAlias];
        Case testCase = [
            SELECT Id, OwnerId
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Coach_Outreach')
        ];

        // Must store as map and then use serialize/deserialize because
        // normally can't set attributes of this object
        Map<String, Object> caseEmailDefaults = new Map<String, Object>{
            'targetSObject' => new EmailMessage(),
            'contextId' => testCase.Id,
            'actionType' => 'SendEmail',
            'actionName' => 'Case.New_Send_Email',
            'fromAddressList' => new List<String>{ 'salesforce@test.com' }
        };
        QuickAction.SendEmailQuickActionDefaults defaultsSettingEmail = (QuickAction.SendEmailQuickActionDefaults) JSON.deserialize(
            JSON.serialize(caseEmailDefaults),
            QuickAction.SendEmailQuickActionDefaults.class
        );

        System.runAs(testUser) {
            Test.startTest();
            qadh.onInitDefaults(new List<QuickAction.SendEmailQuickActionDefaults>{ defaultsSettingEmail });
            Test.stopTest();
        }

        System.assertEquals(
            testUser.Recruiter_Email__c,
            ((EmailMessage) defaultsSettingEmail.getTargetSObject()).FromAddress
        );
    }

    @isTest
    private static void testGetEmailFromAddressGroupAdvisorCase() {
        QADefaultHandler qadh = new QADefaultHandler();
        EmailMessage em = new EmailMessage();
        Case testCase = [
            SELECT Id, OwnerId
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Advisor_Outreach') AND Owner.Name = :groupName
        ];
        Success_Pod__c testPod = [SELECT Primary_Email__c FROM Success_Pod__c WHERE OwnerId = :testCase.OwnerId];

        Test.startTest();
        qadh.setEmailFromAndToAddress(testCase.Id, em);
        Test.stopTest();

        System.assertEquals(testPod.Primary_Email__c, em.FromAddress);
    }

    @isTest
    private static void testGetEmailFromAddressUserAdvisorCase() {
        QADefaultHandler qadh = new QADefaultHandler();
        EmailMessage em = new EmailMessage();
        Case testCase = [
            SELECT Id, Most_Recent_Queue__c
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Advisor_Outreach') AND Owner.Alias = :userAlias
        ];
        Success_Pod__c testPod = [
            SELECT Primary_Email__c
            FROM Success_Pod__c
            WHERE Owner_Name__c = :testCase.Most_Recent_Queue__c
        ];

        Test.startTest();
        qadh.setEmailFromAndToAddress(testCase.Id, em);
        Test.stopTest();

        System.assertEquals(testPod.Primary_Email__c, em.FromAddress);
    }

    @isTest
    private static void testGetEmailFromAddressCoachCase() {
        QADefaultHandler qadh = new QADefaultHandler();
        EmailMessage em = new EmailMessage();
        User testUser = [SELECT Recruiter_Email__c FROM User WHERE Alias = :userAlias];
        Case testCase = [
            SELECT Id, Most_Recent_Queue__c
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Coach_Outreach')
        ];

        System.runAs(testUser) {
            Test.startTest();
            qadh.setEmailFromAndToAddress(testCase.Id, em);
            Test.stopTest();
        }

        System.assertEquals(testUser.Recruiter_Email__c, em.FromAddress);
    }

    @isTest
    private static void testNullCcAddress() {
        QADefaultHandler qadh = new QADefaultHandler();
        EmailMessage em = new EmailMessage();
        User testUser = [SELECT Recruiter_Email__c FROM User WHERE Alias = :userAlias];
        Case testCase = [
            SELECT Id, Most_Recent_Queue__c
            FROM Case
            WHERE RecordTypeId = :IDHelper.getRTID('Case', 'ASU_Coach_Outreach')
        ];

        em.CcAddress = testUser.Recruiter_Email__c;
        System.runAs(testUser) {
            Test.startTest();
            qadh.setEmailFromAndToAddress(testCase.Id, em);
            Test.stopTest();
        }

        System.assertEquals(null, em.CcAddress);
    }

    @isTest
    private static void testIsAdvisorCase() {
        QADefaultHandler qadh = new QADefaultHandler();
        Case advisorCase = new Case(
            RecordTypeId = IDHelper.getRTID('Case', 'ASU_Advisor_Outreach'),
            Subject = 'Advisor Case',
            Description = 'Advisor Case'
        );
        Case notAdvisorCase = new Case(
            RecordTypeId = IDHelper.getRTID('Case', 'ASU_Coach_Outreach'),
            Subject = 'Not Advisor Case',
            Description = 'Not Advisor Case'
        );

        System.assert(qadh.isAdvisorCase(advisorCase));
        System.assert(!qadh.isAdvisorCase(notAdvisorCase));
    }

    @isTest
    private static void testCaseOwnedByGroup() {
        QADefaultHandler qadh = new QADefaultHandler();
        User testUser = [SELECT Id FROM User WHERE Alias = :userAlias];
        Group testGroup = [SELECT Id FROM Group WHERE Name = :groupName];

        Case userCase = new Case(OwnerId = testUser.Id, Subject = 'User Case', Description = 'User Case');
        Case groupCase = new Case(OwnerId = testGroup.Id, Subject = 'Group Case', Description = 'Group Case');

        System.assert(!qadh.caseOwnedByGroup(userCase));
        System.assert(qadh.caseOwnedByGroup(groupCase));
    }

    @isTest
    private static void testNullContextId() {
        QADefaultHandler qadh = new QADefaultHandler();
        qadh.setEmailFromAndToAddress(null, null);
        List<Case> errorList = [SELECT Id FROM Case WHERE Origin__c = 'Error Logger'];
        System.assertEquals(1, errorList.size());
    }
}