force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Is_Functional_Group_Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Functional Group Private</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Classification__c/fields/Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Queue_Id__c</fullName>
    <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
    <description>If a case with this Private functional group is assigned to a user, and that user is then deprovisioned, set the owner of the case to this Id post-deprovision.</description>
    <inlineHelpText>This is the default 18 digits queue id used by the user deprovision process when the case owner is deprovisioned and case Functional Group is Private.</inlineHelpText>
    <label>Queue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Processing_Notes__c</fullName>
        <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
        <description>Notes about the deprovision process - steps taken and errors encountered.</description>
        <inlineHelpText>Notes from the deprovision process that is triggered by checking the checkbox Deprovision_User__c.</inlineHelpText>
        <label>Processing Notes</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/UserDeprovisionCaseTransferBatch.cls
public class UserDeprovisionCaseTransferBatch implements Database.Batchable<SObject>, Database.Stateful {
    private List<Id> userToDeprovisionIds;
    private Map<User, Boolean> userDeprovisionCapabilityMap;
    private Map<Id, User> userIdToUserMap;
    Map<Id, String> userToProcessingNotesMap;
    private Integer totalCasesTransferred;
    private Map<Id, Integer> countTransferredPerUser;

    public UserDeprovisionCaseTransferBatch(Map<User, Boolean> userDeprovisionCapabilityMap) {
        this.userDeprovisionCapabilityMap = userDeprovisionCapabilityMap;
        this.userIdToUserMap = new Map<Id, User>();
        this.userToDeprovisionIds = new List<Id>();
        this.userToProcessingNotesMap = new Map<Id, String>();
        this.countTransferredPerUser = new Map<Id, Integer>();
        this.totalCasesTransferred = 0;

        for (User userToDeprovision : userDeprovisionCapabilityMap.keySet()) {
            if (userDeprovisionCapabilityMap.get(userDeprovisioner) == true) {
                this.userToDeprovisionIds.add(userToDeprovision.Id);
            }
            this.userIdToUserMap.put(userToDeprovision.Id, userToDeprovision);
        }
    }

    public Database.Querylocator start(Database.BatchableContext context) {
        String query = 'SELECT Id, OwnerId, CC_Functional_Group__c, CC_Functional_Group__r.Name, CC_Functional_Group__r.Queue_Id__c, CC_Functional_Group__r.Is_Functional_Group_Private__c FROM Case WHERE OwnerId IN :userToDeprovisionIds';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext context, List<Case> scope) {
        List<Case> casesToUpdate = new List<Case>();

        for (Case userCase : scope) {
            if (!countTransferredPerUser.keySet().contains(userCase.OwnerId)) {
                countTransferredPerUser.put(userCase.OwnerId, 0);
            }

            String deprovisionedUserId = userCase.OwnerId;
            try {
                if (userCase != null) {
                    if (userCase.CC_Functional_Group__r.Is_Functional_Group_Private__c) {
                        userCase.OwnerId = userCase.CC_Functional_Group__r.Queue_Id__c;
                        casesToUpdate.add(userCase);
                        totalCasesTransferred++;
                        countTransferredPerUser.put(deprovisionedUserId, countTransferredPerUser.get(deprovisionedUserId) + 1);
                    }
                }
            } catch (Exception e) {
                String message = 'Exception Thrown for case ID (' + userCase.Id + ') : ' + e.getMessage();
                addToProcessingNotes(userCase.OwnerId, message)
                addToProcessingNotes(userCase.OwnerId, e.getStackTraceString());

                List<String> vars = new List<String>();

                vars.add(ErrorLogger.convertIdToJSON('deprovisionedUser.Id', userCase.OwnerId));
                ErrorLogger.ErrorLoggerQueue logQueue = new ErrorLogger.ErrorLoggerQueue(e, vars, false, true);
                System.enqueueJob(logQueue);
            }
        }
        Database.update(casesToUpdate, false);
    }

    public void finish(Database.BatchableContext context) {
        System.debug('Successfully transferred ' + totalCasesTransferred + ' cases.');
        for (Id userId : countTransferredPerUser.keySet()) {
            Integer countTransferred = countTransferredPerUser.get(userId);

            String message = 'Successfully transferred ' + countTransferred + ' cases.';
            addToProcessingNotes(userId, message);
        }

        for(Id userId : userIdToUserMap.keySet()) {
            userToProcessingNotesMap.put(userId, userIdToUserMap.get(userId).Processing_Notes__c);
        }

        UserDeprovisionerOrganizer.updateSobjectRecords('Id', userIdToUserMap.values(), userToProcessingNotes);
    }

    public void addToProcessingNotes(Id userId, String message) {
        if (userIdToUserMap.containsKey(userId)){
            User userToUpdate = userIdToUserMap.get(userId);
            String updatedProcessingNotes = userToUpdate.Processing_Notes__c + message + '\n';
            userToUpdate.Processing_Notes__c = updatedProcessingNotes;
        }
    }

    public class DeprovisionUserException extends Exception {
    }
}