force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Category.</description>
        <label>Case Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.CC_Functional_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Category)</relationshipLabel>
        <relationshipName>Cases_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Sub Category.</description>
        <label>Case Sub-Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.CC_Category__c</valueField>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Sub Category)</relationshipLabel>
        <relationshipName>Cases_Sub_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case_Classification__c.object
<CustomObject>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CaseClassificationPicklistTest.cls
@isTest
private class CaseClassificationPicklistTest {
    private static CaseClassificationPicklistService picklistService;

    @testSetup
    private static void setUpTest() {
        CaseClassificationFactory ccMaker = new CaseClassificationFactory();
        ccMaker.createAndInsertSetOfCaseClassification();
    }

    @isTest
    private static void testInitialSetUp() {
        picklistService = new CaseClassificationPicklistService();

        System.assertEquals(2, picklistService.functionalGroupOptions.size());
        System.assertEquals(1, picklistService.categoryOptions.size());
        System.assertEquals(1, picklistService.subCategoryOptions.size());
    }

    @isTest
    private static void testChangeFunctionalGroup() {
        picklistService = new CaseClassificationPicklistService();
        Map<String, Case_Classification__c> caseClassificationMap = getCaseClassificationData();
        picklistService.selectedFunctionalGroup = caseClassificationMap.get('Test Functional Group0').Id;

        System.assertEquals(2, picklistService.functionalGroupOptions.size());
        System.assertEquals(2, picklistService.categoryOptions.size());
        System.assertEquals(1, picklistService.subCategoryOptions.size());
    }

    @isTest
    private static void testChangeCategory() {
        picklistService = new CaseClassificationPicklistService();
        Map<String, Case_Classification__c> caseClassificationMap = getCaseClassificationData();
        picklistService.selectedFunctionalGroup = caseClassificationMap.get('Test Functional Group0').Id;
        picklistService.selectedCategory = caseClassificationMap.get('Test Category0').Id;

        System.assertEquals(2, picklistService.functionalGroupOptions.size());
        System.assertEquals(2, picklistService.categoryOptions.size());
        System.assertEquals(2, picklistService.subCategoryOptions.size());
    }

    @isTest
    private static void testAddDetailsToCase() {
        picklistService = new CaseClassificationPicklistService();
        CaseFactory.DefaultCase caseMaker = new CaseFactory.DefaultCase();
        Case createdCase = (Case) caseMaker.create(1)[0];

        Map<String, Case_Classification__c> caseClassificationMap = getCaseClassificationData();
        picklistService.selectedFunctionalGroup = caseClassificationMap.get('Test Functional Group0').Id;
        picklistService.selectedCategory = caseClassificationMap.get('Test Category0').Id;
        picklistService.selectedSubCategory = caseClassificationMap.get('Test Sub Category0').Id;
        picklistService.addCaseClassificationToCase(createdCase);

        System.assertEquals(createdCase.CC_Functional_Group__c, caseClassificationMap.get('Test Functional Group0').Id);
        System.assertEquals(createdCase.CC_Category__c, caseClassificationMap.get('Test Category0').Id);
        System.assertEquals(createdCase.CC_Sub_Category__c, caseClassificationMap.get('Test Sub Category0').Id);
    }

    private static Map<String, Case_Classification__c> getCaseClassificationData() {
        List<Case_Classification__c> allCaseClassification = [SELECT Id, Name FROM Case_Classification__c];

        Map<String, Case_Classification__c> nameToCC = new Map<String, Case_Classification__c>();

        for (Case_Classification__c caseClassificationToMap : allCaseClassification) {
            nameToCC.put(caseClassificationToMap.Name, caseClassificationToMap);
        }

        return nameToCC;
    }
}