force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Category.</description>
        <label>Case Category</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Parent__c</field>
                <operation>equals</operation>
                <valueField>$Source.CC_Functional_Group__c</valueField>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Category)</relationshipLabel>
        <relationshipName>Cases_Category</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web</description>
        <inlineHelpText>Where was this Case initiated?</inlineHelpText>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Advising Community</fullName>
                </value>
                <value>
                    <fullName>Automated</fullName>
                </value>
                <value>
                    <fullName>BBSS</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Clone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                    <default>true</default>
                    <label>Email</label>
                </value>
                <value>
                    <fullName>Error Logger</fullName>
                </value>
                <value>
                    <fullName>ESM</fullName>
                </value>
                <value>
                    <fullName>Fax</fullName>
                </value>
                <value>
                    <fullName>FC DPC</fullName>
                </value>
                <value>
                    <fullName>FC Poly</fullName>
                </value>
                <value>
                    <fullName>FC Tempe</fullName>
                </value>
                <value>
                    <fullName>FC West</fullName>
                </value>
                <value>
                    <fullName>Help Desk</fullName>
                </value>
                <value>
                    <fullName>Incoming Call</fullName>
                </value>
                <value>
                    <fullName>In Person</fullName>
                </value>
                <value>
                    <fullName>My ASU</fullName>
                </value>
                <value>
                    <fullName>Orientation</fullName>
                </value>
                <value>
                    <fullName>Outgoing Call</fullName>
                </value>
                <value>
                    <fullName>Outreach</fullName>
                </value>
                <value>
                    <fullName>Pitch</fullName>
                </value>
                <value>
                    <fullName>Resource</fullName>
                </value>
                <value>
                    <fullName>Student Profile</fullName>
                </value>
                <value>
                    <fullName>Text</fullName>
                </value>
                <value>
                    <fullName>U.S. Mail</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</description>
        <inlineHelpText>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <label>Category</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>ASURITE_Id__c</fullName>
        <description>[??] - ASURITE ID</description>
        <formula>Contact.ASURite_ID__c</formula>
        <label>ASURITE Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmplId__c</fullName>
        <description>[PeopleSoft] - EMPLID</description>
        <formula>Contact.EMPLID__c</formula>
        <label>EMPLID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>bomgar__Bomgar_Username__c</fullName>
        <label>Bomgar Username</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/BomgarCreateCaseUtil.cls
global class BomgarCreateCaseUtil {
    global static String createCase(bomgar__BomgarWebEvent__c bgEvent) {
        Map<String, String> dynamicFieldMap = new Map<String, String>();
        // map to store Case Classification name vs Id
        // related to Functional Group Help Desk and
        // Category records with Help Desk as parent
        map<String, Id> mapCCNameToId = new Map<String, Id>();
        for (Case_Classification__c caseClass : [
            SELECT Id, Name
            FROM Case_Classification__c
            WHERE
                Active__c = TRUE
                AND ((RecordType.Name = 'Functional Group'
                AND Name = 'Help Desk')
                OR (RecordType.Name = 'Category'
                AND Parent__r.Name = 'Help Desk'))
        ]) {
            mapCCNameToId.put(caseClass.Name, caseClass.Id);
        }

        // Handle special chars in external key
        String jsonObject = bgEvent.bomgar__ExternalKey__c.substring(5)
            .replace('\r\n', '\\r\\n')
            .replace('\n', '\\n')
            .replace('\r', '\\r')
            .replace('\t', '\\t')
            .replace('\b', '\\b')
            .replace('\f', '\\f');
        system.debug('jsonObject: ' + jsonObject);
        String.escapeSinglequotes(jsonObject);
        JSONParser parser;
        try {
            parser = JSON.createParser(jsonObject);
            while (parser.nextToken() != null) {
                if (parser.getCurrentToken() == JSONToken.FIELD_NAME) {
                    String key = parser.getText();
                    parser.nextToken();
                    String value = parser.getText();
                    dynamicFieldMap.put(key, value);
                }
            }
        } catch (Exception ex) {
            List<String> vars = new List<String>();
            vars.add(ErrorLogger.convertStringToJSON('jsonObject', jsonObject));
            ErrorLogger.log(ex, vars, false);
        }

        Contact contact = null;
        Case c = new Case();

        String emplId = dynamicFieldMap.get('employeeNumber');
        String externalKey = dynamicFieldMap.get('externalKey');
        String asurite = dynamicFieldMap.get('asuriteId');
        String description = dynamicFieldMap.get('description');
        String firstname = '';
        String lastname = '';
        Boolean error = false;
        String errorStr = '';

        // Handle ASURITE for BB chat if asurite is null.
        // (bb_asurite__ca or asurite_@ce.asu.edu)
        if (externalKey == 'BB' && asurite == '') {
            if (description.contains('ASURITE ID:')) {
                asurite = description.substring(
                    description.indexOf('ASURITE ID:') + 12,
                    description.indexOf('Full Name:')
                );

                if (asurite.contains('_')) {
                    String[] strs = asurite.split('_');

                    for (String s : strs) {
                        if (s.length() > 5 && !s.contains('@') && !s.contains('.')) {
                            asurite = s;
                        }
                    }
                }
            }
        }

        if (externalKey == 'BB' && asurite != '') {
            if (asurite.contains('_')) {
                String[] strs = asurite.split('_');

                for (String s : strs) {
                    if (s.length() > 5 && !s.contains('@') && !s.contains('.')) {
                        asurite = s;
                    }
                }
            }
        }

        List<RecordType> recordTypes = [SELECT Id FROM RecordType WHERE Name = 'ASU Service'];

        for (RecordType rt : recordTypes) {
            c.RecordTypeId = rt.Id;
        }

        // Set case values

        c.Status = 'New';
        c.Description = String.isEmpty(description) ? 'Case Created from Bomgar' : description;
        c.Priority = 'Normal';
        c.Origin__c = 'Chat';
        c.CC_Functional_Group__c = (mapCCNameToId.containsKey('Help Desk')) ? mapCCNameToId.get('Help Desk') : null;
        c.Subject = (mapCCNameToId.containsKey('Help Desk')) ? 'Help Desk' : '' + ' Live Chat';

        // Check if finance chat and route, if not default to gen
        if (externalKey == 'Finances') {
            c.CC_Category__c = (mapCCNameToId.containsKey('Finances (Help Desk)'))
                ? mapCCNameToId.get('Finances (Help Desk)')
                : null;
        } else {
            c.CC_Category__c = (mapCCNameToId.containsKey('General Help Desk'))
                ? mapCCNameToId.get('General Help Desk')
                : null;
        }

        // If contact is still null, try and find contact by asuriteId
        if (contact == null && asurite != '') {
            contact = lookupContactByASURITE(asurite);
        }

        // Lookup contact by employeeNumber
        if (contact == null && emplId != '') {
            contact = lookupContactByEmployeeId(emplId);
        }

        // Final check to see if Contact was found. If not, create one.
        if (contact != null) {
            c.ContactId = contact.Id;
        } else {
            // Handle parsing out name from description if creating a new Contact
            if (externalKey == 'BB' && description != '') {
                if (description.contains('Full Name:') && description.contains('Course Role:')) {
                    String name = description.substring(
                        description.indexOf('Full Name:') + 10,
                        description.indexOf('Course Role:')
                    );

                    name = name.trim();
                    String[] strs;

                    if (name.contains(' ')) {
                        strs = name.split(' ');

                        if (strs.size() == 2) {
                            firstname = strs[0];
                            lastname = strs[1];
                        }
                    } else {
                        firstname = name;
                    }
                }
            }

            if (asurite != '') {
                // Try to create a new Contact
                Contact newContact = new Contact();
                newContact.Email = firstname + '.' + lastname + '@asu.edu';
                newContact.Email = asurite + '@asu.edu';
                newContact.ASURite_ID__c = asurite;
                newContact.EMPLID__c = emplId;
                newContact.MailingPostalCode = '11111';

                if (lastname != '') {
                    newContact.LastName = lastname;
                } else {
                    lastname = asurite;
                    newContact.LastName = lastname;
                }

                if (firstname != '') {
                    newContact.FirstName = firstname;
                } else {
                    firstname = 'BomgarError';
                    newContact.FirstName = firstname;
                }

                insert newContact;

                // Attach new contact to case.
                c.ContactId = newContact.Id;
            } else {
                c.Reason = 'Bomgar Error';
                error = true;
            }
        }

        // On error, log all the contact info we have.
        if (error) {
            c.Description =
                c.Description +
                'UNABLE TO FIND/CREATE A ' +
                'CONTACT WITH THESE VALUES: ' +
                ' - Name: ' +
                firstname +
                ' ' +
                lastname +
                ' - ASURITE: ' +
                asurite +
                ' - EmplId: ' +
                emplId +
                ' - ' +
                errorStr;
        }

        insert c;

        return c.Id;
    }

    global static Contact lookupContactByEmployeeId(String employeeId) {
        List<Contact> contacts = [SELECT Id, ASURite_ID__c, EMPLID__c FROM Contact WHERE EMPLID__c = :employeeId];

        for (Contact contact : contacts) {
            return contact;
        }

        return null;
    }

    global static Contact lookupContactByASURITE(String asurite) {
        List<Contact> contacts = [SELECT Id, ASURite_ID__c, EMPLID__c FROM Contact WHERE ASURITE_Id__c = :asurite];

        for (Contact contact : contacts) {
            return contact;
        }

        return null;
    }

    global static User lookupUserByBomgarUsername(String bomgarUsername) {
        List<User> users = [SELECT Id FROM User WHERE bomgar__Bomgar_Username__c = :bomgarUsername];

        if (users == null) {
            throw new BomgarCreateCaseException('No Users Found for Bomgar Username[' + bomgarUsername + ']');
        }

        return users[0];
    }

    global static User lookupUserByFederationId(String bomgarUsername) {
        String federationId = bomgarUserName + '@admin.asu.edu';

        List<User> users = [SELECT Id FROM User WHERE ContactId = NULL AND FederationIdentifier = :federationId];

        if (users == null) {
            throw new BomgarCreateCaseException('No Users Found for Bomgar Username[' + bomgarUsername + ']');
        }

        return users[0];
    }

    global static Id getOwnerIdBySessionId(String sessionId) {
        List<bomgar__Participant__c> myList = [
            SELECT bomgar__Username__c
            FROM bomgar__Participant__c
            WHERE
                bomgar__IsPrimary__c = TRUE
                AND bomgar__ParticipantType__c = 'Representative'
                AND bomgar__BomgarSession__r.Id = :sessionId
        ];

        for (bomgar__Participant__c bomgarParticipant : myList) {
            if (bomgarParticipant != null && bomgarParticipant.bomgar__Username__c != null) {
                User owner = lookupUserByFederationId(bomgarParticipant.bomgar__Username__c);

                if (owner != null) {
                    return owner.Id;
                }
            }
        }

        return null;
    }

    @future(callout=true)
    global static void assignCase(String lsid, String caseId) {
        Map<String, String> parameters = new Map<String, String>();
        parameters.put('lsid', lsid);
        parameters.put('custom.external_key', caseId);

        try {
            Bomgar.BomgarAPIAccess.CallCommandAPI(Bomgar.BomgarAPIAccess.CommandType.SetSessionAttributes, parameters);
        } catch (Exception e) {
            Bomgar.BomgarAPIAccess.RecordError('BomgarCreateCaseUtil assignCase Failure', e);
        }
    }

    private class BomgarCreateCaseException extends Exception {
    }
}