force-app/main/default/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Case_Assignment_Rule__c.field-meta.xml
<CustomField>
    <fullName>Case_Assignment_Rule__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</description>
    <inlineHelpText>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</inlineHelpText>
    <label>Case Assignment Rule</label>
    <referenceTo>Case_Assignment_Rule__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case_Assignment_Rule__c.object
<CustomObject><fields>
        <fullName>Customer_Notice_Email_From_Name__c</fullName>
        <description>[??] - The "Name" associated with the Email Address used  for the notice emailed to the customer that a Case has been created.</description>
        <inlineHelpText>The "Name" associated with the Email Address used  for the notice emailed to the customer that a Case has been created.</inlineHelpText>
        <label>Customer Notice Email From Name</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Email_Address__c</fullName>
        <description>[??] - Case email address</description>
        <inlineHelpText>This Email Address is used:
1. To identify which Assignment Rule to Use (if this address is found in the "Initial Request Sent To Addresses")
2. As the "From" address for the notice emailed to the customer that a Case has been created.</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Email_Template_ID__c</fullName>
        <description>[??] - The 15 character (case sensitive) ID used to identify the Email Template used for the notice emailed to the customer that a Case has been created. You can view this ID immediatly after "...salesforce.com/" in the URL when viewing the desired Template.</description>
        <inlineHelpText>The 15 character (case sensitive) ID used to identify the Email Template used for the notice emailed to the customer that a Case has been created. You can view this ID immediatly after "...salesforce.com/" in the URL when viewing the desired Template.</inlineHelpText>
        <label>Email Template ID</label>
        <length>15</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Reply_To_Email_Address__c</fullName>
        <description>[??] - This Email Address is used as the "Reply To" address for the email that is sent to the customer when a Case has been created. If not specified, the "Email Address" field is used.</description>
        <inlineHelpText>This Email Address is used as the "Reply To" address for the email that is sent to the customer when a Case has been created. If not specified, the "Email Address" field is used.</inlineHelpText>
        <label>Reply To Email Address</label>
        <type>Email</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object used to assign case records. Criteria based on email address or association with a web form campaign record.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Case Assignment Rule</label><nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Case Assignment Rule</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Email_To_Case_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Value__c</fullName>
        <description>The value for this setting</description>
        <inlineHelpText>The value for this setting</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Contains configuration settings for the Email-to-Case handler</description>
    <label>Email To Case Configuration</label>
</CustomObject>

force-app/main/default/classes/EmailAPIService.cls
@RestResource(urlMapping='/EmailService/*')
global class EmailAPIService {
    static Map<String, String> configMap = new Map<String, String>();

    @HttpPost
    global static void sendAutoReply(String emailCaseId, String carId) {
        RestResponse res = RestContext.response;
        loadConfigurationSettings();

        // Get ReplyTo from CAR
        List<Case_Assignment_Rule__c> assignmentRule = new List<Case_Assignment_Rule__c>();
        String replyToAddress;
        String emailFromName;
        Id emailTemplateId;
        try {
            // Get required fields, ensure carId is valid
            assignmentRule = [
                SELECT
                    Email_Address__c,
                    Reply_To_Email_Address__c,
                    Customer_Notice_Email_From_Name__c,
                    Email_Template_ID__c
                FROM Case_Assignment_Rule__c
                WHERE Id = :carId
            ];
            replyToAddress = assignmentRule[0].Reply_To_Email_Address__c;
            emailFromName = assignmentRule[0].Customer_Notice_Email_From_Name__c;
            emailTemplateId = assignmentRule[0].Email_Template_ID__c;
        } catch (Exception e) {
            res.statusCode = 400;
            String errorMessage = 'Invalid carId';
            res.responseBody = blob.valueOf(buildErrorResponse(emailCaseId, carId, errorMessage));
        }

        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        if (emailTemplateId != null) {
            mail.setTemplateId(emailTemplateId);
        }
        try {
            // Ensure emailCaseId is valid, get ContactId from Case
            List<Case> emailCaseIdCheck = new List<Case>();
            emailCaseIdCheck = [SELECT Id, ContactId FROM Case WHERE Id = :emailCaseId];
            mail.setWhatId(emailCaseIdCheck[0].Id);
            mail.setTargetObjectId(emailCaseIdCheck[0].ContactId);
        } catch (Exception e) {
            res.statusCode = 400;
            String errorMessage = 'Invalid emailCaseId or associated Case was missing a valid Contact';
            res.responseBody = blob.valueOf(buildErrorResponse(emailCaseId, carId, errorMessage));
        }

        OrgWideEmailAddress oweaToUse = new OrgWideEmailAddress();
        OrgWideEmailAddress defaultOwea = getDefaultOrgWideEmailAddress();
        Boolean noOweaFound = false;

        // Find the appropriate OrgWideEmailAddress for this reply
        try {
            oweaToUse = [SELECT Id FROM OrgWideEmailAddress WHERE Address = :replyToAddress];
            mail.setOrgWideEmailAddressId(oweaToUse.Id);
        } catch (Exception e) {
            // Use context user's information if there is no default OrgWideEmailAddress configured
            if (defaultOwea == null && emailFromName != null) {
                mail.setSenderDisplayName(emailFromName);
            } else {
                mail.setOrgWideEmailAddressId(defaultOwea.Id);
            }
        }

        //Send the email
        try {
            Messaging.reserveSingleEmailCapacity(1);
            Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ mail });
        } catch (Exception e) {
            //Most likely SINGLE_EMAIL_LIMIT_EXCEEDED; catching so the transaction will continue
        }
    }

    /**
     * Get the Org Wide Email Address
     */
    global static OrgWideEmailAddress getDefaultOrgWideEmailAddress() {
        OrgWideEmailAddress oweaLookup;
        String orgWideEmailAddress = getConfigurationSetting('Default Org Wide Email Address');

        if (orgWideEmailAddress != null && orgWideEmailAddress != '') {
            List<OrgWideEmailAddress> oweaList = [
                SELECT Id, DisplayName, Address
                FROM OrgWideEmailAddress
                WHERE Address = :orgWideEmailAddress
            ];
            if (oweaList.size() > 0) {
                oweaLookup = oweaList[0];
            }
        }

        return oweaLookup;
    }

    /**
     * Get config settings
     */
    global static String getConfigurationSetting(String settingName) {
        if (configMap.containsKey(settingName)) {
            return configMap.get(settingName);
        }

        return '';
    }
    /**
     * Load config settings
     */
    global static void loadConfigurationSettings() {
        Email_To_Case_Configuration__c[] configList = [SELECT Name, Value__c FROM Email_To_Case_Configuration__c];
        if (configList.size() > 0) {
            for (Email_To_Case_Configuration__c c : configList) {
                configMap.put(c.Name, c.Value__c);
            }
        }
    }
    /**
     * Rebuild payload for output on error
     */
    global static String buildErrorResponse(String emailCaseId, String carId, String error) {
        String response = 'Error Info: ' + error + '\n';
        response += '{\n\t\"emailCaseId\": \"' + emailCaseId + '\",\n';
        response += '\t\"carId\": \"' + carId + '\"\n}';
        return response;
    }
}