force-app/main/default/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CC_Functional_Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field looks up to the Case Classification object where record type = Functional Group.</description>
        <label>Case Functional Group</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Visible__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.Active__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Cases (Functional Group)</relationshipLabel>
        <relationshipName>Cases_Functional_Group</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/Case_Assignment_Rule__c.field-meta.xml
<CustomField>
    <fullName>Case_Assignment_Rule__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</description>
    <inlineHelpText>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</inlineHelpText>
    <label>Case Assignment Rule</label>
    <referenceTo>Case_Assignment_Rule__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Ed_Plus_Org_Viewable__c.field-meta.xml
<CustomField>
    <fullName>Ed_Plus_Org_Viewable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field denote if the Ed Plus org can see this case.</description>
    <label>Ed Plus Org Viewable</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Case_Assignment_Rule__c.object
<CustomObject><fields>
        <fullName>Email_Address__c</fullName>
        <description>[??] - Case email address</description>
        <inlineHelpText>This Email Address is used:
1. To identify which Assignment Rule to Use (if this address is found in the "Initial Request Sent To Addresses")
2. As the "From" address for the notice emailed to the customer that a Case has been created.</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Reply_To_Email_Address__c</fullName>
        <description>[??] - This Email Address is used as the "Reply To" address for the email that is sent to the customer when a Case has been created. If not specified, the "Email Address" field is used.</description>
        <inlineHelpText>This Email Address is used as the "Reply To" address for the email that is sent to the customer when a Case has been created. If not specified, the "Email Address" field is used.</inlineHelpText>
        <label>Reply To Email Address</label>
        <type>Email</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object used to assign case records. Criteria based on email address or association with a web form campaign record.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Case Assignment Rule</label><nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Case Assignment Rule</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Case_Assignment_Rule__c/fields/CC_Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>CC_Functional_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case Classification Functional Group field</description>
    <inlineHelpText>Lookup to the Case Classification Functional Group field</inlineHelpText>
    <label>Case Functional Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Functional Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>CAR (Functional Group)</relationshipLabel>
    <relationshipName>Case_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Assignment_Rule__c/fields/Do_Not_Change_in_Sandbox_Refresh__c.field-meta.xml
<CustomField>
    <fullName>Do_Not_Change_in_Sandbox_Refresh__c</fullName>
    <businessOwnerGroup>Data_Owner_Salesforce_Team</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>Checkbox that denotes whether to scramble an email when doing a sandbox refresh</description>
    <inlineHelpText>If this box is checked, the corresponding CAR should not be scrambled when refreshing a sandbox.</inlineHelpText>
    <label>Do Not Change in Sandbox Refresh</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>me3hs_User_ID__c</fullName>
        <description>[eAdvisor Data Warehouse] me3 User Id in email format</description>
        <inlineHelpText>[eAdvisor Data Warehouse] me3 User Id in email format</inlineHelpText>
        <label>me3hs User ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>[import] - Birthday for the lead</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recruiting_Email__c</fullName>
        <description>[import] - Used to preserve Lead email address and to transfer to the Contact record</description>
        <label>Recruiting Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <description>[import] - Secondary email address for the lead</description>
        <label>Secondary Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sandbox_DEV__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>In DEV, set UTO team as admin, Recruitment with Leads profile, with specific users as delegated admin.</inlineHelpText>
        <label>DEV</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ObjectScrambleService.cls
public class ObjectScrambleService {
    private ObjectTypes objectType;
    public enum ObjectTypes {
        CONTACT,
        CONTACT_NO_PHONE,
        EDPLUS_CASE,
        LEAD,
        CONVERTED_LEAD,
        USER,
        CAR,
        DELETED_SILVERPOP
    }

    public ObjectScrambleService(ObjectTypes objectType) {
        this.objectType = objectType;
    }

    public String getQueryFromObject() {
        String queryToReturn;
        switch on objectType {
            when CONTACT {
                queryToReturn =
                    'SELECT Email, Corporate_Relations_Email__c, EPO_Email__c, ASU_Email__c, ' +
                    'Last_Case_Email_Used__c, Lead_Email__c, Lead_Secondary_Email__c, me3hs_User_ID__c, ' +
                    'Parent_Email__c, Personal_Email__c, Birthdate FROM Contact WHERE ' +
                    generateNotLikeSandboxDomainStatement('Email');
            }
            when CONTACT_NO_PHONE {
                queryToReturn = 'SELECT Id, HomePhone, Phone FROM Contact WHERE HomePhone = null AND Phone != null';
            }
            when EDPLUS_CASE {
                queryToReturn = 'SELECT Id FROM Case WHERE LastModifiedDate >= 2020-03-01T00:00:00Z AND (CC_Functional_Group__c = \'a240W000001jHG6\' OR CC_Functional_Group__c = \'a240W000001jHH0\' OR CC_Functional_Group__c = \'a240W000001jHG9\'  OR CC_Functional_Group__c = \'a240W000001jHG8\' OR CC_Functional_Group__c = \'a240W000001jHGB\' OR  CC_Functional_Group__c = \'a240W000001jHHr\')';
            }
            when LEAD {
                queryToReturn =
                    'SELECT Id, Date_of_Birth__c, Email, Recruiting_Email__c, Secondary_Email__c FROM LEAD WHERE ' +
                    generateNotLikeSandboxDomainStatement('Email');
            }
            when CONVERTED_LEAD {
                queryToReturn = 'SELECT Id FROM LEAD WHERE IsConverted = true';
            }
            when DELETED_SILVERPOP {
                queryToReturn = 'SELECT Id FROM ' + System.Label.SilverPopName;
            }
            when CAR {
                queryToReturn =
                    'SELECT Id, Email_Address__c, Reply_To_Email_Address__c FROM Case_Assignment_Rule__c WHERE ' +
                    generateNotLikeSandboxDomainStatement('Email_Address__c') +
                    ' AND Do_Not_Change_in_Sandbox_Refresh__c = FALSE';
            }
            when USER {
                Id sysAdminId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
                queryToReturn =
                    'SELECT Id FROM User WHERE IsActive = true AND Sandbox_DEV__c = false AND (NOT Username LIKE \'%@00dn000000091oqeay.com\') AND ProfileId <> \'' +
                    sysAdminId +
                    '\'';
            }
        }

        return queryToReturn;
    }

    public ObjectScramble getScrambleClassForObject(sObject objectToScramble) {
        ObjectScramble objectScrambler;
        switch on objectType {
            when CONTACT {
                objectScrambler = new ContactScrambler((Contact) objectToScramble);
            }
            when CONTACT_NO_PHONE {
                objectScrambler = new ContactPhoneAdder((Contact) objectToScramble);
            }
            when EDPLUS_CASE {
                objectScrambler = new CaseScrambler((Case) objectToScramble);
            }
            when LEAD {
                objectScrambler = new LeadScrambler((Lead) objectToScramble);
            }
            when CONVERTED_LEAD {
                objectScrambler = new LeadDeleter((Lead) objectToScramble);
            }
            when DELETED_SILVERPOP {
                objectScrambler = new SilverpopDeleter(objectToScramble);
            }
            when CAR {
                objectScrambler = new CarScrambler((Case_Assignment_Rule__c) objectToScramble);
            }
            when USER {
                objectScrambler = new UserScrambler((User) objectToScramble);
            }
        }

        return objectScrambler;
    }

    public String getObjectHeader() {
        String header;
        switch on objectType {
            when CONTACT {
                header =
                    'Id,Birthdate,Email,Corporate_Relations_Email__c,EPO_Email__c,ASU_Email__c,Last_Case_Email_Used__c,Lead_Email__c,' +
                    'Lead_Secondary_Email__c,me3hs_User_ID__c,Parent_Email__c,Personal_Email__c,silverpop__Silverpop_RecipientID__c\n';
            }
            when CONTACT_NO_PHONE {
                header = 'Id,HomePhone\n';
            }
            when EDPLUS_CASE {
                header = 'Id,Ed_Plus_Org_Viewable__c\n';
            }
            when LEAD {
                header = 'Id,Date_of_Birth__c,Email,Recruiting_Email__c,Secondary_Email__c,silverpop__Silverpop_RecipientID__c\n';
            }
            when CAR {
                header = 'Id,Email_Address__c,Reply_To_Email_Address__c\n';
            }
            when CONVERTED_LEAD {
                header = 'Id\n';
            }
            when DELETED_SILVERPOP {
                header = 'Id\n';
            }
            when USER {
                header = 'Id,IsActive\n';
            }
        }

        return header;
    }

    @TestVisible
    private static String generateNotLikeSandboxDomainStatement(String fieldName) {
        String sandboxDomain = Scrambler.getSandboxDomain();
        return '(NOT ' + fieldName + ' LIKE \'%.' + sandboxDomain + '\')';
    }
}