force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SuncardPhotoController.cls
public with sharing class SuncardPhotoController {
    public Contact theContact;

    public SuncardPhotoController(ApexPages.StandardController stdController) {
        this.theContact = (Contact) stdController.getRecord();

        theContact = ContactService.getContactInformation(theContact.Id);
    }

    public String getSuncardPhotoURL() {
        String suncardPhotoURL = SuncardPhotoService.getSunCardPhotoURL(theContact.ASURite_ID__c, theContact.EMPLID__c);

        return suncardPhotoURL;
    }
}