force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>me3hs_User_ID__c</fullName>
        <description>[eAdvisor Data Warehouse] me3 User Id in email format</description>
        <inlineHelpText>[eAdvisor Data Warehouse] me3 User Id in email format</inlineHelpText>
        <label>me3hs User ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <description>[import] - Birthday for the lead</description>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Recruiting_Email__c</fullName>
        <description>[import] - Used to preserve Lead email address and to transfer to the Contact record</description>
        <label>Recruiting Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Secondary_Email__c</fullName>
        <description>[import] - Secondary email address for the lead</description>
        <label>Secondary Email</label>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>Sandbox_DEV__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>In DEV, set UTO team as admin, Recruitment with Leads profile, with specific users as delegated admin.</inlineHelpText>
        <label>DEV</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ObjectScrambleServiceTest.cls
@isTest
private class ObjectScrambleServiceTest {
    @isTest
    private static void testContactQuery() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.CONTACT);

        System.assertEquals(
            'SELECT Email, Corporate_Relations_Email__c, EPO_Email__c, ASU_Email__c, ' +
            'Last_Case_Email_Used__c, Lead_Email__c, Lead_Secondary_Email__c, me3hs_User_ID__c, ' +
            'Parent_Email__c, Personal_Email__c, Birthdate FROM Contact WHERE (' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Email') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Corporate_Relations_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('EPO_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('ASU_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Last_Case_Email_Used__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Lead_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Lead_Secondary_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('me3hs_User_ID__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Parent_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Personal_Email__c') +
            ')',
            scrambleService.getQueryFromObject()
        );
    }

    @isTest
    private static void testContactHeader() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.CONTACT);

        System.assertEquals(
            'Id,Birthdate,Email,Corporate_Relations_Email__c,EPO_Email__c,ASU_Email__c,Last_Case_Email_Used__c,Lead_Email__c,' +
            'Lead_Secondary_Email__c,me3hs_User_ID__c,Parent_Email__c,Personal_Email__c,silverpop__Silverpop_RecipientID__c\n',
            scrambleService.getObjectHeader()
        );
    }

    @isTest
    private static void testContactScramblerType() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.CONTACT);
        Contact contactToScramble = new Contact();
        System.assert(
            scrambleService.getScrambleClassForObject(contactToScramble) instanceof ContactScrambler,
            'Scramble class was not of type Contact Scrambler'
        );
    }

    @isTest
    private static void testLeadQuery() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.LEAD);

        System.assertEquals(
            'SELECT Id, Date_of_Birth__c, Email, Recruiting_Email__c, Secondary_Email__c FROM LEAD WHERE (' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Email') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Recruiting_Email__c') +
            ' AND ' +
            ObjectScrambleService.generateNotLikeSandboxDomainStatement('Secondary_Email__c') +
            ')',
            scrambleService.getQueryFromObject()
        );
    }

    @isTest
    private static void testLeadHeader() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.LEAD);

        System.assertEquals(
            'Id,Date_of_Birth__c,Email,Recruiting_Email__c,Secondary_Email__c,silverpop__Silverpop_RecipientID__c\n',
            scrambleService.getObjectHeader()
        );
    }

    @isTest
    private static void testLeadScramblerType() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.LEAD);
        Lead leadToScramble = new Lead();
        System.assert(
            scrambleService.getScrambleClassForObject(leadToScramble) instanceof LeadScrambler,
            'Scramble class was not of type Lead Scrambler'
        );
    }

    @isTest
    private static void testUserQuery() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.USER);
        Id sysAdminId = [SELECT Id FROM Profile WHERE Name = 'System Administrator' LIMIT 1].Id;
        String expectedQuery =
            'SELECT Id FROM User WHERE IsActive = true AND Sandbox_DEV__c = false AND (NOT Username LIKE \'%@00dn000000091oqeay.com\') AND ProfileId <> \'' +
            sysAdminId +
            '\'';
        System.assertEquals(expectedQuery, scrambleService.getQueryFromObject());
    }

    @isTest
    private static void testUserHeader() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.USER);

        System.assertEquals('Id,IsActive\n', scrambleService.getObjectHeader());
    }

    @isTest
    private static void testUserScramblerType() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(ObjectScrambleService.ObjectTypes.USER);
        User userToScramble = new User();
        System.assert(
            scrambleService.getScrambleClassForObject(userToScramble) instanceof UserScrambler,
            'Scramble class was not of type User Scrambler'
        );
    }

    @isTest
    private static void testObjectDoesNotExist() {
        ObjectScrambleService scrambleService = new ObjectScrambleService(null);
        System.assertEquals(null, scrambleService.getObjectHeader());
        System.assertEquals(null, scrambleService.getQueryFromObject());
    }
}