force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact_Upload__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Complete with Errors</fullName>
                </value>
                <value>
                    <fullName>Complete with No Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains records representing a batch of Contacts to be added to Marketing Subscriptions</description>
    <label>Contact Upload</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Contact Upload  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Upload_Detail__c.object
<CustomObject>
    <fields>
        <fullName>ASURITE__c</fullName>
        <label>ASURITE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Upload__c</fullName>
        <label>Contact Upload</label>
        <referenceTo>Contact_Upload__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <label>EMPLID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Processing_Notes__c</fullName>
        <label>Processing Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <label>Subscriber Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>Subscriber__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the record-level detail of a contact upload file. It's used to search for contact (create if not found), then add them to a subscription used by the Subscription Center and Marketing Cloud email sends.</description>
    <label>Contact Upload Detail</label>
    <nameField>
        <displayFormat>CUD-{0000000}</displayFormat>
        <label>Contact Upload Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Upload Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <formula>IF(ISBLANK(Contact__r.Email), Lead__r.Email, Contact__r.Email)</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactUploadDetailServiceTest.cls
@isTest
private class ContactUploadDetailServiceTest {
    private static Map<Integer, String> columnPosToHeaderMap;
    private static ContactUploadDetailService detailService;
    private static Subscription__c subForDetails;
    private static List<String> contactValues;

    private static void setup() {
        ContactUploadFactory.DefaultContactUpload contactUploadCreator = new ContactUploadFactory.DefaultContactUpload();
        Contact_Upload__c contactUpload = (Contact_Upload__c) contactUploadCreator.create(1)[0];
        insert contactUpload;

        columnPosToHeaderMap = new Map<Integer, String>();
        columnPosToHeaderMap.put(0, 'ASURITE');
        columnPosToHeaderMap.put(1, 'First Name');
        columnPosToHeaderMap.put(2, 'Last Name');
        columnPosToHeaderMap.put(3, 'Email Address');
        columnPosToHeaderMap.put(4, 'EMPLID');

        SubscriptionFactory.ParentSubscription subscriptionCreator = new SubscriptionFactory.ParentSubscription();
        subForDetails = (Subscription__c) subscriptionCreator.create(1)[0];
        insert subForDetails;

        detailService = new ContactUploadDetailService(contactUpload.Id, columnPosToHeaderMap);
        detailService.setSubscriptionId(subForDetails.Id);
        detailService.setSubscriberStatus('Subscribed');

        contactValues = new List<String>{ 'tester', 'Test', 'Person', 'test@test.com', '1234567890' };
    }

    @isTest
    private static void contactCreationFromListOfStrings() {
        setup();
        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        System.assertEquals('Success', cudBeingCreated.Status__c);
        System.assertEquals('tester', cudBeingCreated.ASURITE__c);
        System.assertEquals('Test', cudBeingCreated.First_Name__c);
        System.assertEquals('Person', cudBeingCreated.Last_Name__c);
        System.assertEquals('test@test.com', cudBeingCreated.Email__c);
        System.assertEquals('Subscribed', cudBeingCreated.Subscriber_Status__c);
    }

    @isTest
    private static void createSubscriberForDetail() {
        setup();
        Contact createdContact = createAndInsertNewTestContact();

        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        cudBeingCreated.Contact__c = createdContact.Id;
        List<Contact_Upload_Detail__c> cudList = new List<Contact_Upload_Detail__c>();
        cudList.add(cudBeingCreated);
        detailService.createSubscriberStatusMap(cudList);
        Subscriber__c subCreated = detailService.createSubscriberForUploadDetail(cudBeingCreated);
        System.assertEquals(createdContact.Id, subCreated.Contact__c);
    }

    @isTest
    private static void findContactWithEMPLID() {
        setup();
        Contact createdContact = createAndInsertNewTestContact();

        Test.startTest();
        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        ContactUploadSearcher searcher = new ContactUploadSearcher(
            new List<Contact_Upload_Detail__c>{ cudBeingCreated }
        );
        searcher.searchAndCreateContacts();
        Test.stopTest();

        System.assertEquals(createdContact.Id, cudBeingCreated.Contact__c);
    }

    @isTest
    private static void createSubscriberForUploadDetailSubscribedStatus() {
        setup();
        Contact createdContact = createAndInsertNewTestContact();

        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        cudBeingCreated.Contact__c = createdContact.Id;
        cudBeingCreated.Subscriber_Status__c = 'Subscribed';
        List<Contact_Upload_Detail__c> cudList = new List<Contact_Upload_Detail__c>();
        cudList.add(cudBeingCreated);
        detailService.createSubscriberStatusMap(cudList);
        Subscriber__c subCreated = detailService.createSubscriberForUploadDetail(cudBeingCreated);
        System.assertEquals(subCreated.Subscriber_Status__c, 'Subscribed');
    }

    @isTest
    private static void createSubscriberForUploadDetailUnsubscribedStatus() {
        setup();
        Contact createdContact = createAndInsertNewTestContact();

        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        cudBeingCreated.Contact__c = createdContact.Id;
        cudBeingCreated.Subscriber_Status__c = 'Unsubscribed';

        List<Contact_Upload_Detail__c> cudList = new List<Contact_Upload_Detail__c>();
        cudList.add(cudBeingCreated);
        detailService.createSubscriberStatusMap(cudList);
        Subscriber__c subCreated = detailService.createSubscriberForUploadDetail(cudBeingCreated);
        System.assertEquals(subCreated.Subscriber_Status__c, 'Unsubscribed');
    }

    @isTest
    private static void tryForcingUnsubbedSubscriberToBeSubbed() {
        setup();
        Contact createdContact = createAndInsertNewTestContact();

        Contact_Upload_Detail__c cudBeingCreated = detailService.createAndValidateRow(contactValues);
        cudBeingCreated.Contact__c = createdContact.Id;
        cudBeingCreated.Subscriber_Status__c = 'Unsubscribed';
        List<Contact_Upload_Detail__c> cudList = new List<Contact_Upload_Detail__c>();
        cudList.add(cudBeingCreated);
        detailService.createSubscriberStatusMap(cudList);
        Subscriber__c subCreated = detailService.createSubscriberForUploadDetail(cudBeingCreated);
        insert subCreated;
        System.assertEquals(subCreated.Subscriber_Status__c, 'Unsubscribed');

        Contact_Upload_Detail__c cudBeingUpdated = detailService.createAndValidateRow(contactValues);
        cudBeingUpdated.Contact__c = createdContact.Id;
        cudBeingUpdated.Subscriber_Status__c = 'Subscribed';

        List<Contact_Upload_Detail__c> cudListUpdated = new List<Contact_Upload_Detail__c>();
        cudListUpdated.add(cudBeingUpdated);
        detailService.createSubscriberStatusMap(cudListUpdated);
        Subscriber__c subUpdated = detailService.createSubscriberForUploadDetail(cudBeingUpdated);
        System.assertEquals(subUpdated.Subscriber_Status__c, 'Unsubscribed');
        System.assert(
            cudListUpdated[0]
                .Processing_Notes__c.contains('Subscriber Status cannot be updated from Unsubscribed To Subscribed')
        );
    }

    private static Contact createAndInsertNewTestContact() {
        ContactFactory.DefaultContact contactCreator = new ContactFactory.DefaultContact();
        Contact createdContact = (Contact) contactCreator.create(1)[0];
        createdContact.EMPLID__c = '1234567890';
        insert createdcontact;
        return createdContact;
    }
}