force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>me3hs_User_ID__c</fullName>
        <description>[eAdvisor Data Warehouse] me3 User Id in email format</description>
        <inlineHelpText>[eAdvisor Data Warehouse] me3 User Id in email format</inlineHelpText>
        <label>me3hs User ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactScramblerTest.cls
@isTest
private class ContactScramblerTest {
    @TestSetup
    private static void setup() {
        Contact c = new Contact(
            FirstName = 'TestContact',
            LastName = 'TestContact',
            Email = 'test.contact@test.test',
            Corporate_Relations_Email__c = 'test.contact@test.test',
            EPO_Email__c = 'test.contact@test.test',
            ASU_Email__c = 'test.contact@test.test',
            Last_Case_Email_Used__c = 'test.contact@test.test',
            Lead_Email__c = 'test.contact@test.test',
            Lead_Secondary_Email__c = 'test.contact@test.test',
            me3hs_User_ID__c = 'test.contact@test.test',
            Parent_Email__c = 'test.contact@test.test',
            Personal_Email__c = 'test.contact@test.test',
            Birthdate = System.today()
        );

        insert c;
    }

    @IsTest
    private static void testScramble() {
        Contact contactToScramble = [
            SELECT
                Id,
                Email,
                Corporate_Relations_Email__c,
                EPO_Email__c,
                ASU_Email__c,
                Last_Case_Email_Used__c,
                Lead_Email__c,
                Lead_Secondary_Email__c,
                me3hs_User_ID__c,
                Parent_Email__c,
                Personal_Email__c,
                Birthdate,
                silverpop__Silverpop_RecipientID__c
            FROM Contact
            LIMIT 1
        ];

        ContactScrambler scramble = new ContactScrambler(contactToScramble);
        Test.startTest();
        Contact scrambledContact = (Contact) scramble.scrambleFields();
        Test.stopTest();

        System.assert(scrambledContact.email.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(
            scrambledContact.Corporate_Relations_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.'))
        );
        System.assert(scrambledContact.EPO_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(scrambledContact.ASU_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(
            scrambledContact.Last_Case_Email_Used__c.contains('.' + UserInfo.getUserName().substringAfterLast('.'))
        );
        System.assert(scrambledContact.Lead_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(
            scrambledContact.Lead_Secondary_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.'))
        );
        System.assert(scrambledContact.me3hs_User_ID__c.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(scrambledContact.Parent_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.')));
        System.assert(
            scrambledContact.Personal_Email__c.contains('.' + UserInfo.getUserName().substringAfterLast('.'))
        );
        System.assertNotEquals(Date.today(), scrambledContact.Birthdate);
        System.assertEquals(null, scrambledContact.silverpop__Silverpop_RecipientID__c);
    }

    @isTest
    private static void testToCsvString() {
        Contact contactToScramble = [
            SELECT
                Id,
                Email,
                Corporate_Relations_Email__c,
                EPO_Email__c,
                ASU_Email__c,
                Last_Case_Email_Used__c,
                Lead_Email__c,
                Lead_Secondary_Email__c,
                me3hs_User_ID__c,
                Parent_Email__c,
                Personal_Email__c,
                Birthdate,
                silverpop__Silverpop_RecipientID__c
            FROM Contact
            LIMIT 1
        ];

        String expectedString =
            contactToScramble.Id +
            ',' +
            contactToScramble.Birthdate +
            ',' +
            contactToScramble.Email +
            ',' +
            contactToScramble.Corporate_Relations_Email__c +
            ',' +
            contactToScramble.EPO_Email__c +
            ',' +
            contactToScramble.ASU_Email__c +
            ',' +
            contactToScramble.Last_Case_Email_Used__c +
            ',' +
            contactToScramble.Lead_Email__c +
            ',' +
            contactToScramble.Lead_Secondary_Email__c +
            ',' +
            contactToScramble.me3hs_User_ID__c +
            ',' +
            contactToScramble.Parent_Email__c +
            ',' +
            contactToScramble.Personal_Email__c +
            ',#N/A\n';

        ContactScrambler scrambler = new ContactScrambler(contactToScramble);

        String csvString = scrambler.toCsvString();

        System.assertEquals(expectedString, csvString);
    }
}