force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Suncard_Photo__c.object
<CustomObject><fields>
        <fullName>URL__c</fullName>
        <description>The URL to call the web service.</description>
        <label>URL</label>
        <type>Url</type>
    </fields><customSettingsType>List</customSettingsType><description>A custom setting to house the Suncard Photo URL to use while calling out to the web service.</description><enableFeeds>false</enableFeeds><label>Suncard Photo Service</label><visibility>Public</visibility></CustomObject>

force-app/main/default/classes/Test_SuncardPhotoController.cls
@isTest
private class Test_SuncardPhotoController {
    @isTest
    static void testSuncardPhotoURL() {
        Contact testContact = ContactService.createTestContact();
        testContact.ASURite_ID__c = 'testing';
        testContact.EMPLID__c = '1234567890';

        insert testContact;

        Suncard_Photo__c sunSetting = new Suncard_Photo__c(
            Name = 'Suncard Photo Service',
            URL__c = 'https://nowhere.come'
        );

        insert sunSetting;

        SingleRequestMock fakeResponse = new SingleRequestMock(200, 'Complete', '[{"Name": "sForceTest1"}]', null);

        PageReference sunPage = Page.SuncardPhoto;
        Test.setCurrentPage(sunPage);

        Test.startTest();

        Test.setMock(HttpCalloutMock.class, fakeResponse);
        ApexPages.StandardController std = new ApexPages.StandardController(testContact);
        SuncardPhotoController sun = new SuncardPhotoController(std);

        String testURL = sun.getSuncardPhotoURL();

        Test.stopTest();

        System.assertNotEquals(null, testURL);
    }
}