force-app/main/default/objects/Persistence_Outlook__c.object
<CustomObject>
    <fields>
        <fullName>Current_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>CURRENT_FLG</description>
        <label>Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Persistence Outlooks</relationshipLabel>
        <relationshipName>Persistence_Outlooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Contains the necessary information for the civitas section in portals.</description>
    <label>Persistence Outlook</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Persistence Outlook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persistence Outlooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PersistenceOutlookService.cls
public class PersistenceOutlookService  {

    static void updateOldPersistenceOutlookRecords(List<Persistence_Outlook__c newList) {
        Set<Contact> contactsConnectedToOutlook = new List<Contact>();
        for (Persistence_Outlook__c outlook : newList) {
            contactsConnectedToOutlook.add(outlook.Contact__c);
            outlook.Current_Flag__c = true; 
        }

        List<Persistence_Outlook__c> oldOutlooksToUpdate = [
            SELECT Id 
            FROM Persistence_Outlook__c 
            WHERE Contact IN: contactsConnectedToOutlook
            AND Current_Flag__c = true
        ];

        for (Persistence_Outlook__c oldOutlook : oldOutlooksToUpdate ) {
            oldOutlook.Current_Flag__c = false;
        }

        update oldOutlook;
    }
}