force-app/main/default/objects/PS_Country_Map__c.object
<CustomObject>
    <fields>
        <fullName>Country_Code__c</fullName>
        <description>Salesforce Country Picklist Country Code</description>
        <label>Country Code</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country_Name__c</fullName>
        <description>Salesforce Country Picklist Name</description>
        <label>Country Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integration_Value__c</fullName>
        <description>Salesforce Country Picklist Integration Value</description>
        <label>Integration Value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PS_Country_Code__c</fullName>
        <description>Code from PeopleSoft Country table</description>
        <externalId>true</externalId>
        <label>PS Country Code</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Mapping rules for PeopleSoft country field to Salesforce Country Picklist</description>
    <label>PS Country Map</label>
    <nameField>
        <label>PS Country</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PS Country Map</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PSCountryMapServiceTest.cls
@isTest
public with sharing class PSCountryMapServiceTest {
    @isTest
    private static void testMapPSCountryToIntegrationValue() {
        List<PS_Country_Map__c> countries = new List<PS_Country_Map__c>();
        for (Integer i = 0; i < 3; i++) {
            countries.add(
                new PS_Country_Map__c(
                    Name = 'China ' + i,
                    PS_Country_Code__c = 'CH' + i,
                    Country_Name__c = 'China ' + i,
                    Integration_Value__c = 'China',
                    Country_Code__c = 'C' + i
                )
            );
            countries.add(
                new PS_Country_Map__c(
                    Name = 'United States ' + i,
                    PS_Country_Code__c = 'US' + i,
                    Country_Name__c = 'United States ' + i,
                    Integration_Value__c = 'United States',
                    Country_Code__c = 'U' + i
                )
            );
        }
        insert countries;

        Test.startTest();
        Map<String, List<PS_Country_Map__c>> countryMapping = PSCountryMapService.mapPSCountryToIntegrationValue();
        Test.stopTest();

        System.assertEquals(2, countryMapping.keySet().size());
        for (String integVal : countryMapping.keySet()) {
            List<PS_Country_Map__c> countriesForIntegVal = countryMapping.get(integVal);
            System.assertEquals(3, countriesForIntegVal.size());
        }
    }
}