force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this Subscription will be made available for ASU constituents to "opt-in" when managing their subscriptions. Please note that selecting this option requires that your team has a plan for engaging newly opted-in subscribers.</inlineHelpText>
        <label>Available for Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Makes this record and associated Contact or Lead Subscriber records only visible to the Users that are members of the Queue listed as this Subscription's Owner. Note that the Subscriber record must be owned by a Queue in order to check this box.</inlineHelpText>
        <label>Subscriber Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Description__c</fullName>
        <label>Subscription Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <inlineHelpText>Business Unit types are primarily used to store opt-in information 
Area of Interest types store general interests, within a BU (e.g. Financial Aid, Academic Research) 
List types store explicit list (e.g. newsletter, membership)</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Area of Interest</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubscriptionFactory.cls
@isTest
public class SubscriptionFactory {
    public class DefaultSubscription extends TestFactory {
        public DefaultSubscription() {
            super(
                new Subscription__c(
                    Name = 'Test Subscription',
                    Subscription_Type__c = 'List',
                    Subscriber_Private_in_Salesforce__c = false
                )
            );
            this.addToFieldsToIncrement('Name');
        }
    }

    public class ParentSubscription extends TestFactory {
        public ParentSubscription() {
            super(
                new Subscription__c(
                    Subscription_Type__c = 'Business Unit',
                    Name = 'ParentSub',
                    Subscription_Description__c = 'Parent Sub Description',
                    Available_for_Opt_In__c = true,
                    Subscriber_Private_in_Salesforce__c = false
                )
            );
            this.addToFieldsToIncrement('Name');
            this.addToFieldsToIncrement('Subscription_Description__c');
        }
    }
}