force-app/main/default/objects/User.object
<CustomObject>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User/fields/omniChannel_loggedIn__c.field-meta.xml
<CustomField>
    <fullName>omniChannel_loggedIn__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logged on to omni channel</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User/fields/Out_Of_Office_Message__c.field-meta.xml
<CustomField>
    <fullName>Out_Of_Office_Message__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Out of Office message for SMS text message auto reply</description>
    <inlineHelpText>Ed Plus Success Coach - You can enter an Out of Office Start Date, Out of Office End Date, Out of Office Message to auto-reply to your incoming SMS text messages.</inlineHelpText>
    <label>Out Of Office Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/omnichannelController.cls
public class omnichannelController {
    public static String outOfOfficeMessage { get; set; }
    public static Boolean loggedInStatus { get; set; }

    @auraEnabled
    public static boolean updateOmniChannelInfo() {
        try {
            string userId = UserInfo.getUserId();

            User user = [SELECT omniChannel_loggedIn__c, Out_Of_Office_Message__c FROM user WHERE id = :userId];
            user.omniChannel_loggedIn__c = false;
            user.Out_Of_Office_Message__c = outOfOfficeMessage;

            Database.UpsertResult result = Database.upsert(user);
            return result.isSuccess();
        } catch (Exception e) {
            AuraHandledException auraExcep = new AuraHandledException(e.getMessage());
            auraExcep.setMessage(e.getMessage());
            throw auraExcep;
        }
    }
}