src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[??] - is maintained by Gene’s logic using the geomarket/zip relationship defined CollegeBoard, held in the SF key value table.  The Geomarket lumps several zips into a single code giving a broader geographical representation, there are 3 geomarkets assigned to the state of Arizona.</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or manual] - Name of Territoy Manager</description>
        <inlineHelpText>The user assigned as the current Territory Manager for this Institution.</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[Peoplesoft] - Geomarket code tied to the zipcode via a picklist</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Value__c.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[manual entry] - Geomarket code, this is only used for teritory assignment</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geomarket_ZIP__c</fullName>
        <description>[manual entry] - Zip code tied to Geomarket, this is only used for territory assignment</description>
        <externalId>true</externalId>
        <label>Geomarket ZIP</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used for key value mapping needs; ZIP code to Geomarket Codes are contained in here. This object is owned by Enrollment Services team.</description>
    <label>Key Value</label>
    <nameField>
        <displayFormat>Key Value - {0000}</displayFormat>
        <label>Key Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountTriggerTest.cls
@isTest
private class AccountTriggerTest {
    @isTest
    private static void testCreateAndUpdateAccount() {
        Account acc = new Account();
        acc.Name = 'Testaccount';
        insert acc;

        acc.Name = 'Testaccount2';
        update acc;

        System.assertEquals(acc.Name, 'Testaccount2');

        delete acc;
        undelete acc;
    }

    @isTest
    private static void testAccountGeomarketCodeAssignment() {
        UserFactory.DefaultUser userCreator = new UserFactory.DefaultUser();
        User testUser = (User) userCreator.create(1)[0];
        Id saProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;
        testUser.ProfileId = saProfile;
        insert testUser;

        Account highSchool = new Account();
        highSchool.Name = 'Test High School';
        insert highSchool;

        Contact con = new Contact();
        con.FirstName = 'TestFirstName';
        con.LastName = 'TestLastName';
        con.MailingPostalCode = '90210';
        con.Geomarket_Code__c = 'CA-01';
        insert con;

        con = [SELECT Id, AccountId FROM Contact WHERE Id = :con.Id];

        Key_Value__c KV = new Key_Value__c();
        KV.Geomarket_ZIP__c = '85287';
        KV.Geomarket_Code__c = 'GM-01';
        insert KV;

        Opportunity Opp = new Opportunity();
        Opp.Name = 'Test Opp';
        Opp.Contact__c = con.Id;
        Opp.AccountId = con.AccountID;
        Opp.StageName = 'Prospect';
        Opp.CloseDate = date.today() + 365;
        Opp.Type = 'First Time Freshman';
        Opp.OwnerId = TestUser.Id;
        insert Opp;

        AccountService.assignTerritoryDone = false;

        Test.startTest();
        highSchool.ShippingPostalCode = '85287';
        highSchool.Territory_Manager__c = TestUser.Id;
        update highSchool;
        Test.stopTest();

        String accountGeoCodeAfterUpdate = [SELECT Id, Geomarket_Code__c FROM Account WHERE Id = :highSchool.Id LIMIT 1]
        .Geomarket_Code__c;

        System.assert(
            accountGeoCodeAfterUpdate == KV.Geomarket_Code__c,
            'Account Geomarket Code did not match by ZIP code'
        );
    }
}