src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Campaign.object
<CustomObject>
    <sharingModel>Private</sharingModel>
    <recordTypes>
        <fullName>Cohort</fullName>
        <active>true</active>
        <description>Record type used to group Leads and Contacts into specific constituent groups.</description>
        <label>Cohort</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SF_Birthdate_Updated__c</fullName>
        <label>SF.Birthdate Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Birthdate__c</fullName>
        <label>SF.Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SF_First_Name_Updated__c</fullName>
        <label>SF.First Name Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_First_Name__c</fullName>
        <label>SF.First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Last_Name_Updated__c</fullName>
        <label>SF.Last Name Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Last_Name__c</fullName>
        <label>SF.Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Address_Updated__c</fullName>
        <label>SF.Mailing Address Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_City__c</fullName>
        <label>SF.Mailing City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Country__c</fullName>
        <label>SF.Mailing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_State__c</fullName>
        <label>SF.Mailing State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Street__c</fullName>
        <label>SF.Mailing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_ZIP__c</fullName>
        <label>SF.Mailing ZIP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mobile_Updated__c</fullName>
        <label>SF.Mobile Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Mobile__c</fullName>
        <label>SF.Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject><fields>
        <fullName>Active_Relationship__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, indicates that this Relationship is Active.</description>
        <inlineHelpText>Indicates the Relationship is current. Will automatically be set to false when:
1. The Relationship End Date is set to a value in the past - OR -
2. A Relationship End Date set for the future is reached.</inlineHelpText>
        <label>Active Relationship</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Relationship_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Records the date this Relationship began.</description>
        <inlineHelpText>The date this Relationship began. Will automatically be set to Today's date, but can be edited.</inlineHelpText>
        <label>Relationship Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Defines the type or Relationship (e.g. Employee, Parent, Spouse).</description>
        <label>Relationship Type (is)</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization/Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <description>The Contact's Title. Used in Contact to Account relationships.</description>
        <inlineHelpText>Used for Contact to Account Relationships to indicate the Contact's Title at the associated Account.</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Relationship</label><nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Relationships</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The organization tracked on this Relationship Record. Used in Contact to Account and Account to Account Relationships.</description>
    <inlineHelpText>The organization tracked on this Relationship Record.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Can only associate contacts with Org accounts</errorMessage>
        <filterItems>
            <field>Account.Contact__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person tracked on this Relationship Record. Used in Contact to Account and Contact to Contact Relationships.</description>
    <inlineHelpText>The person tracked on this Relationship Record.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/NewCorporateRelationsContactController.cls
public with sharing class NewCorporateRelationsContactController 
{	
	public Account account { get;set; }
	public Contact contact { get;set; }
	public RecordType cohortRecordType { get;set; }
	public Relationship__c relationship { get;set; }
	public Integer page { get;set; }
	public List<Account> allAccounts;
	public List<Relationship__c> relationshipList { get;set; }
	public List<CampaignMember> campaignMemberList { get;set; }
	public List<SelectOption> campaignOptions;
	public List<SelectOption> childCampaignOptions { get;set; }
	public List<Campaign> cohortCampaigns;
	public List<Campaign> childCohortCampaigns;
	public Set<String> currentSet;
	public Set<String> accountSet;
	public String selectedParentId { get;set; }
	public String selectedChildId { get;set; }

	public NewCorporateRelationsContactController() 
	{
		page = 1;
		account = new Account();
		contact = new Contact();
		cohortRecordType = new RecordType();
		currentSet = new Set<String>();
		relationship = new Relationship__c();
		relationshipList = new List<Relationship__c>();
		campaignMemberList = new List<CampaignMember>();
		cohortRecordType = [SELECT Id 
							FROM RecordType 
							WHERE Name = 'Cohort'];
		allAccounts = [SELECT Name
					   FROM Account];
		accountSet = new Set<String>();
	}

	public List<SelectOption> getCampaignOptions() 
	{
		cohortCampaigns = [SELECT Id, Name, RecordTypeId 
					       FROM Campaign 
					       WHERE RecordTypeId = :cohortRecordType.Id 
					       AND IsActive = true
					       AND ParentId = null 
					       ORDER BY Name ASC];
        campaignOptions = new List<SelectOption>();
        campaignOptions.add(new SelectOption( '' ,'--Select--'));
        for (Campaign c : cohortCampaigns ) 
        {
            campaignOptions.add(new SelectOption(c.Id , c.Name));
        }
        return campaignOptions;
    }

    public void populateChildCampaigns() 
    {
        childCohortCampaigns = [SELECT Id, Name, RecordTypeId 
					       		FROM Campaign 
					       		WHERE RecordTypeId = :cohortRecordType.Id 
					       		AND IsActive = true 
					       		AND ParentId = :selectedParentId
					       		ORDER BY Name ASC];
        childCampaignOptions = new List<SelectOption>();
        childCampaignOptions.add(new SelectOption( '' ,'--Select--'));
        for (Campaign c : childCohortCampaigns ) 
        {
            childCampaignOptions.add(new SelectOption(c.Id , c.Name));
        }
    }

    public void saveToDatabase() 
    {
    	try 
    	{
			contact.SF_First_Name__c = contact.FirstName;
            contact.SF_First_Name_Updated__c = Datetime.now();
            contact.SF_Last_Name__c = contact.LastName;
            contact.SF_Last_Name_Updated__c = Datetime.now();
            contact.SF_Mobile__c = contact.MobilePhone;
            contact.SF_Mobile_Updated__c = Datetime.now();
            contact.SF_Mailing_Street__c = contact.MailingStreet;
            contact.SF_Mailing_City__c = contact.MailingCity;
            contact.SF_Mailing_Country__c = contact.MailingCountryCode;
            contact.SF_Mailing_State__c = contact.MailingStateCode;
            contact.SF_Mailing_ZIP__c = contact.MailingPostalCode;
            contact.SF_Mailing_Address_Updated__c = Datetime.now();
            contact.SF_Birthdate__c = contact.Birthdate;
            contact.SF_Birthdate_Updated__c = Datetime.now();
            insert contact; 

	        for (Relationship__c r: relationshipList) 
	        {
	            r.Active_Relationship__c = true;
	            r.Contact__c = contact.Id;
	        }
            insert relationshipList;

	        for (CampaignMember c: campaignMemberList) 
	        {   
	            c.ContactId = contact.Id;
	        }
            insert campaignMemberList;
		} 
		catch (exception e) 
		{

		}
    }

    public void addRelationship() 
    {
    	Relationship__c rNew = new Relationship__c();
    	rNew.Title__c = relationship.Title__c;
    	rNew.Account__c = relationship.Account__c;
    	rNew.Relationship_Type__c = relationship.Relationship_Type__c;
    	rNew.Relationship_Start_Date__c = relationship.Relationship_Start_Date__c;
    	relationshipList.add(rNew);
    }

    public void addParentCampaignMember() 
    {
    	CampaignMember pNew = new CampaignMember();
    	pNew.CampaignId = selectedParentId;
    	if (!currentSet.contains(selectedParentId)) 
    	{
    		campaignMemberList.add(pNew);
    		currentSet.add(selectedParentId);
    	}
    }

    public void addCampaignMember() 
    {
    	CampaignMember cNew = new CampaignMember();
    	cNew.CampaignId = selectedChildId;
    	if (!currentSet.contains(selectedChildId)) 
    	{
    		campaignMemberList.add(cNew);
    		currentSet.add(selectedChildId);
    	}
    }

    public PageReference page2()
    {
		page = 2;
		return ApexPages.currentPage();
	}

	public PageReference page3()
	{
		page = 3;
		return ApexPages.currentPage();
	}

	public void addPage() 
	{
		addRelationship();
		addParentCampaignMember();
		addCampaignMember();
		relationship = null;
		relationship = new Relationship__c();
		selectedParentId = null;
		selectedChildId = null;
		childCampaignOptions = null;
	}

	public PageReference cancelAccount()
	{
		page = 2;
		return ApexPages.currentPage();
	}

	public PageReference insertAccount()
	{
		for (Account a: allAccounts)
		{
			if (a.Name != null)
			{
				accountSet.add(a.Name);
			}

		}
		try
		{
			if (!accountSet.contains(account.Name))
			{
				insert account;
				page = 2;
				return ApexPages.currentPage();
			}
			else
			{
				ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Account already exists. You can press the \'Back\' button to return to the previous page and search for the Account you\'re looking for.'));
				return null;
			}
		}
		catch (Exception e)
		{

		}
		return null;
	}

	public PageReference save() 
	{
		addRelationship();
		addParentCampaignMember();
		addCampaignMember();
		saveToDatabase();
		PageReference submit = new PageReference('/' + contact.Id);
		submit.setRedirect(true);
		return submit;
	}

	public PageReference saveAndNew() 
	{
		addRelationship();
		addCampaignMember();
		saveToDatabase();
		PageReference submit = ApexPages.currentPage();
		submit.setRedirect(true);
		return submit;
	}	
}