src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[??] - is maintained by Gene’s logic using the geomarket/zip relationship defined CollegeBoard, held in the SF key value table.  The Geomarket lumps several zips into a single code giving a broader geographical representation, there are 3 geomarkets assigned to the state of Arizona.</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>[Peoplesoft or manual] - Examples Include: 2YR, 4YR, HS, CC, COL, K8, NA, NTL, SCD, UKN, UNV, VOC</description>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2YR</fullName>
                </value>
                <value>
                    <fullName>4YR</fullName>
                </value>
                <value>
                    <fullName>HS</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>COL</fullName>
                </value>
                <value>
                    <fullName>K8</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NTL</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
                <value>
                    <fullName>UKN</fullName>
                </value>
                <value>
                    <fullName>UNV</fullName>
                </value>
                <value>
                    <fullName>VOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or manual] - Name of Territoy Manager</description>
        <inlineHelpText>The user assigned as the current Territory Manager for this Institution.</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - look up to the user for the Corporate Relations Leads</description>
        <label>Corporate Relations Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[Peoplesoft] - Geomarket code tied to the zipcode via a picklist</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Value__c.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[manual entry] - Geomarket code, this is only used for teritory assignment</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geomarket_ZIP__c</fullName>
        <description>[manual entry] - Zip code tied to Geomarket, this is only used for territory assignment</description>
        <externalId>true</externalId>
        <label>Geomarket ZIP</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used for key value mapping needs; ZIP code to Geomarket Codes are contained in here. This object is owned by Enrollment Services team.</description>
    <label>Key Value</label>
    <nameField>
        <displayFormat>Key Value - {0000}</displayFormat>
        <label>Key Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[import] - Geomarket code for the lead</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Institution_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[import] - Last institution the Lead has attended. The institution can be a high school or a college.</description>
        <label>Last Institution Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Lead_Account_Institution</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>[import] - Examples include: First Time Freshman, Transfer, Readmission, Masters, Doctoral, Juris Doctor, Certificate, Non-Degree</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Career__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>First Time Freshman</fullName>
                </value>
                <value>
                    <fullName>Transfer</fullName>
                </value>
                <value>
                    <fullName>Readmission</fullName>
                </value>
                <value>
                    <fullName>Masters</fullName>
                </value>
                <value>
                    <fullName>Doctoral</fullName>
                </value>
                <value>
                    <fullName>Juris Doctor</fullName>
                </value>
                <value>
                    <fullName>Certificate</fullName>
                </value>
                <value>
                    <fullName>Non-Degree</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Previous_Education__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Institution stored as an Account record.</description>
        <label>Institution</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Institution</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>[??] - Relationship to the contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <formula>TEXT(Account__r.Institution_Type__c)</formula>
        <label>Institution Type</label>
        <type>Text</type>
    </fields>
    <description>Self-reported academic history from application</description>
    <label>Previous Education</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <label>Previous Education Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Previous Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory_Assignment_Rule__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_By_State__c</fullName>
        <label>Assignment By State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armed Forces Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_by_Country__c</fullName>
        <description>For International Territory Assignment</description>
        <label>Assignment by Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Campus__c</fullName>
        <label>Campus</label>
        <picklist>
            <picklistValues>
                <fullName>Downtown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tempe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Defer_Territory_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer Territory Assignment</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Geomarket__c</fullName>
        <label>Geomarket</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>International__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>National_Scholarship__c</fullName>
        <label>National Scholarship</label>
        <picklist>
            <picklistValues>
                <fullName>National Achievement Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Achievement Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Hispanic Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gammage Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Designate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Finalist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Time Freshman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Readmission</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Previous_User_ID__c</fullName>
        <label>Previous User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_End__c</fullName>
        <inlineHelpText>Based on opportunities numbered 1-100, opportunities will be assigned ending at this number (MAX = 100)</inlineHelpText>
        <label>Range End</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_Start__c</fullName>
        <description>Based on opportunities numbered 1-100, opportunities in countries that are split will be assigned starting at this number.</description>
        <label>Range Start</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Key__c</fullName>
        <formula>If (TEXT(Rule_Type__c) = 'Freshman Scholar',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International Admitted - Conditional',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_by_Country__c), 
If (TEXT(Rule_Type__c) = 'Location',TEXT(Rule_Type__c)+'|'+TEXT(Location__c), 
If (TEXT(Rule_Type__c) = 'Geomarket',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + Geomarket__c, 
If (TEXT(Rule_Type__c) = 'State',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_By_State__c), 
If (TEXT(Rule_Type__c) = 'Default User',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c),'') 
))))))</formula>
        <label>Rule Key</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Type__c</fullName>
        <label>Rule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Freshman Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geomarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Admitted - Conditional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assign to?</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Auto_Territory_Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object is used to define the rules for recruitment auto territory assignment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Territory Assignment Rule</label><nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Auto Territory Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Territory Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Opportunity_Type__c</columns>
        <columns>Rule_Type__c</columns>
        <columns>User__c</columns>
        <columns>Assignment_by_Country__c</columns>
        <columns>Assignment_By_State__c</columns>
        <columns>Campus__c</columns>
        <columns>Defer_Territory_Assignment__c</columns>
        <columns>Geomarket__c</columns>
        <columns>International__c</columns>
        <columns>Location__c</columns>
        <columns>National_Scholarship__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews></CustomObject>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>First Time Freshman</fullName>
            </value>
            <value>
                <fullName>Transfer</fullName>
            </value>
            <value>
                <fullName>Non-Degree</fullName>
            </value>
            <value>
                <fullName>Readmission</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Rule_Type__c.field-meta.xml
<CustomField>
    <fullName>Rule_Type__c</fullName>
    <label>Rule Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Freshman Scholar</fullName>
            </value>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Location</fullName>
            </value>
            <value>
                <fullName>Geomarket</fullName>
            </value>
            <value>
                <fullName>State</fullName>
            </value>
            <value>
                <fullName>Default User</fullName>
            </value>
            <value>
                <fullName>International Admitted - Conditional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchDeferredTATest.cls
@isTest
private class BatchDeferredTATest {
    private static List<User> testUsers;

    static void setup() {
        UserFactory.DefaultUser userCreator = new UserFactory.DefaultUser();
        testUsers = userCreator.create(2);

        Id saProfile = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id;

        for (User u : testUsers) {
            u.ProfileId = saProfile;
        }

        insert testUsers;
    }

    @isTest
    static void testBatchAccountDeferredLeadTA() {
        setup();
        User TestUser = testUsers[0];
        User TestUser2 = testUsers[1];

        Key_Value__c KVHS = new Key_Value__c();
        KVHS.Geomarket_ZIP__c = '84108';
        KVHS.Geomarket_Code__c = 'UT-01';
        insert KVHS;

        Account HS = new Account();
        HS.Name = 'Test High School';
        HS.ShippingPostalCode = '84108';
        HS.Geomarket_Code__c = 'UT-01';
        HS.Institution_Type__c = 'HS';
        HS.Territory_Manager__c = TestUser.Id;
        insert HS;

        List<Lead> leadInsertList = new List<Lead>();
        for (Integer i = 0; i < 1; i++) {
            Lead l = new Lead(
                LastName = 'LName' + i,
                FirstName = 'FName' + i,
                Company = 'Company',
                Email = 'test' + i + '@test.test',
                LeadSource = 'Email',
                Type__c = 'First Time Freshman',
                Last_Institution_Attended__c = HS.id
            );
            leadInsertList.add(l);
        }
        insert leadInsertList;

        TerritoryAssignmentAccount.assignTerritoryDone = false;

        HS.Territory_Manager__c = TestUser2.Id;
        update HS;

        Database.QueryLocator QL;
        Database.BatchableContext BC;
        List<SObject> leadList = new List<SObject>();
        BatchAccountDeferredLeadTA acctDeferredLeadTA = new BatchAccountDeferredLeadTA();

        QL = acctDeferredLeadTA.start(bc);
        Database.QueryLocatorIterator QLI = QL.iterator();
        while (QLI.hasNext()) {
            Lead l = (Lead) QLI.next();
            System.debug(l);
            leadList.add(l);
        }
        acctDeferredLeadTA.execute(BC, leadList);
        acctDeferredLeadTA.finish(BC);
    }

    @isTest
    static void testBatchAccountDeferredOppTA() {
        setup();
        User TestUser = testUsers[0];
        User TestUser2 = testUsers[1];

        Account HS = new Account();
        HS.Name = 'Test High School';
        HS.Institution_Type__c = 'HS';
        HS.Territory_Manager__c = TestUser.Id;
        insert HS;

        Contact Con = new Contact();
        Con.FirstName = 'TestFirstName';
        Con.LastName = 'TestLastName';
        Con.Email = 'test@test.com';
        insert Con;

        Previous_Education__c pe = new Previous_Education__c();
        pe.Contact__c = Con.Id;
        pe.Account__c = HS.Id;
        insert pe;

        Con = [SELECT Id, AccountId FROM Contact WHERE Id = :Con.Id];

        Opportunity Opp = new Opportunity();
        Opp.Name = 'Test Opp';
        Opp.Contact__c = Con.Id;
        Opp.AccountId = Con.AccountId;
        Opp.StageName = 'Prospect';
        Opp.Type = 'First Time Freshman';
        Opp.CloseDate = date.today() + 365;
        insert Opp;

        TerritoryAssignmentAccount.assignTerritoryDone = false;

        HS.Territory_Manager__c = TestUser2.Id;
        update HS;

        Database.QueryLocator QL;
        Database.BatchableContext BC;
        List<SObject> oppList = new List<SObject>();
        BatchAccountDeferredOppTA acctDeferredOppTA = new BatchAccountDeferredOppTA();

        QL = acctDeferredOppTA.start(bc);
        Database.QueryLocatorIterator QLI = QL.iterator();
        while (QLI.hasNext()) {
            Opportunity o = (Opportunity) QLI.next();
            System.debug(o);
            oppList.add(o);
        }
        acctDeferredOppTA.execute(BC, oppList);
        acctDeferredOppTA.finish(BC);
    }

    @isTest
    static void testBatchTARDeferredLeadTA() {
        setup();
        User TestUser = testUsers[0];
        User TestUser2 = testUsers[1];

        Territory_Assignment_Rule__c Atar1 = new Territory_Assignment_Rule__c();
        Atar1.Rule_Type__c = 'Default User';
        Atar1.User__c = TestUser.Id;
        Atar1.Opportunity_Type__c = 'First Time Freshman';
        insert Atar1;

        List<Lead> leadInsertList = new List<Lead>();
        for (Integer i = 0; i < 1; i++) {
            Lead l = new Lead(
                LastName = 'LName' + i,
                FirstName = 'FName' + i,
                Company = 'Company',
                Email = 'test' + i + '@test.test',
                LeadSource = 'Email',
                Type__c = 'First Time Freshman'
            );
            leadInsertList.add(l);
        }
        insert leadInsertList;

        TerritoryAssignmentRule.assignTerritoryDone = false;

        Atar1.User__c = TestUser2.Id;
        update Atar1;

        Database.QueryLocator QL;
        Database.BatchableContext BC;
        List<SObject> leadList = new List<SObject>();
        BatchTARDeferredLeadTA tarDeferredLeadTA = new BatchTARDeferredLeadTA();

        QL = tarDeferredLeadTA.start(bc);
        Database.QueryLocatorIterator QLI = QL.iterator();
        while (QLI.hasNext()) {
            Lead l = (Lead) QLI.next();
            leadList.add(l);
        }
        tarDeferredLeadTA.execute(BC, leadList);
        tarDeferredLeadTA.finish(BC);
    }

    @isTest
    static void testBatchTARDeferredOppTA() {
        setup();
        User TestUser = testUsers[0];
        User TestUser2 = testUsers[1];

        Contact Con = new Contact();
        Con.FirstName = 'TestFirstName';
        Con.LastName = 'TestLastName';
        insert Con;

        Con = [SELECT Id, AccountId FROM Contact WHERE Id = :Con.Id];

        Territory_Assignment_Rule__c Atar1 = new Territory_Assignment_Rule__c();
        Atar1.Rule_Type__c = 'Default User';
        Atar1.User__c = TestUser.Id;
        Atar1.Opportunity_Type__c = 'First Time Freshman';
        insert Atar1;

        Opportunity Opp = new Opportunity();
        Opp.Name = 'Test Opp';
        Opp.StageName = 'Prospect';
        Opp.Type = 'First Time Freshman';
        Opp.CloseDate = date.today() + 365;
        Opp.Contact__c = Con.Id;
        Opp.AccountId = Con.AccountId;
        insert Opp;

        TerritoryAssignmentRule.assignTerritoryDone = false;

        Atar1.User__c = TestUser2.Id;
        update Atar1;

        Database.QueryLocator QL;
        Database.BatchableContext BC;
        List<SObject> oppList = new List<SObject>();
        BatchTARDeferredOppTA tarDeferredOppTA = new BatchTARDeferredOppTA();

        QL = tarDeferredOppTA.start(bc);
        Database.QueryLocatorIterator QLI = QL.iterator();
        while (QLI.hasNext()) {
            Opportunity o = (Opportunity) QLI.next();
            oppList.add(o);
        }
        tarDeferredOppTA.execute(BC, oppList);
        tarDeferredOppTA.finish(BC);
    }
}