src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>[Peoplesoft or manual] - Examples Include: 2YR, 4YR, HS, CC, COL, K8, NA, NTL, SCD, UKN, UNV, VOC</description>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2YR</fullName>
                </value>
                <value>
                    <fullName>4YR</fullName>
                </value>
                <value>
                    <fullName>HS</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>COL</fullName>
                </value>
                <value>
                    <fullName>K8</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NTL</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
                <value>
                    <fullName>UKN</fullName>
                </value>
                <value>
                    <fullName>UNV</fullName>
                </value>
                <value>
                    <fullName>VOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or manual] - Name of Territoy Manager</description>
        <inlineHelpText>The user assigned as the current Territory Manager for this Institution.</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_College_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft, or import] - Name of last college attended</description>
        <label>Last College Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last College Attended)</relationshipLabel>
        <relationshipName>Contacts_HS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_HS_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or import] - Name of last high school attended</description>
        <label>Last High School Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last High School Attended)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to indicate the record should be evaluated for territory assignment. When set to true the trigger will fire. The trigger sets the value back to false.</description>
        <inlineHelpText>If the Opportunity owner needs to be reassigned based on the Contact's recruitment details, please check this box for the auto-territory assignment rules to run.</inlineHelpText>
        <label>Territory Assignment Required</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Previous_Education__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Institution stored as an Account record.</description>
        <label>Institution</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Institution</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>[??] - Relationship to the contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <formula>TEXT(Account__r.Institution_Type__c)</formula>
        <label>Institution Type</label>
        <type>Text</type>
    </fields>
    <description>Self-reported academic history from application</description>
    <label>Previous Education</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <label>Previous Education Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Previous Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PreviousEducationService.cls
public without sharing class PreviousEducationService {
    public static Boolean assignTerritoryDone = false;

    /**
     * Update the Previous Educations' Contacts' Last_HS_Attended__c and Last_College_Attended__c
     * This expects to run once ALL Previous Eductions are retrievable via SOQL (so in the AFTER triggers)
     */
    public static void updateContactsLastEducations(List<Previous_Education__c> prevEdList) {
        Set<Id> contactIdSet = new Set<Id>();
        Map<String, Previous_Education__c> mostRecentPrevEdsPerContactForHSAndCollege = new Map<String, Previous_Education__c>();
        Map<Id, Contact> contactsToUpdate = new Map<Id, Contact>();

        //Get all the contact IDs attached to the PEs we're looking at
        for (Previous_Education__c prevEd : prevEdList)
            contactIdSet.add(prevEd.Contact__c);

        if (contactIdSet.isEmpty())
            return; // none of the Prev Educations have contact lookups

        // Get all the previous educations for these contacts
        List<Previous_Education__c> allPrevEdForContacts = new List<Previous_Education__c>(
            [
                SELECT Id, Contact__c, Account__c, Institution_Type__c, CreatedDate, LastModifiedDate
                FROM Previous_Education__c
                WHERE Contact__c IN :contactIdSet
            ]
        );

        // Sort the PEs into a map by Contact ID (we have two entries for each contact, one for HS and one for College)
        // maps from "<ContactId>|<Type>" (either H or C for HS or college respectively) to the most recently modified
        // Previous_Education for that contact of that type
        for (Previous_Education__c prevEd : allPrevEdForContacts) {
            string mapKey = makeKey(prevEd);
            if (mapKey != null) {
                if (!mostRecentPrevEdsPerContactForHSAndCollege.containsKey(mapKey)) {
                    // don't have anything for this contact's high school or college yet
                    mostRecentPrevEdsPerContactForHSAndCollege.put(mapKey, prevEd);
                } else {
                    // already have a PrevEd for this contact's high school or college
                    Previous_Education__c curPrevEd = mostRecentPrevEdsPerContactForHSAndCollege.get(mapKey);
                    // use the new PrevEd IF its LastModifiedDate is more recent
                    if (curPrevEd.LastModifiedDate < prevEd.LastModifiedDate) {
                        mostRecentPrevEdsPerContactForHSAndCollege.put(mapKey, prevEd);
                    }
                }
            }
        }

        //Get data from all the contacts attached to the PEs
        Map<Id, Contact> contactMap = new Map<Id, Contact>(
            [SELECT Id, Last_HS_Attended__c, Last_College_Attended__c FROM Contact WHERE Id IN :contactIdSet]
        );

        // For each previous education we are changing - we need to potentially update its Contact
        for (Previous_Education__c prevEd : prevEdList) {
            // skip if this prev ed has no contact
            if (prevEd.Contact__c == null)
                continue;
            // otherwise let's get the details from this contact
            Contact thisContact = contactMap.get(prevEd.Contact__c);
            if (thisContact == null)
                continue;

            // Key to find most recent prevEd for this <ContactId>|<Type> pair
            String key = makeKey(prevEd);

            if (prevEd.Institution_Type__c == 'HS') {
                // For High school prevEducation
                if (
                    mostRecentPrevEdsPerContactForHSAndCollege.containsKey(key) &&
                    mostRecentPrevEdsPerContactForHSAndCollege.get(key).Id != thisContact.Last_HS_Attended__c
                ) {
                    // This contact's Last HS attended doesn't match the one on the most recent high school - so let's update it
                    Contact contactWithLastHSAttendedSet = new Contact(
                        Id = prevEd.Contact__c,
                        Last_HS_Attended__c = mostRecentPrevEdsPerContactForHSAndCollege.get(key).Account__c
                    );
                    ObjectService.updateSObjectInMap(contactsToUpdate, contactWithLastHSAttendedSet);
                }
            } else if (prevEd.Institution_Type__c == '2YR' || prevEd.Institution_Type__c == '4YR') {
                //Else, if this is a college prevEducation
                if (
                    mostRecentPrevEdsPerContactForHSAndCollege.containsKey(key) &&
                    mostRecentPrevEdsPerContactForHSAndCollege.get(key).Id != thisContact.Last_College_Attended__c
                ) {
                    // This contact's Last HS attended doesn't match the one on the most recent high school - so let's update it
                    Contact contactWithLastHSAttendedSet = new Contact(
                        Id = prevEd.Contact__c,
                        Last_College_Attended__c = mostRecentPrevEdsPerContactForHSAndCollege.get(key).Account__c
                    );
                    ObjectService.updateSObjectInMap(contactsToUpdate, contactWithLastHSAttendedSet);
                }
            }
        }

        if (!contactsToUpdate.isEmpty())
            update contactsToUpdate.values();
    }

    private static String makeKey(Previous_Education__c prevEd) {
        String key = '';

        if (prevEd.Contact__c == null)
            return null;

        key += prevEd.Contact__c;

        if (prevEd.Institution_Type__c == 'HS')
            key += '|H';
        else
            key += '|C';

        return key;
    }

    public static void assignTerritory(List<Previous_Education__c> newPreviousEducations) {
        if (assignTerritoryDone) {
            return;
        }

        // Get all contact ids for these Previous Educations
        Set<Id> contactIdSet = new Set<Id>();
        for (Previous_Education__c previousEducation : newPreviousEducations)
            contactIdSet.add(previousEducation.Contact__c);

        // If these Previous Educations had some contact lookups - we need to update the territory assignment for their Opportunities
        if (!contactIdSet.isEmpty()) {
            List<Opportunity> oppList = new List<Opportunity>(
                [
                    SELECT
                        Id,
                        Contact__c,
                        Account.Name,
                        Account.Institution_Type__c,
                        Account.Territory_Manager__c,
                        Type,
                        OwnerId
                    FROM Opportunity
                    WHERE Contact__c IN :contactIdSet
                ]
            );

            List<Opportunity> oppToUpdate = new List<Opportunity>();

            for (Opportunity opp : oppList) {
                opp.Territory_Assignment_Required__c = true;
                oppToUpdate.add(opp);
            }

            if (!oppToUpdate.isEmpty())
                TerritoryAssignmentService.updateOpportunityList(oppToUpdate);
        }
        assignTerritoryDone = true;
    }
}