src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <description>[Peoplesoft or manual] - Examples Include: 2YR, 4YR, HS, CC, COL, K8, NA, NTL, SCD, UKN, UNV, VOC</description>
        <label>Institution Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2YR</fullName>
                </value>
                <value>
                    <fullName>4YR</fullName>
                </value>
                <value>
                    <fullName>HS</fullName>
                </value>
                <value>
                    <fullName>CC</fullName>
                </value>
                <value>
                    <fullName>COL</fullName>
                </value>
                <value>
                    <fullName>K8</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
                <value>
                    <fullName>NTL</fullName>
                </value>
                <value>
                    <fullName>SCD</fullName>
                </value>
                <value>
                    <fullName>UKN</fullName>
                </value>
                <value>
                    <fullName>UNV</fullName>
                </value>
                <value>
                    <fullName>VOC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_College_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft, or import] - Name of last college attended</description>
        <label>Last College Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last College Attended)</relationshipLabel>
        <relationshipName>Contacts_HS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_HS_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or import] - Name of last high school attended</description>
        <label>Last High School Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last High School Attended)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Previous_Education__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup to the Institution stored as an Account record.</description>
        <label>Institution</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Institution</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <description>[??] - Relationship to the contact</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Previous Education</relationshipLabel>
        <relationshipName>Previous_Education</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Institution_Type__c</fullName>
        <formula>TEXT(Account__r.Institution_Type__c)</formula>
        <label>Institution Type</label>
        <type>Text</type>
    </fields>
    <description>Self-reported academic history from application</description>
    <label>Previous Education</label>
    <nameField>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <label>Previous Education Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Previous Education</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Test_PreviousEducationTrigger.cls
@istest
private with sharing class Test_PreviousEducationTrigger{  

// Need to update with the correct test user
User TestUser = [Select Id FROM User WHERE Profile.Name = 'System Administrator' AND isActive = true LIMIT 1];  

private static testMethod void testContactUpdateFromPreviousEducation() { 
        
    Account HS = new Account();
    HS.Name = 'Test High School';
    HS.Institution_Type__c = 'HS';
    insert HS;

    Account College = new Account();
    College.Name = 'Test College';
    College.Institution_Type__c = '4YR';
    insert College;
    
    Contact Con = new Contact();
    Con.FirstName = 'TestFirstName';
    Con.LastName = 'TestLastName';
    Con.Last_HS_Attended__c = null;
    Con.Last_College_Attended__c = null;
    insert Con;
    System.Debug('Contact ID = ' + Con.Id);
    
    Test.startTest();
        //Test inserting a High School. The trigger updates the contact accordingly. 
        Previous_Education__c PEHS = new Previous_Education__c();
        PEHS.Contact__c = Con.Id;
        PEHS.Account__c = HS.Id;
        insert PEHS;

        //Test Inserting a College. The trigger updates the contact accordingly. 
        Previous_Education__c PEC = new Previous_Education__c();
        PEC.Contact__c = Con.Id;
        PEC.Account__c = College.Id;
        insert PEC;
        
        //Updates added to make sure 100% of code lines are covered
        Update PEC;
        Update PEHS;
        
    Test.stopTest();
    
    // Assertions
    Id HSId = [SELECT Last_HS_Attended__c FROM Contact WHERE Id =: Con.Id LIMIT 1].Last_HS_Attended__c;
    System.Debug('HSId = ' + HSId + ' PEHS.Account__c = ' + PEHS.Account__c);    
    System.Assert(HSId == PEHS.Account__c,'Contact Last High School Attended did not update correctly.'); 

    Id CollegeId = [SELECT Last_College_Attended__c FROM Contact WHERE Id =: Con.Id LIMIT 1].Last_College_Attended__c;
    System.Debug('CollegeId = ' + CollegeId + ' PEC.Account__c = ' + PEC.Account__c);
    System.Assert(CollegeId == PEC.Account__c,'Contact Last College Attended did not update correctly.');  
} 
}