src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[??] - is maintained by Gene’s logic using the geomarket/zip relationship defined CollegeBoard, held in the SF key value table.  The Geomarket lumps several zips into a single code giving a broader geographical representation, there are 3 geomarkets assigned to the state of Arizona.</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or manual] - Name of Territoy Manager</description>
        <inlineHelpText>The user assigned as the current Territory Manager for this Institution.</inlineHelpText>
        <label>Territory Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - look up to the user for the Corporate Relations Leads</description>
        <label>Corporate Relations Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[Peoplesoft] - Geomarket code tied to the zipcode via a picklist</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_College_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft, or import] - Name of last college attended</description>
        <label>Last College Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last College Attended)</relationshipLabel>
        <relationshipName>Contacts_HS</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Last_HS_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft or import] - Name of last high school attended</description>
        <label>Last High School Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts (Last High School Attended)</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Key_Value__c.object
<CustomObject>
    <fields>
        <fullName>Geomarket_Code__c</fullName>
        <description>[manual entry] - Geomarket code, this is only used for teritory assignment</description>
        <label>Geomarket Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geomarket_ZIP__c</fullName>
        <description>[manual entry] - Zip code tied to Geomarket, this is only used for territory assignment</description>
        <externalId>true</externalId>
        <label>Geomarket ZIP</label>
        <length>5</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>This object is used for key value mapping needs; ZIP code to Geomarket Codes are contained in here. This object is owned by Enrollment Services team.</description>
    <label>Key Value</label>
    <nameField>
        <displayFormat>Key Value - {0000}</displayFormat>
        <label>Key Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Key Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Geomarket_Code_Map</fullName>
        <active>true</active>
        <label>Geomarket Code Map</label>
    </recordTypes>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location_Code__c</fullName>
        <description>[Peoplesoft] - code for the location</description>
        <externalId>true</externalId>
        <label>Location Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Campus

Location records are manually entered at this time.  
Review SFE-2602 for details of why and how this object works.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Admitted_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft] - Location where the student will attend for the admitted plan.</description>
        <inlineHelpText>Location where the student will attend for the admitted plan.</inlineHelpText>
        <label>Admitted Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Opportunities (Admitted Location)</relationshipLabel>
        <relationshipName>Opportunities_AdmittedLocation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Undergraduate, Graduate, Law</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Manual import, purchased lists, prospect forms, F1/J1, webforms] - Checkbox to if student is international</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Location Object. The applied location for undergraduate students.</description>
        <label>Academic Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity_Assignment_Number_Rand__c</fullName>
        <label>Opportunity Assignment Number Rand</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Assignment_Number__c</fullName>
        <description>A number from 1 to 100 used to divide Opportunities for ad hoc calling lists. Created by combining or the last digit of the minute and second of the Created Time, and adding 1.</description>
        <formula>VALUE(MID(TEXT(CreatedDate),19,1) &amp; MID(TEXT(CreatedDate),16,1)) + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>A number from 1 to 100 used to divide Opportunities for ad hoc calling lists. Created by combining or the last digit of the minute and second of the Created Time, and adding 1.</inlineHelpText>
        <label>Opportunity Assignment Number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[manual import] - Checkbox if the opportunity is a potential National Scholar</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Last_Rule_Type__c</fullName>
        <description>This field is populated by the territory assignment apex code. It should not be edited my any other way.</description>
        <inlineHelpText>Shows the last type of auto territory assignment rule matched.</inlineHelpText>
        <label>Territory Assignment Last Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freshman Scholar</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Lake Havasu</fullName>
                </value>
                <value>
                    <fullName>Last Attended High-School</fullName>
                </value>
                <value>
                    <fullName>Last Attended College</fullName>
                </value>
                <value>
                    <fullName>Geomarket</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Default User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Last_Run__c</fullName>
        <description>The time when territory assignment rules were last run.</description>
        <label>Territory Assignment Last Run</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to indicate the record should be evaluated for territory assignment. When set to true the trigger will fire. The trigger sets the value back to false.</description>
        <inlineHelpText>If the Opportunity owner needs to be reassigned based on the Contact's recruitment details, please check this box for the auto-territory assignment rules to run.</inlineHelpText>
        <label>Territory Assignment Required</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory_Assignment_Rule__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_By_State__c</fullName>
        <label>Assignment By State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armed Forces Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_by_Country__c</fullName>
        <description>For International Territory Assignment</description>
        <label>Assignment by Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Campus__c</fullName>
        <label>Campus</label>
        <picklist>
            <picklistValues>
                <fullName>Downtown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tempe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Defer_Territory_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer Territory Assignment</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Geomarket__c</fullName>
        <label>Geomarket</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>International__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>National_Scholarship__c</fullName>
        <label>National Scholarship</label>
        <picklist>
            <picklistValues>
                <fullName>National Achievement Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Achievement Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Hispanic Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gammage Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Designate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Finalist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Time Freshman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Readmission</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Previous_User_ID__c</fullName>
        <label>Previous User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_End__c</fullName>
        <inlineHelpText>Based on opportunities numbered 1-100, opportunities will be assigned ending at this number (MAX = 100)</inlineHelpText>
        <label>Range End</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_Start__c</fullName>
        <description>Based on opportunities numbered 1-100, opportunities in countries that are split will be assigned starting at this number.</description>
        <label>Range Start</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Key__c</fullName>
        <formula>If (TEXT(Rule_Type__c) = 'Freshman Scholar',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International Admitted - Conditional',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_by_Country__c), 
If (TEXT(Rule_Type__c) = 'Location',TEXT(Rule_Type__c)+'|'+TEXT(Location__c), 
If (TEXT(Rule_Type__c) = 'Geomarket',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + Geomarket__c, 
If (TEXT(Rule_Type__c) = 'State',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_By_State__c), 
If (TEXT(Rule_Type__c) = 'Default User',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c),'') 
))))))</formula>
        <label>Rule Key</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Type__c</fullName>
        <label>Rule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Freshman Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geomarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Admitted - Conditional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assign to?</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Auto_Territory_Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object is used to define the rules for recruitment auto territory assignment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Territory Assignment Rule</label><nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Auto Territory Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Territory Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Opportunity_Type__c</columns>
        <columns>Rule_Type__c</columns>
        <columns>User__c</columns>
        <columns>Assignment_by_Country__c</columns>
        <columns>Assignment_By_State__c</columns>
        <columns>Campus__c</columns>
        <columns>Defer_Territory_Assignment__c</columns>
        <columns>Geomarket__c</columns>
        <columns>International__c</columns>
        <columns>Location__c</columns>
        <columns>National_Scholarship__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews></CustomObject>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lake Havasu</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Rule_Key__c.field-meta.xml
<CustomField>
    <fullName>Rule_Key__c</fullName>
    <formula>If (TEXT(Rule_Type__c) = 'Freshman Scholar',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International Admitted - Conditional',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_by_Country__c), 
If (TEXT(Rule_Type__c) = 'Location',TEXT(Rule_Type__c)+'|'+TEXT(Location__c), 
If (TEXT(Rule_Type__c) = 'Geomarket',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + Geomarket__c, 
If (TEXT(Rule_Type__c) = 'State',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_By_State__c), 
If (TEXT(Rule_Type__c) = 'Default User',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c),'') 
))))))</formula>
    <label>Rule Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryAssignmentOpportunity.cls
public without sharing class TerritoryAssignmentOpportunity {
    public static Boolean assignTerritoryDone = false;

    public void assignTerritory() {
        Set<Id> contactIdSet = new Set<Id>();
        List<Contact> contactList = new List<Contact>();
        Set<Id> locationSet = new Set<Id>();
        Set<Id> ContactIsFTF = new Set<Id>();

        //Get all Contact IDs and First Time Freshman Contact Ids linked to the Opportunities
        for (Opportunity o : (List<Opportunity>) Trigger.new) {
            contactIdSet.Add(o.Contact__c);
            locationSet.add(o.Admitted_Location__c == null ? o.Location__c : o.Admitted_Location__c);

            if (o.Type == 'First Time Freshman') {
                ContactIsFTF.add(o.Contact__c);
            }
        }

        if (contactIdSet.size() > 0) {
            //Load all contacts attached to the Opportunities
            contactList = [
                SELECT
                    Id,
                    Geomarket_Code__c,
                    MailingPostalCode,
                    MailingState,
                    MailingCountry,
                    Last_HS_Attended__c,
                    Last_College_Attended__c,
                    Last_HS_Attended__r.Territory_Manager__c,
                    Last_HS_Attended__r.Territory_Manager__r.IsActive,
                    Last_HS_Attended__r.Territory_Manager__r.Name,
                    Last_College_Attended__r.Territory_Manager__c,
                    Last_College_Attended__r.Territory_Manager__r.Name,
                    Last_College_Attended__r.Territory_Manager__r.IsActive
                FROM Contact
                WHERE Id IN :contactIdSet
            ];
        }

        /**
         * Start Contact Geomarket Code Evaluation
         */
        if (Trigger.isBefore && contactList.size() > 0) {
            Set<String> ContactZips = new Set<String>();
            Map<String, String> KVMap = new Map<String, String>();
            Set<Id> InstitutionIdSet = new Set<Id>();

            //Load up the last HS and last College attended for all contacts
            //Also load up the Zip codes for all contacts
            for (Contact c : contactList) {
                if (!InstitutionIdSet.contains(c.Last_HS_Attended__c)) {
                    InstitutionIdSet.add(c.Last_HS_Attended__c);
                }

                if (!InstitutionIdSet.contains(c.Last_College_Attended__c)) {
                    InstitutionIdSet.add(c.Last_College_Attended__c);
                }
                //Ensures Zipcode is five digits or less
                string shortZip = TerritoryAssignmentHelper.shortenZipCode(c.MailingPostalCode);
                ContactZips.add(shortZip);
            }

            if (ContactZips.size() > 0 && InstitutionIdSet.size() > 0) {
                //Load all Accounts representing HSs or Colleges attended by Contacts on Opps
                Map<Id, Account> InstMap = new Map<Id, Account>(
                    [SELECT Id, Geomarket_Code__c FROM Account WHERE Id IN :InstitutionIdSet]
                );

                List<Key_Value__c> KVList = [
                    SELECT Id, Geomarket_ZIP__c, Geomarket_Code__c
                    FROM Key_Value__c
                    WHERE RecordType.DeveloperName = 'Geomarket_Code_Map' AND Geomarket_ZIP__c IN :ContactZips
                ];

                for (Key_Value__c K : KVList) {
                    KVMap.put(K.Geomarket_ZIP__c, K.Geomarket_Code__c);
                }

                List<Contact> geoMarketChanged = new List<Contact>();
                //For each contact
                for (Contact Cons : contactList) {
                    //Ensures Zipcode is five digits or less
                    string shortZip = TerritoryAssignmentHelper.shortenZipCode(Cons.MailingPostalCode);

                    //If the contact is a FTF and has a last HS attended
                    //Update the contact's geomarket code to reflect this
                    if (Cons.Last_HS_Attended__c != null && ContactIsFTF.contains(Cons.Id)) {
                        Account thisInstitution = InstMap.get(Cons.Last_HS_Attended__c);
                        if (
                            thisInstitution.Geomarket_Code__c != null &&
                            Cons.Geomarket_Code__c != thisInstitution.Geomarket_Code__c
                        ) {
                            Cons.Geomarket_Code__c = thisInstitution.Geomarket_Code__c;
                            geoMarketChanged.add(Cons);
                        } else if (Cons.Geomarket_Code__c != KVMap.get(shortZip)) {
                            Cons.Geomarket_Code__c = KVMap.get(shortZip);
                            geoMarketChanged.add(Cons);
                        }
                    } else if (Cons.Last_College_Attended__c != null && !ContactIsFTF.contains(Cons.Id)) {
                        //Else if the contact is not an FTF and has a last college attended
                        //Update the contact's geomarket code to reflect this
                        Account thisInstitution = InstMap.get(Cons.Last_College_Attended__c);
                        if (
                            thisInstitution.Geomarket_Code__c != null &&
                            Cons.Geomarket_Code__c != thisInstitution.Geomarket_Code__c
                        ) {
                            Cons.Geomarket_Code__c = thisInstitution.Geomarket_Code__c;
                            geoMarketChanged.add(Cons);
                        } else if (Cons.Geomarket_Code__c != KVMap.get(shortZip)) {
                            Cons.Geomarket_Code__c = KVMap.get(shortZip);
                            geoMarketChanged.add(Cons);
                        }
                    } else if (Cons.Geomarket_Code__c != KVMap.get(shortZip)) {
                        //Else simply update the contact's geomarket code to reflect their postal code
                        Cons.Geomarket_Code__c = KVMap.get(shortZip);
                        geoMarketChanged.add(Cons);
                    }
                }

                if (geoMarketChanged.size() > 0) {
                    TerritoryAssignmentHelper.updateContactList(geoMarketChanged);
                }
            }
        }

        /**
         * Start Territory Assignment Evaluation
         */
        Boolean anyTerritoryAssignmentRequired = false;

        for (Opportunity o : (List<Opportunity>) Trigger.new) {
            // Force all new undergraduate opportunities to be evaluated for territory assignment
            if (Trigger.isInsert) {
                if (o.Career__c != 'Undergraduate') {
                    o.Territory_Assignment_Required__c = false;
                } else {
                    anyTerritoryAssignmentRequired = true;
                    o.Territory_Assignment_Required__c = true;
                }
            } else if (Trigger.isUpdate) {
                // Only evaluate territory assignment for opportunities where a field changes that could impact an assignment
                Map<ID, Opportunity> OpportunityOldMap = (Map<ID, Opportunity>) Trigger.oldMap;

                if (o.Career__c != 'Undergraduate') {
                    o.Territory_Assignment_Required__c = false;
                } else if (
                    o.Territory_Assignment_Required__c == true ||
                    OpportunityOldMap.get(o.Id).Type != o.Type ||
                    OpportunityOldMap.get(o.Id).International_Student__c != o.International_Student__c ||
                    OpportunityOldMap.get(o.Id).Location__c != o.Location__c ||
                    OpportunityOldMap.get(o.Id).StageName != o.StageName ||
                    OpportunityOldMap.get(o.Id).Potential_National_Scholar__c != o.Potential_National_Scholar__c
                ) {
                    anyTerritoryAssignmentRequired = true;
                    o.Territory_Assignment_Required__c = true;
                }
            }
        }

        if (anyTerritoryAssignmentRequired) {
            Map<Id, Contact> contactMap = new Map<Id, Contact>(contactList);
            Map<Id, Location__c> locationMap = new Map<Id, Location__c>(
                [SELECT Id, Name, Location_Code__c FROM Location__c WHERE Id IN :locationSet]
            );

            // Build map with Territory_Assignment_Rule__c Rule_Key__c values
            List<Territory_Assignment_Rule__c> TerritoryAssignmentRuleList = new List<Territory_Assignment_Rule__c>(
                [SELECT Id, Rule_Key__c, User__c, User__r.IsActive FROM Territory_Assignment_Rule__c]
            );

            Map<String, Territory_Assignment_Rule__c> TerritoryAssignmentRuleMap = new Map<String, Territory_Assignment_Rule__c>();
            for (Territory_Assignment_Rule__c TARM : TerritoryAssignmentRuleList) {
                TerritoryAssignmentRuleMap.put(TARM.Rule_Key__c, TARM);
            }

            // Get all of the tars keyed by rule key. Used for international assignment now.
            Map<String, List<Territory_Assignment_Rule__c>> mapOfTarsByRuleKey = TerritoryAssignmentHelper.mapTerritoryAssignmentRulesToRuleKey();

            for (Opportunity Opp : (List<Opportunity>) Trigger.New) {
                Boolean inactiveUserFound = false;
                Contact thisContact = contactMap.get(Opp.Contact__c);
                Location__c thisLocation = locationMap.get(
                    Opp.Admitted_Location__c == null ? Opp.Location__c : Opp.Admitted_Location__c
                );

                if (thisLocation == null) {
                    thisLocation = new Location__c();
                }

                // Start Territory Assignment Rules Evaluation
                if (Opp.Territory_Assignment_Required__c && thisContact != null) {
                    Opp.Territory_Assignment_Required__c = false;
                    Opp.Territory_Assignment_Last_Run__c = Datetime.Now();

                    // Freshman Scholar
                    if (Opp.Type == 'First Time Freshman' && Opp.Potential_National_Scholar__c) {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get('Freshman Scholar');

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Freshman Scholar';

                                continue;
                            }
                        }
                    }

                    // Location
                    if (
                        thisLocation != null &&
                        thisLocation.Location_Code__c != null &&
                        thisLocation.Location_Code__c.equalsIgnoreCase('CALHC')
                    ) {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Location' + '|' + 'Lake Havasu'
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Location - Lake Havasu';

                                continue;
                            }
                        }
                    }

                    // International
                    if (Opp.International_Student__c) {
                        List<Territory_Assignment_Rule__c> possibleTars = new List<Territory_Assignment_Rule__c>();
                        Territory_Assignment_Rule__c tar = null;
                        Decimal oppAssignNumber = Opp.Opportunity_Assignment_Number_Rand__c;
                        String oppCountry = thisContact.MailingCountry;

                        if (String.isNotEmpty(oppCountry)) {
                            oppCountry = TerritoryAssignmentHelper.getSFCountry(oppCountry);
                        }

                        // Avoid NPE on Opportunity Assignment Number Rand. At least one of these should be populated.
                        if (oppAssignNumber == null) {
                            oppAssignNumber = Opp.Opportunity_Assignment_Number__c;
                        }

                        // Begin filter hierarchy
                        if (Opp.StageName == 'Admitted - Conditional') {
                            possibleTars = mapOfTarsByRuleKey.get('International Admitted - Conditional');
                        } else if (Opp.Type == 'Transfer') {
                            possibleTars = mapOfTarsByRuleKey.get('International|Transfer|' + oppCountry);

                            /**
                             * The oppCountry may be defined, but we don't have a Transfer TAR for it.
                             * Use the default TAR for International Transfer
                             */
                            if (possibleTars == null || possibleTars.isEmpty()) {
                                possibleTars = mapOfTarsByRuleKey.get('International|Transfer|');
                            }
                        } else if (String.isNotEmpty(oppCountry)) {
                            possibleTars = mapOfTarsByRuleKey.get('International|' + Opp.Type + '|' + oppCountry);
                        }

                        // Hit the default International manager
                        if (possibleTars == null || possibleTars.isEmpty()) {
                            possibleTars = mapOfTarsByRuleKey.get('International||');
                        }

                        tar = TerritoryAssignmentHelper.getTerritoryAssignmentRule(possibleTars, oppAssignNumber);

                        // As long as we found a relevant Territory Assignment Rule, populate the information on the Opportunity
                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar != null &&
                                    Opp.Territory_Assignment_Last_Rule_Type__c != 'International'
                                    ? tar.User__c
                                    : Opp.OwnerId;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = tar.Rule_Key__c;

                                continue;
                            }
                        }
                    }

                    // Last High School Attended
                    if (
                        thisContact.Last_HS_Attended__c != null &&
                        thisContact.Last_HS_Attended__r.Territory_Manager__c != null &&
                        Opp.Type == 'First Time Freshman'
                    ) {
                        if (thisContact.Last_HS_Attended__r.Territory_Manager__r.IsActive == false) {
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                            inactiveUserFound = true;
                        } else {
                            Opp.OwnerId = thisContact.Last_HS_Attended__r.Territory_Manager__c;
                            Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Last Attended High School';

                            continue;
                        }
                    }

                    // Last College Attended
                    if (
                        thisContact.Last_College_Attended__c != null &&
                        thisContact.Last_College_Attended__r.Territory_Manager__c != null &&
                        Opp.Type == 'First Time Freshman'
                    ) {
                        if (thisContact.Last_College_Attended__r.Territory_Manager__r.IsActive == false) {
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                            inactiveUserFound = true;
                        } else {
                            Opp.OwnerId = thisContact.Last_College_Attended__r.Territory_Manager__c;
                            Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Last Attended College, Type First Time Freshman';

                            continue;
                        }
                    }

                    if (
                        thisContact.Last_College_Attended__c != null &&
                        thisContact.Last_College_Attended__r.Territory_Manager__c != null &&
                        Opp.Type == 'Readmission'
                    ) {
                        if (thisContact.Last_College_Attended__r.Territory_Manager__r.IsActive == false) {
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                            inactiveUserFound = true;
                        } else {
                            Opp.OwnerId = thisContact.Last_College_Attended__r.Territory_Manager__c;
                            Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Last Attended College, Type Readmission';

                            continue;
                        }
                    }

                    if (
                        thisContact.Last_College_Attended__c != null &&
                        thisContact.Last_College_Attended__r.Territory_Manager__c != null &&
                        Opp.Type == 'Transfer'
                    ) {
                        if (thisContact.Last_College_Attended__r.Territory_Manager__r.IsActive == false) {
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                            inactiveUserFound = true;
                        } else {
                            Opp.OwnerId = thisContact.Last_College_Attended__r.Territory_Manager__c;
                            Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                            Opp.Territory_Assignment_Last_Rule_Type__c = 'Last Attended College, Type Transfer';

                            continue;
                        }
                    }

                    // Geomarket Code
                    if (thisContact.Geomarket_Code__c != null && Opp.Type == 'First Time Freshman') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Geomarket' + '|' + Opp.Type + '|' + thisContact.Geomarket_Code__c
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Geomarket, Type First Time Freshman';

                                continue;
                            }
                        }
                    }

                    if (thisContact.Geomarket_Code__c != null && Opp.Type == 'Readmission') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Geomarket' + '|' + Opp.Type + '|' + thisContact.Geomarket_Code__c
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Geomarket, Type Readmission';

                                continue;
                            }
                        }
                    }

                    if (thisContact.Geomarket_Code__c != null && Opp.Type == 'Transfer') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Geomarket' + '|' + Opp.Type + '|' + thisContact.Geomarket_Code__c
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Geomarket, Type Transfer';

                                continue;
                            }
                        }
                    }

                    // State
                    if (thisContact.MailingState != null) {
                        String USState = thisContact.MailingState;
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'State' + '|' + Opp.Type + '|' + USState
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'State, ' + USState + ', Type ' + Opp.Type;

                                continue;
                            }
                        }
                    }

                    // Default User
                    if (Opp.Type == 'Graduate') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';

                                continue;
                            }
                        }
                    } else if (Opp.Type == 'Law') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';

                                continue;
                            }
                        }
                    } else if (Opp.Type == 'First Time Freshman') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                if (!inactiveUserFound) {
                                    Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';
                                }

                                Opp.Territory_Assignment_Required__c = false;

                                continue;
                            }
                        }
                    } else if (Opp.Type == 'Transfer') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';

                                continue;
                            }
                        }
                    } else if (Opp.Type == 'Non-Degree') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';

                                continue;
                            }
                        }
                    } else if (Opp.Type == 'Readmission') {
                        Territory_Assignment_Rule__c tar = TerritoryAssignmentRuleMap.get(
                            'Default User' + '|' + Opp.Type
                        );

                        if (tar != null) {
                            if (tar.User__r.IsActive == false) {
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Inactive Territory Manager';
                                inactiveUserFound = true;
                            } else {
                                Opp.OwnerId = tar.User__c;
                                Opp.Territory_Assignment_Last_Run__c = Datetime.Now();
                                Opp.Territory_Assignment_Last_Rule_Type__c = 'Default User';

                                continue;
                            }
                        }
                    }
                }
            }
        }

        assignTerritoryDone = true;
    }
}