src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject><fields>
        <fullName>Active_Relationship__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, indicates that this Relationship is Active.</description>
        <inlineHelpText>Indicates the Relationship is current. Will automatically be set to false when:
1. The Relationship End Date is set to a value in the past - OR -
2. A Relationship End Date set for the future is reached.</inlineHelpText>
        <label>Active Relationship</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Relationship_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Records the date this Relationship began.</description>
        <inlineHelpText>The date this Relationship began. Will automatically be set to Today's date, but can be edited.</inlineHelpText>
        <label>Relationship Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Defines the type or Relationship (e.g. Employee, Parent, Spouse).</description>
        <label>Relationship Type (is)</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization/Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <description>The Contact's Title. Used in Contact to Account relationships.</description>
        <inlineHelpText>Used for Contact to Account Relationships to indicate the Contact's Title at the associated Account.</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Relationship</label><nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Relationships</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person tracked on this Relationship Record. Used in Contact to Account and Contact to Contact Relationships.</description>
    <inlineHelpText>The person tracked on this Relationship Record.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated organization in an Account to Account Relationship. Used in Account to Account Relationships only. Note that the Related List from this Lookup is never to be added to a page layout.</description>
    <inlineHelpText>The associated organization in an Account to Account Relationship.</inlineHelpText>
    <label>Related Account (of)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Can only associate contacts to ORG Accounts</errorMessage>
        <filterItems>
            <field>Account.Contact__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships - Related Account</relationshipLabel>
    <relationshipName>Reciprocal_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationships__c.object
<CustomObject>
    <fields>
        <fullName>Reciprocal__c</fullName>
        <label>Reciprocal</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <customSettingsType>List</customSettingsType>
    <description>Value Pairs of Relationship Types (e.g. Parent - Child, Mentor - Mentee).</description>
    <label>Relationships</label>
</CustomObject>

force-app/main/default/classes/NewCorporateRelationsControllerTest.cls
@isTest
private class NewCorporateRelationsControllerTest {
    private static Campaign testCampaign;
    private static Campaign testChildCampaign;
    private static Account testAccount;
    private static Contact testContact;
    private static Relationship__c testR;
    private static CampaignMember testCM;
    private static Id crId;
    private static NewCorporateRelationsContactController ncr;

    private static void setupData() {
        // Create custom setting to store the recip values
        Relationships__c partnerRel = new Relationships__c();
        partnerRel.Name = 'Partner';
        partnerRel.Reciprocal__c = 'Partner';

        insert partnerRel;

        crId = [SELECT Id FROM RecordType WHERE Name = 'Corporate Relations' AND SobjectType = 'Campaign'].Id;

        testCampaign = new Campaign(Name = 'Test Campaign', RecordTypeId = crId);

        insert testCampaign;

        testChildCampaign = new Campaign(Name = 'Test Child Campaign', ParentId = testCampaign.Id, RecordTypeId = crId);

        insert testChildCampaign;

        testAccount = new Account(Name = 'Test Account', Website = 'www.example.com');

        insert testAccount;

        testContact = new Contact(FirstName = 'John', LastName = 'Doe');

        insert testContact;

        testR = new Relationship__c(
            Related_Account__c = testAccount.Id,
            Active_Relationship__c = true,
            Contact__c = testContact.Id,
            Title__c = 'Test Title',
            Relationship_Type__c = 'Partner',
            Relationship_Start_Date__c = Date.today()
        );

        insert testR;

        testCM = new CampaignMember(CampaignId = testCampaign.Id, ContactId = testContact.Id);

        insert testCM;

        ncr = new NewCorporateRelationsContactController();
    }

    @isTest
    static void testSave() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.getRelTypeOptions();
        ncr.contact = testContact;
        ncr.relationship = testR;
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        ncr.getCampaignOptions();
        ncr.populateChildCampaigns();
        PageReference confirmSave = new PageReference('/' + testContact.Id);
        System.assertEquals(confirmSave.getUrl(), ncr.save().getUrl());
    }

    @isTest
    static void testInsertAccount() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.account = testAccount;
        ncr.cancelAccount();
        ncr.page3();
        ncr.page6();
        ncr.backToRelationship();
        ncr.click();
        ncr.insertAccount();
        List<Account> accountList = [SELECT Id FROM Account];

        System.assertNotEquals(null, accountList);
    }

    @isTest
    static void testInsertRelationship() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.relationship = testR;
        ncr.addRelationshipPage();
        ncr.insertRelationship();
        List<Relationship__c> relList = [SELECT Id FROM Relationship__c];

        System.assertNotEquals(null, relList);
    }

    @isTest
    static void testInsertCampaignMember() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.page5();
        ncr.addCampaignPage();
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        ncr.getCampaignOptions();
        ncr.populateChildCampaigns();
        ncr.insertCampaignMember();
        List<CampaignMember> camMemList = [SELECT Id FROM CampaignMember];

        System.assertNotEquals(null, camMemList);
    }

    @isTest
    static void testSaveAndNew() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.contact = testContact;
        ncr.relationship = testR;
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        ncr.getCampaignOptions();
        ncr.populateChildCampaigns();
        PageReference confirmSave = ApexPages.currentPage();

        System.assertEquals(confirmSave.getUrl(), ncr.saveAndNew().getUrl());
    }

    @isTest
    static void testAddPageSave() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.contact = testContact;
        ncr.relationship = testR;
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        ncr.getCampaignOptions();
        ncr.populateChildCampaigns();
        ncr.page2();
        ncr.addPage();
        ncr.relationship = testR;
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        PageReference confirmSave = new PageReference('/' + testContact.Id);

        System.assertEquals(confirmSave.getUrl(), ncr.save().getUrl());
    }

    @isTest
    static void testValidations() {
        setupData();
        PageReference crPage = Page.NewCorporateRelationsContact;
        Test.setCurrentPage(crPage);
        ncr.relationship.Relationship_Type__c = null;
        ncr.insertRelationship();
        ncr.selectedParentId = null;
        ncr.addPage();
        ncr.saveAndNew();
        ncr.insertCampaignMember();
        ncr.cancelAndSaveRelationship();
        ncr.cancelAndSaveCampaignMember();
        ncr.cancelAndSave();
        ncr.relationshipSaveAndNew();
        ncr.campaignMemberSaveAndNew();
        ncr.contact = testContact;
        ncr.relationship = testR;
        ncr.selectedParentId = testCampaign.Id;
        ncr.selectedChildId = testChildCampaign.Id;
        ncr.getCampaignOptions();
        ncr.populateChildCampaigns();
        ncr.insertRelationship();
        ncr.insertCampaignMember();
        ncr.cancelAndSaveRelationship();
        ncr.cancelAndSaveCampaignMember();
        ncr.cancelAndSave();
        ncr.relationshipSaveAndNew();
        ncr.campaignMemberSaveAndNew();
        ncr.addRelationshipPage();
        ncr.relationship.Relationship_Type__c = null;
        ncr.addRelationshipPage();
        ncr.relationship.Relationship_Type__c = 'Email';
        ncr.addCampaignPage();
    }
}