src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[import] - Examples include: Undergraduate, Graduate</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Convert_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[import] - If a Contact is connected here, the Lead will automatically convert to that Contact (without an Opportunity).</description>
        <inlineHelpText>If a Contact  is connected here, the Lead will automatically convert to that Contact (without an Opportunity).</inlineHelpText>
        <label>Convert: Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[import] - Look up to the term object</description>
        <label>Enrollment Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Lead_Term</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the prospective student is the first to attend college from his/her family.</description>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the student meets certain criteria that labels he or she as an international student.</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Web form question: Check here if interested in earning your degree exclusively Online</description>
        <inlineHelpText>If checked, the student is interested in earning their degree online.</inlineHelpText>
        <label>Interested in Online Degree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Potential National Scholar checkbox</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Western Undergraduate Exchange - a prospective student who might be eligible for reduced tuition rate based on the students geographic location and other criteria.</description>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Segment__c</fullName>
        <description>[import] - Examples include: Admissible, Barrett Eligible, Scholar, Under Admissible</description>
        <label>Search Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admissible</fullName>
                </value>
                <value>
                    <fullName>Barrett Eligible</fullName>
                </value>
                <value>
                    <fullName>Scholar</fullName>
                </value>
                <value>
                    <fullName>Under Admissible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Self_Reported_SES__c</fullName>
        <description>Socioeconomic status (SES) is determined by a combination of parental income, 
education, occupation, and household items.</description>
        <inlineHelpText>Socioeconomic status reported by the prospective student.</inlineHelpText>
        <label>Self-Reported SES</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Very High</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Undergraduate, Graduate, Law</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[???] - Student is a first generation college student</description>
        <inlineHelpText>Student is a first generation college student</inlineHelpText>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Manual import, purchased lists, prospect forms, F1/J1, webforms] - Checkbox to if student is international</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online_Degree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Webform or manual entry] - Checkbox to indicate they are interested in online education</description>
        <label>Interested in Online Degree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[manual import] - Checkbox if the opportunity is a potential National Scholar</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Segment__c</fullName>
        <description>[??] - Examples Include: Admissible, Barrett Eligible, Scholar, Under Admissible</description>
        <label>Search Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admissible</fullName>
                </value>
                <value>
                    <fullName>Barrett Eligible</fullName>
                </value>
                <value>
                    <fullName>Scholar</fullName>
                </value>
                <value>
                    <fullName>Under Admissible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Self_Reported_SES__c</fullName>
        <description>Socioeconomic status (SES) is determined by a combination of parental income, 
education, occupation, and household items.</description>
        <inlineHelpText>Socioeconomic status reported by the prospective student.</inlineHelpText>
        <label>Self-Reported SES</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Very High</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[peoplesoft] - Picklist with the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plan__c.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Graduate, Law, Undergraduate</description>
        <label>(DO NOT USE) Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Listing of all Plans (majors)</description>
    <label>Plan</label>
    <nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plans</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples inlcude: Graduate, Law, Non-Credit, Undergraduate</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Non-Credit</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Listing of all University programs (Colleges)</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/OpportunityService.cls
public class OpportunityService {
    /**
     * Creates an undergraduate prospect opportunity
     * @param contactToAssociate A contact that will be associated
     * @return undergradProspect An undergraduate prospect opportunity
     */

    static Id undergradProspectId;
    static Id gradProspectId;

    private static void loadIds() {
        List<RecordType> prospectIds = [
            SELECT Id, Name
            FROM RecordType
            WHERE (Name = 'Undergraduate Prospect' OR Name = 'Graduate Prospect') AND SobjectType = 'Opportunity'
        ];

        for (RecordType id : prospectIds) {
            if (id.Name == 'Undergraduate Prospect') {
                undergradProspectId = id.Id;
            }
            if (id.Name == 'Graduate Prospect') {
                gradProspectId = id.Id;
            }
        }
    }

    public static Opportunity createTestUndergraduateProspect(Contact contactToAssociate) {
        Date closeDate = Date.today();
        if (undergradProspectId == null) {
            loadIds();
        }

        Opportunity undergradProspect = new Opportunity();
        undergradProspect.Contact__c = contactToAssociate.Id;
        undergradProspect.RecordTypeId = undergradProspectId;
        undergradProspect.StageName = 'Prospect';
        undergradProspect.CloseDate = closeDate.addYears(1);
        undergradProspect.Name = 'Test Opportunity';
        undergradProspect.AccountId = contactToAssociate.AccountId;

        return undergradProspect;
    }

    /**
     * Creates one Undergraduate Prospect opportunity for each contact provided.
     * @param contactsToAssociate A list of contacts
     * @return oppList A list of undergraduate prospect opportunities
     */
    public static List<Opportunity> createTestUndergraduateProspects(List<Contact> contactsToAssociate) {
        List<Opportunity> undergradProspects = new List<Opportunity>();

        Date closeDate = Date.today();

        if (undergradProspectId == null) {
            loadIds();
        }

        for (Contact con : contactsToAssociate) {
            Opportunity o = new Opportunity();
            o.Contact__c = con.Id;
            o.RecordTypeId = undergradProspectId;
            o.StageName = 'Prospect';
            o.CloseDate = closeDate.addYears(1);
            o.Name = 'Test Opportunity for ' + con.Name;
            o.AccountId = con.AccountId;
            undergradProspects.add(o);
        }

        return undergradProspects;
    }

    /**
     * Creates one Graduate Prospect opportunity for each contact provided.
     * @param contactsToAssociate A list of contacts
     * @return oppList A list of undergraduate prospect opportunities
     */
    public static List<Opportunity> createTestGraduateProspects(List<Contact> contactsToAssociate) {
        List<Opportunity> gradProspects = new List<Opportunity>();

        Date closeDate = Date.today();

        if (gradProspectId == null) {
            loadIds();
        }

        for (Contact con : contactsToAssociate) {
            Opportunity o = new Opportunity();
            o.Contact__c = con.Id;
            o.RecordTypeId = gradProspectId;
            o.StageName = 'Prospect';
            o.CloseDate = closeDate.addYears(1);
            o.Name = 'Test Opportunity for ' + con.Name;
            o.AccountId = con.AccountId;
            gradProspects.add(o);
        }

        return gradProspects;
    }

    /**
     * Generates a random number for Territory Assignment
     * @return randNumber A random Integer between 0 and 100
     */
    public static Integer generateOpportunityAssignmentNumber() {
        Double randNumber = Math.random() * 100;

        return randNumber.intValue();
    }

    /**
     * Finds all Opportunities that are tied to a Leads Convert_Contact__c and
     * updates information from a Lead on the Opportunites.
     * @param Set<Id> A set of lead ids to map to opportunities
     * @return List<Opportunity> A list of opportunities with the mapped lead data
     */
    public static List<Opportunity> mapLeadDataToOpportunity(Set<Id> leadIds) {
        List<Lead> leadsFromConversion = new List<Lead>();
        Map<Id, Lead> contactIdToLeadMap = new Map<Id, Lead>();
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();

        Map<String, String> opportunityToLeadFields = new Map<String, String>{
            'Career__c' => 'Career__c',
            'Term__c' => 'Enrollment_Term__c',
            'First_Generation__c' => 'First_Generation__c',
            'Online_Degree__c' => 'Online__c',
            'International_Student__c' => 'International_Student__c',
            'Potential_National_Scholar__c' => 'Potential_National_Scholar__c',
            'Potential_WUE__c' => 'Potential_WUE__c',
            'Search_Segment__c' => 'Search_Segment__c',
            'Self_Reported_SES__c' => 'Self_Reported_SES__c',
            'Military_Status__c' => 'Veteran_Status__c'
        };

        String leadQueryFields = '';
        String oppQueryFields = '';

        // Build a string for querying all the lead fields
        for (String s : opportunityToLeadFields.values()) {
            leadQueryFields += s + ', ';
        }

        leadQueryFields = leadQueryFields.subString(0, leadQueryFields.length() - 2);

        String leadQuery = 'SELECT ConvertedContactId, ' + leadQueryFields + ' FROM Lead WHERE Id IN :leadIds';

        leadsFromConversion = Database.query(leadQuery);

        // Map the Contact Ids to the Lead Data
        for (Lead newLead : leadsFromConversion) {
            contactIdToLeadMap.put(newLead.ConvertedContactId, newLead);
        }

        Set<Id> contactIds = contactIdToLeadMap.keySet();

        // Bulid a string for querying all the opportunity fields
        for (String s : opportunityToLeadFields.keySet()) {
            oppQueryFields += s + ', ';
        }

        oppQueryFields = oppQueryFields.subString(0, oppQueryFields.length() - 2);

        // Get all the opportunities associated with these contacts
        String oppQuery = 'SELECT Contact__c, ' + oppQueryFields + ' FROM Opportunity WHERE Contact__c IN :contactIds';
        opportunitiesToUpdate = Database.query(oppQuery);

        // Update all the opportunity information
        for (Opportunity opp : opportunitiesToUpdate) {
            Lead leadData = contactIdToLeadMap.get(opp.Contact__c);

            for (String oppField : opportunityToLeadFields.keySet()) {
                if (opp.get(oppField) == null) {
                    String leadField = opportunityToLeadFields.get(oppField);
                    opp.put(oppField, leadData.get(leadField));
                }
            }
        }

        return opportunitiesToUpdate;
    }

    public static void populateNullContactsFromAccounts(List<Opportunity> newOpportunities) {
        Set<Id> accountIds = new Set<Id>();
        Map<Id, Account> accountMap = new Map<Id, Account>();

        for (Opportunity newOpportunity : newOpportunities) {
            if (newOpportunity.AccountId != null && newOpportunity.Contact__c == null) {
                accountIds.add(newOpportunity.AccountId);
            }
        }

        if (accountIds.size() > 0) {
            accountMap = new Map<Id, Account>([SELECT Id, Contact__c FROM Account WHERE Id IN :accountIds]);
        }

        for (Opportunity newOpportunity : newOpportunities) {
            newOpportunity.Opportunity_Assignment_Number_Rand__c = generateOpportunityAssignmentNumber();
            if (newOpportunity.Contact__c == null) {
                Account oppsAccount = accountMap.get(newOpportunity.AccountId);
                newOpportunity.Contact__c = oppsAccount.Contact__c;
            }
        }
    }

    public static void updateCollegeIfPlanChanged(
        List<Opportunity> updatedOpportunities,
        Map<Id, Opportunity> previousOpportunitiesMap
    ) {
        List<Id> planIds = new List<Id>();
        Map<Id, Id> programColleges = new Map<Id, Id>();

        for (Opportunity updatedOpportunity : updatedOpportunities) {
            Opportunity previousOpportunity = previousOpportunitiesMap.get(updatedOpportunity.Id);
            if (updatedOpportunity.Academic_Plan__c != previousOpportunity.Academic_Plan__c) {
                planIds.add(updatedOpportunity.Academic_Plan__c);
            }
            if (updatedOpportunity.Admitted_Plan__c != previousOpportunity.Admitted_Plan__c) {
                planIds.add(updatedOpportunity.Admitted_Plan__c);
            }
        }

        for (Plan__c plan : [SELECT Id, Program__c FROM Plan__c WHERE Id IN :planIds]) {
            programColleges.put(plan.Id, plan.Program__c);
        }

        for (Opportunity updatedOpportunity : updatedOpportunities) {
            Opportunity previousOpportunity = previousOpportunitiesMap.get(updatedOpportunity.Id);
            if (
                updatedOpportunity.Admitted_Plan__c != null &&
                updatedOpportunity.Admitted_Plan__c != previousOpportunity.Admitted_Plan__c
            ) {
                updatedOpportunity.College__c = programColleges.get(updatedOpportunity.Admitted_Plan__c);
            } else if (
                updatedOpportunity.Academic_Plan__c != null &&
                updatedOpportunity.Academic_Plan__c != previousOpportunity.Academic_Plan__c
            ) {
                updatedOpportunity.College__c = programColleges.get(updatedOpportunity.Academic_Plan__c);
            }
        }
    }
}