src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - Relationship field to the Contact record</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts_Contact</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SF_Birthdate_Updated__c</fullName>
        <label>SF.Birthdate Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Birthdate__c</fullName>
        <label>SF.Birthdate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SF_First_Name_Updated__c</fullName>
        <label>SF.First Name Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_First_Name__c</fullName>
        <label>SF.First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Last_Name_Updated__c</fullName>
        <label>SF.Last Name Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Last_Name__c</fullName>
        <label>SF.Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Address_Updated__c</fullName>
        <label>SF.Mailing Address Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_City__c</fullName>
        <label>SF.Mailing City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Country__c</fullName>
        <label>SF.Mailing Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_State__c</fullName>
        <label>SF.Mailing State</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_Street__c</fullName>
        <label>SF.Mailing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>SF_Mailing_ZIP__c</fullName>
        <label>SF.Mailing ZIP</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SF_Mobile_Updated__c</fullName>
        <label>SF.Mobile Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>SF_Mobile__c</fullName>
        <label>SF.Mobile</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject><fields>
        <fullName>Active_Relationship__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If checked, indicates that this Relationship is Active.</description>
        <inlineHelpText>Indicates the Relationship is current. Will automatically be set to false when:
1. The Relationship End Date is set to a value in the past - OR -
2. A Relationship End Date set for the future is reached.</inlineHelpText>
        <label>Active Relationship</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Relationship_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <description>Records the date this Relationship began.</description>
        <inlineHelpText>The date this Relationship began. Will automatically be set to Today's date, but can be edited.</inlineHelpText>
        <label>Relationship Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Relationship_Type__c</fullName>
        <description>Defines the type or Relationship (e.g. Employee, Parent, Spouse).</description>
        <label>Relationship Type (is)</label>
        <picklist>
            <picklistValues>
                <fullName>Child</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sibling</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Spouse</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Volunteer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent/Guardian</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Intern Employer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Organization/Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Member</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parent Organization</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Subsidiary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Affiliate Organization</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Title__c</fullName>
        <description>The Contact's Title. Used in Contact to Account relationships.</description>
        <inlineHelpText>Used for Contact to Account Relationships to indicate the Contact's Title at the associated Account.</inlineHelpText>
        <label>Title</label>
        <length>100</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Relationship</label><nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Relationships</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The organization tracked on this Relationship Record. Used in Contact to Account and Account to Account Relationships.</description>
    <inlineHelpText>The organization tracked on this Relationship Record.</inlineHelpText>
    <label>Account</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Can only associate contacts with Org accounts</errorMessage>
        <filterItems>
            <field>Account.Contact__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person tracked on this Relationship Record. Used in Contact to Account and Contact to Contact Relationships.</description>
    <inlineHelpText>The person tracked on this Relationship Record.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Relationship__c/fields/Related_Account__c.field-meta.xml
<CustomField>
    <fullName>Related_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The associated organization in an Account to Account Relationship. Used in Account to Account Relationships only. Note that the Related List from this Lookup is never to be added to a page layout.</description>
    <inlineHelpText>The associated organization in an Account to Account Relationship.</inlineHelpText>
    <label>Related Account (of)</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Can only associate contacts to ORG Accounts</errorMessage>
        <filterItems>
            <field>Account.Contact__c</field>
            <operation>equals</operation>
            <value></value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Relationships - Related Account</relationshipLabel>
    <relationshipName>Reciprocal_Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/NewCorporateRelationsContactController.cls
public class NewCorporateRelationsContactController {
    public Account account { get; set; }
    public Contact contact { get; set; }
    public RecordType crRecordType { get; set; }
    public Relationship__c relationship { get; set; }
    public Boolean showCancel { get; set; }
    public Boolean clickedAccount { get; set; }
    public Integer page { get; set; }
    public List<Relationship__c> relationshipList { get; set; }
    public List<CampaignMember> campaignMemberList { get; set; }
    public List<SelectOption> campaignOptions;
    public List<SelectOption> childCampaignOptions { get; set; }
    public List<SelectOption> relTypeOptions;
    public List<Campaign> crCampaigns;
    public List<Campaign> childCrCampaigns;
    public Set<String> currentSet;
    public String selectedParentId { get; set; }
    public String selectedChildId { get; set; }

    public Id contactToAccountRTId {
        get {
            if (contactToAccountRTId == null) {
                contactToAccountRTId = [
                    SELECT Id
                    FROM RecordType
                    WHERE SObjectType = 'Relationship__c' AND Name = 'Contact To Account'
                    LIMIT 1
                ]
                .Id;
            }

            return contactToAccountRTId;
        }
        set;
    }

    public NewCorporateRelationsContactController() {
        page = 1;
        account = new Account();
        contact = new Contact();
        crRecordType = new RecordType();
        currentSet = new Set<String>();
        relationship = new Relationship__c();
        relationship.recordTypeId = contactToAccountRTId;
        relationshipList = new List<Relationship__c>();
        campaignMemberList = new List<CampaignMember>();
        crRecordType = [SELECT Id FROM RecordType WHERE Name = 'Corporate Relations' AND SobjectType = 'Campaign'];
    }

    public List<SelectOption> getCampaignOptions() {
        crCampaigns = [
            SELECT Id, Name, RecordTypeId
            FROM Campaign
            WHERE RecordTypeId = :crRecordType.Id AND IsActive = TRUE AND ParentId = NULL
            ORDER BY Name ASC
        ];

        campaignOptions = new List<SelectOption>();
        campaignOptions.add(new SelectOption('', '--Select--'));
        for (Campaign c : crCampaigns) {
            campaignOptions.add(new SelectOption(c.Id, c.Name));
        }

        return campaignOptions;
    }

    public void populateChildCampaigns() {
        childCrCampaigns = [
            SELECT Id, Name, RecordTypeId
            FROM Campaign
            WHERE RecordTypeId = :crRecordType.Id AND IsActive = TRUE AND ParentId = :selectedParentId
            ORDER BY Name ASC
        ];

        childCampaignOptions = new List<SelectOption>();
        if (childCrCampaigns == null) {
            childCampaignOptions.add(new SelectOption('', '--Select--'));
        } else {
            childCampaignOptions.add(new SelectOption('', 'None'));
        }

        for (Campaign c : childCrCampaigns) {
            childCampaignOptions.add(new SelectOption(c.Id, c.Name));
        }
    }

    public List<SelectOption> getRelTypeOptions() {
        Schema.DescribeFieldResult fieldResult = Relationship__c.Relationship_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        relTypeOptions = new List<SelectOption>();
        relTypeOptions.add(new SelectOption('', '--Select--'));
        for (Schema.PicklistEntry f : ple) {
            if (f.getValue() == 'Employee' || f.getValue() == 'Member' || f.getValue() == 'Volunteer') {
                relTypeOptions.add(new SelectOption(f.getLabel(), f.getValue()));
            }
        }
        return relTypeOptions;
    }

    public void addRelationship() {
        Relationship__c rNew = new Relationship__c();
        rNew.Title__c = relationship.Title__c;
        rNew.Related_Account__c = relationship.Account__c;
        rNew.Relationship_Type__c = relationship.Relationship_Type__c;
        rNew.Relationship_Start_Date__c = relationship.Relationship_Start_Date__c;
        relationshipList.add(rNew);
    }

    public void addParentCampaignMember() {
        CampaignMember pNew = new CampaignMember();
        pNew.CampaignId = selectedParentId;
        if (!currentSet.contains(selectedParentId)) {
            campaignMemberList.add(pNew);
            currentSet.add(selectedParentId);
        }
    }

    public void addCampaignMember() {
        if (selectedChildId != null) {
            CampaignMember cNew = new CampaignMember();
            cNew.CampaignId = selectedChildId;
            if (!currentSet.contains(selectedChildId)) {
                campaignMemberList.add(cNew);
                currentSet.add(selectedChildId);
            }
        }
    }

    public PageReference page2() {
        page = 2;

        return ApexPages.currentPage();
    }

    public PageReference page3() {
        page = 3;

        return ApexPages.currentPage();
    }

    public PageReference page4() {
        page = 4;

        return ApexPages.currentPage();
    }

    public PageReference page5() {
        page = 5;

        return ApexPages.currentPage();
    }

    public PageReference page6() {
        page = 6;

        return ApexPages.currentPage();
    }

    public void addPage() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return;
        }

        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );

            return;
        }
        addRelationship();
        addParentCampaignMember();
        addCampaignMember();
        showCancel = true;
        relationship = null;
        relationship = new Relationship__c();
        relationship.RecordTypeId = contactToAccountRTId;
        selectedParentId = null;
        selectedChildId = null;
        childCampaignOptions = null;
    }

    public void addRelationshipPage() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return;
        }

        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );
            return;
        }
        addRelationship();
        addParentCampaignMember();
        addCampaignMember();
        relationship = null;
        relationship = new Relationship__c();
        relationship.RecordTypeId = contactToAccountRTId;
        page = 4;
    }

    public void addCampaignPage() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return;
        }

        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );

            return;
        }
        addRelationship();
        addParentCampaignMember();
        addCampaignMember();
        relationship = null;
        relationship = new Relationship__c();
        relationship.RecordTypeId = contactToAccountRTId;
        selectedParentId = null;
        selectedChildId = null;
        childCampaignOptions = null;
        page = 5;
    }

    public Boolean validateRT() {
        if (relationship.Relationship_Type__c == null) {
            return false;
        } else {
            return true;
        }
    }

    public Boolean validateDA() {
        if (selectedParentId == null) {
            return false;
        } else {
            return true;
        }
    }

    public void click() {
        clickedAccount = true;
    }

    public void backToRelationship() {
        page4();
    }

    public void cancelAccount() {
        page2();
    }

    public PageReference insertAccount() {
        try {
            insert account;
            page = 2;

            return ApexPages.currentPage();
        } catch (Exception e) {
        }

        return null;
    }

    public PageReference insertRelationship() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return null;
        }

        addRelationship();
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public PageReference insertCampaignMember() {
        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );

            return null;
        }
        addParentCampaignMember();
        addCampaignMember();
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public PageReference cancelAndSaveCampaignMember() {
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public PageReference cancelAndSaveRelationship() {
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public PageReference cancelAndSave() {
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public PageReference relationshipSaveAndNew() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return null;
        }
        addRelationship();
        saveToDatabase();
        PageReference submit = ApexPages.currentPage();
        submit.setRedirect(true);

        return submit;
    }

    public PageReference campaignMemberSaveAndNew() {
        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );
            return null;
        }
        addParentCampaignMember();
        addCampaignMember();
        saveToDatabase();
        PageReference submit = ApexPages.currentPage();
        submit.setRedirect(true);

        return submit;
    }

    public PageReference saveAndNew() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );
            return null;
        }

        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );

            return null;
        }
        addRelationship();
        addParentCampaignMember();
        addCampaignMember();
        saveToDatabase();
        PageReference submit = ApexPages.currentPage();
        submit.setRedirect(true);

        return submit;
    }

    public PageReference save() {
        if (!validateRT()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Relationship Type.')
            );

            return null;
        }
        if (!validateDA()) {
            ApexPages.addmessage(
                new ApexPages.message(ApexPages.severity.ERROR, 'You must select a Department Affiliation.')
            );

            return null;
        }
        addRelationship();
        addParentCampaignMember();
        addCampaignMember();
        saveToDatabase();
        PageReference submit = new PageReference('/' + contact.Id);
        submit.setRedirect(true);

        return submit;
    }

    public void saveToDatabase() {
        try {
            contact.Corporate_Relations_Email__c = contact.Email;
            contact.SF_First_Name__c = contact.FirstName;
            contact.SF_First_Name_Updated__c = Datetime.now();
            contact.SF_Last_Name__c = contact.LastName;
            contact.SF_Last_Name_Updated__c = Datetime.now();
            contact.SF_Mobile__c = contact.MobilePhone;
            contact.SF_Mobile_Updated__c = Datetime.now();
            contact.SF_Mailing_Street__c = contact.MailingStreet;
            contact.SF_Mailing_City__c = contact.MailingCity;
            contact.SF_Mailing_Country__c = contact.MailingCountryCode;
            contact.SF_Mailing_State__c = contact.MailingStateCode;
            contact.SF_Mailing_ZIP__c = contact.MailingPostalCode;
            contact.SF_Mailing_Address_Updated__c = Datetime.now();
            contact.SF_Birthdate__c = contact.Birthdate;
            contact.SF_Birthdate_Updated__c = Datetime.now();

            insert contact;

            for (Relationship__c r : relationshipList) {
                r.Active_Relationship__c = true;
                r.Contact__c = contact.Id;
                r.recordTypeId = contactToAccountRTID;
            }

            insert relationshipList;

            for (CampaignMember c : campaignMemberList) {
                c.ContactId = contact.Id;
            }

            insert campaignMemberList;
        } catch (exception e) {
        }
    }
}