src/objects/Auto_Subscriber_Setting__mdt.object
<CustomObject>
    <description>Contains objects to enable and disable various auto subscribe filters.</description>
    <label>Auto Subscriber Setting</label>
    <pluralLabel>Auto Subscriber Settings</pluralLabel>
</CustomObject>

src/objects/Student_Program_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/AutoSubscriberService.cls
public with sharing class AutoSubscriberService {
    List<sObject> recordsToProcess { get; set; }
    AutoSubscriberHelper helper;
    @TestVisible
    List<Database.UpsertResult> results;

    public AutoSubscriberService(List<sObject> recordsToProcess, String typeOfObject) {
        this.recordsToProcess = recordsToProcess;
        helper = new AutoSubscriberHelper(typeOfObject);
    }

    public void processStudentProgramPlanRecords() {
        List<Student_Program_Plan__c> convertedRecordsToProcess = (List<Student_Program_Plan__c>) recordsToProcess;
        List<Subscriber__c> subsToCreate = new List<Subscriber__c>();
        List<Id> subscriptionIdsForSubs = new List<Id>();
        helper.buildContactToSubscriberMapWithProgramPlan(convertedRecordsToProcess);

        for (Auto_Subscriber_Setting__mdt subSetting : helper.settingToSubscription.keyset()) {
            subscriptionIdsForSubs.addAll(helper.settingToSubscription.get(subSetting));
        }

        helper.createSubscriptionParentMap(subscriptionIdsForSubs);

        for (Student_Program_Plan__c programPlan : convertedRecordsToProcess) {
            for (Auto_Subscriber_Setting__mdt subSetting : helper.settingToSubscription.keyset()) {
                if (AutoSubscriberFilterHelper.filterProgramPlan(subSetting.DeveloperName, programPlan)) {
                    subsToCreate.addAll(
                        helper.createSubscriber(programPlan.Contact__c, helper.settingToSubscription.get(subSetting))
                    );
                }
            }
        }

        if (!subsToCreate.isEmpty()) {
            results = Database.upsert(subsToCreate, false);
        }
    }

    public void processCampaignMemberRecords() {
        List<CampaignMember> convertedRecordsToProcess = (List<CampaignMember>) recordsToProcess;
        List<Subscriber__c> subsToCreate = new List<Subscriber__c>();
        List<Id> subscriptionIdsForSubs = new List<Id>();
        helper.buildContactToSubscriberMapWithCampaignMember(convertedRecordsToProcess);
        helper.setCampaignAndOpportunityInformation(convertedRecordsToProcess);

        for (Auto_Subscriber_Setting__mdt subSetting : helper.settingToSubscription.keyset()) {
            subscriptionIdsForSubs.addAll(helper.settingToSubscription.get(subSetting));
        }

        helper.createSubscriptionParentMap(subscriptionIdsForSubs);

        for (CampaignMember member : convertedRecordsToProcess) {
            for (Auto_Subscriber_Setting__mdt subSetting : helper.settingToSubscription.keyset()) {
                if (AutoSubscriberFilterHelper.filterCampaignMember(subSetting.DeveloperName, member)) {
                    subsToCreate.addAll(
                        helper.createSubscriber(member.ContactId, helper.settingToSubscription.get(subSetting))
                    );
                }
            }
        }

        if (!subsToCreate.isEmpty()) {
            results = Database.upsert(subsToCreate, false);
        }
    }
}