src/objects/Auto_Subscriber_Setting__mdt.object
<CustomObject>
    <description>Contains objects to enable and disable various auto subscribe filters.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Related_Object__c</fullName>
        <description>Select the object that this rule should correspond with.</description>
        <inlineHelpText>Select the object that this rule should correspond with.</inlineHelpText>
        <label>Related Object</label>
        <referenceTo>EntityDefinition</referenceTo>
        <relationshipLabel>Auto_Subscriber_Settings</relationshipLabel>
        <relationshipName>Auto_Subscriber_Settings</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Subscriptions_To_Add__c</fullName>
        <description>A list of all the subscriptions that a subscriber should be added for, for this setting.</description>
        <inlineHelpText>Please add each Subscription you would like the user to be added to separated by a comma (No Spaces)</inlineHelpText>
        <label>Subscriptions To Add</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Auto Subscriber Setting</label>
    <pluralLabel>Auto Subscriber Settings</pluralLabel>
</CustomObject>

src/objects/Student_Program_Plan__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/AutoSubscriberService.cls
public with sharing class AutoSubscriberService {
    List<sObject> recordsToProcess {get; set;}
    String typeOfObject;
    Map<Auto_Subscriber_Setting__mdt, List<String>> settingToSubscription;

    public AutoSubscriberService(List<sObject> recordsToProcess, String typeOfObject) {
        settingToSubscription = new Map<Auto_Subscriber_Setting__mdt, List<String>>();
        this.recordsToProcess = recordsToProcess;
        this.typeOfObject = typeOfObject;

        createSubscriptionMap();
    }

    private void createSubscriptionMap() {
        List<Auto_Subscriber_Setting__mdt> subscriberSettings = [
            SELECT Subscriptions_To_Add__c, DeveloperName
            FROM Auto_Subscriber_Setting__mdt
            WHERE Active__c = true AND
            Related_Object__r.DeveloperName =: typeOfObject
        ];

        for (Auto_Subscriber_Setting__mdt subSetting : subscriberSettings) {
            List<String> subscriptionIds = new List<String>();

            if (subSetting.Subscriptions_To_Add__c != null) {
                subscriptionIds = subSetting.Subscriptions_To_Add__c.split(',');
            }

            settingToSubscription.put(subSetting, subscriptionIds);
        }
    }

    public void processStudentProgramPlanRecords() {
        List<Student_Program_Plan__c> convertedRecordsToProcess = (List<Student_Program_Plan__c>) recordsToProcess;
        List<Subscriber__c> subsToCreate = new List<Subscriber__c>();

        for (Student_Program_Plan__c programPlan : convertedRecordsToProcess) {
            for (Auto_Subscriber_Setting__mdt subSetting : settingToSubscription.keyset()) {
                if (AutoSubscriberFilterHelper.filterProgramPlan(subSetting.DeveloperName, programPlan)) {
                    subsToCreate.addAll(createSubscriberForProgramPlan(programPlan, settingToSubscription.get(subSetting)));
                }
            }
        }

        if (!subsToCreate.isEmpty()) {
            insert subsToCreate;
        }
    }

    private List<Subscriber__c> createSubscriberForProgramPlan(Student_Program_Plan__c programPlan, List<String> subList) {
        List<Subscriber__c> subsToCreate = new List<Subscriber__c>();

        for (String subscriptionId : subList) {
            Subscriber__c subFromProgramPlan = new Subscriber__c();
            subFromProgramPlan.Subscription__c = subscriptionId;
            subFromProgramPlan.Contact__c = programPlan.Contact__c;
            subFromProgramPlan.Subscriber_Status__c = 'Subscribed';

            subsToCreate.add(subFromProgramPlan);
        }
        
        
        return subsToCreate;
    }
}