src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>LeadOrContactID__c</fullName>
        <formula>IF(ISBLANK(ContactId),CASESAFEID(LeadId),CASESAFEID(ContactId))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>LeadOrContactID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Attendees__c</fullName>
        <description>The Number of Guests plus 1.</description>
        <formula>Number_of_Guests__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The Number of Guests plus 1.</inlineHelpText>
        <label>Number of Attendees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Guests__c</fullName>
        <description>Number of guests attendee will be bringing besides themselves</description>
        <label>Number of Guests</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByCampaign</sharingModel>
</CustomObject>

force-app/main/default/classes/CampusVisitController.cls
public with sharing class CampusVisitController {
    @AuraEnabled(cacheable=True)
    public static List<CampaignMember> getCampaignMembers(){
        return [
            SELECT Name, Id, LeadOrContactID__c, Type, Contact.MailingState, Status, Number_of_Guests__c, Number_of_Attendees__c
            FROM CampaignMember
            LIMIT 1000
        ];
    }

    @AuraEnabled(cacheable=True)
    public static List<CampaignMember> searchCampaignMembers(String searchString){
        searchString = '%' + searchString + '%';
        return [
            SELECT Name, Id, LeadOrContactID__c, Type, Contact.MailingState, Status, Number_of_Guests__c, Number_of_Attendees__c
            FROM CampaignMember
            WHERE Name LIKE: searchString
            LIMIT 1000
        ];
    }

    /*@AuraEnabled
    public static void deleteContacts(List<Id> contactIds){
        if(contactIds.size() > 0 ){
            delete [SELECT Id FROM Contact WHERE Id in: contactIds];
        }
    } */
}