src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Subscription_Center_Description__c</fullName>
        <description>Used for Subscription Center record types - If this campaign is marked Visible on Subscription Center, this text will display on the Subscription Center page. 500 character limit.</description>
        <inlineHelpText>Used for Subscription Center record types - If this campaign is marked Visible on Subscription Center, this text will display on the Subscription Center page. 500 character limit.</inlineHelpText>
        <label>MC Subscription Center Description</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to associate an Email Campaign to a Subscription.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Preference__c</fullName>
        <description>[Peoplesoft] - Examples include: Home Phone, Local Phone, Mobile Phone, Email</description>
        <label>Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Local Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile Phone</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Contact_Preference__c</fullName>
        <description>[import] - Designates the primary contact method.</description>
        <inlineHelpText>Select the primary method the Lead would like to be contacted.</inlineHelpText>
        <label>Contact Preference</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                    <default>true</default>
                    <label>Email</label>
                </value>
                <value>
                    <fullName>Home Phone</fullName>
                </value>
                <value>
                    <fullName>Mobile Phone</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Subscriptions</relationshipLabel>
        <relationshipName>Lead_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this Subscription will be made available for ASU constituents to "opt-in" when managing their subscriptions. Please note that selecting this option requires that your team has a plan for engaging newly opted-in subscribers.</inlineHelpText>
        <label>Available for Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Center_Description__c</fullName>
        <inlineHelpText>A short (up to 1000 character) description to be displayed for ASU constituents who are managing their subscription preferences in the subscription center.</inlineHelpText>
        <label>Subscription Center Description</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <inlineHelpText>Business Unit types are primarily used to store opt-in information 
Area of Interest types store general interests, within a BU (e.g. Financial Aid, Academic Research) 
List types store explicit list (e.g. newsletter, membership)</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Area of Interest</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubscriptionCenterTest.cls
@isTest
private class SubscriptionCenterTest {
    private static final Integer SUBSCRIBED_COUNT = 5;
    private static Integer NOT_SUBSCRIBED_COUNT = 10;

    @testSetup
    private static void testSetup() {
        Integer i = 0;

        List<Subscription__c> subscriptions = TestDataFactory.createTestSubscriptions(SUBSCRIBED_COUNT);
        for (Subscription__c subscription : subscriptions) {
            i++;
            subscription.Name = 'Subscribed Sub ' + i;
            subscription.Available_for_Opt_In__c = true;
        }
        insert subscriptions;

        i = 0;
        List<Subscription__c> availableSubscriptions = TestDataFactory.createTestSubscriptions(NOT_SUBSCRIBED_COUNT);
        for (Subscription__c subscription : availableSubscriptions) {
            i++;
            subscription.Name = 'Available Sub ' + i;
            subscription.Available_for_Opt_In__c = true;
        }
        insert availableSubscriptions;

        // Rename the Parent subs so they're unique
        List<Subscription__c> parentSubList = new List<Subscription__c>();
        i = 0;
        for (Subscription__c sub : [SELECT Id, Name FROM Subscription__c WHERE Subscription_Type__c = 'Business Unit']) {
            i++;
            sub.Name = 'Parent' + i;
            parentSubList.add(sub);
        }
        update parentSubList;

        List<Contact> contacts = ContactService.createTestContacts(1);
        insert contacts;

        List<Subscriber__c> subscribers = TestDataFactory.createTestSubscribers(contacts, subscriptions);
        insert subscribers;

    }

    @isTest
    private static void testMain() {
        SubscriptionCenterController controller;
        Id subscriber = [SELECT Id FROM Contact LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(subscriber));

        controller = new SubscriptionCenterController();

        Integer subCounter = 0;
        for (String key : controller.subsByParentSubIdMap.keySet()) {
            subCounter += controller.subsByParentSubIdMap.get(key).size();
        }
        System.assertEquals(SUBSCRIBED_COUNT, subCounter);

        List<SubscriptionCenterController.SubscriberWrapper> availableSubList = new List<SubscriptionCenterController.SubscriberWrapper>();
        Integer availableSubCounter = 0;

        for (String key: controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
            availableSubList = controller.availableSubsByParentSubIdMap.get(key);
        }
        System.assertEquals(NOT_SUBSCRIBED_COUNT, availableSubCounter);

        System.debug('notSubbedBuSubIdToWrapperMap: ' + controller.notSubbedBuSubIdToWrapperMap);

        availableSubList[0].subscriberStatus = 'Subscribed';
        controller.updateSubscriptions();

        subCounter = 0;
        for (String key: controller.subsByParentSubIdMap.keySet()) {
            subCounter += controller.subsByParentSubIdMap.get(key).size();
        }

        availableSubCounter = 0;
        for (String key: controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
            availableSubList = controller.availableSubsByParentSubIdMap.get(key);
        }
        System.assertEquals(SUBSCRIBED_COUNT + NOT_SUBSCRIBED_COUNT, subCounter);
        System.assertEquals(0, availableSubCounter);
    }

    @isTest
    private static void testUnsubParent() {
        SubscriptionCenterController controller;
        Id subscriber = [SELECT Id FROM Contact LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(subscriber));

        controller = new SubscriptionCenterController();

        // Unsubscribe any subscribed Parent subs
        for (String key : controller.subbedBuSubIdToWrapperMap.keySet()) {
            controller.subbedBuSubIdToWrapperMap.get(key).subscriberStatus = 'Unsubscribed';
        }
        controller.updateSubscriptions();

        // Confirm that all Child subs have been unsubscribed
        List<Subscriber__c> subList = new List<Subscriber__c>([
            SELECT Id 
            FROM Subscriber__c 
            WHERE Subscriber_Status__c = 'Subscribed'
        ]);
        System.assertEquals(0, subList.size());
    }

    @isTest
    private static void testSubParent() {
        SubscriptionCenterController controller;
        Id subscriber = [SELECT Id FROM Contact LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(subscriber));

        controller = new SubscriptionCenterController();

        Integer subCounter = 0;
        for (String key : controller.subsByParentSubIdMap.keySet()) {
            subCounter += controller.subsByParentSubIdMap.get(key).size();
        }
        System.assertEquals(SUBSCRIBED_COUNT, subCounter);

        Set<Id> unsubbedParentSubIds = new Set<Id>();
        // Subscribe any unsubscribed Parent subs
        for (String key : controller.notSubbedBuSubIdToWrapperMap.keySet()) {
            controller.notSubbedBuSubIdToWrapperMap.get(key).subscriberStatus = 'Subscribed';
            unsubbedParentSubIds.add(key);
        }
        controller.updateSubscriptions();

        // Confirm that Parent subs have been subscribed
        List<Subscriber__c> subList = new List<Subscriber__c>([
            SELECT Id 
            FROM Subscriber__c 
            WHERE Subscription__c IN :unsubbedParentSubIds 
                AND Subscriber_Status__c = 'Subscribed'
        ]);
        System.assert(subList.size() > 0);
    }

    @isTest
    private static void testLead() {
        SubscriptionCenterController controller;
        Lead l = TestDataFactory.createLead('Sub');
        l.Email = 'tes9845345t@test.test';
        l.Company = 'None';
        l.Status = 'Prospect';
        l.Contact_Preference__c = 'Email';
        insert l;
        List<Subscriber__c> subList = new List<Subscriber__c>([SELECT Id, Contact__c, Lead__c FROM Subscriber__c]);
        for (Subscriber__c sub : subList) {
            sub.Contact__c = null;
            sub.Lead__c = l.Id;
        }
        update subList;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(l.Id));

        controller = new SubscriptionCenterController();

        Integer subCounter = 0;
        for (String key : controller.subsByParentSubIdMap.keySet()) {
            subCounter += controller.subsByParentSubIdMap.get(key).size();
        }
        System.assertEquals(SUBSCRIBED_COUNT, subCounter);

        List<SubscriptionCenterController.SubscriberWrapper> availableSubList = new List<SubscriptionCenterController.SubscriberWrapper>();
        Integer availableSubCounter = 0;

        for (String key : controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
            availableSubList = controller.availableSubsByParentSubIdMap.get(key);
        }
        System.assertEquals(NOT_SUBSCRIBED_COUNT, availableSubCounter);

        System.debug('notSubbedBuSubIdToWrapperMap: ' + controller.notSubbedBuSubIdToWrapperMap);

        availableSubList[0].subscriberStatus = 'Subscribed';
        controller.updateSubscriptions();

        subCounter = 0;
        for (String key : controller.subsByParentSubIdMap.keySet()) {
            subCounter += controller.subsByParentSubIdMap.get(key).size();
        }

        availableSubCounter = 0;
        for (String key : controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
            availableSubList = controller.availableSubsByParentSubIdMap.get(key);
        }
        System.assertEquals(SUBSCRIBED_COUNT + NOT_SUBSCRIBED_COUNT, subCounter);
        System.assertEquals(0, availableSubCounter);
    }

    @isTest
    private static void testDirectUnsubscribe() {
        SubscriptionCenterController controller;
        Id subscriberId = [SELECT Id FROM Subscriber__c WHERE Subscriber_Status__c = 'Subscribed' LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('action', 'unsubscribe');
        ApexPages.CurrentPage().getParameters().put('subscriberId', String.valueOf(subscriberId));

        controller = new SubscriptionCenterController();
        controller.doUnsubscribe();

        List<Subscriber__c> subCheck = new List<Subscriber__c>([
            SELECT Id, Subscriber_Status__c 
            FROM Subscriber__c 
            WHERE Id = :subscriberId
        ]);
        System.assertEquals('Unsubscribed', subCheck[0].Subscriber_Status__c);
    }

    @isTest
    private static void testDirectUnsubscribeCampaign() {
        Subscriber__c subscriber = [
            SELECT Id, Subscription__c, Contact__c 
            FROM Subscriber__c 
            WHERE Subscriber_Status__c = 'Subscribed' 
            LIMIT 1
        ];
        Campaign testCampaign = TestDataFactory.createCampaign(
            'sub', Schema.SObjectType.Campaign.getRecordTypeInfosByName().get('Communication').getRecordTypeId());
        testCampaign.Subscription__c = subscriber.Subscription__c;
        insert testCampaign;

        SubscriptionCenterController controller;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('action', 'unsubscribe');
        ApexPages.CurrentPage().getParameters().put('campaignId', String.valueOf(testCampaign.Id));
        ApexPages.CurrentPage().getParameters().put('subscriberKey', subscriber.Contact__c);

        controller = new SubscriptionCenterController();
        controller.doUnsubscribe();

        List<Subscriber__c> subCheck = new List<Subscriber__c>([
            SELECT Id, Subscriber_Status__c 
            FROM Subscriber__c 
            WHERE Id = :subscriber.Id
        ]);
        System.assertEquals('Unsubscribed', subCheck[0].Subscriber_Status__c);
    }

    @isTest
    private static void testDirectUnsubscribeSubIds() {
        Subscriber__c subscriber = [
            SELECT Id, Subscription__c, Contact__c 
            FROM Subscriber__c 
            WHERE Subscriber_Status__c = 'Subscribed' 
            LIMIT 1
        ];

        SubscriptionCenterController controller;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('action', 'unsubscribe');
        ApexPages.CurrentPage().getParameters().put('subscriptionId', subscriber.Subscription__c);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', subscriber.Contact__c);

        controller = new SubscriptionCenterController();
        controller.doUnsubscribe();

        List<Subscriber__c> subCheck = new List<Subscriber__c>([
            SELECT Id, Subscriber_Status__c 
            FROM Subscriber__c 
            WHERE Id = :subscriber.Id]);
        System.assertEquals('Unsubscribed', subCheck[0].Subscriber_Status__c);
    }

    @isTest
    private static void testOptOut() {
        SubscriptionCenterController controller;
        Id subscriberId = [SELECT Id FROM Contact LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(subscriberId));

        controller = new SubscriptionCenterController();
        controller.toggleOptOut();

        List<Subscriber__c> subCheck = new List<Subscriber__c>([
            SELECT Id 
            FROM Subscriber__c 
            WHERE Subscriber_Status__c = 'Subscribed'
        ]);
        Boolean contactHasOptedOutOfEmail = [
            SELECT Id, HasOptedOutOfEmail 
            FROM Contact 
            WHERE Id = :subscriberId
        ].HasOptedOutOfEmail;
        System.assertEquals(0, subCheck.size());
        System.assertEquals(true, contactHasOptedOutOfEmail);
    }

    @isTest
    private static void testFilterAvailableSubs() {
        SubscriptionCenterController controller;
        Id subscriberId = [SELECT Id FROM Contact LIMIT 1].Id;

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', String.valueOf(subscriberId));

        controller = new SubscriptionCenterController();

        List<SubscriptionCenterController.SubscriberWrapper> availableSubList = 
            new List<SubscriptionCenterController.SubscriberWrapper>();
        Integer availableSubCounter = 0;
        for (String key : controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
            availableSubList = controller.availableSubsByParentSubIdMap.get(key);
        }
        System.assertEquals(NOT_SUBSCRIBED_COUNT, availableSubCounter);

        controller.searchTerms = 'Available Sub ' + (NOT_SUBSCRIBED_COUNT - 1);
        controller.filterAvailableSubscriptions();

        availableSubCounter = 0;
        for (String key : controller.availableSubsByParentSubIdMap.keySet()) {
            availableSubCounter += controller.availableSubsByParentSubIdMap.get(key).size();
        }
        System.assertEquals(1, availableSubCounter);
    }

    @isTest
    private static void testSubscriberWrapperConstructors() {
        SubscriptionCenterController controller;
        Subscriber__c subscriber = [
            SELECT Id, Subscription__c, Contact__c, Lead__c, Subscriber_Status__c, 
                Subscription__r.Subscription_Center_Description__c, Subscription__r.Name
            FROM Subscriber__c 
            LIMIT 1
        ];

        PageReference subscriptionCenterPage = Page.SubscriptionCenter;
        Test.setCurrentPage(subscriptionCenterPage);
        ApexPages.CurrentPage().getParameters().put('subscriberKey', subscriber.Contact__c);

        controller = new SubscriptionCenterController();
        SubscriptionCenterController.SubscriberWrapper sw = 
            new SubscriptionCenterController.SubscriberWrapper(subscriber);
        System.assertEquals(subscriber.Subscriber_Status__c, sw.subscriberStatus);
    }
}