src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Case_Assignment_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>When a Case is created with this Campaign listed as the "Case Source", some ASU managed processes will use the Case Assignment Rule listed for specific guidance on how to provision that Case.</inlineHelpText>
        <label>Case Assignment Rule</label>
        <referenceTo>Case_Assignment_Rule__c</referenceTo>
        <relationshipLabel>Source Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Type</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Admitted Student Day</fullName>
                </value>
                <value>
                    <fullName>Adult Workshop</fullName>
                </value>
                <value>
                    <fullName>Alumni Sun Devil Send-Offs</fullName>
                </value>
                <value>
                    <fullName>American Dream Academy</fullName>
                </value>
                <value>
                    <fullName>Arizona Fall Circuit</fullName>
                </value>
                <value>
                    <fullName>ASU College On-Campus Event</fullName>
                </value>
                <value>
                    <fullName>ASU College OOS Event</fullName>
                </value>
                <value>
                    <fullName>ASU College Visit</fullName>
                </value>
                <value>
                    <fullName>ASU Scholar Information Night</fullName>
                </value>
                <value>
                    <fullName>AVID</fullName>
                </value>
                <value>
                    <fullName>AZ Commission</fullName>
                </value>
                <value>
                    <fullName>Barrett</fullName>
                </value>
                <value>
                    <fullName>Barrett Summer Scholars</fullName>
                </value>
                <value>
                    <fullName>Barrett Summer Scholars - 7th</fullName>
                </value>
                <value>
                    <fullName>Barrett Summer Scholars - 8th</fullName>
                </value>
                <value>
                    <fullName>Barrett Summer Scholars - 9th</fullName>
                </value>
                <value>
                    <fullName>Barrett Summer Scholars - HS Alumni Engagement</fullName>
                </value>
                <value>
                    <fullName>Becoming a Sun Devil</fullName>
                </value>
                <value>
                    <fullName>Campus Expo</fullName>
                </value>
                <value>
                    <fullName>College-Career Fair</fullName>
                </value>
                <value>
                    <fullName>College Fair - Independent/School District</fullName>
                </value>
                <value>
                    <fullName>College Fair - NACAC</fullName>
                </value>
                <value>
                    <fullName>College Fair - Regional ACAC</fullName>
                </value>
                <value>
                    <fullName>College Session</fullName>
                </value>
                <value>
                    <fullName>Community College Visit</fullName>
                </value>
                <value>
                    <fullName>Community Organization Events</fullName>
                </value>
                <value>
                    <fullName>Concierge</fullName>
                </value>
                <value>
                    <fullName>Destination ASU</fullName>
                </value>
                <value>
                    <fullName>Dream it.Do it. EXPO</fullName>
                </value>
                <value>
                    <fullName>Early Outreach</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Associate_Case_to_Active_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Associate_Case_to_Active_Opportunity__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to indicate if the case should be associated with an open, active opportunity.  Used in case trigger.
[DW: sfe_case]</description>
    <inlineHelpText>If checked, the case should be associated with an open, active opportunity.</inlineHelpText>
    <label>Associate Case to Active Opportunity</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Assignment_Rule__c.field-meta.xml
<CustomField>
    <fullName>Case_Assignment_Rule__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</description>
    <inlineHelpText>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</inlineHelpText>
    <label>Case Assignment Rule</label>
    <referenceTo>Case_Assignment_Rule__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Case_Source__c.field-meta.xml
<CustomField>
    <fullName>Case_Source__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft/ RFI] - Represents the Form External Id for the source of the Case. (Should be a SF Id of a Campaign)</description>
    <inlineHelpText>[Mulesoft/ RFI] - Represents the Form External Id for the source of the Case. (Should be a SF Id of a Campaign)</inlineHelpText>
    <label>Case Source</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Most_Recent_Queue__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Queue__c</fullName>
    <description>[DW: sfe_case]</description>
    <inlineHelpText>This field will determine where a case lands if it is re-opened within 14 days after closing.</inlineHelpText>
    <label>Most Recent Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup field to the Opportunity object to be able to relate the case to a prospect or applicant opportunity record.
[DW: sfe_case]</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ASU_Admission_Services.recordType-meta.xml
<RecordType>
    <fullName>ASU_Admission_Services</fullName>
    <active>true</active>
    <businessProcess>ASU Service</businessProcess>
    <description>Record type used to manage the undergraduate admission processes (Freshman, Applicant, Transfer, International service teams).</description>
    <label>ASU Admission Services</label>
    
    
    
</RecordType>

src/objects/Case_Assignment_Rule__c.object
<CustomObject><fields>
        <fullName>Associate_Case_to_Active_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox that indicates whether or not the case, when created, should be associated with an active Opportunity record.</description>
        <inlineHelpText>Check this box if this case assignment rule should also stamp an indicator on the Case to associate it with an Active Opportunity.</inlineHelpText>
        <label>Associate Case to Active Opportunity</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Queue_ID__c</fullName>
        <description>[??] - The 15 character (case sensitive) ID of the Queue or User associated with this Assignment Rule.This ID  is shown immediatly after "....salesforce.com/p/own/Queue/d?id="  in the URL when viewing the Queue or  "...salesforce.com/" when viewing the User.</description>
        <inlineHelpText>The 15 character (case sensitive) ID of the Queue or User associated with this Assignment Rule.This ID  is shown immediatly after "....salesforce.com/p/own/Queue/d?id="  in the URL when viewing the Queue or  "...salesforce.com/" when viewing the User.</inlineHelpText>
        <label>Queue or User ID</label>
        <length>15</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object used to assign case records. Criteria based on email address or association with a web form campaign record.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Case Assignment Rule</label><nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Case Assignment Rule</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment_Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Reference field to User to relate assigned Enrollment Coach to prospective student information.</description>
        <label>Enrollment Coach</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities_EnrollmentCoach</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect_Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If membership in a Campaign resulted in the creation of this Opportunity, a direct link is provisioned here.</inlineHelpText>
        <label>Prospect Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Prospect_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If a Case was created along with this Opportunity, a direct link to that Case is provisioned here.</inlineHelpText>
        <label>Prospect Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Prospect Opportunity Case</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Territory_Assignment_Last_Rule_Type__c</fullName>
        <description>This field is populated by the territory assignment apex code. It should not be edited my any other way.</description>
        <inlineHelpText>Shows the last type of auto territory assignment rule matched.</inlineHelpText>
        <label>Territory Assignment Last Rule Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Freshman Scholar</fullName>
                </value>
                <value>
                    <fullName>International</fullName>
                </value>
                <value>
                    <fullName>Lake Havasu</fullName>
                </value>
                <value>
                    <fullName>Last Attended High-School</fullName>
                </value>
                <value>
                    <fullName>Last Attended College</fullName>
                </value>
                <value>
                    <fullName>Geomarket</fullName>
                </value>
                <value>
                    <fullName>State</fullName>
                </value>
                <value>
                    <fullName>Default User</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Test_Waiver_Reviewed_By__c.field-meta.xml
<CustomField>
    <fullName>Test_Waiver_Reviewed_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Test Waiver Reviewed By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/CaseHandler.cls
public without sharing class CaseHandler
implements ITrigger {

    Map<ID, Contact> relatedContactMap = new Map<ID, Contact>();
    Map<Id, Campaign> sourceMap = new Map<Id, Campaign>();
    List<RecordType> recruitmentCaseRT;
    Set<Id> groupIds;
    Savepoint sp;

    /**
    * bulkBefore
    *
    * This method is called prior to execution of a BEFORE trigger. Use this to cache
    * any data required into maps prior execution of the trigger.
    */
    public void bulkBefore()
    {
        if (Trigger.isUpdate)
        {
            Map<Id, String> groupNameMap = GroupService.mapGroupIdToName();

            for (Case caze : (List<Case>) Trigger.new)
            {
                if (groupNameMap.containsKey(caze.OwnerId))
                {
                    caze.Most_Recent_Queue__c = groupNameMap.get(caze.OwnerId);
                }
            }
        }

        if (!Trigger.isInsert)
        {
            return;
        }

        recruitmentCaseRT = new List<RecordType>([SELECT Id FROM RecordType WHERE SobjectType='Case' AND DeveloperName = 'ASU_Admission_Services']);
        if (recruitmentCaseRT.size() < 1)
        return;

        Set<Id> caseContactIdSet = new Set<ID>();
        Set<Id> campaignIdSet = new Set<Id>();

        for (Case c: (List<Case>)Trigger.new)
        {
            if (c.RecordTypeId == recruitmentCaseRT[0].Id)
            {
                campaignIdSet.add(c.Case_Source__c);
                // Case "a"
                // SFR-1109; removed boolean check here to correct bug on webform submissions
                //if (c.Associate_Case_to_Active_Opportunity__c == true) {
                caseContactIdSet.add(c.ContactId);
                //}

            }
        }

        relatedContactMap = new Map<Id, Contact>([SELECT Id, (Select Id, StageName, Territory_Assignment_Last_Rule_Type__c, OwnerId, Owner.IsActive, Enrollment_Coach__c, Enrollment_Coach__r.IsActive, CreatedDate, IsClosed FROM Opportunities__r ORDER BY IsClosed ASC, CreatedDate DESC) FROM Contact WHERE Id in :caseContactIdSet]);
        if (campaignIdSet.size() > 0) {
            sourceMap = new Map<Id, Campaign>([SELECT Id, Case_Assignment_Rule__r.Id, Case_Assignment_Rule__r.Queue_ID__c, Case_Assignment_Rule__r.Category__c, Case_Assignment_Rule__r.Sub_Category__c, Case_Assignment_Rule__r.Origin__c, Case_Assignment_Rule__r.Functional_Group__c, Case_Assignment_Rule__r.Type_of_Additional_Assignment_Needed__c FROM Campaign WHERE Id IN :campaignIdSet]);
        }

    }

    /**
    * bulkAfter
    *
    * This method is called prior to execution of an AFTER trigger. Use this to cache
    * any data required into maps prior execution of the trigger.
    */
    public void bulkAfter() {}

        /**
        * beforeInsert
        *
        * This method is called iteratively for each record to be inserted during a BEFORE
        * trigger. Never execute any SOQL/SOSL etc in this and other iterative methods.
        */
        public void beforeInsert(SObject so) {
            Case c = (Case)so;

            if (recruitmentCaseRT.size() > 0 && c.RecordTypeId == recruitmentCaseRT[0].Id) {
                Contact con = relatedContactMap.get(c.ContactId);
                List<Opportunity> opList = new List<Opportunity>();
                Case_Assignment_Rule__c defaultCAR;
                boolean ownerSet = false;

                if (con != null)
                opList = con.Opportunities__r;

                system.debug('GRF c: ' + c);
                system.debug('GRF opList: ' + opList);

                // SFR-1109; moved boolean check here to correct bug on webform submissions
                if (c.Associate_Case_to_Active_Opportunity__c == true && opList != null && opList.size() > 0)
                c.Opportunity__c = opList[0].Id;

                // Special handling for API users below for webform integrations'
                system.debug('GRF Username: ' + UserInfo.getFirstName());
                system.debug('GRF sourceMap: ' + sourceMap);
                if (!UserInfo.getFirstName().equals('API') || UserInfo.getLastName().equals('ASU EMAIL SERVICE')) {
                    // SFR-1109; added opList check here to correct bug on webform submissions
                    if (opList != null && opList.size() > 0) {
                        // Case "b"
                        if (c.Type_of_Additional_Assignment_Needed__c == 'Territory Manager' && c.Associate_Case_to_Active_Opportunity__c == true) {
                            if (opList[0].Territory_Assignment_Last_Rule_Type__c != 'Default User' && opList[0].Owner.IsActive == true && opList[0].IsClosed == false) {
                                c.OwnerId = opList[0].OwnerId;
                                ownerSet = true;
                            }
                        }
                        // Case "c"
                        else if (c.Type_of_Additional_Assignment_Needed__c == 'Enrollment Coach' && c.Associate_Case_to_Active_Opportunity__c == true) {
                            if (opList[0].Enrollment_Coach__c != null && opList[0].Enrollment_Coach__r.IsActive == true && opList[0].IsClosed == false) {
                                c.OwnerId = opList[0].Enrollment_Coach__c;
                                ownerSet = true;
                            }
                        }
                    }
                }
                // Case for API users (webforms)
                else {
                    if (sourceMap.containsKey(c.Case_Source__c)) {
                        Campaign source = sourceMap.get(c.Case_Source__c);
                        // Did we find a related Case Assignment Rule?
                        if (source.Case_Assignment_Rule__c != null) {

                            // SFE-690 Apply TM/EC logic to API users as well as non-API users
                            if (opList != null && opList.size() > 0) {
                                // Case "b"
                                if (source.Case_Assignment_Rule__r.Type_of_Additional_Assignment_Needed__c == 'Territory Manager') {
                                    if (opList[0].Territory_Assignment_Last_Rule_Type__c != 'Default User' && opList[0].Owner.IsActive == true && opList[0].IsClosed == false) {
                                        c.OwnerId = opList[0].OwnerId;
                                        c.Type_of_Additional_Assignment_Needed__c = 'Territory Manager';
                                        ownerSet = true;
                                    }
                                }
                                // Case "c"
                                else if (source.Case_Assignment_Rule__r.Type_of_Additional_Assignment_Needed__c == 'Enrollment Coach') {
                                    if (opList[0].Enrollment_Coach__c != null && opList[0].Enrollment_Coach__r.IsActive == true && opList[0].IsClosed == false) {
                                        c.OwnerId = opList[0].Enrollment_Coach__c;
                                        c.Type_of_Additional_Assignment_Needed__c = 'Enrollment Coach';
                                        ownerSet = true;
                                    }
                                }
                            }

                            if (!ownerSet && source.Case_Assignment_Rule__r.Queue_ID__c != null)
                            c.OwnerId = ID.valueOf(source.Case_Assignment_Rule__r.Queue_ID__c);
                            if (source.Case_Assignment_Rule__r.Origin__c != null)
                            c.Origin__c = source.Case_Assignment_Rule__r.Origin__c;
                            if (source.Case_Assignment_Rule__r.Category__c != null)
                            c.Category__c = source.Case_Assignment_Rule__r.Category__c;
                            if (source.Case_Assignment_Rule__r.Sub_Category__c != null)
                            c.Sub_Category__c = source.Case_Assignment_Rule__r.Sub_Category__c;
                            if (source.Case_Assignment_Rule__r.Functional_Group__c != null)
                            c.Functional_Group__c =source.Case_Assignment_Rule__r.Functional_Group__c;
                        }
                        else {
                            // No related Case Assignment Rule found; use the Territory Manager if found
                            if (opList != null && opList.size() > 0 && opList[0].Territory_Assignment_Last_Rule_Type__c != 'Default User' && opList[0].Owner.IsActive == true)
                            c.OwnerId = opList[0].OwnerId;
                            else {
                                // No valid Territory Manager found; use default Case Assignment Rule
                                if (defaultCAR == null) {
                                    defaultCar = [SELECT Id, Queue_ID__c, Origin__c, Category__c, Sub_Category__c, Functional_Group__c, Type_of_Additional_Assignment_Needed__c FROM Case_Assignment_Rule__c WHERE Email_Address__c = 'admissions@asu.edu'];
                                    if (!(defaultCAR == null)) {

                                        // SFE-690 Apply TM/EC logic to API users as well as non-API users
                                        if (opList != null && opList.size() > 0) {
                                            // Case "b"
                                            if (defaultCar.Type_of_Additional_Assignment_Needed__c == 'Territory Manager') {
                                                if (opList[0].Territory_Assignment_Last_Rule_Type__c != 'Default User' && opList[0].Owner.IsActive == true && opList[0].IsClosed == false) {
                                                    c.OwnerId = opList[0].OwnerId;
                                                    c.Type_of_Additional_Assignment_Needed__c = 'Territory Manager';
                                                    ownerSet = true;
                                                }
                                            }
                                            // Case "c"
                                            else if (defaultCar.Type_of_Additional_Assignment_Needed__c == 'Enrollment Coach') {
                                                if (opList[0].Enrollment_Coach__c != null && opList[0].Enrollment_Coach__r.IsActive == true && opList[0].IsClosed == false) {
                                                    c.OwnerId = opList[0].Enrollment_Coach__c;
                                                    c.Type_of_Additional_Assignment_Needed__c = 'Enrollment Coach';
                                                    ownerSet = true;
                                                }
                                            }
                                        }
                                        if (!ownerSet && defaultCar.Queue_ID__c != null)
                                        c.OwnerId = ID.valueOf(defaultCar.Queue_ID__c);

                                        if (defaultCAR.Origin__c != null)
                                        c.Origin__c = defaultCAR.Origin__c;
                                        if (defaultCAR.Category__c != null)
                                        c.Category__c = defaultCAR.Category__c;
                                        if (defaultCAR.Sub_Category__c != null)
                                        c.Sub_Category__c = defaultCAR.Sub_Category__c;
                                        if (defaultCAR.Functional_Group__c != null)
                                        c.Functional_Group__c = defaultCAR.Functional_Group__c;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }


        /**
        * beforeUpdate
        *
        * This method is called iteratively for each record to be updated during a BEFORE
        * trigger.
        */
        public void beforeUpdate(SObject oldSo, SObject so)
        {
            Case oldCase = (Case) oldSo;
            Case newCase = (Case) so;

            if (newCase.Functional_Group__c != oldCase.Functional_Group__c && oldCase.Functional_Group__c != 'External Unit')
            {
                newCase.Most_Recent_Functional_Group__c = oldCase.Functional_Group__c;
            }
        }

        /**
        * beforeDelete
        *
        * This method is called iteratively for each record to be deleted during a BEFORE
        * trigger.
        */
        public void beforeDelete(SObject so){}

            /**
            * beforeFinally
            *
            * This method is called at the end of the execution of a BEFORE trigger. Use this to finalize
            * any bulk operations for a BEFORE trigger.
            */
            public void beforeFinally(){}

                /**
                * afterInsert
                *
                * This method is called iteratively for each record inserted during an AFTER
                * trigger. Always put field validation in the 'After' methods in case another trigger
                * has modified any values. The record is 'read only' by this point.
                */
                public void afterInsert(SObject so) {}

                    /**
                    * afterUpdate
                    *
                    * This method is called iteratively for each record updated during an AFTER
                    * trigger.
                    */
                    public void afterUpdate(SObject oldSo, SObject so) {
                        Case c = (Case)so;
                        Case oldc = (Case)oldSo;

                        //Forward the email and attach any case attachments as well
                        if (c.Status == 'Closed: Forwarded' && oldC.Status != 'Closed: Forwarded'){
                            //Prevent recursive update and sending of mail
                            if(!CaseUtilities.emailForwarded){
                                CaseUtilities.emailForwarded = true;
                                CaseUtilities.forwardCaseAttachments(c.Id, c.Forward_To_Email__c , c.Forward_To_Email_Calculation__c);
                            }
                        }
                    }

                    /**
                    * afterDelete
                    *
                    * This method is called iteratively for each record deleted during an AFTER
                    * trigger.
                    */
                    public void afterDelete(SObject so){}

                        /**
                        * andFinally
                        *
                        * This method is called once all records have been processed by the trigger. Use this
                        * method to accomplish any final operations such as creation or updates of other records.
                        */
                        public void andFinally() {

                        }

                    }