src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <inlineHelpText>Use this field to define which audience type this Campaign is targeting.</inlineHelpText>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Used to associate an Email Campaign to a Subscription.</inlineHelpText>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Undergraduate, Graduate, Law</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Relationship</label><nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Relationship Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Relationships</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Relationship__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person tracked on this Relationship Record. Used in Contact to Account and Contact to Contact Relationships.</description>
    <inlineHelpText>The person tracked on this Relationship Record.</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Relationships</relationshipLabel>
    <relationshipName>Relationships</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Career__c</fullName>
        <description>Data sourced from PS_ACAD_CAR_TBL.DESCR</description>
        <label>Career</label>
        <picklist>
            <picklistValues>
                <fullName>Undergraduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscriber_Auto_Subscription_Mapping__mdt/Subscriber_Auto_Subscription_Mapping__mdt.object-meta.xml
<CustomObject>
    <description>Used to evaluate automatic subscription criteria and is dependent on object type
        and functional group.</description>
    <label>Subscriber Auto Subscription Mapping</label>
    <pluralLabel>Subscriber Auto Subscription Mappings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Subscriber_Auto_Subscription_Mapping__mdt/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Subscriber_Auto_Subscription_Mapping__mdt/fields/Related_Object__c.field-meta.xml
<CustomField>
    <fullName>Related_Object__c</fullName>
    <description>Select the object that this rule should correspond with.</description>
    <inlineHelpText>Select the object that this rule should correspond with.</inlineHelpText>
    <label>Related Object</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Subscriber_Auto_Subscription_Mappings</relationshipLabel>
    <relationshipName>Subscriber_Auto_Subscription_Mappings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Subscriber_Auto_Subscription_Mapping__mdt/fields/Subscriptions_To_Add__c.field-meta.xml
<CustomField>
    <fullName>Subscriptions_To_Add__c</fullName>
    <description>A list of all the subscriptions that a subscriber should be added for, for this setting.</description>
    <inlineHelpText>Please add each Subscription you would like the user to be added to separated by a comma (No Spaces)</inlineHelpText>
    <label>Subscriptions To Add</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Child Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <inlineHelpText>Business Unit types are primarily used to store opt-in information 
Area of Interest types store general interests, within a BU (e.g. Financial Aid, Academic Research) 
List types store explicit list (e.g. newsletter, membership)</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Area of Interest</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubscriberAutoSubscriptionHelper.cls
public with sharing class SubscriberAutoSubscriptionHelper {
    String typeOfObject;
    public Map<Subscriber_Auto_Subscription_Mapping__mdt, List<String>> settingToSubscription;
    @TestVisible
    Map<Id, List<Subscriber__c>> contactToSubscriber;
    public static Map<Id, String> campaignToRecordTypeName;
    public static Map<Id, String> contactToCareer;
    public static Map<Id, String> subscriptionToParent;

    /**
     * Constructor to initialize the helper with the object type.
     *
     * @param typeOfObject Type of the object being processed.
     */
    public SubscriberAutoSubscriptionHelper(String typeOfObject) {
        settingToSubscription = new Map<Subscriber_Auto_Subscription_Mapping__mdt, List<String>>();
        contactToSubscriber = new Map<Id, List<Subscriber__c>>();
        this.typeOfObject = typeOfObject;
        createSubscriptionMap();
    }

    /**
     * Creates a map of subscription settings to subscriptions.
     */
    private void createSubscriptionMap() {
        List<Subscriber_Auto_Subscription_Mapping__mdt> subscriberSettings = [
            SELECT Subscriptions_To_Add__c, DeveloperName
            FROM Subscriber_Auto_Subscription_Mapping__mdt
            WHERE Active__c = TRUE AND Related_Object__r.DeveloperName = :typeOfObject
        ];

        for (Subscriber_Auto_Subscription_Mapping__mdt subSetting : subscriberSettings) {
            List<String> subscriptionIds = new List<String>();

            if (subSetting.Subscriptions_To_Add__c != null) {
                subscriptionIds = subSetting.Subscriptions_To_Add__c.split(',');
            }

            settingToSubscription.put(subSetting, subscriptionIds);
        }
    }

    /**
     * Creates a map of subscription IDs to their parent subscriptions.
     *
     * @param subscriptionIds List of subscription IDs.
     */
    public void createSubscriptionParentMap(List<Id> subscriptionIds) {
        subscriptionToParent = new Map<Id, String>();
        List<Subscription__c> subscriptionsForSubs = [
            SELECT Id, Parent_Subscription__c
            FROM Subscription__c
            WHERE Id IN :subscriptionIds
        ];

        for (Subscription__c sub : subscriptionsForSubs) {
            if (sub.Parent_Subscription__c != null) {
                subscriptionToParent.put(sub.Id, sub.Parent_Subscription__c);
            }
        }
    }

    /**
     * Creates subscriber records for the given contact and subscription list.
     *
     * @param contactId Contact ID.
     * @param subList List of subscription IDs.
     * @return List of created subscriber records.
     */
    public List<Subscriber__c> createSubscriber(Id contactId, List<String> subList) {
        List<Subscriber__c> subsToCreate = new List<Subscriber__c>();

        for (String subscriptionId : subList) {
            Subscriber__c newSub = new Subscriber__c();
            newSub.Subscription__c = subscriptionId;
            newSub.Contact__c = contactId;
            newSub.Subscriber_Status__c = 'Subscribed';

            if (shouldNewSubBeUpserted(newSub)) {
                subsToCreate.add(newSub);
            }
        }

        return subsToCreate;
    }

    /**
     * Builds a map of contacts to their subscribers based on relationships.
     *
     * @param relationships List of relationship records.
     */
    public void buildContactToSubscriberMapWithRelationship(List<Relationship__c> relationships) {
        Set<Id> contactsFromRelationships = new Set<Id>();
        for (Relationship__c relationship : relationships) {
            if (relationship.Contact__c != null) {
                contactsFromRelationships.add(relationship.Contact__c);
            }
        }

        List<Subscriber__c> subsForContacts = [
            SELECT
                Id,
                Contact__c,
                Subscription__c,
                Subscriber_Status__c,
                Subscription__r.Id,
                Subscription__r.Parent_Subscription__c,
                Subscription__r.Subscription_Type__c
            FROM Subscriber__c
            WHERE Contact__c IN :contactsFromRelationships
            ORDER BY Contact__c
        ];

        if (!subsForContacts.isEmpty()) {
            Id currentContact = subsForContacts[0].Contact__c;
            List<Subscriber__c> subsForSpecificContact = new List<Subscriber__c>();
            for (Subscriber__c sub : subsForContacts) {
                if (currentContact == sub.Contact__c) {
                    subsForSpecificContact.add(sub);
                } else {
                    contactToSubscriber.put(currentContact, subsForSpecificContact);
                    subsForSpecificContact = new List<Subscriber__c>();
                    subsForSpecificContact.add(sub);
                }
            }
            contactToSubscriber.put(currentContact, subsForSpecificContact);
        }
    }

    /**
     * Builds a map of contacts to their subscribers based on program plans.
     *
     * @param programPlans List of program plan records.
     */
    public void buildContactToSubscriberMapWithProgramPlan(List<Student_Program_Plan__c> programPlans) {
        Set<Id> contactsFromPlans = new Set<Id>();
        for (Student_Program_Plan__c plan : programPlans) {
            if (plan.Contact__c != null) {
                contactsFromPlans.add(plan.Contact__c);
            }
        }

        List<Subscriber__c> subsForContacts = [
            SELECT
                Id,
                Contact__c,
                Subscription__c,
                Subscriber_Status__c,
                Subscription__r.Id,
                Subscription__r.Parent_Subscription__c,
                Subscription__r.Subscription_Type__c
            FROM Subscriber__c
            WHERE Contact__c IN :contactsFromPlans
            ORDER BY Contact__c
        ];

        if (!subsForContacts.isEmpty()) {
            Id currentContact = subsForContacts[0].Contact__c;
            List<Subscriber__c> subsForSpecificContact = new List<Subscriber__c>();
            for (Subscriber__c sub : subsForContacts) {
                if (currentContact == sub.Contact__c) {
                    subsForSpecificContact.add(sub);
                } else {
                    contactToSubscriber.put(currentContact, subsForSpecificContact);
                    subsForSpecificContact = new List<Subscriber__c>();
                    subsForSpecificContact.add(sub);
                }
            }
            contactToSubscriber.put(currentContact, subsForSpecificContact);
        }
    }

    /**
     * Builds a map of contacts to their subscribers based on campaign members.
     *
     * @param campaignMemberList List of campaign member records.
     */
    public void buildContactToSubscriberMapWithCampaignMember(List<CampaignMember> campaignMemberList) {
        Set<Id> contactsFromCampaignMembers = new Set<Id>();
        for (CampaignMember member : campaignMemberList) {
            if (member.ContactId != null) {
                contactsFromCampaignMembers.add(member.ContactId);
            }
        }

        List<Subscriber__c> subsForContacts = [
            SELECT
                Id,
                Contact__c,
                Subscription__c,
                Subscriber_Status__c,
                Subscription__r.Id,
                Subscription__r.Parent_Subscription__c,
                Subscription__r.Subscription_Type__c
            FROM Subscriber__c
            WHERE Contact__c IN :contactsFromCampaignMembers
            ORDER BY Contact__c
        ];

        if (!subsForContacts.isEmpty()) {
            Id currentContact = subsForContacts[0].Contact__c;
            List<Subscriber__c> subsForSpecificContact = new List<Subscriber__c>();
            for (Subscriber__c sub : subsForContacts) {
                if (currentContact == sub.Contact__c) {
                    subsForSpecificContact.add(sub);
                } else {
                    contactToSubscriber.put(currentContact, subsForSpecificContact);
                    subsForSpecificContact = new List<Subscriber__c>();
                    subsForSpecificContact.add(sub);
                }
            }
            contactToSubscriber.put(currentContact, subsForSpecificContact);
        }
    }

    /**
     * Sets campaign and opportunity information for the given campaign members.
     *
     * @param campaignMemberList List of campaign member records.
     */
    public void setCampaignAndOpportunityInformation(List<CampaignMember> campaignMemberList) {
        Set<Id> contactsFromCampaignMembers = new Set<Id>();
        Set<Id> campaignFromCampaignMembers = new Set<Id>();
        for (CampaignMember member : campaignMemberList) {
            if (member.ContactId != null) {
                contactsFromCampaignMembers.add(member.ContactId);
            }
            if (member.CampaignId != null) {
                campaignFromCampaignMembers.add(member.CampaignId);
            }
        }

        setCareerFromOpportunity(contactsFromCampaignMembers);
        setCampaignRecordTypeName(campaignFromCampaignMembers);
    }

    /**
     * Sets career information for the given contacts based on their opportunities.
     *
     * @param contactIds Set of contact IDs.
     */
    private void setCareerFromOpportunity(Set<Id> contactIds) {
        List<Opportunity> opportunityForContacts = [
            SELECT Career__c, Contact__r.Id
            FROM Opportunity
            WHERE Contact__c IN :contactIds
            ORDER BY LastModifiedDate ASC
        ];

        contactToCareer = new Map<Id, String>();

        for (Opportunity oppWithCareer : opportunityForContacts) {
            contactToCareer.put(oppWithCareer.Contact__r.Id, oppWithCareer.Career__c);
        }
    }

    /**
     * Sets campaign record type names for the given campaigns.
     *
     * @param campaignFromCampaignMembers Set of campaign IDs.
     */
    private void setCampaignRecordTypeName(Set<Id> campaignFromCampaignMembers) {
        List<Campaign> campaignsFromMembers = [
            SELECT RecordType.Name
            FROM Campaign
            WHERE Id IN :campaignFromCampaignMembers
        ];

        campaignToRecordTypeName = new Map<Id, String>();
        for (Campaign campaignWithName : campaignsFromMembers) {
            campaignToRecordTypeName.put(campaignWithName.Id, campaignWithName.RecordType.Name);
        }
    }

    /**
     * Determines if a new subscriber should be upserted.
     *
     * @param newSub The subscriber to check.
     * @return True if the subscriber should be upserted, false otherwise.
     */
    private Boolean shouldNewSubBeUpserted(Subscriber__c newSub) {
        List<Subscriber__c> currentSubsForContact = contactToSubscriber.get(newSub.Contact__c);

        Set<Id> unsubscribedParentIds = new Set<Id>();

        if (currentSubsForContact == null || currentSubsForContact.isEmpty()) {
            return true;
        }

        for (Subscriber__c sub : currentSubsForContact) {
            if (
                sub.Subscription__r.Subscription_Type__c == 'Business Unit' &&
                sub.Subscriber_Status__c == 'Unsubscribed'
            ) {
                unsubscribedParentIds.add(sub.Subscription__r.Id);
            }
        }

        if (unsubscribedParentIds.contains(subscriptionToParent.get(newSub.Subscription__c))) {
            return false;
        }

        for (Subscriber__c sub : currentSubsForContact) {
            if (newSub.Subscription__c == sub.Subscription__c) {
                if (sub.Subscriber_Status__c == 'No Preference') {
                    newSub.Id = sub.Id;
                    return true;
                } else {
                    return false;
                }
            }
        }

        return true;
    }
}