src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Event_End_Date__c</fullName>
        <description>Event end date</description>
        <label>Event End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Event_Start_Date__c</fullName>
        <description>Date the event will start.</description>
        <label>Event Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Interest_PeopleSoft_Major__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Interest PeopleSoft Major</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested__c</fullName>
        <description>College, school or department who requested this Campaign.</description>
        <inlineHelpText>College, school or department who requested this Campaign.</inlineHelpText>
        <label>Department / College</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barrett The Honors College</fullName>
                </value>
                <value>
                    <fullName>College of Public Programs</fullName>
                </value>
                <value>
                    <fullName>Coll Technology &amp; Innovation</fullName>
                </value>
                <value>
                    <fullName>Corporate Relations</fullName>
                </value>
                <value>
                    <fullName>Cronkite School-Journ/MassComm</fullName>
                </value>
                <value>
                    <fullName>Enrollment Services</fullName>
                </value>
                <value>
                    <fullName>Graduate Education</fullName>
                </value>
                <value>
                    <fullName>Health Solutions</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Art</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Dance</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Design</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Digital Culture</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Film</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Music</fullName>
                </value>
                <value>
                    <fullName>Herberger Institute - Theatre</fullName>
                </value>
                <value>
                    <fullName>Ira A Fulton Engineering</fullName>
                </value>
                <value>
                    <fullName>Ira A Fulton Engineering - CBBG</fullName>
                </value>
                <value>
                    <fullName>Ira A Fulton Engineering - FSE Outreach</fullName>
                </value>
                <value>
                    <fullName>Ira A Fulton Engineering - Polytechnic</fullName>
                </value>
                <value>
                    <fullName>Lake Havasu</fullName>
                </value>
                <value>
                    <fullName>Liberal Arts &amp; Sciences</fullName>
                </value>
                <value>
                    <fullName>MaryLouFulton Teachers College</fullName>
                </value>
                <value>
                    <fullName>New Interdis Arts &amp; Sciences</fullName>
                </value>
                <value>
                    <fullName>Nursing &amp; Health Innovation</fullName>
                </value>
                <value>
                    <fullName>O'Connor College of Law</fullName>
                </value>
                <value>
                    <fullName>School for the Future of Innovation in Society</fullName>
                </value>
                <value>
                    <fullName>School of Global Management</fullName>
                </value>
                <value>
                    <fullName>School of Letters &amp; Sciences</fullName>
                </value>
                <value>
                    <fullName>School of Sustainability</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/CampaignMemberService.cls
public with sharing class CampaignMemberService {
    /**
     * Returns all the fields on CampaignMember in a String
     * @return A string containing all the CampaignMember fields
     */
    public static String campaignMemberFieldsToString() {
        String campaignMemberFields = null;

        Map<String, SObjectField> campaignMemberFieldMap = ObjectService.getObjectFieldMap('CampaignMember');

        campaignMemberFields = ObjectService.objectFieldsToString(campaignMemberFieldMap);

        return campaignMemberFields;
    }

    /**
     * Get a list of CampaignMembers for the provided Contact Id
     * @param The Id of the Contact to search on
     * @return A list of CampaignMembers for the provided Contact Id
     */
    public static List<CampaignMember> getCampaignMembers(Id contactId) {
        String camFields = campaignMemberFieldsToString();

        List<CampaignMember> camMems = new List<CampaignMember>();

        String soql =
            '' +
            'SELECT ' +
            camFields +
            ', Campaign.RecordType.Name, Campaign.Name, ' +
            'Campaign.ParentId, Campaign.Type, Campaign.Requested__c, Campaign.Parent.Name, ' +
            'Campaign.Event_Start_Date__c, Campaign.Event_End_Date__c, ' +
            'Campaign.Interest_PeopleSoft_Major__c, Campaign.StartDate, Campaign.EndDate ' +
            'FROM CampaignMember ' +
            'WHERE ContactId = :contactId ';

        camMems = Database.query(soql);

        return camMems;
    }

    /**
     * Create a test list of CampaignMembers for the provided Contact Id
     * @param The Id of the Contact to create CampaignMembers for
     * @param A list of Campaigns to add the Contact to
     * @return A list of CampaignMembers for the provided Contact Id to insert
     */
    public static List<CampaignMember> createTestCampaignMembers(Id contactId, List<Campaign> camList) {
        List<CampaignMember> camMems = new List<CampaignMember>();

        for (Campaign cam : camList) {
            CampaignMember tempCamMem = new CampaignMember(CampaignId = cam.Id, ContactId = contactId, Status = 'Sent');

            if (cam.RecordType.Name == 'Corporate Relations') {
                tempCamMem.Status = 'Active';
            }

            camMems.add(tempCamMem);
        }

        return camMems;
    }
}