src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/CAP__c.field-meta.xml
<CustomField>
    <fullName>CAP__c</fullName>
    <description>[??] - Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</description>
    <formula>Contact.CAP__c</formula>
    <inlineHelpText>Displays a green icon for a College Achievement Plan participant (yellow for possible). Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02. (or if possible is checked)</inlineHelpText>
    <label>CAP</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Created_By_Name__c.field-meta.xml
<CustomField>
    <fullName>Created_By_Name__c</fullName>
    <description>[??] - Displays the First and Last Name of the individual who Created this Case. Used for Templates and Visualforce pages.
[DW: sfe_case]</description>
    <formula>CreatedBy.FirstName &amp; " " &amp; CreatedBy.LastName</formula>
    <inlineHelpText>Displays the First and Last Name of the individual who Created this Case. Used for Templates and Visualforce pages.</inlineHelpText>
    <label>Created By Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web
[DW: sfe_case]</description>
    <inlineHelpText>Where was this Case initiated?</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advising Community</fullName>
            </value>
            <value>
                <fullName>Alteryx</fullName>
            </value>
            <value>
                <fullName>Alteryx - Financial Intake</fullName>
            </value>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>BBSS</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
            <value>
                <fullName>Coach Initiated</fullName>
            </value>
            <value>
                <fullName>EdPlus Salesforce</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Error Logger</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>FC DPC</fullName>
            </value>
            <value>
                <fullName>FC LOSAN</fullName>
            </value>
            <value>
                <fullName>FC Poly</fullName>
            </value>
            <value>
                <fullName>FC Tempe</fullName>
            </value>
            <value>
                <fullName>FC Virtual</fullName>
            </value>
            <value>
                <fullName>FC West</fullName>
            </value>
            <value>
                <fullName>Financial Intake</fullName>
            </value>
            <value>
                <fullName>Handshake</fullName>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>My ASU</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Outgoing Call</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Qualtrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Visible_by_Contact__c.field-meta.xml
<CustomField>
    <fullName>Visible_by_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used in the Case Query for the My ASU service center to display the Case to the logged in User.
[DW: sfe_case]</description>
    <inlineHelpText>If checked, this Case should be visible by the Contact in the My ASU Help tab.</inlineHelpText>
    <label>Visible by Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Web_Submission__c.field-meta.xml
<CustomField>
    <fullName>Web_Submission__c</fullName>
    <description>[??] - When a Case is created via a webform submission, that form can pass a hidden identifier to this text field. This is then used to correctly assign the Case (via Workflow or Apex).</description>
    <inlineHelpText>When a Case is created via a webform submission, that form can pass a hidden identifier to this text field. This is then used to correctly assign the Case (via Workflow or Apex).</inlineHelpText>
    <label>Web Submission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Affiliation_Alumni__c</fullName>
        <description>[Peoplesoft] - Relations with Institution</description>
        <label>Alumni</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Affiliation_Courtesy_Affiliate__c</fullName>
        <description>[Peoplesoft] - Relation with Institution</description>
        <label>Courtesy Affiliate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Affiliation_Employee__c</fullName>
        <description>[Peoplesoft] - Relation with Institution;  Examples include: Current, Previous Relation with Institution</description>
        <label>Employee</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Affiliation_Student_Applicant__c</fullName>
        <description>[Peoplesoft] - Relations with Institution; Examples include: Current, Previous Relations with Institution</description>
        <label>Student Applicant</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Affiliation_Student__c</fullName>
        <description>[Peoplesoft] - Relations with Institution; Examples include: Current, Previous Relations with Institution</description>
        <label>Student</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Current</fullName>
                </value>
                <value>
                    <fullName>Previous</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAP_Student_Group_Count__c</fullName>
        <description>[Peoplesoft] - A count of the total Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02. Used to determine if this Contact should be flagged as a College Achievement Plan participant.</description>
        <inlineHelpText>A count of the total Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02. Used to determine if this Contact should be flagged as a College Achievement Plan participant.</inlineHelpText>
        <label>CAP Student Group Count</label>
        <summaryFilterItems>
            <field>Student_Group__c.SG_Status__c</field>
            <operation>equals</operation>
            <value>True</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Student_Group__c.SG_PeopleSoft_Code__c</field>
            <operation>equals</operation>
            <value>CP00, CP01, CP02</value>
        </summaryFilterItems>
        <summaryForeignKey>Student_Group__c.SG_Contact__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <description>[Peoplesoft] - Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</description>
        <formula>IF(CAP_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator","CAP Participant",20,20), 
IF(CAP_Ineligible_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator_Ineligable","CAP Ineligible",20,20), 
IF(CAP_Possible__c, 
IMAGE("/resource/CAP_Student_Indicator_Potential","CAP Possible",20,20), 
"")))</formula>
        <inlineHelpText>Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</inlineHelpText>
        <label>CAP</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[peoplesoft] - Picklist with the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Campus_Community</businessOwnerGroup>
    <complianceGroup>FERPA</complianceGroup>
    <description>Lookup to the EMPLID in the Contact Object
[Peoplesoft] - PeopleSoft unique ID
[MDM] - Read/Write - Critical to MDM
[DW: sfe_contact]</description>
    <formula>Contact__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>EMPLID</inlineHelpText>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>Session_A_C_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin</description>
        <label>Session A/C Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Session_B_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin for Session B</description>
        <label>Session B Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/ServiceCenter.cls
public with sharing class ServiceCenter {

    public Case c { get; set; }
    public Id caseContId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].ContactId;
    public List<Contact> contactList = [SELECT Id, Name FROM Contact WHERE Id = :caseContId];
    public Id caseId;
    Contact loggedInContact;
    String userAlias;

    public ServiceCenter() { c = new Case(); }
    public ServiceCenter(AKBController controller) { c = new Case(); }

    //Grab the logged in contact.
    public Contact getLoggedInContact() {
        userAlias = [SELECT Alias FROM User WHERE Id = :UserInfo.getUserId()].Alias;
        loggedInContact = [SELECT Id, Name FROM Contact WHERE ASURITE_Id__c = :userAlias];

        System.Debug('User Alias: ' + userAlias);
        System.Debug('Contact: ' + loggedInContact);
        return loggedInContact;
    }
    
    //Create and submit the case. Redirects user to service tab with confirmation.
    public PageReference submitCase() {
        getLoggedInContact();
        try {
            c.ContactId = loggedInContact.Id;
            System.Debug('Case Contact Id: ' + c.ContactId);
            c.Web_Submission__c = 'My ASU Standard';
            insert c;
            PageReference confirmPage = new PageReference('/studentSC?Confirm=case');
            confirmPage.setRedirect(true);
            return confirmPage;
        } catch (Exception e) {
            ApexPages.addMessages(e);
            System.Debug ('Message: ' + e.getMessage());
            System.Debug ('Cause: ' + e.getCause());
            System.Debug ('Stack Trace: ' + e.getStackTraceString());
            return null;
        }
    }
    
    //Removes the confirmation fromt the screen and then refreshes the page.
    public PageReference removeParam() {
        PageReference confirmPage = new PageReference('/studentSC');
        confirmPage.setRedirect(true);
        return confirmPage; 
    }
    
    
    //Codeblock for getting and displaying cases.
    public Solution[] getSolutions() {
        return [SELECT Id, SolutionNumber, SolutionName, Status FROM Solution];
    }
    
    public Case[] getMyCases() {
        if(contactList.isEmpty()){
            return [SELECT Subject, Status, Description, Origin, Origin__c FROM Case WHERE IsClosed = False AND Visible_by_Contact__c = true AND Created_By_Name__c = :UserInfo.getName()];
        } else {
            return [SELECT Subject, Status, Description, Origin, Origin__c FROM Case WHERE IsClosed = False AND Visible_by_Contact__c = true AND ContactId = :caseContId];
        }
    }
    
    public Case[] getClosedCases() {
        if(contactList.isEmpty()) {
            return [SELECT Subject, Status, Description, Origin, Origin__c FROM Case WHERE IsClosed = True AND Visible_by_Contact__c = true AND Created_By_Name__c = :UserInfo.getName()];
        } else {
            return [SELECT Subject, Status, Description, Origin FROM Case WHERE IsClosed = True AND Visible_by_Contact__c = true AND ContactId = :caseContId];
        }
    }
    
    public CaseFeed[] getCaseFeed() {
        return [SELECT Body, SystemModStamp from CaseFeed WHERE ParentId = :ApexPages.currentPage().getParameters().get('id') and CreatedById = :UserInfo.getUserId()];
    }
    
    public PageReference viewCase() {
        caseId = ApexPages.currentPage().getParameters().get('caseId');
        return new PageReference('/viewcase?id=' + caseId);
    }
    
    
    //Codeblock for showing/hiding elements on the page. Includes contact/opportunity information.
    public Id contId = [SELECT ContactId FROM User WHERE Id = :UserInfo.getUserId() LIMIT 1].ContactId;
    public Date d = date.today();
   
    public Term__c termcAC = [SELECT Session_A_C_Start_Date__c FROM Term__c where session_A_C_Start_Date__c > :system.today() limit 1];
    public Term__c termcB = [SELECT Session_B_Start_Date__c FROM Term__c where session_B_Start_Date__c > :system.today() limit 1];
    
    //public List<Term__c> termc = [SELECT Session_A_C_Start_Date__c, Session_B_Start_Date__c FROM Term__c];
    public List<Contact> cont = [SELECT Id, Name, EmplId__c, CAP__c, Personal_Email__c, CAP_Student_Group_Count__c, Affiliation_Student_Applicant__c, Affiliation_Student__c, Affiliation_Employee__c, Affiliation_Alumni__c, Affiliation_Courtesy_Affiliate__c FROM Contact WHERE Id = :contId];
    public List<Opportunity> oppList = [SELECT Career__c, Term__c, StageName, Admitted_Session__c FROM Opportunity WHERE Contact__c = :contId];

    public Boolean getNormalPhone() {
        if(cont == Null || cont.size() == 0) {
            return true;
        } else if(cont[0].CAP__c == Null) {
            return true;
        } else {
            return false;
        }
    }
    
    public Boolean getRoverPhone() {
        if(cont == Null || cont.size() == 0) {
            return false;
        } else if(cont[0].CAP__c == Null) {
            return false;
        } else {
            return true;
        }
    }
    
    //Code to show the different boxes on the Service Tab
    public Boolean getHelpBox() {
        if(cont == Null || cont.size() == 0) {
            return true;
        }
        else if((oppList == Null && cont.size() > 0) || (oppList.size() == 0 && cont.size() > 0)) {
            return true;
        } 
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'A/C') && d < date.valueOf(termcAC.Session_A_C_Start_Date__c)) {
            return false;
        }
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'B') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return false;
        }
        else if(oppList[0].StageName != 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && (cont[0].Affiliation_Student__c == 'Current' || cont[0].Affiliation_Alumni__c == 'Current' || cont[0].Affiliation_Courtesy_Affiliate__c == 'Current' || cont[0].Affiliation_Employee__c == 'Current') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return false;
        }
        else if(cont[0].CAP__c == Null) {
            return true;
        } 
        else {
            return true;
        }
    }
    
    public Boolean getQuestionsBox() {
        if(cont == Null || cont.size() == 0) {
            return false;
        } 
        else if((oppList == Null && cont.size() > 0) || (oppList.size() == 0 && cont.size() > 0)) {
            return false;
        } 
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'A/C') && d < date.valueOf(termcAC.Session_A_C_Start_Date__c)) {
            return true;
        }
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'B') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return true;
        }
        else if(oppList[0].StageName != 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && (cont[0].Affiliation_Student__c == 'Current' || cont[0].Affiliation_Alumni__c == 'Current' || cont[0].Affiliation_Courtesy_Affiliate__c == 'Current' || cont[0].Affiliation_Employee__c == 'Current') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return true;
        }
        else {
            return false;   
        }
    }
    
    public Boolean getMyCasesBox() {
        if(cont == Null || cont.size() == 0) {
            return true;
        } 
        else if((oppList == Null && cont.size() > 0) || (oppList.size() == 0 && cont.size() > 0)) {
            return true;
        } 
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'A/C') && d < date.valueOf(termcAC.Session_A_C_Start_Date__c)) {
            return false;
        }
        else if((oppList[0].StageName == 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && oppList[0].Admitted_Session__c == 'B') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return false;
        }
        else if(oppList[0].StageName != 'Enrolled' && oppList[0].Career__c == 'Undergraduate' && (cont[0].Affiliation_Student__c == 'Current' || cont[0].Affiliation_Alumni__c == 'Current' || cont[0].Affiliation_Courtesy_Affiliate__c == 'Current' || cont[0].Affiliation_Employee__c == 'Current') && d < date.valueOf(termcB.Session_B_Start_Date__c)) {
            return false;
        }
        else {
            return true;   
        }
    }
 
    
    //CodeBlock to get Case details for viewcase page.    
    public Case getCaseDetails() {
        return [SELECT Id, CaseNumber, Functional_Group__c, Subject, Description, CreatedDate, Status, Origin, Created_By_Name__c, ClosedDate FROM Case WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
    } 

    //MyPin reset
    public Decimal myPin;
    public Decimal newPin { get;set; }
    Contact contact;
    public Boolean isPinSuccess { get;set; }
        
    public Contact getContact() {
        if(contId != null) {
            contact = [SELECT Id, Self_Service_PIN__c, PIN_Lockout__c FROM Contact WHERE Id = :contId];
            return contact;
        }
        else {
            contact = [SELECT Id, Self_Service_PIN__c, PIN_Lockout__c FROM Contact WHERE Name = :UserInfo.getName() LIMIT 1];
            return contact;
        }   
    }
    
    public Decimal getMyPin() {
        getContact();
        if(contact != null) {
            myPin = contact.Self_Service_PIN__c;
            return myPin;
        }
        else {
            return null;
        }
    }
    
    public void closePinMessageBox() {
        ApexPages.getMessages().clear();
        isPinSuccess = false;
    }

    public PageReference changePin() {
        try {
            contact.Self_Service_PIN__c = newPin;
            if(contact.PIN_lockout__c == true) {
                contact.PIN_lockout__c = false;
            }
            update contact;
            ApexPages.Message success = new ApexPages.Message(ApexPages.Severity.CONFIRM,'Your PIN has been updated.');
            ApexPages.addMessage(success);
            isPinSuccess = true;
            PageReference ref = ApexPages.currentPage();
            return ref;
        }
        catch(DmlException e) {
            if(e.getMessage().contains('InvalidSelfServicePinException')) {
                ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR,'Your PIN cannot contain your year of birth.<br>Your PIN must not use more than 4 duplicate numbers.<br>Your PIN must be different than your previous PIN.<br>Your PIN cannot use more than 4 sequential numbers in your PIN. Forwards or backwards.<br>Your PIN must be between 6 and 10 characters.');
                ApexPages.addMessage(error);
                isPinSuccess = false;
                return null;    
            }
            else {
                throw e;   
            }
        }
    }
}