src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Case_Assignment_Rule__c.field-meta.xml
<CustomField>
    <fullName>Case_Assignment_Rule__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</description>
    <inlineHelpText>[Mulesoft] - Derived from the Enterprise RFI submission/payload, integration will set this field based on program, owner org code and the case source campaign. When using this field, it will not use RT assignment from the CAR.</inlineHelpText>
    <label>Case Assignment Rule</label>
    <referenceTo>Case_Assignment_Rule__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>Functional_Group__c</fullName>
    <description>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.
[DW: sfe_case]</description>
    <inlineHelpText>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.</inlineHelpText>
    <label>Functional Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Academic Partnerships</fullName>
            </value>
            <value>
                <fullName>Academic Transfer Credit Solutions</fullName>
            </value>
            <value>
                <fullName>Access ASU Outreach</fullName>
            </value>
            <value>
                <fullName>Admission Appeals</fullName>
            </value>
            <value>
                <fullName>Admission Services</fullName>
            </value>
            <value>
                <fullName>Admission Services OPS</fullName>
            </value>
            <value>
                <fullName>ASASU- Associated Students of ASU</fullName>
            </value>
            <value>
                <fullName>ASU Colleges at Lake Havasu</fullName>
                <label>ASU@Lake Havasu</label>
            </value>
            <value>
                <fullName>ASU Advisor Outreach</fullName>
            </value>
            <value>
                <fullName>ASU Coach Outreach</fullName>
            </value>
            <value>
                <fullName>ASU Family Programs</fullName>
            </value>
            <value>
                <fullName>ASU Graduate Advisor Portal</fullName>
            </value>
            <value>
                <fullName>ASU Health</fullName>
            </value>
            <value>
                <fullName>ASU Local</fullName>
            </value>
            <value>
                <fullName>ASU New Student Programs</fullName>
            </value>
            <value>
                <fullName>ASU Online</fullName>
            </value>
            <value>
                <fullName>ASUO Student Engagement</fullName>
            </value>
            <value>
                <fullName>ASU Salesforce Support</fullName>
            </value>
            <value>
                <fullName>ASU-USA Pathways</fullName>
            </value>
            <value>
                <fullName>ASU Wellness</fullName>
            </value>
            <value>
                <fullName>Biosafety</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Career Services</fullName>
            </value>
            <value>
                <fullName>Changemaker</fullName>
            </value>
            <value>
                <fullName>Chief Wellness Officer</fullName>
            </value>
            <value>
                <fullName>Classroom Scheduling</fullName>
            </value>
            <value>
                <fullName>College of ASU - Training</fullName>
            </value>
            <value>
                <fullName>College of Global Futures</fullName>
            </value>
            <value>
                <fullName>Curricular Activities and Actions</fullName>
            </value>
            <value>
                <fullName>Dean of Students</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Case_Assignment_Rule__c.object
<CustomObject><fields>
        <fullName>CTPColumn__c</fullName>
        <description>This picklist lists the columns from the Case Transfer page. It is used to tell where a CAR list will be placed on that page.</description>
        <label>CTP Column</label>
        <picklist>
            <picklistValues>
                <fullName>Service Departments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colleges</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>CTPGroup__c</fullName>
        <description>This picklist lists the Group names for the Case Transfer Page.</description>
        <label>CTP Group</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Partnerships</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Transfer Credit Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access ASU Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admission Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Indian Student Support Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Salesforce Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU-USA Pathways</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Wellness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blackboard UTO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canon (Print Anywhere)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changemaker Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of ASU - Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Health Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Curricular Activities and Actions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean of Students</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department of ASU - Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design and the Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Educational Outreach and Student Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Analysis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enrollment Services ISD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enterprise Marketing Hub</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Environmental Health and Safety</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EOSS - Access ASU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESM Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First in the World Grant</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>CTPVisible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to display the CAR on the Case Transfer page.</description>
        <inlineHelpText>Use this checkbox to display the Case Assignment Rule on the Case Transfer page. If it is checked, it will appear on the page.</inlineHelpText>
        <label>CTP Is Visible</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Email_Address__c</fullName>
        <description>[??] - Case email address</description>
        <inlineHelpText>This Email Address is used:
1. To identify which Assignment Rule to Use (if this address is found in the "Initial Request Sent To Addresses")
2. As the "From" address for the notice emailed to the customer that a Case has been created.</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Functional_Group__c</fullName>
        <description>[??] - Functional Group that is associated with this Case Assignment. Ensure that the value used here exists in Case "Functional Group" Picklist, and that the spelling is identical.</description>
        <inlineHelpText>Enter the Functional Group that is associated with this Case Assignment. Ensure that the value used here exists in Case "Functional Group" Picklist, and that the spelling is identical.</inlineHelpText>
        <label>Functional Group</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Label__c</fullName>
        <description>This is the custom label used for the Case Assignment Rule</description>
        <inlineHelpText>This is the custom label used for the Case Assignment Rule</inlineHelpText>
        <label>CTP Label</label>
        <length>255</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object used to assign case records. Criteria based on email address or association with a web form campaign record.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Case Assignment Rule</label><nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Case Assignment Rule</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

src/classes/CaseTransferController.cls
public with sharing class CaseTransferController 
{
	public Case currentCase { get;set; }
	public List<Case_Assignment_Rule__c> allCARs;
	public List<Schema.PickListEntry> columnList;

	public CaseTransferController() 
	{
		currentCase = [SELECT Id 
					   FROM Case 
					   WHERE Id = :ApexPages.currentPage().getParameters().get('Id')];
		allCARs = [SELECT Id, CTPColumn__c, CTPGroup__c, CTPVisible__c, Email_Address__c, Functional_Group__c, Label__c, Name 
				   FROM Case_Assignment_Rule__c 
				   WHERE CTPColumn__c != null 
				   AND CTPGroup__c != null 
				   AND Label__c != null 
				   AND CTPVisible__c = true];
		Schema.DescribeFieldResult fieldResult = Case_Assignment_Rule__c.CTPColumn__c.getDescribe();
		columnList = fieldResult.getPicklistValues();
	}
}