src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Advisor_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Advisor Outreach</businessProcess>
        <description>used for cases created for the Student Success Portal</description>
        <label>(Admin Only) ASU Advisor Outreach</label>
    </recordTypes>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Service</fullName>
        <active>true</active>
        <businessProcess>ASU Service</businessProcess>
        <description>Record type used for all Service departments.</description>
        <label>ASU Service</label>
    </recordTypes>

src/objects/Portal_Email__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Additional_Message_Text__c</fullName>
        <label>Additional Message Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Most_Recent_Queue__c</fullName>
        <description>The queue the case was most recently assigned to.</description>
        <formula>Case__r.Most_Recent_Queue__c</formula>
        <inlineHelpText>Used to determine which queue to send at if the primary ownerId is a userId.</inlineHelpText>
        <label>Case Most Recent Queue</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Thread_Id__c</fullName>
        <formula>Case__r.Thread_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Thread Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Message_Id__c</fullName>
        <label>Email Message Id</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Template_Name__c</fullName>
        <label>Email Template Name</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor Ad-hoc template</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>From_Address__c</fullName>
        <description>The email address that is sending the email.</description>
        <label>From Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Owner_Id__c</fullName>
        <description>Displays the OwnerId to be used in determining the desired from address.</description>
        <formula>IF(
 ISBLANK( Case_Owner_Id__c ),
 Student_Owner_Id__c,
 Case_Owner_Id__c
)</formula>
        <label>Primary Owner Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Held/Undeliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Bounced/Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Email Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Student</label>
        <referenceTo>Success_Student__c</referenceTo>
        <relationshipLabel>Portal Emails</relationshipLabel>
        <relationshipName>Portal_Emails</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object containing all of the information required to send emails from within the portal through the marketing cloud integration.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Portal Email</label><nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Portal Email Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Portal Emails</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_with_Details</fullName>
        <columns>NAME</columns>
        <columns>CREATED_DATE</columns>
        <columns>RECORDTYPE</columns>
        <columns>Status__c</columns>
        <columns>Contact__c</columns>
        <columns>Email_Template_Name__c</columns>
        <columns>From_Name__c</columns>
        <columns>From_Address__c</columns>
        <filterScope>Everything</filterScope>
        <label>All with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Test_Messages</fullName>
        <booleanFilter>1</booleanFilter>
        <columns>CREATED_DATE</columns>
        <columns>NAME</columns>
        <columns>Status__c</columns>
        <columns>From_Address__c</columns>
        <columns>From_Name__c</columns>
        <columns>Contact__c</columns>
        <columns>Contact_Email__c</columns>
        <columns>Case_Number__c</columns>
        <columns>Case_Owner_Id__c</columns>
        <columns>Contact_First_Name__c</columns>
        <columns>Created_By_Full_Name__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Contact__c</field>
            <operation>equals</operation>
            <value>Dawn Scott</value>
        </filters>
        <label>Test Messages</label>
    </listViews><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes></CustomObject>

force-app/main/default/objects/Portal_Email__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <label>Advisor</label>
</RecordType>

src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Role__c</fullName>
        <label>Resource Role</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Person is available to be assigned Success Students</description>
    <label>Active Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/Test_AdvisorPortalMainPage.cls
@isTest
public class Test_AdvisorPortalMainPage {
    private static Integer numberOfPods;
    private static Integer numberOfCases;
    private static Integer numberOfStudents;
    private static Integer numberOfTabsForUser;
    private static Integer numberOfBlankOptionsForUser;
    private static Integer numberOfTabsForManager;
    private static Integer numberOfBlankOptionsForManager;
    private static Integer numbeOfAdvisorsForManager;
    private static AdvisorPortalMainPageController apmpc;

    /*
     * Static initialization code to mimize repeat code between test methods
     * values take into consideration user having themselves as a viewAsOptions
     * for success resources of type 'User'
     */
    static {
        numberOfPods = 3;
        numberOfCases = 1;
        numberOfStudents = 10;
        numberOfTabsForUser = 2;
        numberOfBlankOptionsForUser = 1;
        numberOfTabsForManager = 3;
        numberOfBlankOptionsForManager = 2;
        numbeOfAdvisorsForManager = 1;
        apmpc = new AdvisorPortalMainPageController();
    }

    @isTest
    private static void checkUserViewAsOptions() {
        UserFactory.makeMeAnAdvisorUser(numberOfPods, numberOfCases, numberOfStudents);

        Test.startTest();
        List<SelectOption> listToTest = apmpc.viewAsOptions;
        Test.stopTest();

        validateUserOptionsSize(listToTest);
        validateCurrentUserOption(listToTest);
        validateBlankOptionsForUser(listToTest);
        validateTabsForUser(listToTest);
        validateCommitteesGroupId(listToTest);
    }

    @isTest
    private static void Test_allowedToMassTransfer() {
        User allowedUser1 = TestDataFactory.createUser(
            'test-mass-transfer-r1',
            [SELECT Id FROM Profile WHERE Name = 'Standard User']
            .Id
        );
        User allowedUser2 = TestDataFactory.createUser(
            'test-mass-transfer-r2',
            [SELECT Id FROM Profile WHERE Name = 'Standard User']
            .Id
        );
        User unallowedUser1 = TestDataFactory.createUser(
            'test-mass-transfer-r3',
            [SELECT Id FROM Profile WHERE Name = 'Standard User']
            .Id
        );
        User unallowedUser2 = TestDataFactory.createUser(
            'test-mass-transfer-r4',
            [SELECT Id FROM Profile WHERE Name = 'Standard User']
            .Id
        );
        User unallowedUser3 = TestDataFactory.createUser(
            'test-mass-transfer-r5',
            [SELECT Id FROM Profile WHERE Name = 'Standard User']
            .Id
        );
        insert new List<User>{ allowedUser1, allowedUser2, unallowedUser1, unallowedUser2, unallowedUser3 };

        Success_Resource__c allowedUser1Resource = new Success_Resource__c(
            Resource__c = allowedUser1.Id,
            Role__c = 'Department Manager',
            IsActive__c = true,
            RecordTypeId = IdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
        );
        Success_Resource__c allowedUser2Resource = new Success_Resource__c(
            Resource__c = allowedUser2.Id,
            Role__c = 'College Manager',
            IsActive__c = true,
            RecordTypeId = IdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
        );
        Success_Resource__c unallowedUserResource = new Success_Resource__c(
            Resource__c = unallowedUser1.Id,
            Role__c = 'User',
            IsActive__c = true,
            RecordTypeId = IdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
        );
        Success_Resource__c unallowedUserResource2 = new Success_Resource__c(
            Resource__c = unallowedUser2.Id,
            Role__c = 'College Manager',
            IsActive__c = false,
            RecordTypeId = IdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
        );
        insert new List<Success_Resource__c>{
            allowedUser1Resource,
            allowedUser2Resource,
            unallowedUserResource,
            unallowedUserResource2
        };

        System.runAs(allowedUser1) {
            apmpc = new AdvisorPortalMainPageController();
            System.assert(apmpc.allowedToMassTransfer, 'Department Manager\'s should be allowed to use this feature');
        }
        System.runAs(allowedUser2) {
            apmpc = new AdvisorPortalMainPageController();
            System.assert(apmpc.allowedToMassTransfer, 'College Manager\'s should be allowed to use this feature');
        }
        System.runAs(unallowedUser1) {
            apmpc = new AdvisorPortalMainPageController();
            System.assert(!apmpc.allowedToMassTransfer, 'User\'s should not be allowed to use this feature');
        }
        System.runAs(unallowedUser2) {
            apmpc = new AdvisorPortalMainPageController();
            System.assert(!apmpc.allowedToMassTransfer, 'Should not consider inactive Success_Resources');
        }
        System.runAs(unallowedUser3) {
            apmpc = new AdvisorPortalMainPageController();
            System.assert(!apmpc.allowedToMassTransfer, 'Default (if no Success_Resources) should be to not allow');
        }
    }

    /*
     * As of right now the answer to this question should always be true.
     * We need to figure out under what circumstances the view as functionality should
     * be displayed and update the controller method.
     */
    public static testMethod void Test_getHasViewAs() {
        system.assert(true, apmpc.hasViewAs);
    }

    /*
     * MimicId has basic getter and setter. We still need to test for code coverate.
     *
     * <p>
     * This may seem simple and unecessary; however, if the getter/setter changes in the future,
     * this will ensure that the new getter/setter are compatible with existing functionality.
     * </p>
     */
    public static testMethod void Test_getSetMimicId() {
        apmpc.OwnerId = UserInfo.getUserId();
        system.assertEquals(UserInfo.getUserId(), apmpc.OwnerId);
    }

    public static testMethod void Test_getAdvisorEmailRTID() {
        system.assertEquals(IDHelper.getRTID('Portal_Email__c', 'Advisor'), apmpc.advisorEmailRTID);
    }

    public static testMethod void Test_getAdvisorProactiveCaseRTID() {
        system.assertEquals(IDHelper.getRTID('Case', 'ASU_Advisor_Outreach'), apmpc.AdvisorProactiveCaseRTID);
    }

    public static testMethod void Test_getAdvisorReactiveCaseRTID() {
        system.assertEquals(IDHelper.getRTID('Case', 'ASU_Service'), apmpc.AdvisorReactiveCaseRTID);
    }

    public static testMethod void Test_getQueries() {
        apmpc.ownerId = UserInfo.getUserId();

        system.assert(apmpc.myProactiveQuery.contains((String) apmpc.OwnerId));
        system.assert(apmpc.myWatchlistQuery.contains((String) apmpc.OwnerId));
        system.assert(apmpc.myStudentsQuery.contains((String) apmpc.OwnerId));
    }

    @isTest
    private static void checkDepartmentManagerViewAsOptions() {
        UserFactory.makeMeAnAdvisorDepartmentManager(numberOfPods, numberOfCases, numberOfStudents);

        Test.startTest();
        List<SelectOption> listToTest = apmpc.viewAsOptions;
        Test.stopTest();

        validateManagerOptionsSize(listToTest);
        validateCurrentUserOption(listToTest);
        validateBlankOptionsForManager(listToTest);
        validateTabsForDepartmentManager(listToTest);
        validateCommitteesGroupId(listToTest);
    }

    @isTest
    private static void checkCollegeManagerViewAsOptions() {
        UserFactory.makeMeAnAdvisorCollegeManager(numberOfPods, numberOfCases, numberOfStudents);

        Test.startTest();
        List<SelectOption> listToTest = apmpc.viewAsOptions;
        Test.stopTest();

        validateManagerOptionsSize(listToTest);
        validateCurrentUserOption(listToTest);
        validateBlankOptionsForManager(listToTest);
        validateTabsForCollegeManager(listToTest);
        validateCommitteesGroupId(listToTest);
    }

    private static void validateUserOptionsSize(List<SelectOption> listToTest) {
        System.assertEquals(numberOfTabsForUser + numberOfBlankOptionsForUser + numberOfPods, listToTest.size());
    }

    private static void validateManagerOptionsSize(List<SelectOption> listToTest) {
        System.assertEquals(
            numberOfTabsForManager +
            numberOfBlankOptionsForManager +
            numbeOfAdvisorsForManager +
            numberOfPods,
            listToTest.size()
        );
    }

    private static void validateCurrentUserOption(List<SelectOption> listToTest) {
        System.assertEquals(UserInfo.getName(), listToTest[0].getLabel());
        System.assertEquals(UserInfo.getUserId(), listToTest[0].getValue());
    }

    private static void validateBlankOptionsForUser(List<SelectOption> listToTest) {
        System.assertEquals('', listToTest[1].getLabel());
        System.assertEquals('', listToTest[1].getValue());
        System.assert(listToTest[1].getDisabled());
    }

    private static void validateBlankOptionsForManager(List<SelectOption> listToTest) {
        System.assertEquals('', listToTest[1].getLabel());
        System.assertEquals('', listToTest[1].getValue());
        System.assert(listToTest[1].getDisabled());

        System.assertEquals('', listToTest[6].getLabel());
        System.assertEquals('', listToTest[6].getValue());
        System.assert(listToTest[6].getDisabled());
    }

    private static void validateTabsForUser(List<SelectOption> listToTest) {
        System.assertEquals('--My Committees--', listToTest[2].getLabel());
        System.assertEquals('', listToTest[2].getValue());
        System.assert(listToTest[2].getDisabled());
    }

    private static void validateTabsForDepartmentManager(List<SelectOption> listToTest) {
        System.assertEquals('--Department Committees--', listToTest[2].getLabel());
        System.assertEquals('', listToTest[2].getValue());
        System.assert(listToTest[2].getDisabled());

        System.assertEquals('--Department Advisors--', listToTest[7].getLabel());
        System.assertEquals('', listToTest[7].getValue());
        System.assert(listToTest[7].getDisabled());
    }

    private static void validateTabsForCollegeManager(List<SelectOption> listToTest) {
        System.assertEquals('--College Advisors--', listToTest[7].getLabel());
        System.assertEquals('', listToTest[7].getValue());
        System.assert(listToTest[7].getDisabled());
    }

    private static void validateCommitteesGroupId(List<SelectOption> listToTest) {
        Validator.setPrefix(Group.class);
        Integer firstCommitteeOptionIndex = 3;
        for (Integer i = firstCommitteeOptionIndex; i < firstCommitteeOptionIndex + numberOfPods; i++) {
            System.assert(Validator.validateId(listToTest[i].getValue()));
        }
    }
}