src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <label>Category</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/CaseClassificationLWCServiceTest.cls
@IsTest
private class CaseClassificationLWCServiceTest{

    @testSetup 
    static void setup() {
        CaseClassificationFactory ccFactory = new CaseClassificationFactory();
        List<Case_Classification__c> classifications = ccFactory.createAndInsertSetOfCaseClassification();
        classifications[0].Name = 'Initial Test Functional Group';
        classifications[1].Name = 'Initial Test Category';
        classifications[2].Name = 'Initial Test Sub Category';

        update classifications;

	}
    
    @IsTest
    private static void testGetActiveClassifications() {
        List<Case_Classification__c> classifications;

        Test.startTest();
            classifications  = CaseClassificationLWCService.getClassifications();
        Test.stopTest();

        System.assertEquals('Initial Test Functional Group', classifications[0].Name);
        System.assertEquals(classifications[0].Id, classifications[1].Parent__c);
    }
}