src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/CC_Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>CC_Functional_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field looks up to the Case Classification object where record type = Functional Group.
[DW: sfe_case]</description>
    <label>Case Functional Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Functional Group</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Visible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>Cases (Functional Group)</relationshipLabel>
    <relationshipName>Cases_Functional_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Is_Functional_Group_Private__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Functional Group Private</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case_Classification__c/fields/Queue_Id__c.field-meta.xml
<CustomField>
    <fullName>Queue_Id__c</fullName>
    <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
    <description>If a case with this Private functional group is assigned to a user, and that user is then deprovisioned, set the owner of the case to this Id post-deprovision.</description>
    <inlineHelpText>This is the default 18 digits queue id used by the user deprovision process when the case owner is deprovisioned and case Functional Group is Private.</inlineHelpText>
    <label>Queue Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/objects/Deprovision_User_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This setting is used to set User field value for the Deprovision User process</description>
    <fields>
        <fullName>Id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Id</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Deprovision User Configuration</label>
</CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/Processing_Notes__c.field-meta.xml
<CustomField>
    <fullName>Processing_Notes__c</fullName>
    <businessOwnerGroup>Data_Owner_IAM_Identity_Management</businessOwnerGroup>
    <description>Notes about the deprovision process - steps taken and errors encountered.</description>
    <inlineHelpText>Notes from the deprovision process that is triggered by checking the checkbox Deprovision_User__c.</inlineHelpText>
    <label>Processing Notes</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

src/classes/UserDeprovisioner.cls
public without sharing class UserDeprovisioner {

    private String processingNotes;
    private User userToDeprovision;
    private Map<String, Deprovision_User_Configuration__c> deprovisionUserConfiguration;
    private List<Case> userCases;
    private List<Case> updatedUserCases;
    private String groupMemberships;

    public UserDeprovisioner() {
        processingNotes = '';
    }

    public void setUserToDeprovision(User userToDeprovision) {
        this.userToDeprovision = userToDeprovision;
        deprovisionUserConfiguration = Deprovision_User_Configuration__c.getAll();
    }

    public User getUserToDeprovision() {
        return userToDeprovision;
    }

    public void setUserCases(List<Case> userCases) {
        this.userCases = userCases;
    }

    public String getProcessingNotes() {
        return processingNotes;
    }

    public User getDeprovisionedUserIdWithProcessingNotes() {
        User deprovisionedUserIdWithProcessingNotes = new User(Id = userToDeprovision.Id, Processing_Notes__c = processingNotes);
        return deprovisionedUserIdWithProcessingNotes;
    }

    public List<Case> getUpdatedUserCases() {
        return updatedUserCases;
    }

    public void setGroupMemberships(String groupMemberships) {
        this.groupMemberships = groupMemberships;
    }

    public void deprovisionUser() {
        try {
            addToProcessingNotes(initialUserTimeStamp());
            if (matchProfileToIgnore()) {
                return;
            }
            changeUserProfile();
            changeUserRole();
            transferPrivateCasesToFunctionalGroup();
            updateUserFields();
            logRemovedGroupMemberships();

        } catch (Exception e) {
            addToProcessingNotes(e.getMessage());
        }
    }

    private void addToProcessingNotes(String message) {
        processingNotes += message + '\n';
    }

    public String initialUserTimeStamp() {
        return System.now() + ' UserId: ' + UserInfo.getUserId() + ', UserName: ' +UserInfo.getName();
    }

    private Boolean matchProfileToIgnore() {
        for (String deprovisionConfigurationName : deprovisionUserConfiguration.keySet()) {
            if (deprovisionConfigurationName.contains('ProfileToIgnore')) {
                Id profileIdToMatch = Id.valueOf(deprovisionUserConfiguration.get(deprovisionConfigurationName).Id__c);
                if (userToDeprovision.ProfileId == profileIdToMatch) {
                    addToProcessingNotes('Profile matched to: ' + deprovisionUserConfiguration.get(deprovisionConfigurationName).Name__c + ', Stopping User Deprovision');
                    return true;
                }
            }
        }
        return false;
    }

    private void changeUserProfile() {
        Deprovision_User_Configuration__c changeProfileTo = deprovisionUserConfiguration.get('Change Profile To');
        addToProcessingNotes('Changed User Profile from: ' + userToDeprovision.ProfileId + ' to ' + changeProfileTo.Name__c);
        userToDeprovision.ProfileId = Id.valueOf(changeProfileTo.Id__c);
    }

    private void changeUserRole() {
        Deprovision_User_Configuration__c changeRoleTo = deprovisionUserConfiguration.get('Change Role To');
        addToProcessingNotes('Changed User Role from: ' + userToDeprovision.UserRoleId + ' to ' + changeRoleTo.Name__c);
        userToDeprovision.UserRoleId = Id.valueOf(changeRoleTo.Id__c);
    }

    private void transferPrivateCasesToFunctionalGroup() {
        updatedUserCases = new List<Case>();
        for (Case userCase : userCases) {
            if (userCase.CC_Functional_Group__r.Is_Functional_Group_Private__c) {
                userCase.OwnerId = userCase.CC_Functional_Group__r.Queue_Id__c;
                updatedUserCases.add(userCase);
                addToProcessingNotes('Transferred case: ' + userCase.Id + ' to Functional Group queue: ' + userCase.CC_Functional_Group__r.Name);
            }
        }
    }

    private void updateUserFields() {
        for (String deprovisionConfigurationName : deprovisionUserConfiguration.keySet()) {
            if (deprovisionConfigurationName.contains('SwitchToFalse')) {
                Deprovision_User_Configuration__c configuration = deprovisionUserConfiguration.get(deprovisionConfigurationName);
                if (userToDeprovision.get(configuration.Name__c) == true) {
                    userToDeprovision.put(configuration.Name__c, false);
                    addToProcessingNotes('Switched ' + configuration.Name__c + ' to false');
                }
            } else if (deprovisionConfigurationName.contains('RemoveValue')) {
                Deprovision_User_Configuration__c configuration = deprovisionUserConfiguration.get(deprovisionConfigurationName);
                if (userToDeprovision.get(configuration.Name__c) != null) {
                    addToProcessingNotes('Removed value '+ userToDeprovision.get(configuration.Name__c) + ' for ' + configuration.Name__c);
                    userToDeprovision.put(configuration.Name__c, null);
                }
            }
        }
    }

    private void logRemovedGroupMemberships() {
        addToProcessingNotes('Removed user from Public Groups: ' + groupMemberships);
    }
}