src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <description>The ASU campus where service is provided.
[DW: sfe_case]</description>
    <inlineHelpText>The ASU campus where service is provided.</inlineHelpText>
    <label>Service Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Downtown</fullName>
            </value>
            <value>
                <fullName>Gila Valley</fullName>
            </value>
            <value>
                <fullName>Havasu</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Polytechnic</fullName>
            </value>
            <value>
                <fullName>Tempe</fullName>
            </value>
            <value>
                <fullName>Thunderbird</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Yuma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Category__c.field-meta.xml
<CustomField>
    <fullName>CC_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field looks up to the Case Classification object where record type = Category.
[DW: sfe_case]</description>
    <label>Case Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.CC_Functional_Group__c</valueField>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Visible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>Cases (Category)</relationshipLabel>
    <relationshipName>Cases_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Change_Date__c.field-meta.xml
<CustomField>
    <fullName>Change_Date__c</fullName>
    <formula>Contact.Change_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Most Recent Outlook Change Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Curr_Cont_Prediction_Level__c.field-meta.xml
<CustomField>
    <fullName>Curr_Cont_Prediction_Level__c</fullName>
    <formula>Contact.Curr_Cont_Prediction_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Outlook Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Most_Recent_Outlook_Change_Direction__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Outlook_Change_Direction__c</fullName>
    <formula>Contact.Most_Recent_Outlook_Change_Direction__c</formula>
    <label>Most Recent Outlook Change Direction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Advisor_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Advisor Outreach</businessProcess>
        <description>used for cases created for the Student Success Portal</description>
        <label>(Admin Only) ASU Advisor Outreach</label>
    </recordTypes>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Change_Date__c</fullName>
        <description>The most recent change in the student's persistence outlook</description>
        <label>Most Recent Outlook Change Date</label>
        <summarizedField>Persistence_Outlook__c.Change_Date__c</summarizedField>
        <summaryForeignKey>Persistence_Outlook__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Curr_Cont_Prediction_Level__c</fullName>
        <description>The persistence outlook prediction level for the student after the most recent change.</description>
        <label>Current Outlook Level</label>
        <summarizedField>Persistence_Outlook__c.Curr_Cont_Prediction_Level__c</summarizedField>
        <summaryForeignKey>Persistence_Outlook__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Most_Recent_Outlook_Change_Direction__c</fullName>
        <description>The direction of change between -2 (for null previous values) to 1 (for positive changes) for the students civitas persistence score</description>
        <label>Most Recent Outlook Change Direction</label>
        <summarizedField>Persistence_Outlook__c.Change_Direction__c</summarizedField>
        <summaryForeignKey>Persistence_Outlook__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <description>Campus

Location records are manually entered at this time.  
Review SFE-2602 for details of why and how this object works.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Student_Group__c.object
<CustomObject><fields>
        <fullName>SG_PeopleSoft_Code__c</fullName>
        <description>[Peoplesoft] - Peoplesoft code</description>
        <label>PeopleSoft Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Student Group information from PeopleSoft</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Group</label><nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Group Label</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Groups</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

force-app/main/default/objects/Student_Group__c/fields/SG_Contact__c.field-meta.xml
<CustomField>
    <fullName>SG_Contact__c</fullName>
    <description>[Peoplesoft] - Relationship to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Groups</relationshipLabel>
    <relationshipName>Student_Groups_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Campus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Data sourced from PS_ACAD_PROG.CAMPUS</description>
        <label>Campus</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Student Program Plans</relationshipLabel>
        <relationshipName>Student_Program_Plans</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Plan_Description__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.DESCR</description>
        <label>Plan Description</label>
        <length>30</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>FTFF + PS_ASU_SR0189_SPRF .ASU_ACAD_LVL_BOT_D</description>
    <label>Cohort</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Program_Plan__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <description>(PeopleSoft) PS_ASU_SR0189_SPRF.RESIDENCY</description>
    <label>Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/classes/AdvisorPortalFilterHelper.cls
/**
* @author Mathew Ruff, Sierra-Cedar
* @date 2019-08-02
*
* Used as a helper class that filters Contacts on the Advisor Portal.
*/
public class AdvisorPortalFilterHelper {
    private static Map<String, Set<Decimal>> outlookScoresByLabels = new Map<String, Set<Decimal>>{
        'very low' => new Set<Decimal>{0, 1, 2, 3},
        'low' => new Set<Decimal>{4, 5},
        'moderate' => new Set<Decimal>{6},
        'high' => new Set<Decimal>{7},
        'very high' => new Set<Decimal>{8, 9, 10}
    };

    private static Map<String, Decimal> outlookChangeByLabels = new Map<String, Decimal>{
        'up' => 1,
        'down' => 0,
        'no change' => -1
    };

    public static List<String> getCachedOwnerIdList() {
        List<String> ownerIdList = new List<String>();
    	if (Cache.Session.contains('advisorPortalOwnerIdList')) {
    		ownerIdList = (List<String>)Cache.Session.get('advisorPortalOwnerIdList');
		}
        return ownerIdList;
    }
    
    public static String getOwnerIdsForQuery() {
        String additionalOwnerIds = '';
        String currentUserId = UserInfo.getUserId();
        String queryString = '(OwnerId = \'' + currentUserId + '\'';
        
        List<String> ownerIdList = getCachedOwnerIdList();
        if (ownerIdList != null && ownerIdList.size() > 0) {
            for (String ownerId : ownerIdList) {
                additionalOwnerIds += ' OR OwnerId = \'' + ownerId + '\'';
            }
        }
        queryString += additionalOwnerIds + ')';
        
        return queryString;
    }

    /**
     * Filters Contact records using SOSL and the provided filter.
     *
     * @param filter, the AdvisorPortalFilter to use.
     * @param contactIds, a Set of Contact Ids to use in the query.
     *
     * @return, a filtered Set of Contact Ids
     */
    public static Set<Id> filterContacts(AdvisorPortalFilter filter, Set<Id> contactIds) {
        if (String.isBlank(filter.studentString)) {
            return contactIds;
        } else {
            return new Map<Id, Contact>((List<Contact>) [
                FIND :filter.studentString
                    RETURNING Contact (Id WHERE Id IN :contactIds)
            ][0]).keySet();
        }
    }

    /**
     * Queries for Case records using the supplied filter and Contact Ids.
     *
     * @param filter, the AdvisorPortalFilter to use.
     * @param contactIds, a Set of Contact Ids to use in the query.
     *
     * @return, a filtered List of Case records.
     */
    public static List<Case> filterCases(AdvisorPortalFilter filter, Set<Id> contactIds) {
        String queryString = '' +
            'SELECT Priority, ' +
                'CaseNumber, ' +
                'Subject, ' +
                'Status, ' +
                'Followup_Date__c, ' +
                'Owner.Name, ' +
                'CreatedDate, ' +
                'CC_Category__r.Name, ' +
                'CC_Category__r.Parent__r.Name, ' +
                'RecordType.Name, ' +
                'Change_Date__c, ' +
                'Curr_Cont_Prediction_Level__c, ' +
                'Most_Recent_Outlook_Change_Direction__c, ' +
                'OwnerId, ' +
                'ContactId ' +
            'FROM Case ' +
            'WHERE ContactId IN :contactIds ' +
            'AND IsClosed = FALSE ' +
            'AND RecordTypeId = \'' + IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach') + '\'';

        if (!String.isBlank(filter.caseCategory)) {
            List<String> categories = filter.caseCategory.split(';');
            queryString += ' AND CC_Category__r.Name IN :categories';
        }

        if (!String.isBlank(filter.caseSubject)) {
            List<String> subjects = filter.caseSubject.split(';');
            queryString += ' AND Subject IN :subjects';
        }

        if (!String.isBlank(filter.caseStatus)) {
            List<String> statuses = filter.caseStatus.split(';');
            queryString += ' AND Status IN :statuses';
        }
        
        queryString += ' AND ' + getOwnerIdsForQuery();

        if (filter.watchlistCasesState != null && filter.watchlistCasesState) {
            queryString += ' AND CC_Category__r.Name = \'Watchlist\' AND CC_Category__r.Parent__r.Name = \'ASU Advisor Outreach\'';
        }

        if (!String.isBlank(filter.outlookScore)) {
            List<Decimal> scores = new List<Decimal>();

            for (String s : filter.outlookScore.split(';')) {
                if (outlookScoresByLabels.containsKey(s)) {
                    scores.addAll(outlookScoresByLabels.get(s));
                }
            }

            queryString += ' AND Curr_Cont_Prediction_Level__c IN :scores';
        }

        if (!String.isBlank(filter.outlookChange)) {
            List<Decimal> changeDirections = new List<Decimal>();

            for (String s : filter.outlookChange.split(';')) {
                if (outlookChangeByLabels.containsKey(s)) {
                    changeDirections.add(outlookChangeByLabels.get(s));
                }
            }

            queryString += ' AND Most_Recent_Outlook_Change_Direction__c IN :changeDirections';
        }

        if (!String.isBlank(filter.createdFromDate)) {
            queryString += ' AND CreatedDate >= ' + Datetime.valueOf(filter.createdFromDate + ' 00:00:00').formatGmt('yyyy-MM-dd\'T\'HH:mm:ssZ');
        }

        if (!String.isBlank(filter.createdToDate)) {
            queryString += ' AND CreatedDate <= ' + Datetime.valueOf(filter.createdToDate + ' 00:00:00').formatGmt('yyyy-MM-dd\'T\'HH:mm:ssZ');
        }

        if (!String.isBlank(filter.followUpFromDate)) {
            queryString += ' AND Followup_Date__c >= ' + filter.followUpFromDate;
        }

        if (!String.isBlank(filter.followUpToDate)) {
            queryString += ' AND Followup_Date__c <= ' + filter.followUpToDate;
        }

        if (!String.isBlank(filter.persistenceFromDate)) {
            queryString += ' AND Change_Date__c >= ' + filter.persistenceFromDate;
        }

        if (!String.isBlank(filter.persistenceToDate)) {
            queryString += ' AND Change_Date__c <= ' + filter.persistenceToDate;
        }

        queryString += ' LIMIT 10000';

        return Database.query(queryString);
    }

    /**
     * Queries for Contact Ids based on the provided filter on Student_Group__c.
     *
     * @param filter, the AdvisorPortalFilter to use.
     * @param contactIds, a Set of Contact Ids to use in the query.
     *
     * @return filteredContactIds, a filtered Set of Contact Ids matching the filter criteria.
     */
    public static Set<Id> filterStudentGroups(AdvisorPortalFilter filter, Set<Id> contactIds) {
        Set<Id> filteredContactIds = new Set<Id>();

        if (!String.isBlank(filter.studentGroupCode)) {
            for (AggregateResult studentPlanResult : [
                SELECT SG_Contact__c
                FROM Student_Group__c
                WHERE SG_Contact__c IN :contactIds
                AND SG_PeopleSoft_Code__c = :filter.studentGroupCode
                GROUP BY SG_Contact__c
                LIMIT 2000
            ]) {
                filteredContactIds.add((Id) studentPlanResult.get('SG_Contact__c'));
            }
            return filteredContactIds;
        } else {
            return contactIds;
        }
    }

    /**
    * Queries for Contact Ids based on the provided filter on Student_Plan__c.
    *
    * @param filter, the AdvisorPortalFilter to use.
    * @param contactIds, a Set of Contact Ids to use in the query.
    *
    * @return filteredContactIds, a filtered Set of Contact Ids matching the filter criteria.
    */
    public static Set<Id> filterStudentPlans(AdvisorPortalFilter filter, Set<Id> contactIds) {
        if (!String.isBlank(filter.academicLevel)
            || !String.isBlank(filter.campus)
            || !String.isBlank(filter.residency)
            || !String.isBlank(filter.major)
        ) {
            Set<Id> filteredContactIds = new Set<Id>();
            String queryString = '' +
                'SELECT Contact__c ' +
                'FROM Student_Program_Plan__c ' +
                'WHERE Contact__c IN :contactIds';

            if (!String.isBlank(filter.academicLevel)) {
                List<String> academicLevels = filter.academicLevel.split(';');
                queryString += ' AND Cohort__c IN :academicLevels';
            }

            if (!String.isBlank(filter.campus)) {
                List<String> campuses = filter.campus.split(';');
                queryString += ' AND Campus__r.Name IN :campuses';
            }

            if (!String.isBlank(filter.residency)) {
                List<String> residencies = filter.residency.split(';');
                queryString += ' AND Residency__c IN :residencies';
            }

            if (!String.isBlank(filter.major)) {
                queryString += ' AND Plan_Description__c LIKE \'%' + filter.major + '%\'';
            }

            queryString += ' GROUP BY Contact__c LIMIT 2000';

            for (AggregateResult studentPlanResult : Database.query(queryString)) {
                filteredContactIds.add((Id) studentPlanResult.get('Contact__c'));
            }
            return filteredContactIds;
        } else {
            return contactIds;
        }
    }
}