src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Affiliation__c.field-meta.xml
<CustomField>
    <fullName>Affiliation__c</fullName>
    <description>[??] - Affiliation of contact for the new case.
[DW: sfe_case]</description>
    <inlineHelpText>Affiliation of contact for the new case.</inlineHelpText>
    <label>Affiliation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Employee</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
            </value>
            <value>
                <fullName>Other ASU</fullName>
            </value>
            <value>
                <fullName>Outside source</fullName>
            </value>
            <value>
                <fullName>Parent</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Third party sponsor</fullName>
            </value>
            <value>
                <fullName>VIP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <description>The ASU campus where service is provided.
[DW: sfe_case]</description>
    <inlineHelpText>The ASU campus where service is provided.</inlineHelpText>
    <label>Service Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Downtown</fullName>
            </value>
            <value>
                <fullName>Gila Valley</fullName>
            </value>
            <value>
                <fullName>Havasu</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Polytechnic</fullName>
            </value>
            <value>
                <fullName>Tempe</fullName>
            </value>
            <value>
                <fullName>Thunderbird</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Yuma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>[Manual or Automated] - Examples include: 098-T, Collections, Counselor, Customer Services, Document Processing, Graduate Applicant Services, Graduation, International, Late Fee Appeals, Loan Research, Non-Degree, Office Specialist, Online Student, Other</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1098-T</fullName>
            </value>
            <value>
                <fullName>Academic Inquiries</fullName>
            </value>
            <value>
                <fullName>Academic Records</fullName>
            </value>
            <value>
                <fullName>Academic Services</fullName>
            </value>
            <value>
                <fullName>Academic Services - Training</fullName>
            </value>
            <value>
                <fullName>Academic Status Reports</fullName>
            </value>
            <value>
                <fullName>Academic Success Operations</fullName>
            </value>
            <value>
                <fullName>Academic Support</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accountancy</fullName>
            </value>
            <value>
                <fullName>Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Admissions (Help Desk)</fullName>
            </value>
            <value>
                <fullName>Admission Services Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Admission Services - General</fullName>
            </value>
            <value>
                <fullName>Admission Services OPS</fullName>
            </value>
            <value>
                <fullName>Admissions Inquiries</fullName>
            </value>
            <value>
                <fullName>Advising</fullName>
            </value>
            <value>
                <fullName>Advising (Help Desk)</fullName>
            </value>
            <value>
                <fullName>Advising - GOEE</fullName>
            </value>
            <value>
                <fullName>Agreements and Contracts</fullName>
            </value>
            <value>
                <fullName>Agribusiness</fullName>
            </value>
            <value>
                <fullName>Airport Arrivals</fullName>
            </value>
            <value>
                <fullName>AISSS Appointments</fullName>
            </value>
            <value>
                <fullName>Alternate Modes</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Alumni Success</fullName>
            </value>
            <value>
                <fullName>Applicant Services - Graduate</fullName>
            </value>
            <value>
                <fullName>Applicant Services - Undergraduate</fullName>
            </value>
            <value>
                <fullName>Appointments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>Functional_Group__c</fullName>
    <description>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.
[DW: sfe_case]</description>
    <inlineHelpText>When creating a new case, Functional Group should be your own group. To transfer this case, click on the Change link in the Case Owner field and select a queue.</inlineHelpText>
    <label>Functional Group</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Academic Partnerships</fullName>
            </value>
            <value>
                <fullName>Academic Transfer Credit Solutions</fullName>
            </value>
            <value>
                <fullName>Access ASU Outreach</fullName>
            </value>
            <value>
                <fullName>Admission Appeals</fullName>
            </value>
            <value>
                <fullName>Admission Services</fullName>
            </value>
            <value>
                <fullName>Admission Services OPS</fullName>
            </value>
            <value>
                <fullName>ASASU- Associated Students of ASU</fullName>
            </value>
            <value>
                <fullName>ASU Colleges at Lake Havasu</fullName>
                <label>ASU@Lake Havasu</label>
            </value>
            <value>
                <fullName>ASU Advisor Outreach</fullName>
            </value>
            <value>
                <fullName>ASU Coach Outreach</fullName>
            </value>
            <value>
                <fullName>ASU Family Programs</fullName>
            </value>
            <value>
                <fullName>ASU Graduate Advisor Portal</fullName>
            </value>
            <value>
                <fullName>ASU Health</fullName>
            </value>
            <value>
                <fullName>ASU Local</fullName>
            </value>
            <value>
                <fullName>ASU New Student Programs</fullName>
            </value>
            <value>
                <fullName>ASU Online</fullName>
            </value>
            <value>
                <fullName>ASUO Student Engagement</fullName>
            </value>
            <value>
                <fullName>ASU Salesforce Support</fullName>
            </value>
            <value>
                <fullName>ASU-USA Pathways</fullName>
            </value>
            <value>
                <fullName>ASU Wellness</fullName>
            </value>
            <value>
                <fullName>Biosafety</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Career Services</fullName>
            </value>
            <value>
                <fullName>Changemaker</fullName>
            </value>
            <value>
                <fullName>Chief Wellness Officer</fullName>
            </value>
            <value>
                <fullName>Classroom Scheduling</fullName>
            </value>
            <value>
                <fullName>College of ASU - Training</fullName>
            </value>
            <value>
                <fullName>College of Global Futures</fullName>
            </value>
            <value>
                <fullName>Curricular Activities and Actions</fullName>
            </value>
            <value>
                <fullName>Dean of Students</fullName>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub-Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>3rd Party Support</fullName>
            </value>
            <value>
                <fullName>ABSL-1</fullName>
            </value>
            <value>
                <fullName>ABSL-2</fullName>
            </value>
            <value>
                <fullName>ABSL-3</fullName>
            </value>
            <value>
                <fullName>Academic/Professional</fullName>
            </value>
            <value>
                <fullName>Academic Calendar</fullName>
            </value>
            <value>
                <fullName>Academic Holds</fullName>
            </value>
            <value>
                <fullName>Access/Login</fullName>
            </value>
            <value>
                <fullName>Access/Permissions</fullName>
            </value>
            <value>
                <fullName>Account Adjustments</fullName>
            </value>
            <value>
                <fullName>Account Management</fullName>
            </value>
            <value>
                <fullName>ACETS</fullName>
            </value>
            <value>
                <fullName>ACL-1</fullName>
            </value>
            <value>
                <fullName>ACL-2</fullName>
            </value>
            <value>
                <fullName>ACL-3</fullName>
            </value>
            <value>
                <fullName>Adding a Guest</fullName>
            </value>
            <value>
                <fullName>Additional Information Coversheet</fullName>
            </value>
            <value>
                <fullName>Adidas</fullName>
            </value>
            <value>
                <fullName>Admin Assistant</fullName>
            </value>
            <value>
                <fullName>Admission Requirements</fullName>
            </value>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Admit/Conditional Letter Inquiry</fullName>
            </value>
            <value>
                <fullName>Adobe Connect/Presenter</fullName>
            </value>
            <value>
                <fullName>Advancement</fullName>
            </value>
            <value>
                <fullName>Advising</fullName>
            </value>
            <value>
                <fullName>Advising Referral</fullName>
            </value>
            <value>
                <fullName>Advisor Portal</fullName>
            </value>
            <value>
                <fullName>Agent Specific</fullName>
            </value>
            <value>
                <fullName>Agent Specific Training</fullName>
            </value>
            <value>
                <fullName>Aggregates</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Help_Desk_Provided_Phone__c</fullName>
        <label>Help Desk Provided Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>SF_Mobile__c</fullName>
        <label>SF.Mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>SMS_Phone__c</fullName>
        <description>Used for SMS campaigns. US phone numbers are 10 characters in length. International numbers are 15 characters in length. A validation rule will check to be sure there are only numeric characters in the field.</description>
        <inlineHelpText>Mobile number (digits only) for recruitment mass texting messages. Field represents an initial opt-in, contact must also opt in via text and may opt out at any time (text STOP in response), opt out status is tracked only in Silverpop, not visible here.</inlineHelpText>
        <label>SMS Mobile Phone Opt In</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <description>[Peoplesoft] - Work phone number</description>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/HelpDeskController.cls
// Custom controller for the HelpDesk page
public with sharing class HelpDeskController
{
    // the following are booleans that are used for rendering/hiding various sections of the page based on context
    public Boolean isNewCaseSelected { get; set; }
    public Boolean isExistingCaseSelected { get; set; }
    public Boolean isNewContactSelected { get; set; }
    public Boolean isCloseCase { get; set; }
    public Boolean isContactSet { get; set; }

    // the new case being created
    public Case mycase { get; set; }

    // the new contact being created
    public Contact mycontact { get; set; }

    // the collection of contacts to display - these are the results of the SOQL query
    public List<Contact> contacts { get; set; }

    // the open cases for the selected contact
    public List<CaseWrapper> cases { get; set; }

    // the soql without the order and limit
    private String soql { get; set; }

    // the selected contact -- this is populated when the "Set as Contact" link is hit on a Contact
    public String selectedContactId { get; set; }

    // the selected case -- this is populated when the "Set as Case" link is hit on a Case
    public String selectedCaseId { get; set; }

    // This method returns a list of Close statuses for Cases
    public List<SelectOption> getcloseCaseStatusOptions()
    {
        List<SelectOption> closeCaseStatusOptions = new List<SelectOption>();
        closeCaseStatusOptions.add(new SelectOption('', '--None--'));
        
        for (CaseStatus cs: [Select Id, MasterLabel From CaseStatus Where IsClosed = true])
        {
            closeCaseStatusOptions.add(new SelectOption(cs.Id, cs.MasterLabel));
        }
        
        return closeCaseStatusOptions;
    }

    public String selectedCloseCaseStatusOption { get; set; }

    // This represents the Contact search fields
    public Contact contactsrch
    {
        get
        {
            if (contactsrch == null)
            {
                contactsrch = new Contact();
            }
            return contactsrch;
        }
        set;
    }

    // This stores the incoming phone number (ANI parameter)
    public String callerId { get; set; }

    // the current sort direction. defaults to asc
    public String sortDir
    {
        get
        {
            if (sortDir == null)
            {
                sortDir = 'asc';
            } return sortDir;
        }
        set;
    }

    // the current field to sort by. defaults to last name
    public String sortField
    {
        get
        {
            if (sortField == null)
            {
                sortField = 'lastName';
            } return sortField;
        }
        set;
    }

    // Init the controller and display some sample data when the page loads
    public HelpDeskController()
    {
        isNewCaseSelected = false;
        isExistingCaseSelected = false;
        isCloseCase = false;
        isNewContactSelected = false;
        isContactSet = false;
        String callerIdWildcarded;
        String callerIdUnformatted;

        soql = 'SELECT Firstname, Lastname, Phone, Help_Desk_Provided_Phone__c, ' +
            'Birthdate, ASURite_ID__c, EMPLID__c, ASU_Email__c,  Personal_Email__c ' +
            'FROM Contact ' +
            'WHERE Firstname != null';

        if (ApexPages.currentPage().getParameters().containsKey('ANI'))
        {
            callerIdUnformatted = ApexPages.currentPage().getParameters().get('ANI');
            callerId = formatPhone(callerIdUnformatted);

            callerIdWildcarded = '%' + callerIdUnformatted.substring(0, 3) + '%' +
                callerIdUnformatted.substring(3, 6) + '%' +
                callerIdUnformatted.substring(6, 10) + '%';

            System.debug(callerIdWildcarded);

            soql += ' AND (HomePhone LIKE \'' + callerIdWildcarded + '\' ' +
                'OR MobilePhone LIKE \'' + callerIdWildcarded + '\' ' +
                'OR OtherPhone LIKE \'' + callerIdWildcarded + '\' ' +
                'OR Phone LIKE \'' + callerIdWildcarded + '\' ' +
                'OR Work_Phone__c LIKE \'' + callerIdWildcarded + '\' ' +
                'OR Help_Desk_Provided_Phone__c LIKE \'' + callerIdWildcarded + '\')';
        }

        runQuery();
    }

    // Reformats a 10 digit phone number to the following format: (xxx) xxx-xxxx
    private static String formatPhone(String phone)
    {
        string nondigits = '[^0-9]';
        string phoneDigits;

        // remove all non numeric
        phoneDigits = phone.replaceAll(nondigits, '');

        // 10 digit: reformat with dashes
        if (phoneDigits.length() == 10)
            return '(' + phoneDigits.substring(0, 3) + ') ' +
                phoneDigits.substring(3, 6) + '-' +
                phoneDigits.substring(6, 10);

        // if it isn't a 10 digit number, return the original because
        // it may contain an extension or special information
        return(phone);
    }

    // toggles the sorting of query from asc<-->desc
    public void toggleSort()
    {
        // simply toggle the direction
        sortDir = sortDir.equals('asc') ? 'desc' : 'asc';
        // run the query again
        runQuery();
    }

    // runs the actual query
    public void runQuery()
    {

        try
        {
            contacts = Database.query(
                soql +
                ' ORDER BY ' + sortField + ' ' + sortDir +
                ' LIMIT 20'
            );
        }
        catch (Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Ooops!'));
        }

    }

    // runs the search with parameters passed via Javascript
    public PageReference runSearch()
    {

        String firstName = Apexpages.currentPage().getParameters().get('firstname');
        String lastName = Apexpages.currentPage().getParameters().get('lastname');
        String phone = Apexpages.currentPage().getParameters().get('phone');
        String birthdate = Apexpages.currentPage().getParameters().get('birthdate');
        String asuriteid = Apexpages.currentPage().getParameters().get('asuriteid');
        String emplid = Apexpages.currentPage().getParameters().get('emplid');
        String directoryEmail = Apexpages.currentPage().getParameters().get('directoryemail');
        String personalEmail = Apexpages.currentPage().getParameters().get('personalemail');
        String birthdateFormatted;
        String phoneWildcarded;
        Integer phoneLength = phone.length();

        if (birthdate.length() > 0)
        {
            birthdateFormatted = String.valueOf(date.parse(birthdate));
        }

        if (phoneLength > 0 && phoneLength <= 3)
        {
            phoneWildcarded = '%' + phone.substring(0, math.min(phoneLength, 3)) + '%';
        }
        else if (phoneLength > 3 && phoneLength <= 6)
        {
            phoneWildcarded = '%' + phone.substring(0, 3) + '%' +
                phone.substring(3, math.min(phoneLength, 6)) + '%';
        }
        else if (phoneLength > 6)
        {
            phoneWildcarded = '%' + phone.substring(0, 3) + '%' +
                phone.substring(3, 6) + '%' + phone.substring(6, math.min(phoneLength, 10)) + '%';
        }


        soql = 'SELECT Firstname, Lastname, Phone, Help_Desk_Provided_Phone__c, Birthdate, ' +
                'ASURite_ID__c, EMPLID__c, ASU_Email__c,  Personal_Email__c ' +
            'FROM Contact ' +
            'WHERE Firstname != null';

        if (!firstName.equals(''))
        {
            soql += ' AND Firstname LIKE \'' + String.escapeSingleQuotes(firstName) + '%\'';
        }

        if (!lastName.equals(''))
        {
            soql += ' AND Lastname LIKE \'' + String.escapeSingleQuotes(lastName) + '%\'';
        }

        if (!phone.equals(''))
        {
            soql += ' AND (HomePhone LIKE \'' + phoneWildcarded + '\' ' +
                'OR MobilePhone LIKE \'' + phoneWildcarded + '\' ' +
                'OR OtherPhone LIKE \'' + phoneWildcarded + '\' ' +
                'OR Phone LIKE \'' + phoneWildcarded + '\' ' +
                'OR SF_Mobile__c LIKE \'' + phoneWildcarded + '\' ' +
                'OR SMS_Phone__c LIKE \'' + phoneWildcarded + '\' ' +
                'OR Work_Phone__c LIKE \'' + phoneWildcarded + '\' ' +
                'OR Help_Desk_Provided_Phone__c LIKE \'' + phoneWildcarded + '\')';
        }

        if (!birthdate.equals(''))
        {
            soql += ' AND Birthdate = ' + birthdateFormatted;
        }

        if (!asuriteid.equals(''))
        {
            soql += ' AND ASURite_ID__c LIKE \'' + String.escapeSingleQuotes(asuriteid) + '%\'';
        }

        if (!emplid.equals(''))
        {
            soql += ' AND EMPLID__c LIKE \'' + String.escapeSingleQuotes(emplid) + '%\'';
        }

        if (!directoryEmail.equals(''))
        {
            soql += ' AND ASU_Email__c LIKE \'' +
                String.escapeSingleQuotes(directoryEmail) + '%\'';
        }

        if (!personalEmail.equals(''))
        {
            soql += ' AND Personal_Email__c LIKE \'' +
                String.escapeSingleQuotes(personalEmail) + '%\'';
        }

        // run the query again
        runQuery();

        return null;
    }

    public void newCase()
    {
        isNewCaseSelected = true;

        if (mycase == null)
        {
            mycase = new Case();
        }
        else
        {
            mycase.clear();
        }

        mycase.ContactId = selectedContactId;
        mycase.Status = 'New';
        mycase.Origin = 'Phone';
        mycase.Campus__c = 'Tempe';
        mycase.Functional_Group__c = 'Help Desk';
    }

    public void newContact()
    {
        isNewContactSelected = true;

        if (mycontact == null)
        {
            mycontact = new Contact();
        }

        mycontact.RecordTypeId = [
            SELECT Id
            FROM RecordType
            WHERE name = 'SF Mastered'
            AND SobjectType = 'Contact' limit 1
        ].Id;

        mycontact.MailingCountryCode = 'US';
        mycontact.Firstname = contactsrch.Firstname;
        mycontact.Lastname = contactsrch.Lastname;
        mycontact.Email = contactsrch.Personal_Email__c;
        mycontact.Phone = contactsrch.Phone;
        mycontact.Help_Desk_Provided_Phone__c = callerId;
        isContactSet = false;
        isNewCaseSelected = false;
        isExistingCaseSelected = false;
    }

    public void clearContactSearch()
    {
        isNewContactSelected = false;
        isContactSet = false;

        if (cases != null)
        {
            cases.clear();
        }

        isNewCaseSelected = false;
        isExistingCaseSelected = false;
        selectedContactId = null;

        if (contactsrch != null)
        {
            contactsrch.clear();
        }

        if (contacts != null)
        {
            contacts.clear();
        }
    }

    public void setAsContact()
    {
        List<Case> casesbase;

        // populate the contact search fields based on the selected contact
        for (Contact co : contacts)
        {
            if (co.id == selectedContactId)
            {
                contactsrch = co;
                isContactSet = true;
                isNewCaseSelected = false;
                isExistingCaseSelected = false;
                break;
            }
        }

        // query to get open cases for the contact
        try
        {
            casesbase = Database.query(
                'SELECT Id, Subject, Reason, Description, Status, Origin, Campus__c, ' +
                    'Affiliation__c, Functional_Group__c, Category__c, Sub_Category__c, ' +
                    'Private_Note_Help_Desk__c, ClosedDate ' +
                'FROM Case ' +
                'WHERE ContactId = :selectedContactId'
            );
        }
        catch (Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Ooops!'));
        }

        if (cases == null)
        {
            cases = new List<CaseWrapper>();
        }
        else
        {
            cases.clear();
        }

        for (Case ca : casesbase)
        {
            CaseWrapper mycw = new CaseWrapper(ca);
            cases.add(mycw);
        }

    }

    public void setAsCase()
    {
        isExistingCaseSelected = true;
        Map<Id, CaseWrapper> m = new Map<Id, CaseWrapper>();

        for (CaseWrapper cas : cases)
        {
            m.put(cas.Ca.Id, cas);
        }

        mycase = (Case) m.get(selectedCaseId).Ca;
    }

    public void saveCase()
    {
        try
        {
            if (String.isEmpty(mycase.Subject))
            {
                mycase.Subject = '-';
            }

            if (String.isEmpty(mycase.Description))
            {
                mycase.Description = '-';
            }

            upsert mycase;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }

    public void cancelCase()
    {
        if (isNewCaseSelected)
        {
            isNewCaseSelected = false;
        }
        else if (isExistingCaseSelected)
        {
            isExistingCaseSelected = false;
        }
    }

    public PageReference saveAndTransferCase()
    {
        boolean success = false;

        try
        {
            upsert mycase;
            PageReference page = new PageReference('/apex/CaseTransfer?id=' + mycase.Id);
            page.setRedirect(true);
            return page;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
            return ApexPages.currentPage();
        }
    }

    public void saveAndCloseCase()
    {
        try
        {
            upsert mycase;
            isCloseCase = true;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }

    public void saveCloseCase()
    {
        if (!(null == selectedCloseCaseStatusOption
            || selectedCloseCaseStatusOption.length() == 0))
        {
            mycase.Status = [
                SELECT MasterLabel
                FROM CaseStatus
                WHERE Id = :selectedCloseCaseStatusOption
            ].MasterLabel;
        }
        try
        {
            upsert mycase;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }

    public void cancelCloseCase()
    {
        if (isNewCaseSelected)
        {
            isNewCaseSelected = false;
        }
        else if (isExistingCaseSelected)
        {
            isExistingCaseSelected = false;
        }

        if (isCloseCase)
        {
            isCloseCase = false;
        }
    }

    public void saveContact()
    {
        try
        {
            insert mycontact;
            isContactSet = true;
            selectedContactId = mycontact.Id;
            isNewContactSelected = false;
            contactsrch = mycontact;
            isNewCaseSelected = false;
            isExistingCaseSelected = false;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }

    public void cancelNewContact()
    {
        isNewContactSelected = false;
        isContactSet = false;
        selectedContactId = null;

        if (mycontact != null)
        {
            mycontact = null;
        }
    }

    public void setAsHelpDeskProvidedPhone()
    {
        try
        {
            Contact contactToUpdate = [
                SELECT Id, Help_Desk_Provided_Phone__c
                FROM Contact
                WHERE Id = :selectedContactId
            ];

            contactsrch.Help_Desk_Provided_Phone__c = callerId;
            contactToUpdate.Help_Desk_Provided_Phone__c = contactsrch.Help_Desk_Provided_Phone__c;

            update contactToUpdate;
        }
        catch (Exception ex)
        {
            ApexPages.addMessages(ex);
        }
    }

    // This wrapper class on Case was created so that we can show a truncated case description
    public class CaseWrapper
    {
        public Case Ca { get; set; }
        public String shortDescr { get; set; }
        public String fullDescr { get; set; }

        public CaseWrapper(Case c)
        {
            Ca = c;

            if (String.isNotEmpty(c.Description))
            {
                shortDescr = c.Description.abbreviate(140);
            }
            else
            {
                shortDescr = ' ';
            }

            fullDescr = c.Description;
        }
    }
}