src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Most_Recent_Queue__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Queue__c</fullName>
    <description>[DW: sfe_case]</description>
    <inlineHelpText>This field will determine where a case lands if it is re-opened within 14 days after closing.</inlineHelpText>
    <label>Most Recent Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web
[DW: sfe_case]</description>
    <inlineHelpText>Where was this Case initiated?</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advising Community</fullName>
            </value>
            <value>
                <fullName>Alteryx</fullName>
            </value>
            <value>
                <fullName>Alteryx - Financial Intake</fullName>
            </value>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>BBSS</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
            <value>
                <fullName>Coach Initiated</fullName>
            </value>
            <value>
                <fullName>EdPlus Salesforce</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Error Logger</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>FC DPC</fullName>
            </value>
            <value>
                <fullName>FC LOSAN</fullName>
            </value>
            <value>
                <fullName>FC Poly</fullName>
            </value>
            <value>
                <fullName>FC Tempe</fullName>
            </value>
            <value>
                <fullName>FC Virtual</fullName>
            </value>
            <value>
                <fullName>FC West</fullName>
            </value>
            <value>
                <fullName>Financial Intake</fullName>
            </value>
            <value>
                <fullName>Handshake</fullName>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>My ASU</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Outgoing Call</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Qualtrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Advisor_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Advisor Outreach</businessProcess>
        <description>used for cases created for the Student Success Portal</description>
        <label>(Admin Only) ASU Advisor Outreach</label>
    </recordTypes>

src/objects/Success_Pod__c.object
<CustomObject>
    <fields>
        <fullName>Owner_Name__c</fullName>
        <formula>Owner:Queue.QueueName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Owner Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/classes/Test_QADefaultHandler.cls
@isTest
public class Test_QADefaultHandler {
    private static QADefaultHandler qadh;
    private static Integer numberOfPods;
    private static Integer numberOfCases;
    private static Integer numberOfStudents;
    private static List<Case> cases;

    static {
        qadh = new QADefaultHandler();
        numberOfPods = 1;
        numberOfCases = 3;
        numberOfStudents = 5;
        cases = new List<Case>([SELECT OwnerId, RecordTypeId, Most_Recent_Queue__c FROM Case]);
    }

    @testSetup
    public static void testSetup() {
        // Short hand to populate some cases that are advisor cases
        TestDataFactory.makeMeAnAdvisorUser(numberOfPods, numberOfCases, numberOfStudents);
    }

    /*
     * Tests the QADefaultHandlers ability to identify advisor cases
     *
     * <p>
     * At this point, all cases are advisor cases so this should always be true.
     * </p>
     */
    public static testMethod void Test_isAdvisorCase() {
        for (Case c : cases) {
            if (c.recordTypeId == IDHelper.getRTID('Case', 'ASU_Advisor_Outreach')) {
                system.assert(qadh.isAdvisorCase(c));
            } else {
                system.assert(!qadh.isAdvisorCase(c));
            }
        }
    }

    /*
     * Tests the QADefaultHandler's ability to determine if the case is
     * owned by a group as opposed to a user.
     */
    public static testMethod void Test_caseOwnedByGroup() {
        for (Case c : cases) {
            if (Validator.validateId(c.OwnerId, Group.class)) {
                system.assert(qadh.caseOwnedByGroup(c));
            } else {
                system.assert(!qadh.caseOwnedByGroup(c));
            }
        }
    }

    /*
     * Tests the QADefaultHandler's ability to determine the from address for the provided case
     */
    public static testMethod void Test_getEmailFromAddress() {
        for (Case c : cases) {
            if (qadh.isAdvisorCase(c)) {
                if (qadh.caseOwnedByGroup(c)) {
                    system.assertEquals(
                        [SELECT Primary_Email__c FROM Success_Pod__c WHERE OwnerId = :c.OwnerId]
                        .Primary_Email__c,
                        qadh.getEmailFromAddress(c.Id)
                    );
                } else {
                    system.assertEquals(
                        [SELECT Primary_Email__c FROM Success_Pod__c WHERE Owner_Name__c = :c.Most_Recent_Queue__c]
                        .Primary_Email__c,
                        qadh.getEmailFromAddress(c.Id)
                    );
                }
            }
        }
    }

    public static testMethod void Test_nullContextId() {
        qadh.getEmailFromAddress(null);
        List<Case> errorList = [SELECT Id FROM Case WHERE Origin__c = 'Error Logger'];
        System.assertEquals(1, errorList.size());
    }
}