src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/CC_Category__c.field-meta.xml
<CustomField>
    <fullName>CC_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field looks up to the Case Classification object where record type = Category.
[DW: sfe_case]</description>
    <label>Case Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.CC_Functional_Group__c</valueField>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Visible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>Cases (Category)</relationshipLabel>
    <relationshipName>Cases_Category</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>CC_Functional_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field looks up to the Case Classification object where record type = Functional Group.
[DW: sfe_case]</description>
    <label>Case Functional Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Functional Group</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Visible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>Cases (Functional Group)</relationshipLabel>
    <relationshipName>Cases_Functional_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web
[DW: sfe_case]</description>
    <inlineHelpText>Where was this Case initiated?</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advising Community</fullName>
            </value>
            <value>
                <fullName>Alteryx</fullName>
            </value>
            <value>
                <fullName>Alteryx - Financial Intake</fullName>
            </value>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>BBSS</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
            <value>
                <fullName>Coach Initiated</fullName>
            </value>
            <value>
                <fullName>EdPlus Salesforce</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Error Logger</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>FC DPC</fullName>
            </value>
            <value>
                <fullName>FC LOSAN</fullName>
            </value>
            <value>
                <fullName>FC Poly</fullName>
            </value>
            <value>
                <fullName>FC Tempe</fullName>
            </value>
            <value>
                <fullName>FC Virtual</fullName>
            </value>
            <value>
                <fullName>FC West</fullName>
            </value>
            <value>
                <fullName>Financial Intake</fullName>
            </value>
            <value>
                <fullName>Handshake</fullName>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>My ASU</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Outgoing Call</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Qualtrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/Visible_by_Contact__c.field-meta.xml
<CustomField>
    <fullName>Visible_by_Contact__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Used in the Case Query for the My ASU service center to display the Case to the logged in User.
[DW: sfe_case]</description>
    <inlineHelpText>If checked, this Case should be visible by the Contact in the My ASU Help tab.</inlineHelpText>
    <label>Visible by Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Coach_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Coach Outreach</businessProcess>
        <description>Case Record type for Cases in the Success Portal</description>
        <label>ASU Coach Outreach</label>
    </recordTypes>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
        
        
    </recordTypes></CustomObject>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/Coaching_Student__c.field-meta.xml
<CustomField>
    <fullName>Coaching_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
    <label>Coaching Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Resource__c.field-meta.xml
<CustomField>
    <fullName>Success_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>links the Success Student to their Assigned Success Resource</description>
    <label>Success Resource</label>
    <referenceTo>Success_Resource__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <description>Used to denote if the student is a Coaching Student for Ed Plus Success Coaches.</description>
    <label>Coach</label>
</RecordType>

src/classes/SuccessStudentService.cls
public class SuccessStudentService {
    private static final Date TOMORROW = System.today().addDays(1);
    
    public static List<Success_Student__c> getStudentsRequiringOutreach(Map<Id, Success_Student__c> successStudents, Map<Id, Success_Student__c> oldMap) {
        List<Success_Student__c> studentsRequiringOutreach = new List<Success_Student__c>();
        
        for (Success_Student__c successStudent : successStudents.values()) {
            if (successStudent.Success_Resource__c != oldmap.get(successStudent.Id).Success_Resource__c &&
                successStudent.Coaching_Student__c) {
                studentsRequiringOutreach.add(successStudent);
            }
        }
        
        return studentsRequiringOutreach;
    }
    
    public static List<Case> createOutreachCases (List<Success_Student__c> successStudents) {
        Id coachCaseRecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Coach_Outreach');
        List<Case> newCases = new List<Case>();
        
        Case_Classification__c classification = [
            SELECT Id, (
                SELECT Id
                FROM Case_Classifications__r
                WHERE Name = 'Ad Hoc'
                LIMIT 1
            )
            FROM Case_Classification__c
            WHERE Name = 'ASU Coach Outreach'
            LIMIT 1
        ];
        
        Id asuCoachOutreachGroup = classification.Id;
        Id adHocCategory = classification.Case_Classifications__r[0].Id;
        
        for (Success_Student__c successStudent : successStudents) {
            Case newCase = new Case(
                CC_Functional_Group__c = asuCoachOutreachGroup,
                CC_Category__c = adHocCategory,
                Description = 'Transferred',
                Followup_Date__c = TOMORROW,
                Origin__c = 'Automated',
                Priority = '3 - Normal Priority',
                Status = 'New',
                Subject = 'New Student Assigned',
                Type = 'System Generated',
                Visible_by_Contact__c = false,
                ContactId = successStudent.Student__c,
                RecordTypeId = coachCaseRecordTypeId,
                OwnerId = successStudent.OwnerId
            );
            
            newCases.add(newCase);
        }
        
        return newCases;  
    }
}