src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Campus__c.field-meta.xml
<CustomField>
    <fullName>Campus__c</fullName>
    <description>The ASU campus where service is provided.
[DW: sfe_case]</description>
    <inlineHelpText>The ASU campus where service is provided.</inlineHelpText>
    <label>Service Location</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Downtown</fullName>
            </value>
            <value>
                <fullName>Gila Valley</fullName>
            </value>
            <value>
                <fullName>Havasu</fullName>
            </value>
            <value>
                <fullName>Los Angeles</fullName>
            </value>
            <value>
                <fullName>Online</fullName>
            </value>
            <value>
                <fullName>Polytechnic</fullName>
            </value>
            <value>
                <fullName>Tempe</fullName>
            </value>
            <value>
                <fullName>Thunderbird</fullName>
            </value>
            <value>
                <fullName>Tucson</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Yuma</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CC_Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>CC_Functional_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field looks up to the Case Classification object where record type = Functional Group.
[DW: sfe_case]</description>
    <label>Case Functional Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Functional Group</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Visible__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>Cases (Functional Group)</relationshipLabel>
    <relationshipName>Cases_Functional_Group</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case.object
    <recordTypes>
        <fullName>ASU_Advisor_Outreach</fullName>
        <active>true</active>
        <businessProcess>ASU Advisor Outreach</businessProcess>
        <description>used for cases created for the Student Success Portal</description>
        <label>(Admin Only) ASU Advisor Outreach</label>
    </recordTypes>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</description>
        <inlineHelpText>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If the field is dependent upon another field, it will be listed here.</description>
        <inlineHelpText>If the field is dependent upon another field, it will be listed here.</inlineHelpText>
        <label>Parent</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Functional Group</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Sub Category</value>
            </filterItems>
            <filterItems>
                <field>Case_Classification__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Category</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Case_Classification__c</referenceTo>
        <relationshipLabel>Case Classifications</relationshipLabel>
        <relationshipName>Case_Classifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Record_Types_String__c</fullName>
        <description>Text/string that represents the values in the multi-select picklist "Record Types" (Record_Types__c) so it can be used in code.</description>
        <label>Record Types String</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Visible__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Used to determine if an active record should be visible in the lookup fields for case.</description>
        <inlineHelpText>Used to determine if an active record should be visible in the lookup fields for case.</inlineHelpText>
        <label>Visible</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <label>Category</label>
    </recordTypes>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Location_Code__c</fullName>
        <description>[Peoplesoft] - code for the location</description>
        <externalId>true</externalId>
        <label>Location Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Campus

Location records are manually entered at this time.  
Review SFE-2602 for details of why and how this object works.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Persistence_Outlook__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Persistence Outlooks</relationshipLabel>
        <relationshipName>Persistence_Outlooks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Contains the necessary information for the civitas section in portals.</description>
    <label>Persistence Outlook</label>
    <nameField>
        <displayFormat>PO-{000000}</displayFormat>
        <label>Persistence Outlook Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Persistence Outlooks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Student_Group__c.object
<CustomObject><fields>
        <fullName>SG_PeopleSoft_Code__c</fullName>
        <description>[Peoplesoft] - Peoplesoft code</description>
        <label>PeopleSoft Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>SG_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Peoplesoft] - Checkbox that shows if the student group is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Student Group information from PeopleSoft</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Group</label><nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Group Label</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Groups</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

force-app/main/default/objects/Student_Group__c/fields/SG_Contact__c.field-meta.xml
<CustomField>
    <fullName>SG_Contact__c</fullName>
    <description>[Peoplesoft] - Relationship to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Groups</relationshipLabel>
    <relationshipName>Student_Groups_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Campus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Data sourced from PS_ACAD_PROG.CAMPUS</description>
        <label>Campus</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Student Program Plans</relationshipLabel>
        <relationshipName>Student_Program_Plans</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Plan_Code__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.ACAD_PLAN</description>
        <label>Plan Code</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Plan_Description__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.DESCR</description>
        <label>Plan Description</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Plan_Type_Text__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.ACAD_PLAN_TYPE</description>
        <label>Plan Type</label>
        <length>3</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <description>FTFF + PS_ASU_SR0189_SPRF .ASU_ACAD_LVL_BOT_D</description>
    <label>Cohort</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Student_Program_Plan__c/fields/Residency__c.field-meta.xml
<CustomField>
    <fullName>Residency__c</fullName>
    <description>(PeopleSoft) PS_ASU_SR0189_SPRF.RESIDENCY</description>
    <label>Residency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>International</fullName>
            </value>
            <value>
                <fullName>Non-Resident</fullName>
            </value>
            <value>
                <fullName>Resident</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Student__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Plan_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Plan, used for assign students to Coaches</description>
    <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
    <label>Plan Code</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <description>Denotes if the Student is a non-Coaching Student.</description>
    <label>Advisor</label>
</RecordType>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/AdvisorPortalFilterSectionControllerTest.cls
@IsTest
private class AdvisorPortalFilterSectionControllerTest {
    @TestSetup
    static void setUpTest() {
        TestDataFactory.createAdvisorStudents(TestDataFactory.createAdvisorPods(1), 1);
    }

    @IsTest
    static void testGetPicklistValues() {
        Test.startTest();
        Map<String, String> picklistValuesMap = AdvisorPortalFilterSectionController.getPicklistValues(
            'Student_Program_Plan__c',
            'Residency__c'
        );
        Test.stopTest();

        System.assert(
            picklistValuesMap.size() > 0,
            'Controller should have returned values for the Residency picklist.'
        );
        System.assert(
            picklistValuesMap.keySet().contains('Resident'),
            'Ensure the picklist map contains at least one valid picklist value.'
        );
    }

    @IsTest
    static void testGetCaseStatusOptions() {
        Test.startTest();
        Map<String, String> caseStatusMap = AdvisorPortalFilterSectionController.getCaseStatusSettings();
        Test.stopTest();

        System.assert(
            caseStatusMap.size() > 0,
            'Controller should have returned values for the Case Status picklist based upon the custom metadata type.'
        );
        System.assert(
            caseStatusMap.keySet().contains('In Progress'),
            'Ensure the picklist map contains at least one valid picklist value.'
        );
    }

    @IsTest
    private static void testCaseSubjectPicklistValues() {
        // Arrange
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];

        String queueId = [SELECT QueueId FROM QueueSobject WHERE SobjectType = 'Case' LIMIT 1].QueueId;

        List<Case> testCases = TestDataFactory.createCases(3);
        Integer i = 0;
        for (Case c : testCases) {
            c.ContactId = testContact.Id;
            c.Subject = 'Subject ' + i;
            c.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
            c.OwnerId = queueId;
            i++;
        }
        insert testCases;

        // Act
        Test.startTest();
        Map<String, String> subjectMap = AdvisorPortalFilterSectionController.getCaseSubjectPicklistValues(
            new List<String>{ queueId }
        );
        Test.stopTest();

        // Assert
        System.assertEquals(3, subjectMap.size(), 'Three subjects should have been found.');
    }

    @IsTest
    private static void testCaseCategoryPicklistValues() {
        // Arrange
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];

        List<Case> testCases = TestDataFactory.createCases(3);
        Integer i = 0;
        for (Case c : testCases) {
            c.ContactId = testContact.Id;
            c.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
            i++;
        }
        insert testCases;

        CaseClassificationFactory caseClassificationsMaker = new CaseClassificationFactory();
        List<Case_Classification__c> classifications = caseClassificationsMaker.createAndInsertSetOfAdvisorOutreachCaseClassification();
        Id functionalGroupId = classifications[0].Id;
        Id categoryWatchlistId = classifications[2].Id;

        update new List<Case_Classification__c>{
            new Case_Classification__c(Id = categoryWatchlistId, Name = 'Watchlist'),
            new Case_Classification__c(Id = functionalGroupId, Name = 'ASU Advisor Outreach')
        };

        String queueId = [SELECT QueueId FROM QueueSobject WHERE SobjectType = 'Case' LIMIT 1].QueueId;

        CaseFactory.AdvisorOutreachCase watchlistCaseMaker = new CaseFactory.AdvisorOutreachCase(
            UserInfo.getUserId(),
            IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach'),
            'Outreach Required',
            functionalGroupId,
            categoryWatchlistId,
            testContact.Id,
            null
        );
        Case caseToFind = (Case) watchlistCaseMaker.create(1)[0];
        caseToFind.Subject = 'Test Subject';
        caseToFind.Followup_Date__c = System.today().addDays(10);
        caseToFind.ownerId = queueId;
        insert caseToFind;

        // Act
        Test.startTest();
        Map<String, String> classificationMap = AdvisorPortalFilterSectionController.getCaseClassificationPicklistValues(
            new List<String>{ queueId }
        );
        Test.stopTest();

        // Assert
        System.assertEquals(1, classificationMap.size(), 'The one Case Category should have been found.');
    }

    @IsTest
    private static void testNoFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );

        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer countCases = 0;
        for (AdvisorPortalContact apContact : results) {
            countCases += apContact.cases.size();
        }
        System.assertEquals(5, countCases, 'Should get 5 total cases returned');
    }

    @IsTest
    private static void testNameFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        testContact1.EmplId__c = '0011221100';
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        testContact2.ASURite_ID__c = 'testid_1';
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.studentString = 'Mister test-contact-ap-r2';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');

        filter.studentString = '0011221100';
        results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');

        filter.studentString = 'testid_1';
        results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
    }

    @IsTest
    private static void testCampusFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Location__c testCampus1 = new Location__c(Location_Code__c = '0011221100', Name = 'test-loc-ap-r1');
        Location__c testCampus2 = new Location__c(Location_Code__c = '0011221101', Name = 'test-loc-ap-r2');
        insert new List<Location__c>{ testCampus1, testCampus2 };

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        testContact1.EmplId__c = '0011221100';
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        testContact2.ASURite_ID__c = 'testid_1';
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Student_Program_Plan__c studentProgramPlan1 = new Student_Program_Plan__c(
            Contact__c = testContact1.Id,
            Campus__c = testCampus1.Id
        );
        Student_Program_Plan__c studentProgramPlan2 = new Student_Program_Plan__c(
            Contact__c = testContact2.Id,
            Campus__c = testCampus2.Id
        );

        insert new List<Student_Program_Plan__c>{ studentProgramPlan1, studentProgramPlan2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.campus = 'test-loc-ap-r2';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
    }

    @IsTest
    private static void testAcademicLevelFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Student_Program_Plan__c studentProgramPlan1 = new Student_Program_Plan__c(
            Contact__c = testContact1.Id,
            Cohort__c = 'test-cohort-1'
        );
        Student_Program_Plan__c studentProgramPlan2 = new Student_Program_Plan__c(
            Contact__c = testContact2.Id,
            Cohort__c = 'test-cohort-2'
        );

        insert new List<Student_Program_Plan__c>{ studentProgramPlan1, studentProgramPlan2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.academicLevel = 'test-cohort-1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');

        filter.academicLevel = 'test-cohort-1;test-cohort-2';
        results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
    }

    @IsTest
    private static void testStudentGroupFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Student_Group__c testSG1 = new Student_Group__c(
            SG_Contact__c = testContact1.Id,
            SG_PeopleSoft_Code__c = 'testapr1',
            SG_Status__c = true
        );
        Student_Group__c testSG2 = new Student_Group__c(
            SG_Contact__c = testContact2.Id,
            SG_PeopleSoft_Code__c = 'testapr2',
            SG_Status__c = true
        );
        insert new List<Student_Group__c>{ testSG1, testSG2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.studentGroupCode = 'testapr1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');
    }

    @IsTest
    private static void testMajorFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Student_Program_Plan__c studentProgramPlan1 = new Student_Program_Plan__c(
            Contact__c = testContact1.Id,
            Plan_Type_Text__c = 'MAJ',
            Plan_Code__c = 'test-code-ap-r1'
        );
        Student_Program_Plan__c studentProgramPlan2 = new Student_Program_Plan__c(
            Contact__c = testContact2.Id,
            Plan_Type_Text__c = 'MAJ',
            Plan_Description__c = 'test-description-ap-r2'
        );

        insert new List<Student_Program_Plan__c>{ studentProgramPlan1, studentProgramPlan2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.major = 'test-code-ap-r1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');

        filter.major = 'test-description-ap-r2';
        results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
    }

    @IsTest
    private static void testResidencyFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Student_Program_Plan__c studentProgramPlan1 = new Student_Program_Plan__c(
            Contact__c = testContact1.Id,
            Residency__c = 'International'
        );
        Student_Program_Plan__c studentProgramPlan2 = new Student_Program_Plan__c(
            Contact__c = testContact2.Id,
            Residency__c = 'Non-Resident'
        );

        insert new List<Student_Program_Plan__c>{ studentProgramPlan1, studentProgramPlan2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.residency = 'International';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');
    }

    @IsTest
    private static void testCaseStatusFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.Status = 'New';
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.Status = 'Outreach Required';
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.Status = 'New';
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.Status = 'Outreach Required';
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.Status = 'New';
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.caseStatus = 'Outreach Required';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(2, caseCount, 'Should get 2 total cases');
    }

    @IsTest
    private static void testCaseCategoryFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case_Classification__c parent = new Case_Classification__c(
            Name = 'ASU Advisor Outreach',
            Active__c = true,
            Visible__c = true,
            Record_Types_String__c = 'wer',
            RecordTypeId = Schema.SObjectType.Case_Classification__c.getRecordTypeInfosByName()
                .get('Functional Group')
                .getRecordTypeId()
        );
        insert parent;

        Case_Classification__c testClassification1 = new Case_Classification__c(
            Name = 'test-category-ap-r1',
            Active__c = true,
            Visible__c = true,
            Parent__c = parent.Id,
            RecordTypeId = Schema.SObjectType.Case_Classification__c.getRecordTypeInfosByName()
                .get('Category')
                .getRecordTypeId()
        );
        Case_Classification__c testClassification2 = new Case_Classification__c(
            Name = 'test-category-ap-r2',
            Active__c = true,
            Visible__c = true,
            Parent__c = parent.Id,
            RecordTypeId = Schema.SObjectType.Case_Classification__c.getRecordTypeInfosByName()
                .get('Category')
                .getRecordTypeId()
        );

        insert new List<Case_Classification__c>{ testClassification1, testClassification2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.CC_Functional_Group__c = parent.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.CC_Functional_Group__c = parent.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.CC_Functional_Group__c = parent.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.CC_Functional_Group__c = parent.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.CC_Functional_Group__c = parent.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        testCase1.CC_Category__c = testClassification1.Id;
        testCase2.CC_Category__c = testClassification2.Id;
        testCase3.CC_Category__c = testClassification1.Id;
        testCase4.CC_Category__c = testClassification2.Id;
        testCase5.CC_Category__c = testClassification1.Id;

        update new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.caseCategory = 'test-category-ap-r1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(3, caseCount, 'Should get 3 total cases');
    }

    @IsTest
    private static void testCaseSubjectFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.Subject = 'test-subject-ap-r1';
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.Subject = 'test-subject-ap-r2';
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.Subject = 'test-subject-ap-r1';
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.Subject = 'test-subject-ap-r2';
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.Subject = 'test-subject-ap-r1';
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.caseSubject = 'test-subject-ap-r1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(3, caseCount, 'Should get 3 total cases');
    }

    @IsTest
    private static void testOutlookScoreFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Persistence_Outlook__c testPersistenceOutlook1 = new Persistence_Outlook__c(
            Contact__c = testContact1.Id,
            Curr_Cont_Prediction_Level__c = 4
        );
        Persistence_Outlook__c testPersistenceOutlook2 = new Persistence_Outlook__c(
            Contact__c = testContact2.Id,
            Curr_Cont_Prediction_Level__c = 6
        );

        insert new List<Persistence_Outlook__c>{ testPersistenceOutlook1, testPersistenceOutlook2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.outlookScore = 'low';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');
    }

    @IsTest
    private static void testOutlookChangeFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Persistence_Outlook__c testPersistenceOutlook1 = new Persistence_Outlook__c(
            Contact__c = testContact1.Id,
            Change_Direction__c = 1
        );
        Persistence_Outlook__c testPersistenceOutlook2 = new Persistence_Outlook__c(
            Contact__c = testContact2.Id,
            Change_Direction__c = 0
        );

        insert new List<Persistence_Outlook__c>{ testPersistenceOutlook1, testPersistenceOutlook2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.outlookChange = 'down';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
    }

    @IsTest
    private static void testCaseCountFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.caseCount = 2;
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact1.Id, results[0].portalContact.Id, 'Should get first test contact');
    }

    @IsTest
    private static void testCreatedDateFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.CreatedDate = System.now().addDays(-2);
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.CreatedDate = System.now().addDays(-2);
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.createdFromDate = System.now().addDays(-3).format('yyyy-MM-dd');
        filter.createdToDate = System.now().addDays(-1).format('yyyy-MM-dd');
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(2, caseCount, 'Should get 2 total cases');
    }

    @IsTest
    private static void testFollowupDateFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.Followup_Date__c = System.today().addDays(1);
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.Followup_Date__c = System.today().addDays(1);
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.followUpFromDate = String.valueof(System.today());
        filter.followUpToDate = String.valueof(System.today().addDays(2));
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(2, caseCount, 'Should get 2 total cases');
    }

    @IsTest
    private static void testPersistanceChangeDateFilter() {
        // Can't really check because impossible to change Change_Date__c field
    }

    @IsTest
    private static void testAllStudentsFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        Contact testContact3 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact4 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2, testContact3, testContact4 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Success_Pod__c testSuccPod = new Success_Pod__c(OwnerId = testUser.Id);

        insert testSuccPod;

        Success_Student__c testSuccessStudent1 = new Success_Student__c(
            Student__c = testContact3.Id,
            Success_Pod__c = testSuccPod.Id
        );
        Success_Student__c testSuccessStudent2 = new Success_Student__c(
            Student__c = testContact2.Id,
            Success_Pod__c = testSuccPod.Id
        );

        insert new List<Success_Student__c>{ testSuccessStudent1, testSuccessStudent2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getAllContactsAndRespectiveCases(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(3, caseCount, 'Should get 3 total cases');
    }

    @IsTest
    private static void testWatchlistCasesFilter() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2 };

        Case_Classification__c parent = new Case_Classification__c(
            Name = 'ASU Advisor Outreach',
            Active__c = true,
            Visible__c = true,
            Record_Types_String__c = 'wer',
            RecordTypeId = Schema.SObjectType.Case_Classification__c.getRecordTypeInfosByName()
                .get('Functional Group')
                .getRecordTypeId()
        );
        insert parent;

        Case_Classification__c testClassification1 = new Case_Classification__c(
            Name = 'Watchlist',
            Active__c = true,
            Visible__c = true,
            Parent__c = parent.Id,
            RecordTypeId = Schema.SObjectType.Case_Classification__c.getRecordTypeInfosByName()
                .get('Category')
                .getRecordTypeId()
        );

        insert new List<Case_Classification__c>{ testClassification1 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.CC_Functional_Group__c = parent.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.CC_Functional_Group__c = parent.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.CC_Functional_Group__c = parent.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.CC_Functional_Group__c = parent.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.CC_Functional_Group__c = parent.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        testCase1.CC_Category__c = testClassification1.Id;
        testCase3.CC_Category__c = testClassification1.Id;
        testCase5.CC_Category__c = testClassification1.Id;

        update new List<Case>{ testCase1, testCase3, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.watchlistCasesState = true;
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(2, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(3, caseCount, 'Should get 3 total cases');
    }

    @IsTest
    static void testMutlipleFiltersAtOnce() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        testContact1.EmplId__c = '0011221100';
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        testContact2.ASURite_ID__c = 'testid_1';
        insert new List<Contact>{ testContact1, testContact2 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.Subject = 'test-subject-ap-r1';
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.Subject = 'test-subject-ap-r2';
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.Subject = 'test-subject-ap-r1';
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.Subject = 'test-subject-ap-r2';
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.Subject = 'test-subject-ap-r1';
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.studentString = 'Mister test-contact-ap-r2';
        filter.caseSubject = 'test-subject-ap-r1';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getContactCaseWrappersWithLessQueries(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 1 contact-case wrapper returned');
        System.assertEquals(testContact2.Id, results[0].portalContact.Id, 'Should get second test contact');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(2, caseCount, 'Should get 2 total cases');
    }

    @IsTest
    private static void testFiltersAndAllStudents() {
        Profile p = [SELECT Id FROM Profile WHERE Profile.Name = 'ASU Read Only'];

        User testUser = TestDataFactory.createUser('text-user-ap-r1', p.Id);
        insert testUser;

        Contact testContact1 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact2 = TestDataFactory.createContact('test-contact-ap-r2');
        Contact testContact3 = TestDataFactory.createContact('test-contact-ap-r1');
        Contact testContact4 = TestDataFactory.createContact('test-contact-ap-r2');
        insert new List<Contact>{ testContact1, testContact2, testContact3, testContact4 };

        Case testCase1 = TestDataFactory.createCase('test-case-ap-r1');
        testCase1.ContactId = testContact1.Id;
        testCase1.ownerId = testUser.Id;
        testCase1.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase2 = TestDataFactory.createCase('test-case-ap-r2');
        testCase2.ContactId = testContact1.Id;
        testCase2.ownerId = testUser.Id;
        testCase2.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase3 = TestDataFactory.createCase('test-case-ap-r3');
        testCase3.ContactId = testContact2.Id;
        testCase3.ownerId = testUser.Id;
        testCase3.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase4 = TestDataFactory.createCase('test-case-ap-r4');
        testCase4.ContactId = testContact2.Id;
        testCase4.ownerId = testUser.Id;
        testCase4.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');
        Case testCase5 = TestDataFactory.createCase('test-case-ap-r5');
        testCase5.ContactId = testContact2.Id;
        testCase5.ownerId = testUser.Id;
        testCase5.RecordTypeId = IDHelper.getRecordTypeId('Case', 'ASU_Advisor_Outreach');

        insert new List<Case>{ testCase1, testCase2, testCase3, testCase4, testCase5 };

        Success_Pod__c testSuccPod = new Success_Pod__c(OwnerId = testUser.Id);

        insert testSuccPod;

        Success_Student__c testSuccessStudent1 = new Success_Student__c(
            Student__c = testContact3.Id,
            Success_Pod__c = testSuccPod.Id
        );
        Success_Student__c testSuccessStudent2 = new Success_Student__c(
            Student__c = testContact2.Id,
            Success_Pod__c = testSuccPod.Id
        );

        insert new List<Success_Student__c>{ testSuccessStudent1, testSuccessStudent2 };

        AdvisorPortalFilter filter = new AdvisorPortalFilter();

        filter.studentString = 'Mister test-contact-ap-r2';
        List<AdvisorPortalContact> results = AdvisorPortalFilterSectionController.getAllContactsAndRespectiveCases(
            new List<Id>{ testUser.Id },
            filter
        );
        System.assertEquals(1, results.size(), 'Should get 2 contact-case wrapper returned');
        Integer caseCount = 0;
        for (AdvisorPortalContact apContact : results) {
            caseCount += apContact.cases.size();
        }
        System.assertEquals(3, caseCount, 'Should get 3 total cases');
    }

    @IsTest
    static void testFilterStudentGroups() {
        // Arrange
        List<Contact> listOfContacts = new List<Contact>();
        listOfContacts.add(
            new Contact(
                FirstName = 'test',
                LastName = 'rtn-advisorportal',
                Email = 'test@email.rtn.test',
                EmplId__c = '13000'
            )
        );
        listOfContacts.add(
            new Contact(
                FirstName = 'test2',
                LastName = 'rtn-advisorportal',
                Email = 'test@email.rtn.test',
                EmplId__c = '13001'
            )
        );
        insert listOfContacts;

        List<Student_Group__c> listOfStudentGroups = new List<Student_Group__c>();
        listOfStudentGroups.add(
            new Student_Group__c(
                SG_Contact__c = listOfContacts[0].Id,
                SG_PeopleSoft_Code__c = 'TESTGRP-r1',
                SG_Status__c = true
            )
        );
        listOfStudentGroups.add(
            new Student_Group__c(
                SG_Contact__c = listOfContacts[0].Id,
                SG_PeopleSoft_Code__c = 'TESTGRP-r2',
                SG_Status__c = true
            )
        );
        listOfStudentGroups.add(
            new Student_Group__c(
                SG_Contact__c = listOfContacts[1].Id,
                SG_PeopleSoft_Code__c = 'TESTGRP-r1',
                SG_Status__c = true
            )
        );
        listOfStudentGroups.add(
            new Student_Group__c(
                SG_Contact__c = listOfContacts[1].Id,
                SG_PeopleSoft_Code__c = 'TESTGRP-r2',
                SG_Status__c = false
            )
        );
        insert listOfStudentGroups;

        AdvisorPortalFilter filter1 = new AdvisorPortalFilter();
        filter1.studentGroupCode = 'testgrp-r1';

        AdvisorPortalFilter filter2 = new AdvisorPortalFilter();
        filter2.studentGroupCode = 'testgrp-r2';

        // Act
        Test.startTest();
        Set<Id> results1 = AdvisorPortalFilterSectionController.filterStudentGroups(
            filter1,
            new Set<Id>{ listOfContacts[0].Id, listOfContacts[1].Id }
        );
        Set<Id> results2 = AdvisorPortalFilterSectionController.filterStudentGroups(
            filter2,
            new Set<Id>{ listOfContacts[0].Id, listOfContacts[1].Id }
        );
        Test.stopTest();

        // Assert
        System.assertEquals(2, results1.size());
        System.assertEquals(1, results2.size());
        System.assert(results1.contains(listOfContacts[0].Id), 'The first contact has an active TESTGRP-r1 plan.');
        System.assert(results1.contains(listOfContacts[1].Id), 'The second contact has an active TESTGRP-r1 plan.');
        System.assert(results2.contains(listOfContacts[0].Id), 'The first contact has an active TESTGRP-r2 plan.');
        System.assert(
            !results2.contains(listOfContacts[1].Id),
            'The second contact does not have an active TESTGRP-r2 plan.'
        );
    }

    @IsTest
    static void testFilterStudentPlans() {
        // Arrange
        List<Contact> listOfContacts = new List<Contact>();
        listOfContacts.add(
            new Contact(
                FirstName = 'test',
                LastName = 'rtn-advisorportal',
                Email = 'test@email.rtn.test',
                EmplId__c = '13000'
            )
        );
        listOfContacts.add(
            new Contact(
                FirstName = 'test2',
                LastName = 'rtn-advisorportal',
                Email = 'test@email.rtn.test',
                EmplId__c = '13001'
            )
        );
        insert listOfContacts;

        List<Location__c> listOfLocations = new List<Location__c>();
        listOfLocations.add(new Location__c(Name = 'Test-r1', Location_Code__c = 'TEST-R1'));
        listOfLocations.add(new Location__c(Name = 'Test-r2', Location_Code__c = 'TEST-R2'));
        insert listOfLocations;

        List<Student_Program_Plan__c> listOfStudentPrograms = new List<Student_Program_Plan__c>();
        listOfStudentPrograms.add(
            new Student_Program_Plan__c(
                Contact__c = listOfContacts[0].Id,
                Cohort__c = 'Senior',
                Campus__c = listOfLocations[0].Id,
                Residency__c = 'Resident',
                Plan_Type_Text__c = 'MAJ',
                Plan_Description__c = 'Computer Science'
            )
        );
        listOfStudentPrograms.add(
            new Student_Program_Plan__c(
                Contact__c = listOfContacts[1].Id,
                Cohort__c = 'Junior',
                Campus__c = listOfLocations[1].Id,
                Residency__c = 'International',
                Plan_Type_Text__c = 'MAJ',
                Plan_Description__c = 'Computer Science'
            )
        );
        listOfStudentPrograms.add(
            new Student_Program_Plan__c(
                Contact__c = listOfContacts[1].Id,
                Cohort__c = 'Senior',
                Campus__c = listOfLocations[1].Id,
                Residency__c = 'Resident',
                Plan_Type_Text__c = 'MAJ',
                Plan_Description__c = 'Law'
            )
        );
        insert listOfStudentPrograms;

        AdvisorPortalFilter filter1 = new AdvisorPortalFilter();
        filter1.academicLevel = 'senior;junior';
        filter1.campus = 'test-r1;test-r2';
        filter1.residency = 'resident;international';
        filter1.major = 'computer';

        AdvisorPortalFilter filter2 = new AdvisorPortalFilter();
        filter2.major = 'law';

        // Act
        Test.startTest();
        Set<Id> results1 = AdvisorPortalFilterSectionController.filterStudentPlans(
            filter1,
            new Set<Id>{ listOfContacts[0].Id, listOfContacts[1].Id }
        );
        Set<Id> results2 = AdvisorPortalFilterSectionController.filterStudentPlans(
            filter2,
            new Set<Id>{ listOfContacts[0].Id, listOfContacts[1].Id }
        );
        Test.stopTest();

        System.debug(results1);
        System.debug(results2);

        // Assert
        System.assertEquals(2, results1.size());
        System.assertEquals(1, results2.size());
        System.assert(
            results1.contains(listOfContacts[0].Id),
            'The first contact should be in the first set of results.'
        );
        System.assert(
            results1.contains(listOfContacts[1].Id),
            'The second contact should be in the first set of results.'
        );
        System.assert(
            !results2.contains(listOfContacts[0].Id),
            'The first contact should not be in the second set of results.'
        );
        System.assert(
            results2.contains(listOfContacts[1].Id),
            'The second contact should be in the second set of results.'
        );
    }
}