src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Curr_Cont_Prediction_Level__c.field-meta.xml
<CustomField>
    <fullName>Curr_Cont_Prediction_Level__c</fullName>
    <formula>Contact.Curr_Cont_Prediction_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Outlook Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Most_Recent_Outlook_Change_Direction__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Outlook_Change_Direction__c</fullName>
    <formula>Contact.Most_Recent_Outlook_Change_Direction__c</formula>
    <label>Most Recent Outlook Change Direction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Curr_Cont_Prediction_Level__c</fullName>
        <description>The persistence outlook prediction level for the student after the most recent change.</description>
        <label>Current Outlook Level</label>
        <summarizedField>Persistence_Outlook__c.Curr_Cont_Prediction_Level__c</summarizedField>
        <summaryForeignKey>Persistence_Outlook__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Most_Recent_Outlook_Change_Direction__c</fullName>
        <description>The direction of change between -2 (for null previous values) to 1 (for positive changes) for the students civitas persistence score</description>
        <label>Most Recent Outlook Change Direction</label>
        <summarizedField>Persistence_Outlook__c.Change_Direction__c</summarizedField>
        <summaryForeignKey>Persistence_Outlook__c.Contact__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portal_Email__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Additional_Message_Text__c</fullName>
        <label>Additional Message Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Most_Recent_Queue__c</fullName>
        <description>The queue the case was most recently assigned to.</description>
        <formula>Case__r.Most_Recent_Queue__c</formula>
        <inlineHelpText>Used to determine which queue to send at if the primary ownerId is a userId.</inlineHelpText>
        <label>Case Most Recent Queue</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Thread_Id__c</fullName>
        <formula>Case__r.Thread_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Thread Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Message_Id__c</fullName>
        <label>Email Message Id</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Template_Name__c</fullName>
        <label>Email Template Name</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor Ad-hoc template</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>From_Address__c</fullName>
        <description>The email address that is sending the email.</description>
        <label>From Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Owner_Id__c</fullName>
        <description>Displays the OwnerId to be used in determining the desired from address.</description>
        <formula>IF(
 ISBLANK( Case_Owner_Id__c ),
 Student_Owner_Id__c,
 Case_Owner_Id__c
)</formula>
        <label>Primary Owner Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Held/Undeliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Bounced/Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Email Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Student</label>
        <referenceTo>Success_Student__c</referenceTo>
        <relationshipLabel>Portal Emails</relationshipLabel>
        <relationshipName>Portal_Emails</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object containing all of the information required to send emails from within the portal through the marketing cloud integration.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Portal Email</label><nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Portal Email Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Portal Emails</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_with_Details</fullName>
        <columns>NAME</columns>
        <columns>CREATED_DATE</columns>
        <columns>RECORDTYPE</columns>
        <columns>Status__c</columns>
        <columns>Contact__c</columns>
        <columns>Email_Template_Name__c</columns>
        <columns>From_Name__c</columns>
        <columns>From_Address__c</columns>
        <filterScope>Everything</filterScope>
        <label>All with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Test_Messages</fullName>
        <booleanFilter>1</booleanFilter>
        <columns>CREATED_DATE</columns>
        <columns>NAME</columns>
        <columns>Status__c</columns>
        <columns>From_Address__c</columns>
        <columns>From_Name__c</columns>
        <columns>Contact__c</columns>
        <columns>Contact_Email__c</columns>
        <columns>Case_Number__c</columns>
        <columns>Case_Owner_Id__c</columns>
        <columns>Contact_First_Name__c</columns>
        <columns>Created_By_Full_Name__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Contact__c</field>
            <operation>equals</operation>
            <value>Dawn Scott</value>
        </filters>
        <label>Test Messages</label>
    </listViews><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes></CustomObject>

force-app/main/default/objects/Portal_Email__c/fields/Additional_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Additional_Message_Text__c</fullName>
    <label>Additional Message Text</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Portal Emails</relationshipLabel>
    <relationshipName>Portal_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email Template Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Advisor Ad-hoc template</fullName>
            </value>
            <value>
                <fullName>CISA Mass Email - May 2017</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Processing</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>MC Subscriber Status: Held/Undeliverable</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>MC Subscriber Status: Bounced/Returned</fullName>
            </value>
            <value>
                <fullName>Salesforce Email Opt Out</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <defaultValue>"A Message from your College and Department"</defaultValue>
    <description>The subject for the email</description>
    <label>Subject</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Success_Student__c.field-meta.xml
<CustomField>
    <fullName>Success_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Success Student</label>
    <referenceTo>Success_Student__c</referenceTo>
    <relationshipLabel>Portal Emails</relationshipLabel>
    <relationshipName>Portal_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Program_Description__c</fullName>
        <description>Data sourced from ACAD_PROG_TBL.DESCR</description>
        <label>Program Description</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Data sourced from PS_ACAD_PROG.ASU_PROGSTATUS1</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active in Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/ASURiteID__c.field-meta.xml
<CustomField>
    <fullName>ASURiteID__c</fullName>
    <formula>Student__r.ASURite_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ASURITE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Curr_Cont_Prediction_Level__c.field-meta.xml
<CustomField>
    <fullName>Curr_Cont_Prediction_Level__c</fullName>
    <formula>Student__r.Curr_Cont_Prediction_Level__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Current Outlook Level</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Student__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Most_Recent_Outlook_Change_Direction__c.field-meta.xml
<CustomField>
    <fullName>Most_Recent_Outlook_Change_Direction__c</fullName>
    <formula>Student__r.Most_Recent_Outlook_Change_Direction__c</formula>
    <label>Most Recent Outlook Change Direction</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Student_Name__c.field-meta.xml
<CustomField>
    <fullName>Student_Name__c</fullName>
    <formula>Student__r.LastName + ', ' + Student__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Student Name</label>
    <type>Text</type>
</CustomField>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/showMyStudentsController.cls
public class showMyStudentsController extends ListViewController {
    private boolean debug = false;
    public Id proactiveCaseRTID {get; set;}
    private String oldQuery {get; set;} // Used to determine if the query changes
    private final Integer cookieExpiration = 22592000; // 30 days in seconds (30 Days * 24 hours * 60 minutes * 60 seconds)
    public Id portalEmailRTID {get; set;}
    private boolean differentField;
    public Boolean emailPreviewMode {get; set;} // Used to determine which set of buttons to show in the email modal
    public List<Database.SaveResult> emailInsertResults {get; set;} // Used to display the results of the email send to the user
    public String collegeFilter {get; set;}
    public string searchString {get; set;}
    public Map<Id,caseWrapper> caseCountMap  {get; set;}
    public List<studentWrapper> studentList {get; set;}

    /*
     * Updats the setCon query with the ORDER BY clause sortField and sortDir
     */
    public void updateQuery() {
        List<String> vars = new List<String>();
        try{
            String tmpQuery = query;
            Integer loc = tmpQuery.indexOf('ORDER');
            tmpQuery = tmpQuery.substring(0, loc);
            setCon = new ApexPages.StandardSetController(DataBase.getQueryLocator(tmpQuery += ' ORDER BY ' + sortField + ' ' + sortDir));
        }
        catch(Exception e){
            vars.add(ErrorLogger.convertStringToJSON('query', query));
            vars.add(ErrorLogger.convertStringToJSON('sortField', sortField));
            vars.add(ErrorLogger.convertStringToJSON('sortDir', sortDir));
            ErrorLogger.log(e, vars, debug);
        }
    }

    /*
     * Get the list of students selected by the end user.
     */
    public List<Success_Student__c> selectedStudents {
        get {
            selectedStudents = new List<Success_Student__c>();

            for (studentWrapper sw : studentList) {
                if (sw.selected) {
                    selectedStudents.add(sw.obj);
                }
            }

            return selectedStudents;
        }

        set {
            selectedStudents = value;

            if (selectedStudents == null) {
                for (studentWrapper sw : studentList) {
                    sw.selected = false;
                }
            }
        }
    }

    /*
     * Portal Email object to store user input for mass emails
     */
    public Portal_Email__c tempEmail {
        get {
            if (tempEmail == null) {
                tempEmail = new Portal_Email__c(
                    RecordTypeId = portalEmailRTID,
                    Subject__c = 'A Message from your College and Department'
                );
            }

            return tempEmail;
        }

        set;
    }

    /*
     * Create portal email records for sending emails through marketing cloud
     */
    public void massEmail() {
        List<String> vars = new List<String>();
        List<Portal_Email__c> emails = new List<Portal_Email__c>();
        try {
            for (Success_Student__c ss : selectedStudents) {
                // Most of the object is formula fields
                emails.add(new Portal_Email__c(
                    Success_Student__c = ss.Id,
                    Contact__c = ss.Student__c,
                    Additional_Message_Text__c = tempEmail.Additional_Message_Text__c,
                    Subject__c = tempEmail.Subject__c,
                    RecordTypeId = portalEmailRTID,
                    Email_Template_Name__c = tempEmail.Email_Template_Name__c
                ));
            }

            if (emails.size() > 0) {
                emailInsertResults = dataBase.insert(emails);
            }

            // Reset the tempEmail
            tempEmail = null;
            emailPreviewMode = false;
        } catch (Exception e){
            vars.add(string.valueOf(emails));
            ErrorLogger.log(e, vars, debug);
        }
    }


    public override void resetRecordList() {
        Success_Student__c tempStudent;

        studentList = new List<studentWrapper>();
        for (SObject so : setCon.getRecords()) {
            tempStudent = (Success_Student__c) so;
            if(tempStudent.Student__c!=null) {
                studentList.add(new studentWrapper(tempStudent));
            }
        }

        resetCaseCounts();
    }

    /*
    * Resets the caseCounts map
    */
    public void resetCaseCounts() {
        caseCountMap = new Map<Id, caseWrapper>();
        Set<Id> contactIds = new Set<Id>();

        if (studentList != null) {
            for (studentWrapper sw : studentList) {
                contactIds.add(sw.obj.Student__c);
            }

            for (Contact c : [SELECT id,
                              (SELECT RecordTypeId
                               FROM Cases
                               WHERE isClosed = false)
                              FROM Contact
                              WHERE Id IN :contactIds]) {
                                  caseCountMap.put(c.id, new caseWrapper());
                                  for (Case cc : c.cases) {
                                      if (cc.recordTypeId == proactiveCaseRTID) {
                                          caseCountMap.get(c.Id).proactiveCount++;
                                      } else {
                                          caseCountMap.get(c.Id).reactiveCount++;
                                      }
                                  }
                              }
        }

    }

    /*
     * Used to track the number of proactive and reactive cases at the contact level
     */
     public class caseWrapper {
        public Integer reactiveCount {get; set;}
        public Integer proactiveCount {get; set;}

        public caseWrapper() {
            reactiveCount = 0;
            proactiveCount = 0;
        }
    }

    /*
     * Class to facilitate selection of students for mass actions
     */
    public class studentWrapper {
        public Boolean selected {get; set;}
        public Success_Student__c obj {get; set;}
        public String changeDir {get; set;}
        public String imageName {get; set;}

        public studentWrapper(Success_Student__c student) {
            selected = false;
            obj = student;

            if (obj.Most_Recent_Outlook_Change_Direction__c == 1) {
                changeDir = 'Up';
            } else if (obj.Most_Recent_Outlook_Change_Direction__c == -1) {
                changeDir = 'Down';
            } else if(obj.Most_Recent_Outlook_Change_Direction__c == 0){
                changeDir = ' ';
            } else {
                changeDir = ' ';
            }

            if (obj.Curr_Cont_Prediction_Level__c < 4) {
               imageName = 'icon-1.png';
            } else if (obj.Curr_Cont_Prediction_Level__c < 6) {
                imageName = 'icon-2.png';
            } else if (obj.Curr_Cont_Prediction_Level__c == 6) {
                imageName = 'icon-3.png';
            } else if (obj.Curr_Cont_Prediction_Level__c == 7) {
                imageName = 'icon-4.png';
            } else {
                imageName = 'icon-5.png';
            }
        }
    }

    /*
     * Class to hold all of the data needed for Civitas
     */
    public class CivitasWrapper {
        public Integer outlookScore {get; set;}
        //Direction is negative for down, 0 for same, and positive for up
        public Integer direction {get; set;}
        public Date changeDate {get; set;}

        public CivitasWrapper(Integer oScore, Integer dir, Date change) {
            outlookScore = oScore;
            direction = dir;
            changeDate = change;
        }
    }

    public boolean searched{
        get{
            if(query == NULL || !query.contains('LIKE')){
                searched = false;
            }
            else{
                searched = true;
            }
            return searched;
        }
        set;
    }

    /*
     * Used to refresh the list to it's orignal state
     */
    public void resetSearch(){
        searchString = NULL;
        collegeFilter = NULL;
        query = queryAttr;
    }

    /*
     * The page can't pass a null value to the setter so we have to use
     * an action call instead.
     */
    public void clearSaveResults() {
        emailInsertResults = null;
        // Had to move this to the end of the execution order (was in mass email)
        // because the page wasn't rerendering after mass email and the selections
        // were being re-submitted.
        selectedStudents = null;
    }

    public void insertFilterIntoQuery() {
        String modifiedQuery = queryAttr;
        String filter = createFilterForStudent();

        Integer loc = modifiedQuery.indexOf('WHERE');
        String leftSideOfQuery = modifiedQuery.substring(0, loc + 5);
        leftSideOfQuery = leftSideOfQuery.trim();
        String rightSideOfQuery = modifiedQuery.subString(loc + 6);
        rightSideOfQuery = rightSideOfQuery.trim();

        modifiedQuery = leftSideOfQuery + filter + rightSideOfQuery;
        query = modifiedQuery;
    }

    private String createFilterForStudent() {
        String filter = createFilterStringForStudent();
        filter += createFilterStringForCollege();
        return filter;
    }

    private String createFilterStringForCollege() {
        if (!String.isEmpty(collegeFilter)) {
            return ' (Student__c IN (SELECT Contact__c FROM Student_Program_Plan__c ' +
                   'WHERE Status__c = \'Active in Program\' AND Program_Description__c LIKE \'%' +
                   collegeFilter + '%\')) AND ';
        }
        return ' ';
    }

    private String createFilterStringForStudent() {
        String searchCon = searchString.trim();
        String createdQuery = ' (' +
            'Student_Name__c LIKE \'%' + String.escapeSingleQuotes(searchCon) + '%\' ' +
                    'OR EMPLID__c LIKE \'%' + String.escapeSingleQuotes(searchCon) + '%\'' +
                    'OR ASURiteID__c LIKE \'%' + String.escapeSingleQuotes(searchCon) + '%\'' +
                ') AND ';
        return createdQuery;
    }
}