src/objects/Case_Assignment_Rule__c.object
<CustomObject><fields>
        <fullName>Case_Record_Type_Id__c</fullName>
        <description>Id of the Case record type that the case should be created as.</description>
        <inlineHelpText>The 15 character case sensitive Id of the record type associated with this assignment rule. This Id is shown immediately after "...salesforce.com/setup/ui/recordtypefields.jsp?id=" in the URL when viewing the record type.</inlineHelpText>
        <label>Case Record Type Id</label>
        <length>15</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Email_Address__c</fullName>
        <description>[??] - Case email address</description>
        <inlineHelpText>This Email Address is used:
1. To identify which Assignment Rule to Use (if this address is found in the "Initial Request Sent To Addresses")
2. As the "From" address for the notice emailed to the customer that a Case has been created.</inlineHelpText>
        <label>Email Address</label>
        <type>Email</type>
    </fields><fields>
        <fullName>Queue_ID__c</fullName>
        <description>[??] - The 15 character (case sensitive) ID of the Queue or User associated with this Assignment Rule.This ID  is shown immediatly after "....salesforce.com/p/own/Queue/d?id="  in the URL when viewing the Queue or  "...salesforce.com/" when viewing the User.</description>
        <inlineHelpText>The 15 character (case sensitive) ID of the Queue or User associated with this Assignment Rule.This ID  is shown immediatly after "....salesforce.com/p/own/Queue/d?id="  in the URL when viewing the Queue or  "...salesforce.com/" when viewing the User.</inlineHelpText>
        <label>Queue or User ID</label>
        <length>15</length>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object used to assign case records. Criteria based on email address or association with a web form campaign record.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Case Assignment Rule</label><nameField>
        <displayFormat>CAR-{0000}</displayFormat>
        <label>Case Assignment Rule</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Case Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel></CustomObject>

force-app/main/default/objects/Case_Assignment_Rule__c/fields/CC_Category__c.field-meta.xml
<CustomField>
    <fullName>CC_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case Classification Category field</description>
    <inlineHelpText>Lookup to the Case Classification Category field</inlineHelpText>
    <label>Case Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Category</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.CC_Functional_Group__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>CAR (Category)</relationshipLabel>
    <relationshipName>Case_Assignment_Rules1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Assignment_Rule__c/fields/CC_Functional_Group__c.field-meta.xml
<CustomField>
    <fullName>CC_Functional_Group__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case Classification Functional Group field</description>
    <inlineHelpText>Lookup to the Case Classification Functional Group field</inlineHelpText>
    <label>Case Functional Group</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Functional Group</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>CAR (Functional Group)</relationshipLabel>
    <relationshipName>Case_Assignment_Rules</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case_Assignment_Rule__c/fields/CC_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>CC_Sub_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to the Case Classification Sub-Category field</description>
    <inlineHelpText>Lookup to the Case Classification Sub-Category field</inlineHelpText>
    <label>Case Sub-Category</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Case_Classification__c.Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.RecordTypeId</field>
            <operation>equals</operation>
            <value>Sub Category</value>
        </filterItems>
        <filterItems>
            <field>Case_Classification__c.Parent__c</field>
            <operation>equals</operation>
            <valueField>$Source.CC_Category__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Case_Classification__c</referenceTo>
    <relationshipLabel>CAR (Sub-Category)</relationshipLabel>
    <relationshipName>Case_Assignment_Rules2</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/NonAuthenticatedLiveAgentController.cls
public without sharing class NonAuthenticatedLiveAgentController {
    public String buttonPressed {set; get;} 
    public String caseDescription {set; get;}
    public String caseRecordType {set; get;}
    public String caseOwnerId {set; get;}
    public String caseFunctionalGroup {set; get;}
    public String caseCategory {set; get;}
    public String caseSubCategory {set; get;}
    public String caseSubject {set; get;}
    public String presurveyQuestion {set; get;}
    public String contactId {set; get;}
    private static final NON_AFFILIATE_CAR_EMAIL = 'non_affiliate_live_chat@asu.edu';

    public NonAuthenticatedLiveAgentController() {
        buttonPressed = LiveAgentUtils.getButtonIdFromURL();
        setCaseDetails();
        setPresurveyQuestion();
    }
    
    private void setCaseDetails() {
        Case_Assignment_Rule__c carForButton = getCarFromButton();
        caseRecordType = carForButton.Case_Record_Type_Id__c;
        caseFunctionalGroup = carForButton.CC_Functional_Group__c;
        caseCategory = carForButton.CC_Category__c;
        caseSubCategory = carForButton.CC_Sub_Category__c;
        setCaseOwnerAndSubject(carForButton);
    }
    
    private Case_Assignment_Rule__c getCarFromButton() {
        String emailForCarFilter = 	NON_AFFILIATE_CAR_EMAIL;
        
        Case_Assignment_Rule__c carFromButton = [SELECT Case_Record_Type_Id__c, CC_Functional_Group__c, CC_Category__c, Queue_ID__c, CC_Sub_Category__c, OwnerId 
                                                 FROM Case_Assignment_Rule__c
                                                 WHERE Email_Address__c =: emailForCarFilter LIMIT 1];
        return carFromButton;
    }
    
    private void setPresurveyQuestion() {
        presurveyQuestion = Label.PreSurveyQuestion;
    }
    
    private void setCaseOwnerAndSubject(Case_Assignment_Rule__c car) {
        if (car.Queue_ID__c.subString(0,3) == IDHelper.findPrefixFromObjectName('Group')) {
        	List<Group> potentialQueue = [SELECT Id, Name FROM Group WHERE Id =: car.Queue_ID__c];
            caseOwnerId = potentialQueue[0].Id;
            caseSubject = potentialQueue[0].Name + ' ' + buttonPressed.replace('_', ' ');
        } else if (car.Queue_ID__c.subString(0,3) == IDHelper.findPrefixFromObjectName('User')) {
            List<User> potentialUser = [SELECT Id, Name FROM User WHERE Id =: car.Queue_ID__c];
            caseOwnerId = potentialUser[0].Id;
            caseSubject = potentialUser[0].Name + ' ' + buttonPressed.replace('_', ' ');
        }
    }
    
    private void setNonAffiliatedContact() {
        Contact nonAffiliatedContact = [SELECT Id FROM Contact WHERE Name = 'Non-Affiliate Chat Caller'];
        contactId = nonAffiliatedContact.Id;
    }
    
}