src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Portal_Email__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Additional_Message_Text__c</fullName>
        <label>Additional Message Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Most_Recent_Queue__c</fullName>
        <description>The queue the case was most recently assigned to.</description>
        <formula>Case__r.Most_Recent_Queue__c</formula>
        <inlineHelpText>Used to determine which queue to send at if the primary ownerId is a userId.</inlineHelpText>
        <label>Case Most Recent Queue</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Thread_Id__c</fullName>
        <formula>Case__r.Thread_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Thread Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Message_Id__c</fullName>
        <label>Email Message Id</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Template_Name__c</fullName>
        <label>Email Template Name</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor Ad-hoc template</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>From_Address__c</fullName>
        <description>The email address that is sending the email.</description>
        <label>From Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Owner_Id__c</fullName>
        <description>Displays the OwnerId to be used in determining the desired from address.</description>
        <formula>IF(
 ISBLANK( Case_Owner_Id__c ),
 Student_Owner_Id__c,
 Case_Owner_Id__c
)</formula>
        <label>Primary Owner Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Held/Undeliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Bounced/Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Email Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Student</label>
        <referenceTo>Success_Student__c</referenceTo>
        <relationshipLabel>Portal Emails</relationshipLabel>
        <relationshipName>Portal_Emails</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object containing all of the information required to send emails from within the portal through the marketing cloud integration.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Portal Email</label><nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Portal Email Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Portal Emails</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_with_Details</fullName>
        <columns>NAME</columns>
        <columns>CREATED_DATE</columns>
        <columns>RECORDTYPE</columns>
        <columns>Status__c</columns>
        <columns>Contact__c</columns>
        <columns>Email_Template_Name__c</columns>
        <columns>From_Name__c</columns>
        <columns>From_Address__c</columns>
        <filterScope>Everything</filterScope>
        <label>All with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Test_Messages</fullName>
        <booleanFilter>1</booleanFilter>
        <columns>CREATED_DATE</columns>
        <columns>NAME</columns>
        <columns>Status__c</columns>
        <columns>From_Address__c</columns>
        <columns>From_Name__c</columns>
        <columns>Contact__c</columns>
        <columns>Contact_Email__c</columns>
        <columns>Case_Number__c</columns>
        <columns>Case_Owner_Id__c</columns>
        <columns>Contact_First_Name__c</columns>
        <columns>Created_By_Full_Name__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Contact__c</field>
            <operation>equals</operation>
            <value>Dawn Scott</value>
        </filters>
        <label>Test Messages</label>
    </listViews><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes></CustomObject>

force-app/main/default/objects/Portal_Email__c/fields/Additional_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Additional_Message_Text__c</fullName>
    <label>Additional Message Text</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <label>Email Template Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Default</fullName>
                <default>true</default>
                <label>Default</label>
            </value>
            <value>
                <fullName>Advisor Ad-hoc template</fullName>
            </value>
            <value>
                <fullName>CISA Mass Email - May 2017</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Email__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <label>Advisor</label>
</RecordType>

src/objects/Success_Pod__c.object
<CustomObject>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/classes/Test_ShowMyCases.cls
@isTest
public class Test_ShowMyCases {
    private static Integer numberOfPods;
    private static Integer numberOfCases;
    private static Integer numberOfStudents;
    private static ShowMyCasesController smsc;
    private static List<Success_Pod__c> pod; // Used to store the pod created for testing
    private static string query;
    
    static {
        smsc = new ShowMyCasesController();
        numberOfPods = 3;
        numberOfcases = 5;
        numberOfStudents = 5;
        
        pod = new List<Success_Pod__c>([SELECT OwnerId FROM Success_Pod__c Limit 1]);
        
        if (pod.size() > 0) {
            Query = 'SELECT CaseNumber, ContactId, Contact.Name, Contact.EMPLID__c, Subject, Description, Status, FollowUp_Date__c ' +
                'FROM Case ' +
                'WHERE OwnerId = \'' + pod[0].ownerId + '\' ' +
                'AND recordTypeId = \'' + RTIDHelper.getRTID('Case', 'ASU Advisor Outreach') + '\' ' +
                'AND isClosed = false';
            
            smsc.query = query;
        }
    }
    
    @testSetup
    public static void testSetup() {
        TestDataFactory.makeMeAnAdvisorUser(numberOfPods, numberOfCases, numberOfStudents);
    }
    
    /*
     * Tests caseList's getter
     */
    public static testMethod void Test_getStudentList() {
        // note, the number of students in the list will either be equal to pageSize
        // Or numberOfStudentsToCreate if this value is fewer than pageSize.
        // This is because the standard set controller will only get the number of records
        // set in setCon.setPageSize().
         
        if (numberOfStudents < smsc.pageSize) {
            system.assertEquals(numberOfStudents, smsc.caseList.size());
        } else {
            system.assertEquals(smsc.pageSize, smsc.caseList.size());
        }
    }
    
    /* 
     * Tests force refresh method and setCons ability to reset the refresh variable
     */
    public static testMethod void Test_forceRefresh() {
        ApexPages.StandardSetController ssc; // Used to store set controller so we can call getter
        List<Case> casesBeforeRefresh = new List<Case>(); // List of cases prior to refresh
        
        ssc = smsc.setCon; // Get setcon to force code to run
        
        for (showMyCasesController.caseWrapper cw : smsc.caseList) {
            casesBeforeRefresh.add(cw.obj);
        }
        
        smsc.refreshList = true; // force a refresh
        
        for (Integer x = 0; x < casesBeforeRefresh.size(); x++) {
            system.assertEquals(casesBeforeRefresh[x].id, smsc.caseList[x].obj.id);
        }
    }
    
    /*
     * Tests the conroller's ability to selectcases and retrive selected cases
     */
    public static testMethod void Test_GetSelectedCases() {
        for (showMyCasesController.caseWrapper cw : smsc.caseList) {
            cw.selected = true;
        }
        
        system.assertEquals(smsc.caseList.size(), smsc.selectedCases.size());
    }
    
    /*
     * Tests the controller's ability to change the owner of cases
     */
    public static testMethod void Test_TransferCases() {
        List<Id> casesToVerify = new List<Id>();
        
        // Select cases to transfer
        for (showMyCasesController.caseWrapper cw : smsc.caseList) {
            cw.selected = true;
        }
        
        // Set ownerId for new cases
        smsc.ownerId = UserInfo.getUserId();
        
        // Store a copy of the cases to use for checking owner ID changed
        for (Case c : smsc.selectedCases) {
            casesToVerify.add(c.Id);
        }
        
        // Transfer
        smsc.transferCases();
        
        // Verify ownerIds changed
        for (Case c : [SELECT OwnerId FROM Case WHERE Id IN :casesToVerify]) {
            system.assertEquals(UserInfo.getUserId(), c.ownerId);
        }
    }
    
    /*
     * Tests the controllers ability to set and get the page size value
     */
    public static testMethod void Test_getSetPageSize() {
        smsc.pageSize = 25;
        system.assertEquals(25, smsc.pageSize);
        
        // Set it again to make sure 25 is not just a value stored in the cookie
        // to minimize chance of missing errors
        smsc.pageSize = 50;
        system.assertEquals(50, smsc.pageSize);
    }
    
    /*
     * Tests the controllers ability to handle null values in sortDir
     */
    public static testmethod void Test_getSort() {
        smsc.sortDir = null; // Set to null
        system.assertEquals('DESC', smsc.sortDir); // Make sure the sortDir is set to default DESC
    }
    
    /*
     * Tests the controllers ability to toggle the sort dir
     */
    public static testmethod void Test_setSortField() {
        // Set sortfield to contact.name
        // verify the query contains "ORDER BY" and "Contact.Name"
        smsc.sortField = 'Contact.Name';
        
        system.assert(smsc.query.contains('ORDER BY'));
        system.assert(smsc.query.contains('Contact.Name'));
    }
    
    /*
     * Tests the controllers ability to insert mass emails
     */
    public static testmethod void Test_MassEmail() {
        // Select students
        for (ShowMyCasesController.caseWrapper cw : smsc.caseList) {
            cw.selected = true; // Select all the cases
        }
        
        // Set TempEmail
        smsc.tempEmail.Email_Template_Name__c = 'Advisor Ad-hoc template';
        smsc.tempEmail.Additional_Message_Text__c = 'Test mass email';
        
        smsc.portalEmailRTID = RTIDHelper.getRTID('Portal_Email__c', 'Advisor');
        
        // Insert Portal Emails
        smsc.massEmail();
        
        system.debug('assert called below me');
        system.assertEquals(smsc.caseList.size(), [SELECT Id FROM Portal_Email__c].size());
        system.debug('assert Called above me');
    }
}