src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[Mulesoft] - When an Enterprise RFI is submitted, integrations will set this field based on what's in the submission/payload.</description>
    <inlineHelpText>[Mulesoft] - When an Enterprise RFI is submitted, integrations will set this field based on what's in the submission/payload.</inlineHelpText>
    <label>Program Code</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>[Peoplesoft] - Code for the program (College)</description>
        <externalId>true</externalId>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Listing of all University programs (Colleges)</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Success_Pod__c.object
<CustomObject>
    <fields>
        <fullName>Committee__c</fullName>
        <description>for import of Advising Committee</description>
        <label>Committee</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <description>This is used for Coach Assignment and Advisor Manager access. The Advisor Manager record should have one of these Program Code values in the Success_Resource_Program_Code__c field in order to have access to this POD's queue.</description>
        <inlineHelpText>This is used for Coach Assignment and Advisor Manager access. The Advisor Manager record should have one of these Program Code values in the Success_Resource_Program_Code__c field in order to have access to this POD's queue.</inlineHelpText>
        <label>Programs</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AD-HOC</fullName>
                </value>
                <value>
                    <fullName>GRAD</fullName>
                </value>
                <value>
                    <fullName>UGAS</fullName>
                </value>
                <value>
                    <fullName>UGBA</fullName>
                </value>
                <value>
                    <fullName>UGCS</fullName>
                </value>
                <value>
                    <fullName>UGES</fullName>
                </value>
                <value>
                    <fullName>UGHI</fullName>
                </value>
                <value>
                    <fullName>UGLA</fullName>
                </value>
                <value>
                    <fullName>UGLS</fullName>
                </value>
                <value>
                    <fullName>UGNH</fullName>
                </value>
                <value>
                    <fullName>UGNU</fullName>
                </value>
                <value>
                    <fullName>UGPP</fullName>
                </value>
                <value>
                    <fullName>UGPR</fullName>
                </value>
                <value>
                    <fullName>UGSU</fullName>
                </value>
                <value>
                    <fullName>UGTB</fullName>
                </value>
                <value>
                    <fullName>UGTE</fullName>
                </value>
                <value>
                    <fullName>UGUC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Role__c</fullName>
        <label>Resource Role</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Resource__r.EmployeeNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Person is available to be assigned Success Students</description>
    <label>Active Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
    <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
    <label>Program Code</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>UGAS</fullName>
            </value>
            <value>
                <fullName>UGBA</fullName>
            </value>
            <value>
                <fullName>UGCS</fullName>
            </value>
            <value>
                <fullName>UGES</fullName>
            </value>
            <value>
                <fullName>UGFA</fullName>
            </value>
            <value>
                <fullName>UGLA</fullName>
            </value>
            <value>
                <fullName>UGLS</fullName>
            </value>
            <value>
                <fullName>UGNH</fullName>
            </value>
            <value>
                <fullName>UGNU</fullName>
            </value>
            <value>
                <fullName>UGPP</fullName>
            </value>
            <value>
                <fullName>UGSU</fullName>
            </value>
            <value>
                <fullName>UGTE</fullName>
            </value>
            <value>
                <fullName>UGHI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource_Name__c.field-meta.xml
<CustomField>
    <fullName>Resource_Name__c</fullName>
    <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
    <label>Resource Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Success_Pod__c.field-meta.xml
<CustomField>
    <fullName>Success_Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child object to Success Pod</description>
    <label>Success Pod</label>
    <referenceTo>Success_Pod__c</referenceTo>
    <relationshipLabel>Success Resources</relationshipLabel>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Student__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Program_Code__c.field-meta.xml
<CustomField>
    <fullName>Program_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to Program, used for assign students to Coaches</description>
    <label>Program Code</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Pod__c.field-meta.xml
<CustomField>
    <fullName>Success_Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This determines which Advisors are assigned to this student.</description>
    <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
    <label>Success Pod</label>
    <referenceTo>Success_Pod__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Resource__c.field-meta.xml
<CustomField>
    <fullName>Success_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>links the Success Student to their Assigned Success Resource</description>
    <label>Success Resource</label>
    <referenceTo>Success_Resource__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <description>Denotes if the Student is a non-Coaching Student.</description>
    <label>Advisor</label>
</RecordType>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/AdvisorPortalMainPageController.cls
public class AdvisorPortalMainPageController {
    public AdvisorPortalMainPageController() {}
    
    /*
     * The ID privded by the view as component
     * 
     * <p>
     * If the ID is null (Page load) use the current Users Id.
     * </p>
     */
    public Id ownerId {
        get {
            if (ownerId == null) {
                ownerId = UserInfo.getUserId();
            }
            
            return ownerId;
        }
        
        set;
    }
    
    /*
     * A list of selectOptions that the currently logged in user
     * has the permission to view as.
     * 
     * <p>
     * Contains the Id of the owner of the cases mapped to a display name (user or pod)
     * </p>
     */
    public List<selectOption> viewAsOptions {
        get {
            if (viewAsOptions == null) {
                viewAsOptions = new List<selectOption>();
                
                // Insert myself
                viewAsOptions.add(new selectOption(UserInfo.getUserId(), UserInfo.getName()));
                
				// Insert My Comittees
                if (myCommittees.size() > 0) {
                    viewAsOptions.add(new selectOption('', '', true));
                    viewAsOptions.add(new selectOption('', '--My Committees--', true));
                    
                	for (Id i : myCommittees.keySet()) {
                        viewAsOptions.add(new selectOption(i, myCommittees.get(i)));
                    }
            	}
                
				// Insert The committees for which I am a manager
                if (mySubordinateCommittees.size() > 0) {
                    viewAsOptions.add(new selectOption('', '', true));
                    viewAsOptions.add(new selectOption('', '--College Committees--', true));
                    
                    for (Id i : mySubordinateCommittees.keySet()) {
                        viewAsOptions.add(new selectOption(i, mySubordinateCommittees.get(i)));
                    }
                }
                
				// Insert all of the users for all of the comittees for which I am a manager
                if (mySubordinates.size() > 0) {
                    viewAsOptions.add(new selectOption('', '', true));
                    viewAsOptions.add(new selectOption('', '--College Advisors--', true));
                    
                    for (Id i : mySubordinates.keySet()) {
                        viewAsOptions.add(new selectOption(i, mySubordinates.get(i)));
                    }
                }
            }
            
            return viewAsOptions;
        }
        
        set;
    }
    
    /*
     * List of My Committees
     */
    public Map<Id, String> myCommittees {
        get {
            String committeeDisplayName; // The display name for the view as and transfer lists
            
            if (myCommittees == null) {
                Set<Id> myPodIds = new Set<Id>();
            	myCommittees = new Map<Id, String>();
                
                system.debug('myResources: ' + string.valueOf(myResources));
                
                for (Success_Resource__c sr : myResources) {
                    myPodIds.add(sr.Success_Pod__c);
                }
                
                for (Success_Pod__c sp : [SELECT Name, OwnerId, Committee__c
                    FROM Success_Pod__c
                    WHERE Id IN :myPodIds
                    ORDER BY Name ASC]) {
                    committeeDisplayName = sp.Name;
                    
                    if (sp.Committee__c != null && sp.Committee__c != '') {
                        committeeDisplayName = committeeDisplayName + ' - ' + sp.Committee__c;
                    }
                        
                    myCommittees.put(sp.OwnerId, committeeDisplayName);
                }
            }
            
            return myCommittees;
        }
        
        set;
    }
    
    /*
     * List of the committees for which I am a manager/admin
     */
    private Map<Id, String> mySubordinateCommittees {
        get {
            String committeeDisplayName;
            
            if (mySubordinateCommittees == null) {
                mySubordinateCommittees = new Map<Id, String>();
                
                for (Success_Pod__c sp : mySubordinatePods) {
                    committeeDisplayName = sp.Name;
                    
                    if (sp.Committee__c != '' && sp.Committee__c != null) {
                    	committeeDisplayName = committeeDisplayName + ' - ' + sp.Committee__c;
                    }
                    
                    mySubordinateCommittees.put(sp.OwnerId, committeeDisplayName);
                }
            }
            
            return mySubordinateCommittees;
        }
        
        set;
    }
    
    /*
     * List of my subordinate pods. To be converted into comittees and resources.
     */
    private List<Success_Pod__c> mySubordinatePods {
        get {
            if (mySubordinatePods == null) {
                mySubordinatePods = new List<Success_Pod__c>();
                
                if (myAdminProgramCodes.size() > 0) {
                    String query = ''; // The completed query
                    String queryFront = 'SELECT OwnerId, Name, Committee__c ' +
                        'FROM Success_Pod__c ' +
                        'WHERE Program__c INCLUDES ('; // The beginning of the query
                    String queryBack = ') ORDER BY Name ASC'; // The end of the query
                    
                    query = queryFront;
                    
                    for (String s : myAdminProgramCodes) {
                        query += '\'' + s + '\',';
                    }
                    
                    query = query.left(query.length()-1);
                    
                    query += queryBack;
                    
                    for (Success_Pod__c sp : database.query(query)) {
                        mySubordinatePods.add(sp);
                    }
                }
            }
            
            return mySubordinatePods;
        }
        
        set;
    }
    
    /*
     * List of my subordinates
     */
    private Map<Id, String> mySubordinates {
        get {
            String subordinateDisplayName;
            
            if (mySubordinates == null) {
                Set<Id> podIds = new Set<Id>();
                mySubordinates = new Map<Id, String>();
                
                for (Success_Pod__c sp : mySubordinatePods) {
                    podIds.add(sp.Id);
                }
                
                for (Success_Resource__c sr : [SELECT Resource__c, Resource_Name__c, Resource__r.Alias
                    FROM Success_Resource__c
                    WHERE Success_Pod__c IN :podIds
                    ORDER BY Resource_Name__c ASC]) {
                    subordinateDisplayName = sr.Resource_Name__c;
                        
                    if (sr.Resource__r.Alias != null && sr.Resource__r.Alias != '') {
                        subordinateDisplayName = subordinateDisplayName + ' - ' + sr.Resource__r.Alias;
                    }
                    mySubordinates.put(sr.Resource__c, subordinateDisplayName);
                }
            }
            
            return mySubordinates;
        }
        
        set;
    }
    
    /*
     * List of my resources
     */
    private List<Success_Resource__c> myResources {
        get {
            if (myResources == null) {
                myResources = [SELECT Success_Pod__c, Success_Pod__r.OwnerId, Program_Code__c, Role__c 
                	FROM Success_Resource__c
                	WHERE Resource__c = :UserInfo.getUserId()
                	AND IsActive__c = true
                	AND RecordTypeId = :AdvisorResourceRTID];
            }
            
            return myResources;
        }
        
        set;
    }
    
    /*
     * Generates a list of all program codes that the user is an admin/manager for
     */
    private List<String> myAdminProgramCodes {
        get {
            if (myAdminProgramCodes == null) {
                string tempCode; // temporarily stores program code field for splitting
                
                myAdminProgramCodes = new List<String>();
                
                for (Success_Resource__c sr : myResources) {
                    if (sr.Role__c == 'Admin' || sr.Role__c == 'Manager') {
                        tempCode = sr.Program_Code__c;
                        
                        for (String s : tempCode.split(';')) {
                            myAdminProgramCodes.add(s);
                        }
                    }
                }
            }
            
            return myAdminProgramCodes;
        }
        
        set;
    }
    
    private Id AdvisorResourceRTID {
        get {
            if (AdvisorResourceRTID == null) {
                AdvisorResourceRTID = [SELECT Id
                    FROM RecordType
                    WHERE SObjectType = 'Success_Resource__c'
                    AND Name = 'Advisor' LIMIT 1].Id;
            }
            
            return AdvisorResourceRTID;
        }
        
        set;
    }
    
    public Id AdvisorProactiveCaseRTID {
        get {
            if (AdvisorProactiveCaseRTID == null) {
                AdvisorProactiveCaseRTID = RTIDHelper.getRTID('Case', 'ASU Advisor Outreach');
            }
            
            return AdvisorProactiveCaseRTID;
        }
        
        set;
    }
    
    public Id advisorEmailRTID {
        get {
            if (advisorEmailRTID == null) {
                advisorEmailRTID = RTIDHelper.getRTID('Portal_Email__c', 'Advisor');
            }
            
            return advisorEmailRTID;
        }
        
        set;
    }
    
    public Id AdvisorReactiveCaseRTID {
        get {
            if (AdvisorReactiveCaseRTID == null) {
                AdvisorReactiveCaseRTID = RTIDHelper.getRTID('Case', 'ASU Service');
            }
            
            return AdvisorReactiveCaseRTID;
        }
        
        set;
    }
    /*
     * The query used to retrieve all proactive cases for the current resource.
     */
    public String myProactiveQuery {
        get {
            if (ownerId != null) {
                myProactiveQuery = 'SELECT CaseNumber, ContactId, Contact.Name, Contact.FirstName, Contact.LastName, Contact.EMPLID__c, Contact.Email, Subject, Description, Status, FollowUp_Date__c ' +
                    'FROM Case ' +
                    'WHERE OwnerId = \'' + ownerId + '\' ' +
                    'AND recordTypeId = \'' + AdvisorProactiveCaseRTID + '\' ' +
                    'AND isClosed = false';
            }
            
            return myProactiveQuery;
        }
        
        set;
    }
    
    /*
     * The query used to retrieve the watchlistCases for the current resource
     */
    public String myWatchlistQuery {
        get {
            if (ownerId != null) {
                myWatchlistQuery = 'SELECT CaseNumber, ContactId, Contact.Name, Contact.FirstName, Contact.LastName, Contact.EMPLID__c, Contact.Email, Subject, Description, Status, FollowUp_Date__c ' +
                    'FROM Case ' +
                    'WHERE OwnerId = \'' + ownerId + '\' ' +
                    'AND recordTypeId = \'' + AdvisorProactiveCaseRTID + '\' ' +
                    'AND Category__c = \'Watchlist\'' +
                    'AND isClosed = false';
            }
            
            return myWatchlistQuery;
        }
        
        set;
    }
    
    /*
     * The query used to retrieve the students for the active resource
     */
    public String myStudentsQuery {
        get {
            if (ownerId != null) {
                myStudentsQuery = 'SELECT Student_Name__c, EMPLID__c, Student__c, Student__r.FirstName, Student__r.LastName ' +
                    'FROM Success_Student__c ' +
                    'WHERE Success_Pod__r.OwnerId = \'' + ownerId + '\' ' +
                        'AND Is_Active__c = true';
            }
            
            return myStudentsQuery;
        }
        
        set;
    }
    
    /*
     * The query used to generate the summary list for the current resource
     */
    public string mySummaryListQuery {
        get {
            if (ownerId != null) {
                mySummaryListQuery = 'SELECT count(Id) total, Subject, Followup_Date__c ' +
                    'FROM Case ' +
                    'WHERE OwnerId = \'' + ownerId + '\' ' +
                    'AND Category__c != \'Watchlist\'' +
                    'AND recordTypeId = \'' + AdvisorProactiveCaseRTID + '\' ' +
                    'AND IsClosed = false ' +
                    'GROUP BY Subject, Followup_Date__c ' +
                    'ORDER BY Followup_Date__c ASC NULLS LAST';
            }
            
            return mySummaryListQuery;
        }
        
        set;
    }
    
    /*
     * Whether or not the currently logged in user has the permission to change
     * who they are viewing as.
     */
    public boolean hasViewAs {
        get {
            // Has view as if the list of select options is greater than 1 (should always have
            // the current user).
            return viewAsOptions.size() > 1 ? true : false;
        }
        
        set;
    }
}