src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>[Manual or Automated] - Examples include: 098-T, Collections, Counselor, Customer Services, Document Processing, Graduate Applicant Services, Graduation, International, Late Fee Appeals, Loan Research, Non-Degree, Office Specialist, Online Student, Other</description>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1098-T</fullName>
            </value>
            <value>
                <fullName>Academic Inquiries</fullName>
            </value>
            <value>
                <fullName>Academic Records</fullName>
            </value>
            <value>
                <fullName>Academic Services</fullName>
            </value>
            <value>
                <fullName>Academic Services - Training</fullName>
            </value>
            <value>
                <fullName>Academic Status Reports</fullName>
            </value>
            <value>
                <fullName>Academic Success Operations</fullName>
            </value>
            <value>
                <fullName>Academic Support</fullName>
            </value>
            <value>
                <fullName>Access</fullName>
            </value>
            <value>
                <fullName>Accountancy</fullName>
            </value>
            <value>
                <fullName>Ad Hoc</fullName>
            </value>
            <value>
                <fullName>Admissions</fullName>
            </value>
            <value>
                <fullName>Admissions (Help Desk)</fullName>
            </value>
            <value>
                <fullName>Admission Services Business Intelligence</fullName>
            </value>
            <value>
                <fullName>Admission Services - General</fullName>
            </value>
            <value>
                <fullName>Admission Services OPS</fullName>
            </value>
            <value>
                <fullName>Admissions Inquiries</fullName>
            </value>
            <value>
                <fullName>Advising</fullName>
            </value>
            <value>
                <fullName>Advising (Help Desk)</fullName>
            </value>
            <value>
                <fullName>Advising - GOEE</fullName>
            </value>
            <value>
                <fullName>Agreements and Contracts</fullName>
            </value>
            <value>
                <fullName>Agribusiness</fullName>
            </value>
            <value>
                <fullName>Airport Arrivals</fullName>
            </value>
            <value>
                <fullName>AISSS Appointments</fullName>
            </value>
            <value>
                <fullName>Alternate Modes</fullName>
            </value>
            <value>
                <fullName>Alumni</fullName>
            </value>
            <value>
                <fullName>Alumni Success</fullName>
            </value>
            <value>
                <fullName>Applicant Services - Graduate</fullName>
            </value>
            <value>
                <fullName>Applicant Services - Undergraduate</fullName>
            </value>
            <value>
                <fullName>Appointments</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/Followup_Date__c.field-meta.xml
<CustomField>
    <fullName>Followup_Date__c</fullName>
    <description>[DW: sfe_case]</description>
    <label>Followup Date</label>
    <type>Date</type>
</CustomField>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SummaryListController.cls
public class SummaryListController {
    public Id proactiveCaseRTID {get; set;} // Stores the ID of the case record type to be summarized
    public String query {get; set;} // Stores the aggregate query that is used to generate the list
    public String Subject {get;set;} // Stores the subject to filter by in the dynamic query
    public String followupDate {get;set;} // Stores the followupDate to filter by in the dynamic query
    private String oldQuery; // Stores the query after generating a list to track if query changes
    public boolean excludeFollowUpDate {get; set;} // Determine if the followup date should be included in the dynamic query

    /*
     * Run query to generate results
     */
    public List<AggregateResult> summaryResult {
        get {
            oldQuery = query; // Store new query
            
            summaryResult = Database.query(query);
            
            return summaryResult;
        }
        
        set;
    }
    
    /*
     * Get the OwnerId from the provided query.
     * 
     * <p>
     * Note, we always convert to the 15 digit Id for simplicity of the algorithm
     * </p>
     */
    public Id ownerId {
        get{
            String temp = query; // Used to store query for processing
            integer loc; // Stores the index at which the owner id appears in the query

            // Strip all spaces from query
            temp = temp.replaceAll('\\s+', '');
            //temp = temp.toLowerCase();
            
            // Locate OwnerId=
            loc = temp.indexOf('OwnerId=') + 9;
            
            // Grab next 15 characters
            temp = temp.substring(loc, loc + 15);

            ownerId = temp;
            
            return ownerId;
        }
        
        set;
    }
    
    /*
     * Stores the dynmically generated query to be displayed in the modal list
     * SELECT CaseNumber, ContactId, Contact.Name, Contact.EMPLID__c, Subject, Description, Status, FollowUp_Date__c FROM Case WHERE OwnerId = :ownerId && Followup_Date__c = :followupDate && subject = :subject
     */
    public String dynamicQuery {
        get {
            // Need to figure out why this is being called 3 times per action.

            dynamicQuery = '' +
                'SELECT CaseNumber, ContactId, Contact.Name, Contact.FirstName, Contact.LastName, Contact.EMPLID__c, Contact.Email, ' +
                    'Subject, Description, Status, FollowUp_Date__c ' +
                'FROM Case ' +
                'WHERE OwnerId = \'' + ownerId + '\' ' +
                'AND subject =  \'' + subject + '\' ' +
                'AND Category__c != \'Watchlist\' ' +
                'AND RecordTypeId = \'' + proactiveCaseRTID + '\' ' +
                'AND IsClosed = false';

            if (!excludeFollowUpDate) {
                if (followUpDate != null && followUpDate != '') {
                    dynamicQuery = dynamicQuery + ' AND Followup_Date__c = ' + followUpDate;
                } else {
                    dynamicQuery = dynamicQuery + ' AND Followup_Date__c = null';
                }
            }
            
            return dynamicQuery;
        }
        
        set;
    }
}