src/objects/Case.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><sharingModel>ReadWriteTransfer</sharingModel></CustomObject>

force-app/main/default/objects/Case/fields/Origin__c.field-meta.xml
<CustomField>
    <fullName>Origin__c</fullName>
    <description>[Manual, Automated] -  Where was this Case initiated? Dependent on Functional Group.  Examples include; Advising Community, BBSS, Email, Incoming Call, In Person, My ASU, Orientation, Outgoing Call, Web
[DW: sfe_case]</description>
    <inlineHelpText>Where was this Case initiated?</inlineHelpText>
    <label>Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Advising Community</fullName>
            </value>
            <value>
                <fullName>Alteryx</fullName>
            </value>
            <value>
                <fullName>Alteryx - Financial Intake</fullName>
            </value>
            <value>
                <fullName>Automated</fullName>
            </value>
            <value>
                <fullName>BBSS</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>Chatbot</fullName>
            </value>
            <value>
                <fullName>Clone</fullName>
            </value>
            <value>
                <fullName>Coach Initiated</fullName>
            </value>
            <value>
                <fullName>EdPlus Salesforce</fullName>
            </value>
            <value>
                <fullName>Email</fullName>
                <default>true</default>
                <label>Email</label>
            </value>
            <value>
                <fullName>Error Logger</fullName>
            </value>
            <value>
                <fullName>Escalation</fullName>
            </value>
            <value>
                <fullName>Fax</fullName>
            </value>
            <value>
                <fullName>FC DPC</fullName>
            </value>
            <value>
                <fullName>FC LOSAN</fullName>
            </value>
            <value>
                <fullName>FC Poly</fullName>
            </value>
            <value>
                <fullName>FC Tempe</fullName>
            </value>
            <value>
                <fullName>FC Virtual</fullName>
            </value>
            <value>
                <fullName>FC West</fullName>
            </value>
            <value>
                <fullName>Financial Intake</fullName>
            </value>
            <value>
                <fullName>Handshake</fullName>
            </value>
            <value>
                <fullName>Help Desk</fullName>
            </value>
            <value>
                <fullName>Incoming Call</fullName>
            </value>
            <value>
                <fullName>In Person</fullName>
            </value>
            <value>
                <fullName>My ASU</fullName>
            </value>
            <value>
                <fullName>Orientation</fullName>
            </value>
            <value>
                <fullName>Outgoing Call</fullName>
            </value>
            <value>
                <fullName>Outreach</fullName>
            </value>
            <value>
                <fullName>Qualtrics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

src/objects/Portal_Email__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Additional_Message_Text__c</fullName>
        <label>Additional Message Text</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Most_Recent_Queue__c</fullName>
        <description>The queue the case was most recently assigned to.</description>
        <formula>Case__r.Most_Recent_Queue__c</formula>
        <inlineHelpText>Used to determine which queue to send at if the primary ownerId is a userId.</inlineHelpText>
        <label>Case Most Recent Queue</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Case_Thread_Id__c</fullName>
        <formula>Case__r.Thread_Id__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Thread Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Message_Id__c</fullName>
        <label>Email Message Id</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Email_Template_Name__c</fullName>
        <label>Email Template Name</label>
        <picklist>
            <picklistValues>
                <fullName>Advisor Ad-hoc template</fullName>
                <default>true</default>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>From_Address__c</fullName>
        <description>The email address that is sending the email.</description>
        <label>From Address</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Owner_Id__c</fullName>
        <description>Displays the OwnerId to be used in determining the desired from address.</description>
        <formula>IF(
 ISBLANK( Case_Owner_Id__c ),
 Student_Owner_Id__c,
 Case_Owner_Id__c
)</formula>
        <label>Primary Owner Id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Record_id__c</fullName>
        <formula>Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record id</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Processing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Held/Undeliverable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Duplicate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Subscriber Status: Bounced/Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salesforce Email Opt Out</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Success Student</label>
        <referenceTo>Success_Student__c</referenceTo>
        <relationshipLabel>Portal Emails</relationshipLabel>
        <relationshipName>Portal_Emails</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Portal Emails</relationshipLabel>
        <relationshipName>Portal_Emails</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Object containing all of the information required to send emails from within the portal through the marketing cloud integration.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Portal Email</label><nameField>
        <displayFormat>PE-{0000000000}</displayFormat>
        <label>Portal Email Number</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Portal Emails</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_with_Details</fullName>
        <columns>NAME</columns>
        <columns>CREATED_DATE</columns>
        <columns>RECORDTYPE</columns>
        <columns>Status__c</columns>
        <columns>Contact__c</columns>
        <columns>Email_Template_Name__c</columns>
        <columns>From_Name__c</columns>
        <columns>From_Address__c</columns>
        <filterScope>Everything</filterScope>
        <label>All with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Test_Messages</fullName>
        <booleanFilter>1</booleanFilter>
        <columns>CREATED_DATE</columns>
        <columns>NAME</columns>
        <columns>Status__c</columns>
        <columns>From_Address__c</columns>
        <columns>From_Name__c</columns>
        <columns>Contact__c</columns>
        <columns>Contact_Email__c</columns>
        <columns>Case_Number__c</columns>
        <columns>Case_Owner_Id__c</columns>
        <columns>Contact_First_Name__c</columns>
        <columns>Created_By_Full_Name__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Contact__c</field>
            <operation>equals</operation>
            <value>Dawn Scott</value>
        </filters>
        <label>Test Messages</label>
    </listViews><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
    </recordTypes></CustomObject>

force-app/main/default/objects/Portal_Email__c/fields/Additional_Message_Text__c.field-meta.xml
<CustomField>
    <fullName>Additional_Message_Text__c</fullName>
    <label>Additional Message Text</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Case_Most_Recent_Queue__c.field-meta.xml
<CustomField>
    <fullName>Case_Most_Recent_Queue__c</fullName>
    <description>The queue the case was most recently assigned to.</description>
    <formula>Case__r.Most_Recent_Queue__c</formula>
    <inlineHelpText>Used to determine which queue to send at if the primary ownerId is a userId.</inlineHelpText>
    <label>Case Most Recent Queue</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/From_Address__c.field-meta.xml
<CustomField>
    <fullName>From_Address__c</fullName>
    <description>The email address that is sending the email.</description>
    <label>From Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Primary_Owner_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Owner_Id__c</fullName>
    <description>Displays the OwnerId to be used in determining the desired from address.</description>
    <formula>IF(
 ISBLANK( Case_Owner_Id__c ),
 Student_Owner_Id__c,
 Case_Owner_Id__c
)</formula>
    <label>Primary Owner Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/fields/Success_Student__c.field-meta.xml
<CustomField>
    <fullName>Success_Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Success Student</label>
    <referenceTo>Success_Student__c</referenceTo>
    <relationshipLabel>Portal Emails</relationshipLabel>
    <relationshipName>Portal_Emails</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Email__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <label>Advisor</label>
</RecordType>

force-app/main/default/objects/Portal_Email__c/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <label>Coach</label>
</RecordType>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <description>Denotes if the Student is a non-Coaching Student.</description>
    <label>Advisor</label>
</RecordType>

force-app/main/default/objects/Success_Student__c/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <description>Used to denote if the student is a Coaching Student for Ed Plus Success Coaches.</description>
    <label>Coach</label>
</RecordType>

src/classes/Test_PortalEmailService.cls
@isTest
public class Test_PortalEmailService {
    static Id advisorRTID = IDHelper.getRTID('Portal_Email__c', 'Advisor');
    static Id coachRTID = IDHelper.getRTID('Portal_Email__c', 'Coach');
    
    @testSetup
    public static void testSetup() {
        TestDataFactory.makeMeAnAdvisorUser(3, 3, 3);
        
        List<Portal_Email__c> emailsToInsert = new List<Portal_Email__c>();
        List<Case> caseList = [Select Id FROM Case];
        List<Success_Student__c> studentList = [Select Id FROM Success_Student__c];
        
        for(Integer i = 0; i < 10; i++){
            Portal_Email__c tmp = new Portal_Email__c();
            tmp.Additional_Message_Text__c = 'Hello World';
            if(Math.mod(i, 2) == 0){
                tmp.Success_Student__c = studentList[0].Id;
            }
            if(Math.mod(i, 3) == 0){
                tmp.RecordTypeId = coachRTID;
            }
            else{
            	tmp.RecordTypeId = advisorRTID;
            }
            tmp.From_Address__c = 'abc123@test.com';
            tmp.Case__c = caseList[0].Id;
            
            emailsToInsert.add(tmp);
        }
        
        insert emailsToInsert;
        
    }
    
    public static testmethod void testSetFromAddressAdvsior(){
         
        Map<Id, Portal_Email__c> emailsToUpdate = new Map<Id, Portal_Email__c>();
        Test.startTest();
        List<Portal_Email__c> emailList = [Select Primary_Owner_Id__c, Case_Most_Recent_Queue__c, RecordTypeId, From_Address__c, Success_Student__c 
                                           FROM Portal_Email__c
                                           WHERE RecordTypeId =: advisorRTID];
        for(Portal_Email__c pe : emailList){
            emailsToUpdate.put(pe.Id, pe);
        }
        PortalEmailService pes = new PortalEmailService();
        PortalEmailService.setFromAddress(emailsToUpdate);
        emailList = [Select From_Address__c, Primary_Owner_Id__c 
                     FROM Portal_Email__C 
                     WHERE RecordTypeId =: advisorRTID AND Success_Student__c = NULL];
        List<EmailMessage> newMessages = [Select Id FROM EmailMessage];
        System.assertEquals(newMessages.size(), 10);
        Test.stopTest();      
    }
    
    public static testmethod void testSetFromAddressCoach(){
        Map<Id, Portal_Email__c> emailsToUpdate = new Map<Id, Portal_Email__c>();
        Test.startTest();
        List<Portal_Email__c> emailList = [Select Primary_Owner_Id__c, Case_Most_Recent_Queue__c, RecordTypeId, From_Address__c, Success_Student__c 
                                           FROM Portal_Email__c
                                           WHERE RecordTypeId =: coachRTID];
        for(Portal_Email__c pe : emailList){
            emailsToUpdate.put(pe.Id, pe);
        }
        
        PortalEmailService pes = new PortalEmailService();
        PortalEmailService.setFromAddress(emailsToUpdate);
        emailList = [Select From_Address__c, Primary_Owner_Id__c 
                     FROM Portal_Email__C 
                     WHERE RecordTypeId =: coachRTID AND Success_Student__c = NULL];
        List<EmailMessage> newMessages = [Select Id FROM EmailMessage];
        System.assertEquals(newMessages.size(), 10);
        Test.stopTest();
    }
    
    /**
     * Tests Coach Emailing for NULL Input
     */
    public static testmethod void testNullCoach(){
        Test.startTest();
      	  PortalEmailService.enqueueCoach(NULL);
        Test.stopTest();
        
        List<Case> errorList = [SELECT Id FROM Case WHERE Origin__c = 'Error Logger'];    
        System.assertEquals(1, errorList.size());
        delete errorList;  
    }
    /**
     * Tests Advisor Emailing for NULL Input
     */ 
    public static testmethod void testNullAdvisor(){

        Test.startTest();
      	  PortalEmailService.enqueueAdvisor(NULL);
        Test.stopTest();
        
        List<Case> errorList = [SELECT Id FROM Case WHERE Origin__c = 'Error Logger'];    
        System.assertEquals(1, errorList.size());
        delete errorList;  
    }
    
}