src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/asu_user_type__c.field-meta.xml
<CustomField>
    <fullName>asu_user_type__c</fullName>
    <description>Referenced in the Search User VF page and within the test code testNoSOSLResults and testUListResults</description>
    <label>(DO NOT USE) ASU User Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>App ID</fullName>
            </value>
            <value>
                <fullName>Duplicate</fullName>
            </value>
            <value>
                <fullName>Knowledge</fullName>
            </value>
            <value>
                <fullName>Knowledge/Marketing</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Service/Knowledge</fullName>
            </value>
            <value>
                <fullName>User</fullName>
                <default>true</default>
                <label>User</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/Test_SearchUsers.cls
@isTest
private class Test_SearchUsers
{
    @testSetup static void setUp()
    {
        Profile p = [
            SELECT Id
            FROM Profile
            WHERE Name = 'System Administrator'
            LIMIT 1
        ];

        User testUser = UserService.createTestUser();
        testUser.FederationIdentifier = 'test@admin.asu.edu';
        testUser.ProfileId = p.Id;
        insert testUser;
    }

    @isTest static void testUListResults()
    {
        User testUser = [
            SELECT Id, FirstName, LastName, Profile.Name, Contact.Name, ContactId,
                Contact.ASURite_Id__c, EmplId__c, contact.EMPLID__c, Alias,
                FederationIdentifier, ASU_User_Type__c, IsActive
            FROM User
            WHERE FederationIdentifier = 'test@admin.asu.edu'
            LIMIT 1
        ];

        PageReference searchUsers = Page.searchUsers;
        Test.setCurrentPage(searchUsers);

        Id[] fixedSearchResults = new Id[1];
        fixedSearchResults[0] = testUser.Id;
        Test.setFixedSearchResults(fixedSearchResults);

        Test.startTest();

        SearchUsers su = new SearchUsers();
        su.hideCommunity = true;
        su.searchString = 'test';
        su.search();

        Test.stopTest();

        System.assert(su.uList.size() == 1);
    }

    @isTest static void testPageSearchError()
    {
        Test.startTest();

        SearchUsers su = new SearchUsers();
        su.hideCommunity = true;
        su.searchString = 't';
        su.search();

        Test.stopTest();

        List<Apexpages.Message> msgs = ApexPages.getMessages();
        Boolean errorPresent = false;

        for (Apexpages.Message msg : msgs)
        {
            if (msg.getDetail().contains('You must enter at least 2 search characters'))
            {
                errorPresent = true;
            }
        }

        System.assert(errorPresent);
    }

    @isTest static void testNoSOSLResults()
    {
        Test.startTest();

        SearchUsers su = new SearchUsers();
        su.searchString = 'test';
        su.search();

        Test.stopTest();

        System.assert(su.uList.size() == 0);
    }
}