src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Convert_Perform_Conversion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - If Checked, this Lead will be converted to a Contact record.</description>
        <inlineHelpText>If Checked, this Lead will be converted to a Contact record.</inlineHelpText>
        <label>Convert Lead: Perform Conversion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[import] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <inlineHelpText>Please enter the student's ID number.</inlineHelpText>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Last_Institution_Attended__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[import] - Last institution the Lead has attended. The institution can be a high school or a college.</description>
        <label>Last Institution Attended</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Lead_Account_Institution</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Campus_Community</businessOwnerGroup>
    <complianceGroup>FERPA</complianceGroup>
    <description>Lookup to the EMPLID in the Contact Object
[Peoplesoft] - PeopleSoft unique ID
[MDM] - Read/Write - Critical to MDM
[DW: sfe_contact]</description>
    <formula>Contact__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>EMPLID</inlineHelpText>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/Test_LeadConversion.cls
@isTest
public class Test_LeadConversion
{
	static final Integer MAX_LEAD = 200;  // The number of leads to convert at once
	static final Integer QUERY_LIMIT_THRESHOLD = 85;  // The number of acceptable queries to run during lead conversion
	
	@testSetup
	static void setup()
	{
		List<Contact> contactData = ContactService.createMultipleTestContacts(MAX_LEAD);
		insert contactData;

		Set<Id> contactIds = new Set<Id>();
		for (Contact c : contactData)
		{
			contactIds.add(c.Id);
		}

		String queryContacts = 'SELECT AccountId, FirstName, LastName, EMPLID__c FROM Contact WHERE Id IN :contactIds';
		contactData = Database.query(queryContacts);

		List<Opportunity> opportunityData = OpportunityService.createTestOpportunities(contactData);
		insert opportunityData;

		Account institution = new Account();
		institution.Name = 'Univesity of Arizona';
		institution.Type = 'HS';

		insert institution;

		List<Lead> leadData = LeadService.createTestLeadsToConvertByEMPLID(contactData);
		insert leadData;
	}

	/**
	 * Tests the maximum number of leads that can be coverted at one time.
	 */
	@isTest
	static void leadConversionLoadTest()
	{
		Integer soqlQueries;

		List<Lead> leadsToConvert = [SELECT Id FROM Lead LIMIT :MAX_LEAD];
		Account institution = [SELECT Id FROM Account WHERE Type = 'HS'];

		for (Lead singleLead : leadsToConvert)
		{
			singleLead.Last_Institution_Attended__c = institution.Id;
			singleLead.Convert_Perform_Conversion__c = true;
		}
		
		test.StartTest();

		update leadsToConvert;
		soqlQueries = Limits.getQueries();
			
		test.StopTest();

		// Acceptable query threshold is less than 85% of the maximum query limit
		System.assert(soqlQueries < QUERY_LIMIT_THRESHOLD, 'Exceeded the acceptable SOQL query limit during conversion of ' + MAX_LEAD + ' leads: ' + soqlQueries);

	}
}