src/objects/Contact_Upload__c.object
<CustomObject>
    <description>Contains records representing a batch of Contacts to be added to Marketing Subscriptions</description>
    <label>Contact Upload</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Contact Upload  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Upload_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Upload__c</fullName>
        <label>Contact Upload</label>
        <referenceTo>Contact_Upload__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <label>EMPLID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <description>This is the record-level detail of a contact upload file. It's used to search for contact (create if not found), then add them to a subscription used by the Subscription Center and Marketing Cloud email sends.</description>
    <label>Contact Upload Detail</label>
    <nameField>
        <displayFormat>CUD-{0000000}</displayFormat>
        <label>Contact Upload Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Upload Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ContactUploadDetailFactory.cls
@isTest
public class ContactUploadDetailFactory {

    public class DefaultContactUploadDetail extends TestFactory {
        public DefaultContactUploadDetail(Contact_Upload__c connectedUpload) {
            super(new Contact_Upload_Detail__c(
                Contact_Upload__c = connectedUpload.Id
            ));
        }
    }
    
    public class ContactUploadDetailWithEMPLID extends TestFactory {
        public ContactUploadDetailWithEMPLID(Contact_Upload__c connectedUpload) {
            super(new Contact_Upload_Detail__c(
                Contact_Upload__c = connectedUpload.Id,
                EMPLID__c = '100000000'
            ));
            this.addToFieldsToIncrement('EMPLID__c');
        }
    }
}