src/objects/Contact_Upload__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Complete with Errors</fullName>
                </value>
                <value>
                    <fullName>Complete with No Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains records representing a batch of Contacts to be added to Marketing Subscriptions</description>
    <label>Contact Upload</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Contact Upload  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Upload_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Upload__c</fullName>
        <label>Contact Upload</label>
        <referenceTo>Contact_Upload__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <label>EMPLID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the record-level detail of a contact upload file. It's used to search for contact (create if not found), then add them to a subscription used by the Subscription Center and Marketing Cloud email sends.</description>
    <label>Contact Upload Detail</label>
    <nameField>
        <displayFormat>CUD-{0000000}</displayFormat>
        <label>Contact Upload Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Upload Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Subscriber_Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Makes this record and associated Contact or Lead Subscriber records only visible to the Users that are members of the Queue listed as this Subscription's Owner. Note that the Subscriber record must be owned by a Queue in order to check this box.</inlineHelpText>
        <label>Subscriber Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/ContactMatcherBatchTest.cls
@isTest
public class ContactMatcherBatchTest {
    @isTest
    static void testContactMatcherBatch() {
        Subscription__c sub = new Subscription__c(
            Name = 'Test',
            Subscriber_Private_in_Salesforce__c = false
        );
        insert sub;

        Contact_Upload__c upload = new Contact_Upload__c();
        upload.Description__c = 'Test Description';
        
        insert upload;

        String csvData = 'First_Name__c,Last_Name__c,Email__c,EMPLID__c\nJohn,Doe,john.doe@example.com,12345';

        ContentVersion version = new ContentVersion(
            Title = 'ContactUploadCSV',
            PathOnClient = 'ContactUpload.csv',
            VersionData = Blob.valueOf(csvData),
            IsMajorVersion = true
        );
        insert version;

        ContentVersion insertedVersion = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id = :version.Id];

        ContentDocumentLink cdl = new ContentDocumentLink(
            ContentDocumentId = insertedVersion.ContentDocumentId,
            LinkedEntityId = upload.Id,
            ShareType = 'V',
            Visibility = 'AllUsers'
        );
        insert cdl;

        Test.startTest();
        ContactMatcherBatch batch = new ContactMatcherBatch(insertedVersion.Id, sub.Id,upload.Id);
        Database.executeBatch(batch, 1);
        Test.stopTest();

        List<Contact_Upload_Detail__c> details = [SELECT Id, Email__c, Status__c FROM Contact_Upload_Detail__c 
                                                  WHERE Contact_Upload__c = :upload.Id];
        
        upload = [SELECT Status__c FROM Contact_Upload__c WHERE Id = :upload.Id];
        System.assert(upload.Status__c.contains('Complete'), 'Upload status should be marked Complete');
    }
}