src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>CAP_Possible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Peoplesoft] - Checkbox that Indicates possible CAP student</description>
        <inlineHelpText>Indicates possible CAP student</inlineHelpText>
        <label>CAP Possible</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Student_Group__c.object
<CustomObject><fields>
        <fullName>SG_PeopleSoft_Code__c</fullName>
        <description>[Peoplesoft] - Peoplesoft code</description>
        <label>PeopleSoft Code</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields>
        <fullName>SG_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Peoplesoft] - Checkbox that shows if the student group is active</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Student Group information from PeopleSoft</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ControlledByParent</externalSharingModel><label>Student Group</label><nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Student Group Label</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Groups</pluralLabel><sharingModel>ControlledByParent</sharingModel></CustomObject>

force-app/main/default/objects/Student_Group__c/fields/SG_Contact__c.field-meta.xml
<CustomField>
    <fullName>SG_Contact__c</fullName>
    <description>[Peoplesoft] - Relationship to contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Groups</relationshipLabel>
    <relationshipName>Student_Groups_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/Role_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Role_Knowledge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PeopleSoft security role = ASU_FC_SF KB Knowledge User. Field viewable by all core profiles.
[DW: sfe_user]</description>
    <inlineHelpText>User also needs Knowledge license checkbox, permission set Knowledge Editor (if not a Service profile) and public group (for content approver) or queue (for format approver).</inlineHelpText>
    <label>Knowledge</label>
    <type>Checkbox</type>
</CustomField>

src/classes/Test_UserHandler.cls
@isTest
public class Test_UserHandler 
{
	@isTest static void changeKnowledgePermission()
	{
		User updateUser = [SELECT Role_Knowledge__c FROM User LIMIT 1];

		updateUser.Role_Knowledge__c = true;

		update updateUser;

		updateUser = [SELECT Role_Knowledge__c FROM User WHERE Id =: updateUser.Id];

		System.assert(!updateUser.Role_Knowledge__c);
	}

	@isTest static void insertCAPUser()
	{
		Contact testContact = ContactService.createTestContact();
		testContact.CAP_Possible__c = TRUE;
		insert testContact;

		Student_Group__c testGroup = new Student_Group__c();
		testGroup.SG_Status__c = TRUE;
		testGroup.SG_PeopleSoft_Code__c = 'CP00';
		testGroup.SG_Contact__c = testContact.Id;
		insert testGroup;

		User testUser = UserService.createTestUser();
		testUser.ContactId = testContact.Id;
		insert testUser;

		Profile communityCapProfile = [SELECT Id FROM Profile WHERE Name = 'ASU Community CAP'];
		testUser = [SELECT ProfileId FROM User WHERE Id = :testUser.Id];

		System.assert(testUser.ProfileId == communityCapProfile.Id);
	}
}