src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <description>[Peoplesoft] - Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</description>
        <formula>IF(CAP_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator","CAP Participant",20,20), 
IF(CAP_Ineligible_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator_Ineligable","CAP Ineligible",20,20), 
IF(CAP_Possible__c, 
IMAGE("/resource/CAP_Student_Indicator_Potential","CAP Possible",20,20), 
"")))</formula>
        <inlineHelpText>Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</inlineHelpText>
        <label>CAP</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Role_Knowledge__c.field-meta.xml
<CustomField>
    <fullName>Role_Knowledge__c</fullName>
    <defaultValue>false</defaultValue>
    <description>PeopleSoft security role = ASU_FC_SF KB Knowledge User. Field viewable by all core profiles.
[DW: sfe_user]</description>
    <inlineHelpText>User also needs Knowledge license checkbox, permission set Knowledge Editor (if not a Service profile) and public group (for content approver) or queue (for format approver).</inlineHelpText>
    <label>Knowledge</label>
    <type>Checkbox</type>
</CustomField>

src/classes/UserHandler.cls
public without sharing class UserHandler implements ITrigger
{
    public void bulkBefore() {}

	public void bulkAfter() {}

	public void beforeInsert(SObject so) 
	{
		User newUser = (User) so;

		if (newUser.UserPermissionsKnowledgeUser)
		{
			newUser.Role_Knowledge__c = true;
		}

		Id communityProfile = [SELECT Id FROM Profile WHERE Name = 'ASU Community'].Id;
		if(newUser.ProfileId == communityProfile)
		{
			Contact newUserContact;
			if(newUser.ContactId == null)
			{
				newUserContact = [SELECT Id, CAP__c FROM Contact WHERE ASURite_ID__c = :newUser.Alias AND FirstName = :newUser.FirstName AND LastName = :newUser.LastName LIMIT 1];
				if(newUserContact == null)
				{
					newUser.ContactId.addError('No Contact for this user!');	
				}
				else
				{
					newUser.ContactId = newUserContact.Id;	
				}
			}
			else
			{
				newUserContact = [SELECT CAP__c FROM Contact WHERE Id = :newUser.ContactId];
			}

			if(newUserContact.CAP__c != null)
			{
				Profile newUserProfile = [SELECT Id FROM Profile WHERE Name = 'ASU Community CAP'];
				newUser.ProfileId = newUserProfile.Id;
			}
		}
	}

	public void beforeUpdate(SObject oldSo, SObject so) 
	{
		User updatedUser = (User) so;
		User oldUser = (User) so;

		if (updatedUser.UserPermissionsKnowledgeUser)
		{
			updatedUser.Role_Knowledge__c = true;
		}
		else
		{
			updatedUser.Role_Knowledge__c = false;
		}
	}

	public void beforeDelete(SObject so) {}

	public void beforeFinally() {}

	public void afterInsert(SObject so)
    {
        User newUser = (User) so;

        UserService.addUsersToChatterGroups(newUser.ProfileId, newUser.Id, null, null);
    }

	public void afterUpdate(SObject oldSo, SObject so)
    {
        User newUser = (User) so;
        User oldUser = (User) oldSo;

        if (newUser.ProfileId != oldUser.ProfileId)
        {
            UserService.addUsersToChatterGroups(newUser.ProfileId, newUser.Id, oldUser
                    .ProfileId, oldUser.Id);
        }
    }

	public void afterDelete(SObject so) {}

	public void andFinally() {}
}