src/objects/Contact_Upload__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Complete with Errors</fullName>
                </value>
                <value>
                    <fullName>Complete with No Errors</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Contains records representing a batch of Contacts to be added to Marketing Subscriptions</description>
    <label>Contact Upload</label>
    <nameField>
        <displayFormat>CU-{0000}</displayFormat>
        <label>Contact Upload  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Uploads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact_Upload_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Upload__c</fullName>
        <label>Contact Upload</label>
        <referenceTo>Contact_Upload__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Processing_Notes__c</fullName>
        <label>Processing Notes</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscriber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Subscriber</label>
        <referenceTo>Subscriber__c</referenceTo>
        <relationshipLabel>Contact Upload Details</relationshipLabel>
        <relationshipName>Contact_Upload_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <description>This is the record-level detail of a contact upload file. It's used to search for contact (create if not found), then add them to a subscription used by the Subscription Center and Marketing Cloud email sends.</description>
    <label>Contact Upload Detail</label>
    <nameField>
        <displayFormat>CUD-{0000000}</displayFormat>
        <label>Contact Upload Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Upload Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <inlineHelpText>populated by a workflow, Subscription &amp; Contact or Lead ID, and used to upsert records to enforce uniqueness so that a person can have only one Subscriber record on this Subscription</inlineHelpText>
        <label>Unique Key</label>
        <length>37</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ContactUploadBatch.cls
public with sharing class ContactUploadBatch implements Database.batchable<String>, Database.AllowsCallouts, Database.Stateful {
    private Id attachmentId;
    private String contactUploadId;
    private static final Integer SCOPE_SIZE = 50; //Batch limit of 100 callouts; 50 allows for 2 per record (1 GET and 1 POST)
    private Boolean errorEncountered = false;
    private Map<Integer, String> columnMap;
    ContactUploadFileReader uploadReader;
    
    public ContactUploadBatch(Id attachmentId) {
        this.attachmentId = attachmentId;
    }

    public Iterable<String> start(Database.BatchableContext batchableContext) {
        if (attachmentId != null) {
            uploadReader = new ContactUploadFileReader(attachmentId);
            contactUploadId = uploadReader.contactCSV.ParentId;
            columnMap = uploadReader.columnMap;
            updateUploadStatus('Processing'); 
            return uploadReader.fileIterator;
        } else {
            return null;
        }
    }

    public void execute(Database.BatchableContext batchableContext, List<String> scope) {
        List<List<String>> csvLines = recreateRowsFromIteration(scope);
        
        List<Contact_Upload_Detail__c> detailsToProcess = new List<Contact_Upload_Detail__c>();
        List<Contact_Upload_Detail__c> detailsInError = new List<Contact_Upload_Detail__c>();
        ContactUploadDetailService detailCreator = new ContactUploadDetailService(contactUploadId, columnMap);
        for (List<String> lineValues: csvLines) {
            Contact_Upload_Detail__c detailFromLine = detailCreator.createAndValidateRow(lineValues);
            if (detailFromLine.Status__c != 'Error') {
                detailsToProcess.add(detailFromLine);
            } else {
                detailsInError.add(detailFromLine);
            }
        }
        ContactUploadSearcher searcher = new ContactUploadSearcher(detailsToProcess);
        searcher.searchAndCreateContacts();
        List<Subscriber__c> subscriberList = new List<Subscriber__c>();
        for (Contact_Upload_Detail__c uploadDetail : detailsToProcess) {
            Subscriber__c subToAdd = detailCreator.createSubscriberForUploadDetail(uploadDetail);
            if (subtoAdd != null) {
                subscriberList.add(subToAdd);
            }
        }
        
        if (subscriberList.size() > 0) {
            Database.upsert(subscriberList, Subscriber__c.Unique_Key__c, false);
        }
        
        Map<String, Id> subKeyToSubIdMap = new Map<String, Id>();

        for (Subscriber__c subscriber: subscriberList) {
            subKeyToSubIdMap.put(subscriber.Unique_Key__c, subscriber.Id);
        }
        
        for (Contact_Upload_Detail__c uploadDetail: detailsToProcess) {
            uploadDetail = detailCreator.addSubscriberToDetail(uploadDetail, subKeyToSubIdMap);
        }
        detailsToProcess.addAll(detailsInError);
        if (detailsToProcess.size() > 0) {
            Database.insert(detailsToProcess, false);
        }
    }
    
    public void finish(Database.BatchableContext batchableContext) {
        List<Contact_Upload_Detail__c> processedDetails = [
            SELECT Status__c 
            FROM Contact_Upload_Detail__c 
            WHERE Contact_Upload__c =: contactUploadId
            LIMIT 50000
        ];
        
        String errorStatus = (processedDetails.isEmpty() ? 'Errors' : 'No Errors');
        
        for (Contact_Upload_Detail__c detail : processedDetails) {
            if (detail.Status__c == 'Error') {
                errorStatus = 'Errors';
            }
        }

        if (contactUploadId != null) {
            updateUploadStatus('Complete with ' + errorStatus);
        }
    }

    private void updateUploadStatus(String status) {
        
        Contact_Upload__c cu = new Contact_Upload__c(
                Id = contactUploadId, 
                Status__c = status);
        update cu;
    }

    private Contact_Upload_Detail__c updateDetailStatus(Contact_Upload_Detail__c cudToUpdate, String status, String error) {
        cudToUpdate.Status__c = status;
        cudToUpdate.Processing_Notes__c += error;
        cudToUpdate.Processing_Notes__c = cudToUpdate.Processing_Notes__c.left(255);
        return cudToUpdate;
    }
    
    private List<List<String>> recreateRowsFromIteration(List<String> tableOfContacts) {
        String csvFile = '';
        for (String row : tableOfContacts) {
            csvFile += row + '\r';
        }
        
        return CsvReader.readCsvFile(Blob.valueOf(csvFile));
    }
}