src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CAP__c</fullName>
        <description>[Peoplesoft] - Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</description>
        <formula>IF(CAP_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator","CAP Participant",20,20), 
IF(CAP_Ineligible_Student_Group_Count__c &gt; 0, 
IMAGE("/resource/CAP_Student_Indicator_Ineligable","CAP Ineligible",20,20), 
IF(CAP_Possible__c, 
IMAGE("/resource/CAP_Student_Indicator_Potential","CAP Possible",20,20), 
"")))</formula>
        <inlineHelpText>Displays a green icon for a College Achievement Plan participant. Automatically set when the Contact has one or more Student Group records where Status is True and PeopleSoft Code is CP00, CP01, or CP02.</inlineHelpText>
        <label>CAP</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

src/classes/JITStudentHandler.cls
global class JITStudentHandler implements Auth.SamlJitHandler
{
    global User createUser(Id samlSsoProviderId, Id communityId, Id portalId,
            String federationIdentifier, Map<String, String> attributes, String assertion)
    {
        String fedId = attributes.get('User.FederationIdentifier');
        List<User> dupeCheck = [
            SELECT Id, FirstName, LastName, Username, ProfileId, Alias, TimeZoneSidKey, Email,
                EmailEncodingKey, LocaleSidKey, LanguageLocaleKey, FederationIdentifier,
                CommunityNickname
            FROM User
            WHERE FederationIdentifier = :fedId
        ];

        if (dupeCheck.size() < 1)
        {
            User u = new User();
            handleJit(true, u, samlSsoProviderId, communityId, portalId,
                    federationIdentifier, attributes, assertion);
            return u;
        }
        else
        {
            return dupeCheck[0];
        }
    }

    global void updateUser(Id userId, Id samlSsoProviderId, Id communityId, Id portalId,
            String federationIdentifier, Map<String, String> attributes, String assertion) { }

    private void handleJit(boolean create, User u, Id samlSsoProviderId, Id communityId, Id portalId,
            String federationIdentifier, Map<String, String> attributes, String assertion)
    {
        if (communityId != null || portalId != null)
        {
            handleUser(create, u, attributes, federationIdentifier, false);
        }
        else
        {
            handleUser(create, u, attributes, federationIdentifier, true);
        }
    }

    private void handleUser(boolean create, User u, Map<String, String> attributes,
            String federationIdentifier, boolean isStandard)
    {
        if (create)
        {
            if (attributes.containsKey('User.FederationIdentifier'))
            {
                String fedId = attributes.get('User.FederationIdentifier');
                String[] fedIdSplit = fedId.split('@');
                u.FederationIdentifier = fedIdSplit[0] + '@asu.edu';

                List<Contact> contactLookup = [
                        SELECT Id, FirstName, LastName, CAP__c
                        FROM Contact
                        WHERE ASURite_ID__c = :fedIdSplit[0]
                        LIMIT 1
                ];

                if (attributes.containsKey('User.Username'))
                {
                    u.Username = attributes.get('User.Username');
                }
                else
                {
                    u.UserName = 'community_' + u.FederationIdentifier;
                }

                if (attributes.containsKey('User.Email'))
                {
                    u.Email = attributes.get('User.Email');
                }
                else
                {
                    u.Email = fedIdSplit[0] + '@asu.edu';
                }

                if (attributes.containsKey('User.FirstName')
                        && attributes.containsKey('User.LastName'))
                {
                    u.FirstName = attributes.get('User.FirstName');
                    u.LastName = attributes.get('User.LastName');
                }
                else
                {
                    u.FirstName = contactLookup[0].FirstName;
                    u.LastName = contactLookup[0].LastName;
                }

                if (contactLookup[0].CAP__c != null)
                {
                    Profile p = [SELECT Id FROM Profile WHERE Name = 'ASU Community CAP'];
                    u.ProfileId = p.Id;
                }
                else
                {
                    Profile p = [SELECT Id FROM Profile WHERE Name = 'ASU Community'];
                    u.ProfileId = p.Id;
                }

                u.CommunityNickname = fedIdSplit[0];
                u.Alias = fedIdSplit[0];
                u.TimeZoneSidKey = 'America/Phoenix';
                u.LocaleSidKey = 'en_US';
                u.EmailEncodingKey = 'ISO-8859-1';
                u.LanguageLocaleKey = 'en_US';
            }
            else
            {
                System.debug('!!!! NO FEDERATION IDENTIFIER PRESENT');
            }
        }
    }

    private class JitException extends Exception { }
}