src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/FAQ__kav.object
<CustomObject><fields>
        <fullName>Answer__c</fullName>
        <description>Article Answer Content</description>
        <label>Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields><articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Articles containing lists of questions and answers.</description><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><label>FAQ</label><pluralLabel>FAQ</pluralLabel></CustomObject>

force-app/main/default/objects/FAQ__kav/recordTypes/FAQ.recordType-meta.xml
<RecordType>
    <fullName>FAQ</fullName>
    <active>true</active>
    <label>FAQ</label>
</RecordType>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>Session_A_C_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin</description>
        <label>Session A/C Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Session_B_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin for Session B</description>
        <label>Session B Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Year__c</fullName>
        <description>[Peoplesoft] - Year</description>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_Id__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_Id__c</fullName>
    <description>[??] - ASURITE ID
[DW: sfe_user]</description>
    <formula>Contact.ASURite_ID__c</formula>
    <label>ASURITE Id</label>
    <type>Text</type>
</CustomField>

src/classes/Test_AutoCompleteController.cls
@isTest
private class Test_AutoCompleteController 
{
    private static Contact testContact;
    private static User testUser;
    private static Profile p;
    private static Term__c termAC;
    private static Term__c termB;
    private static ServiceCenter sc;
    private static AKBController akb;
    
    private static void setUp() 
    {
        p = [SELECT Id FROM Profile WHERE Name='ASU Community'];

        termAC = new Term__c();
    	Date dT = Date.today().adddays(30);
    	termAC.Session_A_C_Start_Date__c = date.newinstance(dT.year(), dT.month(), dT.day());
    	termAC.Year__c = '2015';
    	insert termAC;
    	
        termB = new Term__c();
        dT = Date.today().adddays(40);
    	termB.Session_B_Start_Date__c = date.newinstance(dT.year(), dT.month(), dT.day());
    	termB.Year__c = '2015';
    	insert termB;
    	
     	testContact = ContactService.createTestContact();
     	insert testContact;
     	
     	testUser = new User();
    	testUser.FirstName = 'Jonny';
    	testUser.LastName = 'Test';
    	testUser.Username = 'username@test.com';
    	testUser.Email = 'test@nomail.com';
    	testUser.Alias = testContact.ASURite_ID__c;
    	testUser.CommunityNickname = 'jontestComm';
    	testUser.TimeZoneSidKey = 'America/Phoenix';
    	testUser.LocaleSidKey = 'en_US';
    	testUser.EmailEncodingKey = 'ISO-8859-1';
    	testUser.LanguageLocaleKey = 'en_US';
    	testUser.ProfileId = p.Id;
    	testuser.ContactId = testContact.Id;
    	insert testUser;

        FAQ__kav faqArticle = new FAQ__kav(
            Title = 'testFAQ',
            Summary = 'test from apex',
            Answer__c = 'test',
            Question__c = 'test',
            Language = 'en_US',
            IsVisibleInPKB = true,
            IsVisibleInCsp = true,
            IsVisibleInPrm = true,
            URLName = 'test-FAQ');
        insert faqArticle;

        faqArticle = [SELECT KnowledgeArticleId
                      FROM FAQ__kav
                      WHERE Id = :faqArticle.id];
        KbManagement.PublishingService.publishArticle(faqArticle.KnowledgeArticleId, true);

        PageReference akbPage = Page.akb;
        Test.setCurrentPage(akbPage);
        List<KnowledgeArticleVersion> articleTest = [SELECT KnowledgeArticleId 
                                                     FROM KnowledgeArticleVersion 
                                                     WHERE PublishStatus = 'Online' 
                                                     AND Language = 'en_US' 
                                                     LIMIT 1];
        ApexPages.currentPage().getParameters().put('id', articleTest[0].KnowledgeArticleId);
    }
    
    @isTest static void testSearchArticle() 
    {
        setUp();
        Test.startTest();
        System.runAs(testUser)
        {
            sc = new ServiceCenter();
            AutoCompleteController acc = new AutoCompleteController(sc);
            akb = new AKBController();
            AutoCompleteController acc2 = new AutoCompleteController(akb);
            ApexPages.StandardController standard = new ApexPages.StandardController(testContact);
            AutoCompleteController acc3 = new AutoCompleteController(standard);
    		List<KnowledgeArticleVersion> result = AutoCompleteController.searchArticle('test');
    		System.AssertNotEquals(null, result);
        }
		Test.stopTest();
	}
}