src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactFactory.cls
@isTest
public class ContactFactory extends TestFactory {
    public static final Contact DEFAULT_CONTACT = new Contact(
        FirstName = 'Test',
        LastName = 'Contact',
        Email = 'test@test.com',
        EmplId__c = '12000'
    );
    
    public ContactFactory(Contact testContact) {
        super(testContact);
        this.addToFieldsToIncrement('LastName');
        this.addToFieldsToIncrement('EmplId__c');
    }
    
    public Contact createOne() {
        return (Contact) this.create(1)[0];
    }
    
    public class DefaultContact extends TestFactory {
        public DefaultContact() {
            super(new Contact(
                FirstName = 'Test',
                LastName = 'Contact',
                Email = 'test@test.com',
                EmplId__c = '123456'
            ));
            this.addToFieldsToIncrement('LastName');
            this.addToFieldsToIncrement('EmplId__c');
        }
    }
    
    public class AllEmailsFilled extends TestFactory {
        public AllEmailsFilled(Id accountId) {
            super(new Contact(
                FirstName = 'Test',
                LastName = 'Test',
                Email = 'test@test.com',
                Corporate_Relations_Email__c = 'test@test.com',
                EPO_Email__c = 'test@test.com',
                ASU_Email__c = 'test@test.com',
                Last_Case_Email_Used__c = 'test@test.com',
                Lead_Email__c = 'test@test.com',
                Lead_Secondary_Email__c = 'test@test.com',
                Parent_Email__c = 'test@test.com',
                Personal_Email__c = 'test@test.com',
                Birthdate = System.today()
            ));
            this.addToFieldsToIncrement('LastName');
        }
    }
}