src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>me3hs_User_ID__c</fullName>
        <description>[eAdvisor Data Warehouse] me3 User Id in email format</description>
        <inlineHelpText>[eAdvisor Data Warehouse] me3 User Id in email format</inlineHelpText>
        <label>me3hs User ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>silverpop__Silverpop_RecipientID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Silverpop RecipientID</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactScrambler.cls
public class ContactScrambler implements ObjectScramble {
    Contact contactToScramble;

    public ContactScrambler(Contact contactToScramble) {
        this.contactToScramble = contactToScramble;
    }

    public sObject scrambleFields() {
        scrambleEmails();
        scrambleDates();
        removeSilverpopId();

        return contactToScramble;
    }

    public String toCsvString() {
        String formattedString = contactToScramble.Id;
        formattedString += ',';
        if (contactToScramble.Birthdate != null) {
            formattedString += contactToScramble.Birthdate;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.email)) {
            formattedString += contactToScramble.email;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Corporate_Relations_Email__c)) {
            formattedString += contactToScramble.Corporate_Relations_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.EPO_Email__c)) {
            formattedString += contactToScramble.EPO_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.ASU_Email__c)) {
            formattedString += contactToScramble.ASU_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Last_Case_Email_Used__c)) {
            formattedString += contactToScramble.Last_Case_Email_Used__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Lead_Email__c)) {
            formattedString += contactToScramble.Lead_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Lead_Secondary_Email__c)) {
            formattedString += contactToScramble.Lead_Secondary_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.me3hs_User_ID__c)) {
            formattedString += contactToScramble.me3hs_User_ID__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Parent_Email__c)) {
            formattedString += contactToScramble.Parent_Email__c;
        }
        formattedString += ',';
        if (!String.isEmpty(contactToScramble.Personal_Email__c)) {
            formattedString += contactToScramble.Personal_Email__c;
        }

        formattedString += ',#N/A';

        formattedString += '\n';

        return formattedString;
    }

    private void scrambleEmails() {
        contactToScramble.email = Scrambler.scrambleEmailOrUsername(contactToScramble.email);
        contactToScramble.Corporate_Relations_Email__c = Scrambler.scrambleEmailOrUsername(
            contactToScramble.Corporate_Relations_Email__c
        );
        contactToScramble.EPO_Email__c = Scrambler.scrambleEmailOrUsername(contactToScramble.EPO_Email__c);
        contactToScramble.ASU_Email__c = Scrambler.scrambleEmailOrUsername(contactToScramble.ASU_Email__c);
        contactToScramble.Last_Case_Email_Used__c = Scrambler.scrambleEmailOrUsername(
            contactToScramble.Last_Case_Email_Used__c
        );
        contactToScramble.Lead_Email__c = Scrambler.scrambleEmailOrUsername(contactToScramble.Lead_Email__c);
        contactToScramble.Lead_Secondary_Email__c = Scrambler.scrambleEmailOrUsername(
            contactToScramble.Lead_Secondary_Email__c
        );
        contactToScramble.me3hs_User_ID__c = Scrambler.scrambleEmailOrUsername(contactToScramble.me3hs_User_ID__c);
        contactToScramble.Parent_Email__c = Scrambler.scrambleEmailOrUsername(contactToScramble.Parent_Email__c);
        contactToScramble.Personal_Email__c = Scrambler.scrambleEmailOrUsername(contactToScramble.Personal_Email__c);
    }

    private void scrambleDates() {
        contactToScramble.Birthdate = Scrambler.scrambleDate(contactToScramble.Birthdate);
    }

    private void removeSilverpopId() {
        contactToScramble.silverpop__Silverpop_RecipientID__c = null;
    }
}