src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASU_Email__c</fullName>
        <description>[Peoplesoft] - Official ASU email address (usually first name.last name@asu.edu)</description>
        <inlineHelpText>Official ASU directory email address (usually first and last name)</inlineHelpText>
        <label>Directory Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Corporate_Relations_Email__c</fullName>
        <description>Email used to manage ASU corporate relationships.</description>
        <inlineHelpText>Email used to manage ASU corporate relationships.</inlineHelpText>
        <label>Corporate Relations Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>EPO_Email__c</fullName>
        <description>[Peoplesoft] - Email address of the destination email after ASUrite has been activated.</description>
        <inlineHelpText>This email address is the forwarding email address the person has chosen to receive ASU email communication.</inlineHelpText>
        <label>Destination Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Last_Case_Email_Used__c</fullName>
        <description>[Salesforce] - Last email used by the contact</description>
        <inlineHelpText>The email this Contact last used when sending a message to an ASU address that is processed by Salesforce.</inlineHelpText>
        <label>Last Case Email Used</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Email__c</fullName>
        <description>[data entry or webform] - Transferred field from the Lead record</description>
        <label>Lead Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Lead_Secondary_Email__c</fullName>
        <description>[manual entry] - Additional email address from the Lead record</description>
        <label>Lead Secondary Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <description>[Peoplesoft] - Email address for parents</description>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Personal_Email__c</fullName>
        <description>[Peoplesoft] - Personal email address other than ASU Directory or Destination email addresses</description>
        <inlineHelpText>Personal non-ASU email address listed as Other in PeopleSoft</inlineHelpText>
        <label>Personal Email</label>
        <type>Email</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ContactOperationsForSandBoxRefreshTest.cls
@isTest
private class ContactOperationsForSandBoxRefreshTest {

    private static final Integer ACCOUNT_NUM = 100;
    private static final Integer CONTACT_NUM = 100;
    
	private static testMethod void test() {
        
        //Create Account Test Data 
        List<Account> lstAccount= TestDataFactory.createAccounts(ACCOUNT_NUM);
        insert lstAccount;
        
        //Create Contact Test data
        List<Contact> lstCon = TestDataFactory.createContacts(CONTACT_NUM);
        for (Integer i = 0; i < CONTACT_NUM; i++) {
            lstCon[i].AccountId = lstAccount[0].Id;
            lstCon[i].LastName = 'Test';
            lstCon[i].email = 'Test' + i + '@Test.com';
            lstCon[i].Corporate_Relations_Email__c = 'Test@Test.com';
            lstCon[i].EPO_Email__c = 'Test@Test.com';
            lstCon[i].ASU_Email__c = 'Test@Test.com';
            lstCon[i].Last_Case_Email_Used__c = 'Test@Test.com';
            lstCon[i].Lead_Email__c = 'Test@Test.com';
            lstCon[i].Lead_Secondary_Email__c = 'Test@Test.com';
            lstCon[i].Parent_Email__c = 'Test@Test.com';
            lstCon[i].Personal_Email__c = 'Test@Test.com';
            lstCon[i].Birthdate = system.today();
        } 
        
        insert lstCon;
        
        Test.startTest();
            ContactOperationsForSandBoxRefresh obj = new ContactOperationsForSandBoxRefresh();
            obj.baseUrl = 'https://asu--roger.UAT.cs53.my.salesforce.com';
            DataBase.executeBatch(obj);
            obj.baseUrl = 'https://asu--roger.QA.cs53.my.salesforce.com';
            DataBase.executeBatch(obj);
            obj.baseUrl = 'https://asu--roger.DEV.cs53.my.salesforce.com';
            DataBase.executeBatch(obj);
            DataBase.executeBatch(obj); 
        Test.stopTest();
    }
}