src/objects/Email_To_Case_Configuration__c.object
<CustomObject><fields>
        <fullName>Value__c</fullName>
        <description>The value for this setting</description>
        <inlineHelpText>The value for this setting</inlineHelpText>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields><customSettingsType>List</customSettingsType><description>Contains configuration settings for the Email-to-Case handler</description><enableFeeds>false</enableFeeds><label>Email To Case Configuration</label><visibility>Public</visibility></CustomObject>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>Session_A_C_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin</description>
        <label>Session A/C Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Session_B_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin for Session B</description>
        <label>Session B Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Year__c</fullName>
        <description>[Peoplesoft] - Year</description>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

src/classes/Test_ViewAllCasesController.cls
@isTest
private class Test_ViewAllCasesController
{
    private static User testUser;
    static void setup()
    {
        Term__c termAC = new Term__c();
        Date dTac = Date.today().adddays(365);
        Date dTb = Date.today().adddays(405);
        termAC.Session_A_C_Start_Date__c = date.newinstance(dTac.year(), dTac.month(), dTac.day());
        String ACYear = String.valueOf(dTac.year());
        termAC.Year__c = ACYear;
        insert termAC;

        Term__c termB = new Term__c();
        termB.Session_B_Start_Date__c = date.newinstance(dTb.year(), dTb.month(), dTb.day());
        String BYear = String.valueOf(dTb.year());
        termB.Year__c = BYear;
        insert termB;

        Contact testContact = ContactService.createTestContact();
        insert testContact;

        UserFactory.DefaultUser userCreator = new UserFactory.DefaultUser();
        testUser = (User)userCreator.create(1)[0];
        testUser.ProfileId = [SELECT Id FROM Profile WHERE Name = 'ASU Community'].Id;
        testUser.ContactId = testContact.Id;
        insert testUser;

        
        Email_To_Case_Configuration__c defaultEmail = new Email_To_Case_Configuration__c(Name = 'Default Org Wide Email Address', Value__c = 'testemail@test.com');
        insert defaultEmail;
        
        List<Case> testCases = CaseService.createTestCases(10, testContact);

        // Set the first three testCases to closed
        Integer i = 0;
        for (Case c : testCases)
        {
            if (i < 3)
            {
                c.Status = 'New';
                i++;
            }
            else
            {
                c.Status = 'Closed: Resolved';
            }
        }

        insert testCases;
    }

    @isTest static void testGetAllClosedCases()
    {
        setup();
        PageReference viewAllCasesPage = Page.viewAllCases;
        Test.setCurrentPage(viewAllCasesPage);
        ServiceCenter sc;
        ViewAllCasesController vac;
        List<Case> closedCases = null;

        Test.startTest();
        System.runAs(testUser)
        {
            vac = new ViewAllCasesController();

            closedCases = vac.getAllClosedCases();
        }
        Test.stopTest();

        System.assertEquals(7, closedCases.size());
    }
    
    @isTest
    private static void testCreateJsonEmail() {
        setup();
        PageReference viewAllCasesPage = Page.viewAllCases;
        Test.setCurrentPage(viewAllCasesPage);
        String jsonEmail;
        ServiceCenter sc;
        ViewAllCasesController vac;
        List<Case> closedCases = null;

        Test.startTest();
        System.runAs(testUser)
        {
            vac = new ViewAllCasesController();

            jsonEmail = vac.createJsonEmail();
        }
        Test.stopTest();

        System.assert(jsonEmail.contains('testemail@test.com'));
    }
}