src/objects/Family_Portal_Guardian__c.object
<CustomObject>
    <description>This Object is used to store the Guardian information for the Family Portal Community</description>
    <label>Family Portal Guardian</label>
    <nameField>
        <displayFormat>FPG-{0}</displayFormat>
        <label>Family Portal Guardian ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Portal Guardians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Portal_Student__c.object
<CustomObject>
    <description>This Object is used to store the Guardian's student information</description>
    <fields>
        <fullName>Academic_College__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>ASU Academic College name. This option is available to Family Portal Student record with ASU Student enrollment status.</description>
        <label>Academic College</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Family_Portal_Student_College</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Active_Relationship__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <defaultValue>true</defaultValue>
        <description>True if the guardian has submitted a relationship to a student, false if the guardian has removed a relationship from a student</description>
        <label>Active Relationship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status_Year__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>High School Graduation year for K-12 Student, ASU graduation year for ASU alumni or Expected graduation year for ASU Student</description>
        <label>Enrollment Status Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enrollment_Status__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Student's current Enrollment Status</description>
        <label>Enrollment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K-12 Student</fullName>
                    <default>true</default>
                    <label>K-12 Student</label>
                </value>
                <value>
                    <fullName>ASU Student</fullName>
                </value>
                <value>
                    <fullName>ASU Alumni</fullName>
                </value>
                <value>
                    <fullName>ASU Graduate Student</fullName>
                    <isActive>false</isActive>
                    <label>ASU Graduate Student</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Family_Portal_Guardian__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian Salesforce id</description>
        <label>Family Portal Guardian</label>
        <referenceTo>Family_Portal_Guardian__c</referenceTo>
        <relationshipLabel>Family Portal Students</relationshipLabel>
        <relationshipName>Family_Portal_Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Military_Affiliation__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Student's Military Affiliation</description>
        <label>Military Affiliation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active Military</fullName>
                </value>
                <value>
                    <fullName>Veteran</fullName>
                </value>
                <value>
                    <fullName>Dependent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Student Type indicates International Student, Transfer Student and Barrett Honors student. This option is available to Family Portal Student record with ASU Student enrollment status.</description>
        <label>Student Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Family_Portal_Student_Types</valueSetName>
        </valueSet>
    </fields>
    <label>Family Portal Student</label>
    <nameField>
        <displayFormat>FPS-{0}</displayFormat>
        <label>Family Portal Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Portal Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Family_Portal_Student_College.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>College of Global Futures</fullName>
    </customValue>
    <customValue>
        <fullName>College of Health Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>College of Integrative Sciences and Arts</fullName>
    </customValue>
    <customValue>
        <fullName>Edson College of Nursing and Health Innovation</fullName>
    </customValue>
    <customValue>
        <fullName>Herberger Institute for Design and the Arts</fullName>
    </customValue>
    <customValue>
        <fullName>Ira A. Fulton Schools of Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Mary Lou Fulton Teachers College</fullName>
    </customValue>
    <customValue>
        <fullName>New College of Interdisciplinary Arts and Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Sandra Day O&apos;Connor College of Law</fullName>
    </customValue>
    <customValue>
        <fullName>The College of Liberal Arts and Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Thunderbird School of Global Management</fullName>
    </customValue>
    <customValue>
        <fullName>University College</fullName>
    </customValue>
    <customValue>
        <fullName>W. P. Carey School of Business</fullName>
    </customValue>
    <customValue>
        <fullName>Walter Cronkite School of Journalism and Mass Communication</fullName>
    </customValue>
    <customValue>
        <fullName>Watts College of Public Service and Community Solutions</fullName>
    </customValue>
    <customValue>
        <fullName>School for the Future of Innovation in Society</fullName>
    </customValue>
    <masterLabel>Family Portal Student College</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Family_Portal_Student_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Barrett Honors</fullName>
    </customValue>
    <customValue>
        <fullName>Transfer Student</fullName>
    </customValue>
    <customValue>
        <fullName>International Student</fullName>
    </customValue>
    <masterLabel>Family Portal Student Types</masterLabel>
</GlobalValueSet>

src/classes/FamilyPortalStudentDeduplicationService.cls
public class FamilyPortalStudentDeduplicationService {
    private List<Family_Portal_Student__c> studentsWithChanges;
    private static List<Family_Portal_Student__c> studentsToDelete;
    private static List<Family_Portal_Student__c> studentsToUpdate;

    public FamilyPortalStudentDeduplicationService(List<Family_Portal_Student__c> studentsWithChanges) {
        this.studentsWithChanges = studentsWithChanges;
    }

    public void initialize() {
        if (studentsWithChanges.size() > 0) {
            gatherStudentsAndStartDedupe(studentsWithChanges);

            Set<Family_Portal_Student__c> studentsToUpdateSet = new Set<Family_Portal_Student__c>();
            studentsToUpdateSet.addAll(studentsToUpdate);
            studentsToUpdate.clear();
            studentsToUpdate.addAll(studentsToUpdateSet);
            if (studentsToUpdate.size() > 0) {
                updateStudents(studentsToUpdate);
            }

            Set<Family_Portal_Student__c> studentsToDeleteSet = new Set<Family_Portal_Student__c>();
            studentsToDeleteSet.addAll(studentsToDelete);
            studentsToDelete.clear();
            studentsToDelete.addAll(studentsToDeleteSet);
            if (studentsToDelete.size() > 0) {
                deleteStudents(studentsToDelete);
            }
        }
    }

    public static void gatherStudentsAndStartDedupe(List<Family_Portal_Student__c> updatedStudents) {
        Map<Family_Portal_Student__c, List<Family_Portal_Student__c>> updatedStudentWithMatchedStudents = new Map<Family_Portal_Student__c, List<Family_Portal_Student__c>>();
        studentsToDelete = new List<Family_Portal_Student__c>();
        studentsToUpdate = new List<Family_Portal_Student__c>();

        for (Family_Portal_Student__c updatedStudent : updatedStudents) {
            List<Family_Portal_Student__c> matchedStudentsToCheck = [
                SELECT
                    Id,
                    Academic_College__c,
                    Active_Relationship__c,
                    Enrollment_Status__c,
                    Enrollment_Status_Year__c,
                    Family_Portal_Guardian__c,
                    Military_Affiliation__c,
                    Type__c,
                    CreatedDate
                FROM Family_Portal_Student__c
                WHERE
                    Family_Portal_Guardian__c = :updatedStudent.Family_Portal_Guardian__c
                    AND Enrollment_Status__c = :updatedStudent.Enrollment_Status__c
                    AND ((Enrollment_Status_Year__c = :updatedStudent.Enrollment_Status_Year__c
                    AND Military_Affiliation__c = :updatedStudent.Military_Affiliation__c)
                    OR (Academic_College__c = :updatedStudent.Academic_College__c
                    AND Type__c = :updatedStudent.Type__c
                    AND Military_Affiliation__c = :updatedStudent.Military_Affiliation__c))
                ORDER BY CreatedDate ASC
            ];

            if (matchedStudentsToCheck.size() > 0) {
                updatedStudentWithMatchedStudents.put(updatedStudent, matchedStudentsToCheck);
            }
        }
        deduplicateStudents(updatedStudentWithMatchedStudents);
    }

    private static void deduplicateStudents(
        Map<Family_Portal_Student__c, List<Family_Portal_Student__c>> updatedStudentWithMatchedStudents
    ) {
        for (Family_Portal_Student__c updatedStudent : updatedStudentWithMatchedStudents.keySet()) {
            Family_Portal_Student__c oldestStudent = updatedStudent;
            Family_Portal_Student__c newestStudent = updatedStudent;
            List<Family_Portal_Student__c> relatedstudentsToDelete = new List<Family_Portal_Student__c>();
            List<Family_Portal_Student__c> matchedStudentsToCheck = updatedStudentWithMatchedStudents.get(
                updatedStudent
            );

            Set<Id> studentIdsToDelete = new Set<Id>();
            for (Family_Portal_Student__c student : studentsToDelete) {
                studentIdsToDelete.add(student.Id);
            }

            if (studentIdsToDelete.contains(updatedStudent.Id)) {
                continue;
            }
            if (matchedStudentsToCheck.size() == 1 && matchedStudentsToCheck[0].Id == oldestStudent.Id) {
                continue;
            }
            if (matchedStudentsToCheck.size() > 1) {
                oldestStudent = matchedStudentsToCheck[0];
                newestStudent = matchedStudentsToCheck[matchedStudentsToCheck.size() - 1];
            }

            for (Family_Portal_Student__c matchedStudent : matchedStudentsToCheck) {
                if (
                    matchedStudent.Id != oldestStudent.Id &&
                    matchedStudent.Id != newestStudent.Id &&
                    matchedStudent.CreatedDate > oldestStudent.CreatedDate
                ) {
                    relatedstudentsToDelete.add(matchedStudent);
                }
            }

            studentsToDelete.addAll(relatedstudentsToDelete);

            if (newestStudent.Active_Relationship__c != null) {
                oldestStudent.Active_Relationship__c = newestStudent.Active_Relationship__c;
            }

            if (!studentsToDelete.contains(newestStudent)) {
                studentsToDelete.add(newestStudent);
            }
            if (!studentsToUpdate.contains(oldestStudent)) {
                studentsToUpdate.add(oldestStudent);
            }
        }
    }

    public static void updateStudents(List<Family_Portal_Student__c> students) {
        try {
            update students;
        } catch (DmlException e) {
            List<String> vars = new List<String>();
            vars.add(ErrorLogger.convertListToJSON('students', students));
            ErrorLogger.log(e, vars, false);
        }
    }

    public static void deleteStudents(List<Family_Portal_Student__c> students) {
        try {
            delete students;
        } catch (DmlException e) {
            List<String> vars = new List<String>();
            vars.add(ErrorLogger.convertListToJSON('students', students));
            ErrorLogger.log(e, vars, false);
        }
    }
}