src/objects/Family_Portal_Guardian__c.object
<CustomObject>
    <description>This Object is used to store the Guardian information for the Family Portal Community</description>
    <fields>
        <fullName>Contact__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Guardian Contact id</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Family Portal Guardians</relationshipLabel>
        <relationshipName>Family_Portal_Guardians</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian email</description>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian first name</description>
        <label>First Name</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian last name</description>
        <label>Last Name</label>
        <length>64</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Postal Code of the Guardian Address</description>
        <label>Zip Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Family Portal Guardian</label>
    <nameField>
        <displayFormat>FPG-{0}</displayFormat>
        <label>Family Portal Guardian ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Portal Guardians</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Family_Portal_Guardian_Interest__c.object
<CustomObject>
    <description>This Object is used to store the guardian's interest information</description>
    <fields>
        <fullName>Family_Portal_Guardian__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian Salesforce id</description>
        <label>Family Portal Guardian</label>
        <referenceTo>Family_Portal_Guardian__c</referenceTo>
        <relationshipLabel>Family Portal Guardian Interests</relationshipLabel>
        <relationshipName>Family_Portal_Guardian_Interests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Family Portal Guardian Interest</label>
    <nameField>
        <displayFormat>FPGI-{0}</displayFormat>
        <label>Family Portal Guardian Interest ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Portal Guardian Interests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Family_Portal_Student__c.object
<CustomObject>
    <description>This Object is used to store the Guardian's student information</description>
    <fields>
        <fullName>Family_Portal_Guardian__c</fullName>
        <businessOwnerGroup>Data_Owner_ESISD</businessOwnerGroup>
        <description>Guardian Salesforce id</description>
        <label>Family Portal Guardian</label>
        <referenceTo>Family_Portal_Guardian__c</referenceTo>
        <relationshipLabel>Family Portal Students</relationshipLabel>
        <relationshipName>Family_Portal_Students</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Family Portal Student</label>
    <nameField>
        <displayFormat>FPS-{0}</displayFormat>
        <label>Family Portal Student ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Family Portal Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/ASURITE_for_External_ID__c.field-meta.xml
<CustomField>
    <fullName>ASURITE_for_External_ID__c</fullName>
    <description>[??] - This User's ASURITE. If different from the Federation ID, it will be set that that value via workflow. Used for Upserting User records. Any Upsert should map the ASURITE to this field as the "External ID", and ALSO map the ASURITE to the Federation ID.
[DW: sfe_user]</description>
    <externalId>true</externalId>
    <inlineHelpText>This User's ASURITE. If different from the Federation ID, it will be set that that value via workflow. Used for Upserting User records. Any Upsert should map the ASURITE to this field as the "External ID", and ALSO map the ASURITE to the Federation ID.</inlineHelpText>
    <label>ASURITE for External ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

src/classes/FamilyPortalController.cls
public with sharing class FamilyPortalController {
    public String existingGuardianUserAsuriteId {get; set;}
    public String existingGuardianUserEmplid {get; set;}
    public Family_Portal_Guardian__c familyPortalGuardian {get; set;}
    public Family_Portal_Guardian_Interest__c familyPortalGuardianInterest {get; set;}
    public List<String> guardianChosenInterests {get; set;}
    public List<Family_Portal_Student__c> familyPortalStudentList {get; set;}
    public List<FamilyPortalStudentWrapper> studentWrapperList {get;set;}
    private Integer studentRowCount = 0;

    public FamilyPortalController() {
        familyPortalGuardian =  new Family_Portal_Guardian__c();
        familyPortalGuardianInterest = new Family_Portal_Guardian_Interest__c();
        studentWrapperList =  new List<FamilyPortalStudentWrapper>();
        familyPortalStudentList = new List<Family_Portal_Student__c>();
        addStudentRow();
    }

    public User getGuardianDataFromExistingUser() {
        User existingGuardianUser = [SELECT FirstName, LastName, Email, PostalCode, EmployeeNumber, ASURITE_for_External_ID__c, Id FROM User WHERE Id =: UserInfo.getUserId()];
        return existingGuardianUser;
    }

    public PageReference addStudentRow() {
        studentRowCount++;
        studentWrapperList.add(new FamilyPortalStudentWrapper(new Family_Portal_Student__c(), studentRowCount));
        return null;
    }
    
    public PageReference removeStudentRow() {
        Integer indexToRemove = Integer.valueOf(Apexpages.currentpage().getParameters().get('index'));
        for(Integer i = 0; i < studentWrapperList.size(); i++) {
            if(studentWrapperList[i].studentIndex == indexToRemove ) {
                studentWrapperList.remove(i);     
            }
        }
        return null;
    }

    public PageReference familyPortal() {
        return Page.FamilyPortal;
    }

    public PageReference familyPortalStep2() {
        return Page.FamilyPortalStep2;
    }

    public PageReference familyPortalStep3() {
        return Page.FamilyPortalStep3;
    }

    public PageReference familyPortalStep4a() {
        User existingGuardianUser;
        if (UserInfo.getUserId() != null && familyPortalGuardian.First_Name__c == null && familyPortalGuardian.Last_Name__c == null && familyPortalGuardian.Email__c == null) {
            existingGuardianUser = getGuardianDataFromExistingUser();
            if (existingGuardianUser.FirstName != null) {
                familyPortalGuardian.First_Name__c = existingGuardianUser.FirstName;
            }
            if (existingGuardianUser.LastName != null) {
                familyPortalGuardian.Last_Name__c = existingGuardianUser.LastName;
            }
            if (existingGuardianUser.Email != null) {
                familyPortalGuardian.Email__c = existingGuardianUser.Email;
            }
            if (existingGuardianUser.PostalCode != null) {
                familyPortalGuardian.Zip_Code__c = existingGuardianUser.PostalCode;
            }
            if (existingGuardianUser.EmployeeNumber != null) {
                existingGuardianUserEmplid = existingGuardianUser.EmployeeNumber;
            }
            if (existingGuardianUser.ASURITE_for_External_ID__c != null) {
                existingGuardianUserAsuriteId = existingGuardianUser.ASURITE_for_External_ID__c;
            }
        }
        return Page.FamilyPortalStep4a;
    }

    public PageReference familyPortalStep4b() {
        return Page.FamilyPortalStep4b;
    }

    public PageReference familyPortalStep5() {
        if (!studentWrapperList.isEmpty()) {
            for (FamilyPortalStudentWrapper studentWrapper : studentWrapperList) {
                Family_Portal_Student__c reportedStudent = studentWrapper.familyPortalStudentObj;
                familyPortalStudentList.add(reportedStudent);
            }
        }

        Map<String, String> detailFieldsMap = new Map<String, String>();
        detailFieldsMap.put('emplid', existingGuardianUserEmplid);
        detailFieldsMap.put('asuriteId', existingGuardianUserAsuriteId);
        detailFieldsMap.put('firstName', familyPortalGuardian.First_Name__c);
        detailFieldsMap.put('lastName', familyPortalGuardian.Last_Name__c);
        detailFieldsMap.put('email', familyPortalGuardian.Email__c);
        ConstituentDetail guardianDetail = new ConstituentDetail(detailFieldsMap);

        ConstituentMatcher contactMatcher = new ConstituentMatcher(guardianDetail, 'Contact');
        contactMatcher.searchConstituents();
        List<ConstituentDetail> matchedDetailsWithContacts = contactMatcher.getListOfConstituentsWithMatches();
        for (ConstituentDetail matchedDetailWithContact : matchedDetailsWithContacts) {
            familyPortalGuardian.Contact__c = matchedDetailWithContact.constituentId;
        }

        ConstituentMatcher leadMatcher = new ConstituentMatcher(guardianDetail, 'Lead');
        leadMatcher.searchConstituents();
        List<ConstituentDetail> matchedDetailsWithLeads = leadMatcher.getListOfConstituentsWithMatches();
        for (ConstituentDetail matchedDetailWithLead : matchedDetailsWithLeads) {
            familyPortalGuardian.Lead__c = matchedDetailWithLead.constituentId;
        }

        insert familyPortalGuardian;

        if (familyPortalGuardianInterest.Interest__c != null) {
            familyPortalGuardianInterest.Family_Portal_Guardian__c = familyPortalGuardian.Id;
        }
        insert familyPortalGuardianInterest;

        for (Family_Portal_Student__c reportedStudent : familyPortalStudentList) {
            reportedStudent.Family_Portal_Guardian__c = familyPortalGuardian.Id;
        }
        insert familyPortalStudentList;

        return Page.FamilyPortalStep5;
    }

    public class FamilyPortalStudentWrapper {
        public Family_Portal_Student__c familyPortalStudentObj {get;set;}
        public Integer studentIndex {get;set;}
        
        public FamilyPortalStudentWrapper(Family_Portal_Student__c familyPortalStudentObj, Integer studentIndex) {
            this.familyPortalStudentObj = familyPortalStudentObj;
            this.studentIndex = studentIndex;
        }
    }
}