src/objects/FAQ__kav.object
<CustomObject><fields>
        <fullName>Answer__c</fullName>
        <description>Article Answer Content</description>
        <label>Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields><articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Articles containing lists of questions and answers.</description><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><label>FAQ</label><pluralLabel>FAQ</pluralLabel></CustomObject>

force-app/main/default/objects/FAQ__kav/recordTypes/FAQ.recordType-meta.xml
<RecordType>
    <fullName>FAQ</fullName>
    <active>true</active>
    <label>FAQ</label>
</RecordType>

src/objects/How_To__kav.object
<CustomObject><fields>
        <fullName>Content__c</fullName>
        <description>Article content</description>
        <label>Content</label>
        <length>32768</length>
        
        <type>Html</type>
    </fields><fields>
        <fullName>Functional_Group__c</fullName>
        <description>Group which owns and maintains the article.</description>
        <inlineHelpText>Group which owns and maintains the article.</inlineHelpText>
        <label>Functional Group</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admission Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barrett Honors College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Health Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Liberal Arts and Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Nursing and Health Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Public Service and Community Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulton Schools of Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herberger Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int'l Students and Scholars Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mary Lou Fulton Teachers College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Orientation and Family Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parking and Transit Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provost Office</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registrar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School of Letters and Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School of Sustainability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Student Business Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Study Abroad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun Card Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun Devil Athletics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sun Devil Dining</fullName>
            </picklistValues>
        </picklist>
        
        <type>Picklist</type>
    </fields><articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>InDevelopment</deploymentStatus><description>Articles which describe a process.</description><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><label>How To</label><pluralLabel>How To</pluralLabel></CustomObject>

src/objects/Informational__kav.object
<CustomObject><fields>
        <fullName>Information__c</fullName>
        <description>Article Informational Content</description>
        <label>Information</label>
        <length>32768</length>
        <type>Html</type>
    </fields><articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>InDevelopment</deploymentStatus><description>Articles with general knowledge content.</description><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><label>Informational</label><pluralLabel>Informational</pluralLabel></CustomObject>

src/classes/Test_vfListPaginationController.cls
@IsTest
private class Test_vfListPaginationController
{
    @testSetup static void setUp()
    {
        FAQ__kav faqArticle = new FAQ__kav(
                Title = 'testFAQ',
                Summary = 'test from apex',
                Answer__c = 'test',
                Question__c = 'test',
                Language = 'en_US',
                IsVisibleInPKB = true,
                IsVisibleInCsp = true,
                IsVisibleInPrm = true,
                URLName = 'test-FAQ-asdf');
        insert faqArticle;

        faqArticle = [SELECT KnowledgeArticleId
        FROM FAQ__kav
        WHERE Id = :faqArticle.id];
        KbManagement.PublishingService.publishArticle(faqArticle.KnowledgeArticleId, true);

        How_To__kav howArticle = new How_To__kav(
                Title = 'testHowTo',
                Summary = 'test from apex',
                Content__c = 'test from apex',
                Language = 'en_US',
                IsVisibleInPKB = true,
                IsVisibleInCsp = true,
                IsVisibleInPrm = true,
                URLName = 'testHowTo-asdf');
        insert howArticle;

        howArticle = [SELECT KnowledgeArticleId
        FROM How_To__kav
        WHERE Id = :howArticle.id];
        KbManagement.PublishingService.publishArticle(howArticle.KnowledgeArticleId, true);

        Informational__kav infoArticle = new Informational__kav(
                Title = 'testInfo',
                Summary = 'test from apex',
                Information__c = 'test from apex',
                Language = 'en_US',
                IsVisibleInPKB = true,
                IsVisibleInCsp = true,
                IsVisibleInPrm = true,
                URLName = 'testInfo-asdf');
        insert infoArticle;

        infoArticle = [SELECT KnowledgeArticleId
        FROM Informational__kav
        WHERE Id = :infoArticle.id];
        KbManagement.PublishingService.publishArticle(infoArticle.KnowledgeArticleId, true);
    }

    @isTest static void testViewAllArticlesPage()
    {
        PageReference viewAllArticles = Page.viewAllArticles;
        Test.setCurrentPage(viewAllArticles);
        vfListPaginationController vf = new vfListPaginationController();

        vf.searchstring = 'test';
        vf.articleSearch();
        vf.next();
        vf.firstPage();
        vf.getNextRequired();
        vf.getPrevRequired();
        vf.clearSearchString();

        System.assertEquals('', vf.searchstring);
    }

    @isTest static void teststudentSCPage()
    {
        PageReference studentSC = Page.studentSC;
        Test.setCurrentPage(studentSC);
        ApexPages.currentPage().getParameters().put('q', 'test');
        vfListPaginationController vf = new vfListPaginationController();

        vf.getPageNumber();
        vf.articleSearch();
        vf.viewAllResults();

        // Test long search string
        vf.searchstring = 'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test test test test test test ' +
                          'test test test test';
        vf.articleSearch();

        System.assertEquals(99, vf.searchstring.length());
    }
}