src/objects/FAQ__kav.object
<CustomObject><fields>
        <fullName>Article_Expiration_Date__c</fullName>
        <description>Date in which article will expire and content needs to be reviewed.</description>
        <label>Article Expiration Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Functional_Group__c</fullName>
        <description>Group which owns and maintains the article.</description>
        <inlineHelpText>Group which owns and maintains the article.</inlineHelpText>
        <label>Functional Group</label>
        <picklist>
            <picklistValues>
                <fullName>Academic Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Academic Transfer Credit Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admission Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Bookstore</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barrett Honors College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Career Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Changemaker Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Clubs &amp; Organizations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Health Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Integrative Sciences and Arts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Liberal Arts and Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Nursing and Health Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Public Service and Community Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Counseling Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cronkite</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Disability Resource Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Aid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Year Success</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fraternity &amp; Sorority Life</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulton Schools of Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Services</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herberger Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Housing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Int'l Students and Scholars Center</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Internal Knowledge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library Resources</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mary Lou Fulton Teachers College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New College</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Articles containing lists of questions and answers.</description><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><label>FAQ</label><pluralLabel>FAQ</pluralLabel></CustomObject>

src/classes/Test_EmailAlertArticlesController.cls
@isTest
public class Test_EmailAlertArticlesController {
    
    public static FAQ__kav testFAQ;
    public static List<User> lstUser;
    public static List<Group> lstGroup;
    public static List<GroupMember> lstGroupMember;

    
    /*
    Creating Test Data necessary for executing the test class.
    */
    static void testSetup() {
        
        Profile p =[SELECT Id FROM Profile WHERE Name='System Administrator'];
        User testuser1 = new User(Alias = 'standt', Email='testUser1@test.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testUser1@testorg.com');
         
        User testuser2 = new User(Alias = 'standt', Email='testUser2@test.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='testUser2@testorg.com');
            
        lstUser=new List<User>();
        lstUser.add(testuser1);
        lstUser.add(testuser2);
        insert lstUser;
        
        lstGroup=new List<Group>();
        Group testGroup = new Group(Name='Test Group', Type = 'Queue');
        lstGroup.add(testGroup);
        insert lstGroup;
        
        lstGroupMember= new List<GroupMember>();
        GroupMember grpMember1 = new GroupMember(UserOrGroupId=lstUser[0].Id, GroupId=lstGroup[0].Id);
        GroupMember grpMember2 = new GroupMember(UserOrGroupId=lstUser[1].Id, GroupId=lstGroup[0].Id);
        
        lstGroupMember.add(grpMember1);
        lstGroupMember.add(grpMember2);
        insert lstGroupMember;
        
    }
    
    /* 
    Test Method to test Execute Method of EmailAlertArticle Class.
    */
    @isTest static void testExecuteMethod() {
            
            testSetup();
            
            EmailAlertArticlesController testCont = new EmailAlertArticlesController();
            SchedulableContext sc;
            
            Test.startTest();
            testCont.execute(sc);
            Test.stopTest();
    }
    
    /* Test Method to check whether the userIds returned for a queue is correct*/
    @isTest static void testUsersinQueue() {
            testSetup();
            
            Test.startTest();
            EmailAlertArticlesController testCont = new EmailAlertArticlesController();
            Set<Id> setRetUserId = testCont.returnUserIds('Test Group', lstGroup);
            
            Test.stopTest();
            List<Id> lstRetUserId = new List<Id>();
            lstRetUserId.addAll(setRetUserId);
            
            List<Id> checkUserIds = new List<Id>();
            checkUserIds.add(lstUser[0].Id);
            checkUserIds.add(lstUser[1].Id);
            System.assertEquals(lstRetUserId, checkUserIds);
                
    }
    
    /*Test Method to check whether an Email is sent via Apex for a stagnant Article */
    @isTest static void testSendEmail() {
            Integer noOfEmailsSent;
            
            testFAQ= new FAQ__kav(Language='en_US', Title = 'Test Article', UrlName='TestArticle');
            testFAQ.Functional_Group__c='Academic Technologies';
            insert testFAQ;
            
            EmailAlertArticlesController testCont = new EmailAlertArticlesController();
            
            String query = 'SELECT Id,ArticleNumber, Title, PublishStatus,Functional_Group__c, ValidationStatus,Article_Expiration_Date__c ' + 
            'FROM FAQ__kav ' + 
            'WHERE PublishStatus=\'Draft\' ' +
                'AND Language=\'en_US\' ' + 
                'AND (ValidationStatus=\'Draft\' OR ValidationStatus=\'Format Review\' OR ValidationStatus=\'Content Review\')';
            Test.startTest();
            testCont.SendEmail(query, true, false);
            noOfEmailsSent = Limits.getEmailInvocations();
            Test.stopTest();
            
            System.assertEquals(noOfEmailsSent, 1);
            
    }
    
    
    
}