src/objects/Financial_Aid_Package__c.object
<CustomObject>
    <fields>
        <fullName>FA_Status_Time_Stamp__c</fullName>
        <description>[Salesforce] - shows the day and time the financial aid status field was updated.</description>
        <label>FA Status Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Financial_Aid_Status__c</fullName>
        <description>[Peoplesoft] - Status of student’s financial aid file and progress toward completion.</description>
        <label>Financial Aid Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submit a FAFSA</fullName>
                </value>
                <value>
                    <fullName>Complete Your File</fullName>
                </value>
                <value>
                    <fullName>Eligibility Review &amp; Award Notice</fullName>
                </value>
                <value>
                    <fullName>Act on Your Awards</fullName>
                </value>
                <value>
                    <fullName>Disbursement</fullName>
                </value>
                <value>
                    <fullName>Disbursed</fullName>
                </value>
                <value>
                    <fullName>Applied to Account</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Information received from the FAFSA and when the financial aid package is awarded. It includes fields needed for admitted student communication.</description>
    <label>Financial Aid Package</label>
    <nameField>
        <label>Financial Aid Package Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Financial Aid Packages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/FinancialAidPackageHandler.cls
public class FinancialAidPackageHandler implements ITrigger {
    /**
     * bulkBefore
     *
     * This method is called prior to execution of a BEFORE trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkBefore() {
    }

    /**
     * bulkAfter
     *
     * This method is called prior to execution of an AFTER trigger. Use this to cache
     * any data required into maps prior execution of the trigger.
     */
    public void bulkAfter() {
    }

    /**f
     * beforeInsert
     *
     * This method is called iteratively for each record to be inserted during a BEFORE
     * trigger. Never execute any SOQL/SOSL etc in this and other iterative methods.
     */
    public void beforeInsert(SObject so) {
        Financial_Aid_Package__c faPack = (Financial_Aid_Package__c) so;

        //Set the FA Time Stamp to the current time
        faPack.FA_Status_Time_Stamp__c = System.now();
    }

    /**
     * beforeUpdate
     *
     * This method is called iteratively for each record to be updated during a BEFORE
     * trigger.
     */
    public void beforeUpdate(SObject oldSo, SObject so) {
        Financial_Aid_Package__c newFaPack = (Financial_Aid_Package__c) so;
        Financial_Aid_Package__c oldFaPack = (Financial_Aid_Package__c) oldSo;

        //If the FA Status has changed, update the FA Status Time Stamp with the current time
        if (newFaPack.Financial_Aid_Status__c != oldFaPack.Financial_Aid_Status__c) {
            newFaPack.FA_Status_Time_Stamp__c = System.now();
        }
    }

    /**
     * beforeDelete
     *
     * This method is called iteratively for each record to be deleted during a BEFORE
     * trigger.
     */
    public void beforeDelete(SObject so) {
    }

    /**
     * beforeFinally
     *
     * This method is called at the end of the execution of a BEFORE trigger. Use this to finalize
     * any bulk operations for a BEFORE trigger.
     */
    public void beforeFinally() {
    }

    /**
     * afterInsert
     *
     * This method is called iteratively for each record inserted during an AFTER
     * trigger. Always put field validation in the 'After' methods in case another trigger
     * has modified any values. The record is 'read only' by this point.
     */
    public void afterInsert(SObject so) {
    }

    /**
     * afterUpdate
     *
     * This method is called iteratively for each record updated during an AFTER
     * trigger.
     */
    public void afterUpdate(SObject oldSo, SObject so) {
    }

    /**
     * afterDelete
     *
     * This method is called iteratively for each record deleted during an AFTER
     * trigger.
     */
    public void afterDelete(SObject so) {
    }

    /**
     * andFinally
     *
     * This method is called once all records have been processed by the trigger. Use this
     * method to accomplish any final operations such as creation or updates of other records.
     */
    public void andFinally() {
    }
}