src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[import] - Examples include: Undergraduate, Graduate</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Convert_Create_Opportunity__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - If checked, the Conversion process initiated by checking "Convert: Perform Conversion" will result in the creation of a new Opportunity.</description>
        <inlineHelpText>If checked, the Conversion process initiated by checking "Convert: Perform Conversion" will result in the creation of a new Opportunity.</inlineHelpText>
        <label>Convert: Create Opportunity</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Convert_Perform_Conversion__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - If Checked, this Lead will be converted to a Contact record.</description>
        <inlineHelpText>If Checked, this Lead will be converted to a Contact record.</inlineHelpText>
        <label>Convert Lead: Perform Conversion</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the prospective student is the first to attend college from his/her family.</description>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the student meets certain criteria that labels he or she as an international student.</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Potential National Scholar checkbox</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Western Undergraduate Exchange - a prospective student who might be eligible for reduced tuition rate based on the students geographic location and other criteria.</description>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Segment__c</fullName>
        <description>[import] - Examples include: Admissible, Barrett Eligible, Scholar, Under Admissible</description>
        <label>Search Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admissible</fullName>
                </value>
                <value>
                    <fullName>Barrett Eligible</fullName>
                </value>
                <value>
                    <fullName>Scholar</fullName>
                </value>
                <value>
                    <fullName>Under Admissible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Lead_Interest__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Academic_Interest__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[manual import] - Relation to the Acadmeic Intrest</description>
        <label>Academic Interest</label>
        <referenceTo>Academic_Interest__c</referenceTo>
        <relationshipLabel>Lead Interests</relationshipLabel>
        <relationshipName>Lead_Interests_Academic_Interest</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>College__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[manual import] - Relation to the college</description>
        <label>College</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Lead Interests</relationshipLabel>
        <relationshipName>Lead_Interests_Program</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Eligibility__c</fullName>
        <description>[manual import] - Examples include: Qualified, Unqualified, No Longer Interested Field used for recruiting to determine if the Lead meets the requirements of the program.</description>
        <inlineHelpText>Does the Lead meet program requirements?</inlineHelpText>
        <label>Eligibility</label>
        <picklist>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>External_Application_Number__c</fullName>
        <description>[manual import] - Sybase external application number. Used to match Lead Interest with partial application</description>
        <externalId>true</externalId>
        <label>External Application Number</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[manual import] -  Look up to the Plan</description>
        <label>Plan</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Lead Interests</relationshipLabel>
        <relationshipName>Lead_Interests_Plan</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Source__c</fullName>
        <description>[manual import] - Examples include: Advertisement, ASU UG, College Fair - Int, College Fair - US, Email, Employee Referral, Event, Partial App, Phone Call, Purchased List, Test Scores, Walk-in, Web Form</description>
        <label>Source Type</label>
        <picklist>
            <picklistValues>
                <fullName>Advertisement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU UG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Fair - Int</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Fair - US</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Event</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partial App</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Call</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased List</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Test Scores</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Walk-in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web Form</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Qualifying__c</fullName>
        <description>[manual import] - Examples include: Interested, Undecided, No Longer Interested.  Prospective student's level of interest</description>
        <inlineHelpText>Measure of the prospective student's interest.</inlineHelpText>
        <label>Qualifying</label>
        <picklist>
            <picklistValues>
                <fullName>Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undecided</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Longer Interested</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Source__c</fullName>
        <description>[manual import] - Examples include: Coll Technology &amp; Innovation, College of Public Programs, Cronkite School-Journ/MassComm, Graduate Education, Health Solutions, Herberger Institute, Ira A Fulton Engineering, Liberal Arts &amp; Sciences, MaryLouFulton Teachers College, New Interdis Arts &amp; Sciences, Nursing &amp; Health Innovation, School of Letters &amp; Sciences, School of Sustainability, W.P. Carey School of Business, O'Connor College of Law, Degree Search, ASU Online, USA Today, EGSS Applying, EGSS Financing, EGSS GRE Prep, EGSS Personal Statement, Info Session - Online, Info Session - Campus, GRE, GRE Subject, TOEFL, CA Diversity, Idealist, NNE, Graduate College, Sun Devil Days, Saudi Arabiav</description>
        <label>Source Subtype</label>
        <picklist>
            <controllingField>Primary_Source__c</controllingField>
            <picklistValues>
                <fullName>Coll Technology &amp; Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College of Public Programs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cronkite School-Journ/MassComm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Health Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Herberger Institute</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ira A Fulton Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liberal Arts &amp; Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MaryLouFulton Teachers College</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Interdis Arts &amp; Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nursing &amp; Health Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School of Letters &amp; Sciences</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>School of Sustainability</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>W.P. Carey School of Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>O'Connor College of Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Degree Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASU Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USA Today</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGSS Applying</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGSS Financing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGSS GRE Prep</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EGSS Personal Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session - Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Info Session - Campus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GRE Subject</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TOEFL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA Diversity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idealist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NNE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Status__c</fullName>
        <description>[manual import] - Examples include: Active, Applied, Opt Out, Closed, Converted</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Applied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opt Out</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[manual import] - Relationship to the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Lead Interests</relationshipLabel>
        <relationshipName>Lead_Interests_Term</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Test_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[manual import] - Used to flag records as tests so they will not appear in reports.</description>
        <label>Test Record</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Type__c</fullName>
        <description>[manual import] - Examples include: Lead, Contact</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic Interest or Program a prospective student is interested in pursuing. The prospective student can be a Lead or a Contact.</description><enableActivities>true</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>false</enableEnhancedLookup><enableFeeds>true</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Lead Interest</label><nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000000}</displayFormat>
        <label>Lead Interest Key</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Lead Interests</pluralLabel><recordTypeTrackFeedHistory>false</recordTypeTrackFeedHistory><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Applied_This_Month</fullName>
        <columns>Type__c</columns>
        <columns>NAME</columns>
        <columns>Leads__c</columns>
        <columns>Contact__c</columns>
        <columns>Status__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>LAST_UPDATE</columns>
        <columns>UPDATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Status__c</field>
            <operation>equals</operation>
            <value>Applied</value>
        </filters>
        <filters>
            <field>LAST_UPDATE</field>
            <operation>equals</operation>
            <value>THIS_MONTH</value>
        </filters>
        <label>Applied This Month</label>
        <sharedTo />
    </listViews><recordTypes xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>User</fullName>
        <active>true</active>
        <description>Viewable to non-administrators</description>
        <label>User</label>
    </recordTypes><webLinks xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Mass_Delete</fullName>
        <availability>online</availability>
        <description>Used to delete multiple records</description>
        <displayType>massActionButton</displayType>
        <linkType>javascript</linkType>
        <masterLabel>Mass Delete</masterLabel>
        <openType>onClickJavaScript</openType>
        <protected>false</protected>
        <requireRowSelection>true</requireRowSelection>
        <url>{!REQUIRESCRIPT("/soap/ajax/9.0/connection.js")}

var records = {!GETRECORDIDS( $ObjectType.Lead_Interest__c )};

if (records[0] == null) {
alert("Please select at least one record.") }
else {

var errors = [];
var result = sforce.connection.deleteIds(records);
if (result &amp;&amp; result.length){
var numFailed = 0;
var numSucceeded = 0;
for (var i = 0; i &lt; result.length; i++){
var res = result[i];
if (res &amp;&amp; res.success == 'true'){
numSucceeded++;
} else {
var es = res.getArray("errors");
if (es.length &gt; 0) {
errors.push(es[0].message);
}
numFailed++;
}
}
if (numFailed &gt; 0){
alert("Failed: " + numFailed + "\nSucceeded: " + numSucceeded + " \n Due to: " + errors.join("\n"));
} else {
alert("Number of records deleted: " + numSucceeded);
}
}
window.location.reload();
}</url>
    </webLinks><webLinks xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Send_Email</fullName>
        <availability>online</availability>
        <description>Custom action to send an email to either the Lead or Contact depending on which field is populated</description>
        <displayType>button</displayType>
        <linkType>javascript</linkType>
        <masterLabel>Send Email</masterLabel>
        <openType>onClickJavaScript</openType>
        <protected>false</protected>
        <url>location.replace('/email/author/emailauthor.jsp?p2_lkid= {!Lead_Interest__c.Send_Email__c}&amp;rtype=00Q&amp;retURL=%2F{!Lead_Interest__c.Id}&amp;template_id=00Xd00000019nTy')</url>
    </webLinks></CustomObject>

force-app/main/default/objects/Lead_Interest__c/fields/College__c.field-meta.xml
<CustomField>
    <fullName>College__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[manual import] - Relation to the college</description>
    <label>College</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Lead Interests</relationshipLabel>
    <relationshipName>Lead_Interests_Program</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interest__c/fields/Leads__c.field-meta.xml
<CustomField>
    <fullName>Leads__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>[manual import] -  Relationship to the lead</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Lead Interests</relationshipLabel>
    <relationshipName>Lead_Interests_Lead</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interest__c/fields/Plan__c.field-meta.xml
<CustomField>
    <fullName>Plan__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[manual import] -  Look up to the Plan</description>
    <label>Plan</label>
    <referenceTo>Plan__c</referenceTo>
    <relationshipLabel>Lead Interests</relationshipLabel>
    <relationshipName>Lead_Interests_Plan</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead_Interest__c/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[manual import] - Relationship to the term</description>
    <label>Term</label>
    <referenceTo>Term__c</referenceTo>
    <relationshipLabel>Lead Interests</relationshipLabel>
    <relationshipName>Lead_Interests_Term</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Undergraduate, Graduate, Law</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>College__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Salesforce] - College of interest related to the Program object</description>
        <label>College</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1 AND 2) OR (3 AND 4)</booleanFilter>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Graduate Prospect, Graduate Application</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Career__c</field>
                <operation>equals</operation>
                <value>Graduate, Law</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Undergraduate Application, Undergraduate Prospect</value>
            </filterItems>
            <filterItems>
                <field>Program__c.Career__c</field>
                <operation>equals</operation>
                <value>Undergraduate</value>
            </filterItems>
            <infoMessage>If you are unable to find your college or school, please click the link "Show all results"</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[???] - Student is a first generation college student</description>
        <inlineHelpText>Student is a first generation college student</inlineHelpText>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Manual import, purchased lists, prospect forms, F1/J1, webforms] - Checkbox to if student is international</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online_Degree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Webform or manual entry] - Checkbox to indicate they are interested in online education</description>
        <label>Interested in Online Degree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <description>[Salesforce] - Formula field that displays the current associated Admitted/Academic Plan's name.  Used in reports.</description>
        <formula>IF( Admitted_Plan__c &lt;&gt; "", Admitted_Plan__r.Transcript_Description__c  , Academic_Plan__r.Transcript_Description__c )</formula>
        <inlineHelpText>Displays the current associated Admitted/Academic Plan's name</inlineHelpText>
        <label>Plan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[manual import] - Checkbox if the opportunity is a potential National Scholar</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[peoplesoft] - Picklist with the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Plan_Code__c</fullName>
    <businessOwnerGroup>Data_Owner_WPC_Graduate_Programs_Office</businessOwnerGroup>
    <complianceGroup>FERPA</complianceGroup>
    <description>Formula field that displays the Plan's Plan Code.

(Academic_Plan__r.Plan_Code__c)</description>
    <formula>Academic_Plan__r.Plan_Code__c</formula>
    <inlineHelpText>Formula field that displays the Plan's Plan Code.

(Academic_Plan__r.Plan_Code__c)</inlineHelpText>
    <label>Plan Code</label>
    <type>Text</type>
</CustomField>

src/objects/Plan__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASU_Online__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is not being populated by the PeopleSoft import and will be removed.</description>
        <label>(DO NOT USE) ASU Online</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Graduate, Law, Undergraduate</description>
        <label>(DO NOT USE) Career</label>
        <picklist>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Undergraduate</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Degree_Level__c</fullName>
        <description>[Peoplesoft] -  Degree level of respective academic plan.  Examples include: Masters, Doctoral, Juris Doctor, Certificate, Non-Degree</description>
        <label>(DO NOT USE) Degree Level</label>
        <picklist>
            <picklistValues>
                <fullName>Masters</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doctoral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Juris Doctor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Certificate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Degree</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Degree_Search_Name__c</fullName>
        <description>[Peoplesoft] - PS table: ASU_ACADP_EXTNS, PS field: DESCR100</description>
        <label>Degree Search Name</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Degree__c</fullName>
        <description>[??] - Textbook for degree</description>
        <label>Degree</label>
        <length>8</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Diploma_Description__c</fullName>
        <description>[Peoplesoft] - PS table: ACAD_PLAN_TBL,  PS field: DIPLOMA_DESCR</description>
        <label>Diploma Description</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <description>[Peoplesoft] - Code for the plan (major)</description>
        <externalId>true</externalId>
        <label>Plan Code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Effective_Date__c</fullName>
        <description>[Peoplesoft] - Effective date for the plan</description>
        <label>Plan Effective Date</label>
        <required>true</required>
        <type>Date</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Location__c</fullName>
        <description>[Peoplesoft] - Location for the plan</description>
        <label>(DO NOT USE) Plan Location</label>
        <picklist>
            <picklistValues>
                <fullName>Downtown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tempe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Type__c</fullName>
        <description>[Peoplesoft] - Examples include: CER, MAJ, NDG, PBF</description>
        <label>Plan Type</label>
        <picklist>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>COS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MAJ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MIN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PBF</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SPU</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_URL__c</fullName>
        <description>[Peoplesoft] - URL for the plan (major)</description>
        <formula>IF (TEXT( Program__r.Career__c ) = "Non-Credit" || NOT(Available_in_Degree_Search__c),"", 
"https://webapp4.asu.edu/programs/t5/majorinfo/ASU00/"&amp; Plan_Code__c &amp;"/"&amp; 
CASE(TEXT( Program__r.Career__c ), 
"Law", "graduate", 
"Undergraduate", "undergrad", 
LOWER(TEXT( Program__r.Career__c ))) 
&amp;"/false")</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan URL</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Transcript_Description__c</fullName>
        <label>Transcript Description</label>
        <length>255</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Available_in_Degree_Search__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Peoplesoft] - If box is checked, then the degree is available to view in Degree Search.</description>
        <label>Available in Degree Search</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Organization__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Peoplesoft] - Lookup to the Organization Object. PS table: ACAD_PLAN_OWNER, PS field: ACAD_ORG</description>
        <label>Owner Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Status__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Peoplesoft] - Examples include: Active, Teach Out, Inactive</description>
        <label>Plan Status</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Peoplesoft] - Transcript Description textbox</description>
        <label>Program</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Plans</relationshipLabel>
        <relationshipName>Plans</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>eAdvisor_Organization__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[Peoplesoft] - Lookup to the Organization Object.  Eadvisor Oracle database. Table plancollege to get COLLEGE_ACAD_ORG. And then query PS_ACAD_ORG_TBL  to get the DESCRFORMAL using the value of the college_acad_org for ACAD_ORG in PS_ACAD_ORG_TBL.</description>
        <label>eAdvisor Organization</label>
        <referenceTo>Organization__c</referenceTo>
        <relationshipLabel>Plans (eAdvisor Organization)</relationshipLabel>
        <relationshipName>Plans_eAdvisor_Org</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Listing of all Plans (majors)</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Plan</label><nameField>
        <label>Plan Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Plans</pluralLabel><sharingModel>Read</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASU_Online_Plans</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Plan_Location__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Plan_Location__c</field>
            <operation>includes</operation>
            <value>Online</value>
        </filters>
        <filters>
            <field>ASU_Online__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>ASU Online Managed</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Plans</fullName>
        <columns>NAME</columns>
        <columns>Degree_Search_Name__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>eAdvisor_Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Diploma_Description__c</columns>
        <columns>Degree__c</columns>
        <columns>Plan_URL__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>ASU_Online__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <label>All Plans</label>
        <sharedTo>
            <group>QA_Testing_Group</group>
            <role>ES_Enrollment_Services</role>
            <role>ES_Enrollment_Services_Communication</role>
            <role>UTO_University_Technology_Office</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_PlansAvailbleInDS</fullName>
        <columns>NAME</columns>
        <columns>Degree_Search_Name__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>eAdvisor_Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Diploma_Description__c</columns>
        <columns>Degree__c</columns>
        <columns>Plan_URL__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>ASU_Online__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Available_in_Degree_Search__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>All Plans Available in Degree Search</label>
        <sharedTo>
            <group>QA_Testing_Group</group>
            <role>ES_Enrollment_Services</role>
            <role>ES_Enrollment_Services_Communication</role>
            <role>UTO_University_Technology_Office</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_PlanswithDiplomaName</fullName>
        <columns>NAME</columns>
        <columns>Degree_Search_Name__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>eAdvisor_Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Diploma_Description__c</columns>
        <columns>Degree__c</columns>
        <columns>Plan_URL__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>ASU_Online__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Diploma_Description__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filters>
        <label>All Plans with Diploma Name</label>
        <sharedTo>
            <group>QA_Testing_Group</group>
            <role>ES_Enrollment_Services</role>
            <role>ES_Enrollment_Services_Communication</role>
            <role>UTO_University_Technology_Office</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Planswitheadvisorog</fullName>
        <columns>NAME</columns>
        <columns>Degree_Search_Name__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>eAdvisor_Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Diploma_Description__c</columns>
        <columns>Degree__c</columns>
        <columns>Plan_URL__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>ASU_Online__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>eAdvisor_Organization__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filters>
        <label>All Plans with eAdvisor Org</label>
        <sharedTo>
            <group>QA_Testing_Group</group>
            <role>ES_Enrollment_Services</role>
            <role>ES_Enrollment_Services_Communication</role>
            <role>UTO_University_Technology_Office</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Certificate_Plans</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Plan_Location__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Organization__c</columns>
        <columns>Program__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Plan_Type__c</field>
            <operation>equals</operation>
            <value>CER</value>
        </filters>
        <label>Certificate Plans</label>
        <sharedTo>
            <role>GE_Graduate_Education_Manager</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coll_Technology_Innovation</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Coll Technology &amp; Innovation</value>
        </filters>
        <label>Coll Technology &amp; Innovation</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Doctoral_Programs</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Degree_Level__c</field>
            <operation>equals</operation>
            <value>Doctoral</value>
        </filters>
        <label>Doctoral Programs</label>
        <sharedTo>
            <role>GE_Graduate_Education_Manager</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Graduate_College</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Graduate College</value>
        </filters>
        <label>Graduate College</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Health_Solutions</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>ASU_Online__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Health Solutions</value>
        </filters>
        <label>Health Solutions</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Herberger_Institute</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Herberger Institute</value>
        </filters>
        <label>Herberger Institute</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Ira_A_Fulton_Engineering</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Ira A Fulton Engineering</value>
        </filters>
        <filters>
            <field>Plan_Status__c</field>
            <operation>equals</operation>
            <value>true,Active,Teach Out</value>
        </filters>
        <filters>
            <field>Available_in_Degree_Search__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Ira A Fulton Engineering</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Liberal_Arts_Sciences</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>Liberal Arts &amp; Sciences</value>
        </filters>
        <label>Liberal Arts &amp; Sciences</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Major_Plans</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Plan_Type__c</field>
            <operation>equals</operation>
            <value>MAJ</value>
        </filters>
        <label>Major Plans</label>
        <sharedTo>
            <role>GE_Graduate_Education_Manager</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>New_Interdis_Arts_Sciences</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>New Interdis Arts &amp; Sciences</value>
        </filters>
        <label>New Interdis Arts &amp; Sciences</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Degree_Plans</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Program__c</columns>
        <columns>Organization__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Plan_Type__c</field>
            <operation>equals</operation>
            <value>NDG</value>
        </filters>
        <label>Non-Degree Plans</label>
        <sharedTo>
            <role>GE_Graduate_Education_Manager</role>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Online_Plans</fullName>
        <columns>Degree_Search_Name__c</columns>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Program__c</columns>
        <columns>Plan_Effective_Date__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>LAST_UPDATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>ASU_Online__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Online Plans</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Type_nontraditional</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>Degree__c</columns>
        <columns>Available_in_Degree_Search__c</columns>
        <columns>ASU_Online__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Plan_Type__c</field>
            <operation>equals</operation>
            <value>COS,PBF,PRE,PRP,SPU</value>
        </filters>
        <label>Plan Type Non-traditional</label>
        <sharedTo>
            <group>QA_Testing_Group</group>
        </sharedTo>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Public_Affairs</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Organization__c</field>
            <operation>equals</operation>
            <value>School of Public Affairs</value>
        </filters>
        <label>Public Affairs</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Sustainability</fullName>
        <columns>NAME</columns>
        <columns>Degree_Search_Name__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <columns>Diploma_Description__c</columns>
        <columns>eAdvisor_Organization__c</columns>
        <columns>LAST_UPDATE</columns>
        <columns>UPDATEDBY_USER.ALIAS</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>School of Sustainability</value>
        </filters>
        <label>Sustainability</label>
        <sharedTo />
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>WP_Carey_School_of_Business</fullName>
        <columns>NAME</columns>
        <columns>Plan_Code__c</columns>
        <columns>Organization__c</columns>
        <columns>Plan_Status__c</columns>
        <columns>Plan_Type__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Program__c</field>
            <operation>equals</operation>
            <value>W.P. Carey School of Business</value>
        </filters>
        <label>WP Carey School of Business</label>
        <sharedTo />
    </listViews></CustomObject>

force-app/main/default/objects/Plan__c/fields/Career__c.field-meta.xml
<CustomField>
    <fullName>Career__c</fullName>
    <description>[Peoplesoft] - Examples include: Graduate, Law, Undergraduate</description>
    <label>(DO NOT USE) Career</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>Law</fullName>
            </value>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Code__c.field-meta.xml
<CustomField>
    <fullName>Plan_Code__c</fullName>
    <description>[Peoplesoft] - Code for the plan (major)</description>
    <externalId>true</externalId>
    <label>Plan Code</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Plan_Effective_Date__c.field-meta.xml
<CustomField>
    <fullName>Plan_Effective_Date__c</fullName>
    <description>[Peoplesoft] - Effective date for the plan</description>
    <label>Plan Effective Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Plan__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>[Peoplesoft] - Transcript Description textbox</description>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Plans</relationshipLabel>
    <relationshipName>Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Program__c.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples inlcude: Graduate, Law, Non-Credit, Undergraduate</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
                <value>
                    <fullName>Non-Credit</fullName>
                </value>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Code__c</fullName>
        <description>[Peoplesoft] - Code for the program (College)</description>
        <externalId>true</externalId>
        <label>Program Code</label>
        <length>10</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Listing of all University programs (Colleges)</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/Test_LeadHandler.cls
@isTest
public with sharing class Test_LeadHandler 
{
    // Build Leads    
    static List<Lead> createLeads (Integer quantity) 
    {
        List<Lead> leadList = new List<Lead>();
        
        for (Integer i=0;i<quantity;i++) 
        {
            Lead l = new Lead(LastName='LName'+i, 
                              FirstName='FName'+i,
                              Company='Company', 
                              Email='test'+i+'@test.test', 
                              LeadSource='Email');
            leadList.add(l);
        }

        return leadList;
    }
    
    // Build Lead Interests
    static Id insertProgram(String programName, String programCode) 
    {
        Program__c testProgram = new Program__c(Name=programName, Program_Code__c = programCode);
        insert testProgram;
        return testProgram.Id;
    }
    
    static Id insertPlan(String planName, String planCode, Id programId) 
    {
        Plan__c testPlan = new Plan__c(Name = planName, Plan_Code__c = planCode,Plan_Effective_Date__c = Date.today(), Program__c = programId);
        insert testPlan;
        return testPlan.Id;     
    }
    
    static List<Lead_Interest__c> createLeadInterests(List<Lead> associatedLeads) 
    {
        List<Lead_Interest__c> liList = new List<Lead_Interest__c>();

        Id program1 = insertProgram('Program1', 'P1');
        Id plan1 = insertPlan('Plan1', 'PL1', program1);

        for (Lead l: associatedLeads) 
        {
            Lead_Interest__c li = new Lead_Interest__c(College__c=program1, Plan__c=plan1, Leads__c=l.Id);
            liList.add(li);
        }

        System.debug('Lead Interests: ' + liList);
        
        return liList;
    }

//    @isTest static void testLeadHandler()
//    {
//        Integer numberOfLeads = 200;
//        Lead[] leadList = createLeads(numberOfLeads);
//        insert leadList;
//
//        Lead_Interest__c[] liList = createLeadInterests(leadList);
//        insert liList;
//
//        Set<Id> leadIds = new Set<Id>();
//
//        // Perform Conversion
//        for (Lead l: leadList)
//        {
//            l.Convert_Perform_Conversion__c = true;
//            leadIds.add(l.Id);
//        }
//
//        update leadList;
//
//        //Check conversion results
//        List<Lead> convertedLeads = new List<Lead>([SELECT Id FROM Lead WHERE Id IN :leadIds AND IsConverted = true]);
//
//        System.assertEquals(numberOfLeads, convertedLeads.size());
//    }

    @isTest static void testLeadToOppFieldMapping()
    {
        List<Lead> testLeads = LeadService.createTestLeads(10);
        insert testLeads;

        Set<Id> leadIds = new Set<Id>();
        Set<Id> contactIds = new Set<Id>();

        // Perform conversion
        for (Lead l : testLeads)
        {
            l.Convert_Perform_Conversion__c = true;
            l.Convert_Create_Opportunity__c = true;
            leadIds.add(l.Id);
        }

        Test.startTest();
        update testLeads;
        Test.stopTest();

        List<Lead> convertedContacts = [
                SELECT ConvertedContactId
                FROM Lead
        ];

        System.debug('Lead data ' + convertedContacts);

        for (Lead l : convertedContacts)
        {
            contactIds.add(l.ConvertedContactId);
        }

        System.debug('Converted Contacts: ' + contactIds);

        List<Opportunity> oppsCreated = [
                SELECT Career__c, Term__c, Online_Degree__c, International_Student__c, First_Generation__c, Potential_National_Scholar__c, Potential_WUE__c, Search_Segment__c, Self_Reported_SES__c, Military_Status__c
                FROM Opportunity
                WHERE Contact__c IN :contactIds
        ];


        Lead expectedData = testLeads.get(0);
        Opportunity actualData = oppsCreated.get(0);

        System.assertEquals(expectedData.Career__c, actualData.Career__c, 'Career was not converted correctly');
    }
}