src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[import] - Examples include: Undergraduate, Graduate</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Enrollment_Term__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>[import] - Look up to the term object</description>
        <label>Enrollment Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Lead_Term</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the prospective student is the first to attend college from his/her family.</description>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Indicates the student meets certain criteria that labels he or she as an international student.</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Online__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Web form question: Check here if interested in earning your degree exclusively Online</description>
        <inlineHelpText>If checked, the student is interested in earning their degree online.</inlineHelpText>
        <label>Interested in Online Degree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Potential National Scholar checkbox</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[import] - Western Undergraduate Exchange - a prospective student who might be eligible for reduced tuition rate based on the students geographic location and other criteria.</description>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Segment__c</fullName>
        <description>[import] - Examples include: Admissible, Barrett Eligible, Scholar, Under Admissible</description>
        <label>Search Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admissible</fullName>
                </value>
                <value>
                    <fullName>Barrett Eligible</fullName>
                </value>
                <value>
                    <fullName>Scholar</fullName>
                </value>
                <value>
                    <fullName>Under Admissible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Self_Reported_SES__c</fullName>
        <description>Socioeconomic status (SES) is determined by a combination of parental income, 
education, occupation, and household items.</description>
        <inlineHelpText>Socioeconomic status reported by the prospective student.</inlineHelpText>
        <label>Self-Reported SES</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Very High</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Veteran_Status__c</fullName>
        <description>[import] - Graduate College prospect and Degree Search web form selection.  Examples include: I am active duty, I am a veteran, I am a spouse or dependent of an active duty or veteran, National Guard, Reserves</description>
        <label>Veteran Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Duty</fullName>
                </value>
                <value>
                    <fullName>National Guard</fullName>
                </value>
                <value>
                    <fullName>Reserves</fullName>
                </value>
                <value>
                    <fullName>Spouse/Dependent</fullName>
                </value>
                <value>
                    <fullName>Veteran</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Career__c</fullName>
        <description>[Peoplesoft] - Examples include: Undergraduate, Graduate, Law</description>
        <label>Career</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Undergraduate</fullName>
                </value>
                <value>
                    <fullName>Graduate</fullName>
                </value>
                <value>
                    <fullName>Law</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[Salesforce] - Relationship to the Contact object</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>First_Generation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[???] - Student is a first generation college student</description>
        <inlineHelpText>Student is a first generation college student</inlineHelpText>
        <label>First Generation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>International_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Manual import, purchased lists, prospect forms, F1/J1, webforms] - Checkbox to if student is international</description>
        <label>International Student</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Military_Status__c</fullName>
        <description>[Self-reported] - From the prospective student or the supplemental application. It has not been confirmed.Examples include: Active Duty, National Guard, Veteran, Spouse/Dependent, Armed Forces Reserve</description>
        <inlineHelpText>Self-reported from the prospective student or the supplemental application. It has not been confirmed.</inlineHelpText>
        <label>Military Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Active Duty</fullName>
                </value>
                <value>
                    <fullName>Armed Forces Reserve</fullName>
                </value>
                <value>
                    <fullName>National Guard</fullName>
                </value>
                <value>
                    <fullName>Spouse/Dependent</fullName>
                </value>
                <value>
                    <fullName>Veteran</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Online_Degree__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[Webform or manual entry] - Checkbox to indicate they are interested in online education</description>
        <label>Interested in Online Degree</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_National_Scholar__c</fullName>
        <defaultValue>false</defaultValue>
        <description>[manual import] - Checkbox if the opportunity is a potential National Scholar</description>
        <label>Potential National Scholar</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Potential_WUE__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential WUE</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Search_Segment__c</fullName>
        <description>[??] - Examples Include: Admissible, Barrett Eligible, Scholar, Under Admissible</description>
        <label>Search Segment</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Admissible</fullName>
                </value>
                <value>
                    <fullName>Barrett Eligible</fullName>
                </value>
                <value>
                    <fullName>Scholar</fullName>
                </value>
                <value>
                    <fullName>Under Admissible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Self_Reported_SES__c</fullName>
        <description>Socioeconomic status (SES) is determined by a combination of parental income, 
education, occupation, and household items.</description>
        <inlineHelpText>Socioeconomic status reported by the prospective student.</inlineHelpText>
        <label>Self-Reported SES</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Very High</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Moderate</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Very Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[peoplesoft] - Picklist with the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Term__c.object
<CustomObject><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

src/classes/LeadService.cls
public with sharing class LeadService 
{
	public static Lead createTestLead() 
	{
		Lead testLead = new Lead();
        testLead.FirstName = 'Jonny';
        testLead.LastName = 'Test';
        testLead.Email = 'test@nomail.com';
        testLead.Company = 'Test Company';
		return testLead;
	}

    public static List<Opportunity> mapLeadDataToOpportunity(Set<Id> leadIds)
    {
        List<Lead> leadsFromConversion = new List<Lead>();
        Map<Id, Lead> contactIdToLeadMap= new Map<Id, Lead>();
        List<Opportunity> opportunitiesToUpdate = new List<Opportunity>();

        leadsFromConversion = [
                SELECT ConvertedContactId, Career__c, Enrollment_Term__c, First_Generation__c, Online__c, International_Student__c, Potential_National_Scholar__c, Potential_WUE__c, Search_Segment__c, Self_Reported_SES__c, Veteran_Status__c
                FROM Lead
                WHERE Id IN :leadIds
        ];

        for (Lead newLead : leadsFromConversion)
        {
            contactIdToLeadMap.put(newLead.ConvertedContactId, newLead);
        }

        Set<Id> contactIds = contactIdToLeadMap.keySet();

        // Get all the opportunities associated with these contacts
        opportunitiesToUpdate = [SELECT Id FROM Opportunity WHERE Id IN :contactIds];

        // Update all the opportunity information
        for (Opportunity opp : opportunitiesToUpdate)
        {
            Lead leadData = contactIdToLeadMap.get(opp.Contact__c);

            opp.Career__c = leadData.Career__c;
            opp.Term__c = leadData.Enrollment_Term__c;
            opp.First_Generation__c = leadData.First_Generation__c;
            opp.Online_Degree__c = leadData.Online__c;
            opp.International_Student__c = leadData.International_Student__c;
            opp.Potential_National_Scholar__c = leadData.Potential_National_Scholar__c;
            opp.Potential_WUE__c = leadData.Potential_WUE__c;
            opp.Search_Segment__c = leadData.Search_Segment__c;
            opp.Self_Reported_SES__c = leadData.Self_Reported_SES__c;
            opp.Military_Status__c = leadData.Veteran_Status__c;
        }

        return opportunitiesToUpdate;
    }
}