src/objects/Location__c.object
<CustomObject>
    <description>Campus

Location records are manually entered at this time.  
Review SFE-2602 for details of why and how this object works.</description>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Campus__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Data sourced from PS_ACAD_PROG.CAMPUS</description>
        <label>Campus</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Student Program Plans</relationshipLabel>
        <relationshipName>Student_Program_Plans</relationshipName>
        <type>Lookup</type>
    </fields><fields>
        <fullName>Career__c</fullName>
        <description>Data sourced from PS_ACAD_CAR_TBL.DESCR</description>
        <label>Career</label>
        <picklist>
            <picklistValues>
                <fullName>Undergraduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Completion_Term__c</fullName>
        <description>Data sourced from PS_TERM_TBL.DESCR</description>
        <label>Completion Term</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Degree__c</fullName>
        <description>Data sourced from PS_ACAD_PLAN_TBL.Degree</description>
        <label>Degree</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Effective_Date__c</fullName>
        <description>Data sourced from PS_ACAD_PROG.EFFDT</description>
        <label>Effective Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Plan_Description__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.DESCR</description>
        <label>Plan Description</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Plan_Type_Text__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.ACAD_PLAN_TYPE</description>
        <label>Plan Type</label>
        <length>3</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Primary_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Data sourced from PS_STDNT_PROFILE_MAJ_CURRENT.ASU_PRIME_REC_FLG</description>
        <label>Primary Flag</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Program_Description__c</fullName>
        <description>Data sourced from ACAD_PROG_TBL.DESCR</description>
        <label>Program Description</label>
        <length>100</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Data sourced from PS_ACAD_PROG.ASU_PROGSTATUS1</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active in Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/Student_Program_Plan__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Data sourced from PS_ACAD_PROG.EMPLID</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Student Program Plans</relationshipLabel>
    <relationshipName>Student_Plans</relationshipName>
    <type>Lookup</type>
</CustomField>

src/classes/StudentProgramPlanService.cls
public class StudentProgramPlanService
{
    public static List<PlanWrapper> planList;
    

    /**
    * Get the Student Program Plans for this contact
    * @param the contact Id
    * @return a list of Student Program Plans for that contact
    */
    public static List<Student_Program_Plan__c> getContactStudentProgramPlans(Id contactId)
    {
        String sPPFields = 
            'Status__c, Primary_Flag__c, Completion_Term__c, Plan_Type_Text__c, ' +
            'Plan_Description__c, Career__c, Program_Description__c, Degree__c';
                    
        String selectStudentPP = 'SELECT ' + sPPFields + ' ' +
                ', Campus__r.Name ' +
            'FROM Student_Program_Plan__c ' +
            'WHERE Contact__c = :contactId ' +
            'ORDER BY Status__c, Primary_Flag__c DESC, Completion_Term__c DESC, Plan_Type_Text__c, Plan_Description__c';
        
        List<Student_Program_Plan__c> sPPList = Database.query(selectStudentPP);
        
        // TODO: Re-factor the StudentProfileController to accept the wrapper class rather than the Student_Program_Plan__c
        // sObject. This will result in cleaner code, and allow us to eliminate some inefficiency here.
        
        planList = new List<PlanWrapper>();
        
        for (Student_Program_Plan__c plan : sPPList) {
            planList.add(new PlanWrapper(plan));
        }

        planList.sort();
        
        sPPList = new List<Student_Program_Plan__c>();
        
        for (PlanWrapper w : planList) {
            sPPList.add(w.plan);
        }
        
    	return sPPList;
    }

    /**
    * Get the Student Program Plans before today's date for this contact
    * @param the contact Id
    * @return a list of Student Program Plans for that contact
    */
    public static List<Student_Program_Plan__c> getContactStudentProgramPlansBeforeToday(
        Id contactId
    )
    {
        String sPPFields = 
            'Status__c, Primary_Flag__c, Completion_Term__c, Plan_Type_Text__c, ' +
            'Plan_Description__c, Career__c, Program_Description__c, Degree__c';
        
        List<Student_Program_Plan__c> programPlans = new List<Student_Program_Plan__c>();

        String selectStudentPP = 'SELECT ' + sPPFields + ' ' +
            ', Campus__r.Name ' +
            'FROM Student_Program_Plan__c ' +
            'WHERE Contact__c = :contactId ' +
            'AND Effective_Date__c <= TODAY ' +
            'ORDER BY Status__c, Primary_Flag__c DESC, Completion_Term__c DESC, Plan_Type_Text__c, Plan_Description__c';

        List<Student_Program_Plan__c> sPPList = Database.query(selectStudentPP);

        // TODO: Re-factor the StudentProfileController to accept the wrapper class rather than the Student_Program_Plan__c
        // sObject. This will result in cleaner code, and allow us to eliminate some inefficiency here.
        
        planList = new List<PlanWrapper>();
        
        for (Student_Program_Plan__c plan : sPPList) {
            planList.add(new PlanWrapper(plan));
        }

        planList.sort();
        
        sPPList = new List<Student_Program_Plan__c>();
        
        for (PlanWrapper w : planList) {
            sPPList.add(w.plan);
        }
        
    	return sPPList;
    }
    
    public class PlanWrapper implements Comparable {
        public Student_Program_Plan__c plan;
        
        public Map<String, Integer> planTypeMap = 
        	new Map<String, Integer>{'MAJ' => 0, 'MIN' => 1, 'CER' => 2};
        
        PlanWrapper(Student_Program_Plan__c p) {
            this.plan = p;
        }
        
        // Allows for sorting of the Program Plan list by Status ASC, Primary Flag DESC,
        // Completion Term ASC, Plan Type (MAJ, MIN, CER), and Plan Description (ASC).
        public Integer compareTo(Object compareTo) {
            PlanWrapper compareToPlan = (PlanWrapper)compareTo;
            
            if (this.plan.Status__c == compareToPlan.plan.Status__c) {
                if (this.plan.Primary_Flag__c == compareToPlan.plan.Primary_Flag__c) {
                    if (this.plan.Completion_Term__c == compareToPlan.plan.Completion_Term__c) {
                        if (this.plan.Plan_Type_Text__c == compareToPlan.plan.Plan_Type_Text__c) {
                            if (this.plan.Plan_Description__c == compareToPlan.plan.Plan_Description__c) {
                                return 0;
                            }
                            
                            if (this.plan.Plan_Description__c > compareToPlan.plan.Plan_Description__c) {
                                return 1;
                            }
                            
                            return -1;
                        }
                        
                        if (this.planTypeMap.get(this.plan.Plan_Type_Text__c) > this.planTypeMap.get(compareToPlan.plan.Plan_Type_Text__c)) {
                            return 1;
                        }
                        
                        return -1;
                    }
                    
                    if (this.plan.Completion_Term__c < compareToPlan.plan.Completion_Term__c) {
                        return 1;
                    }
                    
                    return -1;
                }
                         	
                if (String.valueOf(this.plan.Primary_Flag__c) < String.valueOf(compareToPlan.plan.Primary_Flag__c)) {
                    return 1;
                }
                
                return -1;
            }
            
            if (this.plan.Status__c > compareToPlan.plan.Status__c) {
                return 1;
            }
            
            return -1;
        }
    }
}