src/objects/PS_ASU_SP_TRNSFR_V__x.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ACAD_CAREER__c</fullName>
        <description>Data sourced from PS_TRNS_TEST_DTL.ACAD_CAREER</description>
        <externalDeveloperName>ACAD_CAREER</externalDeveloperName>
        <label>Career</label>
        <length>4</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>COURSE_TITLE__c</fullName>
        <description>Data sourced from PS_CRSE_CAT_TC_VW.SUBJECT_SRCH, CATALOG_NBR_SRCH</description>
        <externalDeveloperName>COURSE_TITLE</externalDeveloperName>
        <label>Course Code</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>SCORE__c</fullName>
        <description>Data sourced from PS_TRNS_TEST_DTL.SCORE</description>
        <externalDeveloperName>SCORE</externalDeveloperName>
        <label>Score</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>STRM__c</fullName>
        <description>Data sourced from PS_TRNS_TEST_DTL.ARTICULATION_TERM</description>
        <externalDeveloperName>STRM</externalDeveloperName>
        <label>Term</label>
        <length>4</length>
        <referenceTargetField>Term__c.PeopleSoft_Code__c</referenceTargetField>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Transfer Class By Exam (external)</relationshipLabel>
        <relationshipName>Transfer_Class_By_Exam_external</relationshipName>
        <type>IndirectLookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>TITLE__c</fullName>
        <description>Data sourced from PS_CRSE_CAT_TC_VW.DESCR</description>
        <externalDeveloperName>TITLE</externalDeveloperName>
        <label>Course Title</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UNT_TRNSFR__c</fullName>
        <description>Data sourced from PS_TRNS_TEST_DTL.UNT_TRNSFR</description>
        <externalDeveloperName>UNT_TRNSFR</externalDeveloperName>
        <label>Units Transferred</label>
        <precision>9</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields><deploymentStatus>Deployed</deploymentStatus><description>Data source script can be found here: https://docs.google.com/document/d/1EeZWZpJHLU3B1d-Vsr5xvtlz9u4BggL7wPHobkqEU3c/edit</description><enableFeeds>false</enableFeeds><enableReports>false</enableReports><enableSearch>false</enableSearch><externalDataSource>asu_ps_lightning</externalDataSource><externalName>PS_ASU_SP_TRNSFR_V</externalName><label>Transfer Class By Exam (external)</label><pluralLabel>Transfer Class By Exam (external)</pluralLabel></CustomObject>

force-app/main/default/objects/PS_ASU_SP_TRNSFR_V__x/fields/COURSE_TITLE__c.field-meta.xml
<CustomField>
    <fullName>COURSE_TITLE__c</fullName>
    <description>Data sourced from PS_CRSE_CAT_TC_VW.SUBJECT_SRCH, CATALOG_NBR_SRCH</description>
    <externalDeveloperName>COURSE_TITLE</externalDeveloperName>
    <label>Course Code</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_ASU_SP_TRNSFR_V__x/fields/SCORE__c.field-meta.xml
<CustomField>
    <fullName>SCORE__c</fullName>
    <description>Data sourced from PS_TRNS_TEST_DTL.SCORE</description>
    <externalDeveloperName>SCORE</externalDeveloperName>
    <label>Score</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PS_ASU_SP_TRNSFR_V__x/fields/TITLE__c.field-meta.xml
<CustomField>
    <fullName>TITLE__c</fullName>
    <description>Data sourced from PS_CRSE_CAT_TC_VW.DESCR</description>
    <externalDeveloperName>TITLE</externalDeveloperName>
    <label>Course Title</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PS_ASU_SP_TRNSFR_V__x/fields/UNT_TRNSFR__c.field-meta.xml
<CustomField>
    <fullName>UNT_TRNSFR__c</fullName>
    <description>Data sourced from PS_TRNS_TEST_DTL.UNT_TRNSFR</description>
    <externalDeveloperName>UNT_TRNSFR</externalDeveloperName>
    <label>Units Transferred</label>
    <precision>9</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/StudentProfileExamSortableTest.cls
@isTest
public with sharing class StudentProfileExamSortableTest {
    @isTest
    private static void testSortByTitle() {
        String sortBy = 'Title';

        StudentProfileExamSortable eq1 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(TITLE__c = 'Literature'),
            sortBy
        );
        StudentProfileExamSortable eq2 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(TITLE__c = 'Literature'),
            sortBy
        );
        StudentProfileExamSortable lesser = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(TITLE__c = 'History'),
            sortBy
        );
        StudentProfileExamSortable greater = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(TITLE__c = 'Politics'),
            sortBy
        );

        System.assert(0 > lesser.compareTo(greater));
        System.assert(0 < greater.compareTo(lesser));
        System.assertEquals(0, eq1.compareTo(eq2));
    }

    @isTest
    private static void testSortByCourseTitle() {
        String sortBy = 'Course Title';

        StudentProfileExamSortable eq1 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(COURSE_TITLE__c = 'First-Year Composition'),
            sortBy
        );
        StudentProfileExamSortable eq2 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(COURSE_TITLE__c = 'First-Year Composition'),
            sortBy
        );
        StudentProfileExamSortable lesser = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(COURSE_TITLE__c = 'American History 1870-1940'),
            sortBy
        );
        StudentProfileExamSortable greater = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(COURSE_TITLE__c = 'Geopolitical Conflicts in the Eastern World'),
            sortBy
        );

        System.assert(0 > lesser.compareTo(greater));
        System.assert(0 < greater.compareTo(lesser));
        System.assertEquals(0, eq1.compareTo(eq2));
    }

    @isTest
    private static void testSortByScore() {
        String sortBy = 'Score';

        StudentProfileExamSortable eq1 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(SCORE__c = 80),
            sortBy
        );
        StudentProfileExamSortable eq2 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(SCORE__c = 80),
            sortBy
        );
        StudentProfileExamSortable lesser = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(SCORE__c = 30),
            sortBy
        );
        StudentProfileExamSortable greater = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(SCORE__c = 90),
            sortBy
        );

        System.assert(0 < lesser.compareTo(greater));
        System.assert(0 > greater.compareTo(lesser));
        System.assertEquals(0, eq1.compareTo(eq2));
    }

    @isTest
    private static void testSortByTransfer() {
        String sortBy = 'Transfer';

        StudentProfileExamSortable eq1 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 50),
            sortBy
        );
        StudentProfileExamSortable eq2 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 50),
            sortBy
        );
        StudentProfileExamSortable lesser = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 20),
            sortBy
        );
        StudentProfileExamSortable greater = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 80),
            sortBy
        );

        System.assert(0 < lesser.compareTo(greater));
        System.assert(0 > greater.compareTo(lesser));
        System.assertEquals(0, eq1.compareTo(eq2));
    }

    @isTest
    private static void testSortByInvalidType() {
        String sortBy = 'INVALID';

        StudentProfileExamSortable eq1 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 50),
            sortBy
        );
        StudentProfileExamSortable eq2 = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 50),
            sortBy
        );
        StudentProfileExamSortable lesser = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 20),
            sortBy
        );
        StudentProfileExamSortable greater = new StudentProfileExamSortable(
            new PS_ASU_SP_TRNSFR_V__x(UNT_TRNSFR__c = 80),
            sortBy
        );

        System.assertEquals(0, lesser.compareTo(greater));
        System.assertEquals(0, greater.compareTo(lesser));
        System.assertEquals(0, eq1.compareTo(eq2));
    }
}