src/objects/Service_Center_Maintenance__c.object
<CustomObject><fields>
        <fullName>Displayed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox that decides if the message is displayed on the page.</description>
        <label>Displayed</label>
        <type>Checkbox</type>
    </fields><fields>
        <fullName>Message__c</fullName>
        <description>The message to be displayed on the service center</description>
        <label>Message</label>
        <required>true</required>
        <type>TextArea</type>
    </fields><customSettingsType>List</customSettingsType><description>Custom object that displays service center maintenance messages</description><enableFeeds>false</enableFeeds><label>Service Center Maintenance</label><visibility>Public</visibility></CustomObject>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>Session_A_C_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin</description>
        <label>Session A/C Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Session_B_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin for Session B</description>
        <label>Session B Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Year__c</fullName>
        <description>[Peoplesoft] - Year</description>
        <label>Year</label>
        <length>4</length>
        <required>true</required>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

src/classes/Test_NavLinks.cls
@isTest
private class Test_NavLinks
{
    private static Contact testContact;
    private static NavLinks nav;
    private static Profile p;
    private static ServiceCenter sc;
    private static User testUser;

    private static void setUp()
    {
        p = [
            SELECT Id
            FROM Profile
            WHERE Name = 'ASU Community'
        ];

        Term__c termAC = new Term__c();
        Date dT = Date.today().adddays(30);
        termAC.Session_A_C_Start_Date__c = date.newinstance(dT.year(), dT.month(), dT.day());
        termAC.Year__c = '2015';

        insert termAC;

        Term__c termB = new Term__c();
        dT = Date.today().adddays(40);
        termB.Session_B_Start_Date__c = date.newinstance(dT.year(), dT.month(), dT.day());
        termB.Year__c = '2015';

        insert termB;

        Service_Center_Maintenance__c scm = new Service_Center_Maintenance__c(
            Name = 'The Test Message',
            Displayed__c = true,
            Message__c = 'There is maintenance'
        );

        insert scm;

        testContact = ContactService.createTestContact();

        insert testContact;

        testUser = UserService.createTestUser();
        testUser.ProfileId = p.Id;
        testUser.ContactId = testContact.Id;

        insert testUser;

        PageReference serviceCenter = Page.studentSC;
        Test.setCurrentPage(serviceCenter);
    }

    @isTest static void testInitNoParm()
    {
        setUp();
        Test.startTest();
        System.runAs(testUser)
        {
            sc = new ServiceCenter();
            nav = new Navlinks(sc);
            nav.init();
        }

        Test.stopTest();
    }

    @isTest static void testInitParm()
    {
        setUp();
        Test.startTest();
        System.runAs(testUser)
        {
            sc = new ServiceCenter();
            nav = new NavLinks(sc);
            ApexPages.currentPage().getParameters().put('asuriteId', 'aesanch2');
            ApexPages.currentPage().getParameters().put('time', '1417811918');
            ApexPages.currentPage().getParameters().put('signature',
                'a8539563d36219e592c3376dae079d38887cc9af8374d74929bdf48bb655b93f');
            ApexPages.currentPage().getParameters().put('navbar',
                '{"navbarLinks":[{"Home":"https://webapp4-dev.asu.edu/myasu/student"},' +
                '{"Finances":"https://webapp4-dev.asu.edu/myasu/student/finances"},' +
                '{"Service Center":"https://webapp4-dev.asu.edu/myasu/student/servicecenter"},' +
                '{"Campus Services":"https://webapp4-dev.asu.edu/myasu/student/campusservices"},' +
                '{"Profile":"https://webapp4-dev.asu.edu/myasu/student/profile"}]}');
            nav.init();
            System.debug('merf linkList map ' + nav.linkList);
        }

        Test.stopTest();
    }

    @isTest static void testConstructors()
    {
        setUp();
        Test.startTest();
        System.runAs(testUser)
        {
            sc = new ServiceCenter();
            Navlinks scNav = new Navlinks(sc);
            Contact testContact2 = ContactService.createTestContact();
            ApexPages.StandardController stanContoller = new ApexPages.StandardController(testContact);
            NavLinks standardNav = new Navlinks(stanContoller);
        }

        Test.stopTest();
    }
}