src/objects/StudentTerm__c.object
<CustomObject>
    <fields>
        <fullName>CurrTerm__c</fullName>
        <description>Current Term at ASU</description>
        <label>CurrTerm</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>NextTerm__c</fullName>
        <description>Next Term Coming up</description>
        <label>NextTerm</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PrevTerm__c</fullName>
        <description>Previous term at ASU</description>
        <label>PrevTerm</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the previous, current, and future term.</description>
    <label>StudentTerm</label>
</CustomObject>

force-app/main/default/objects/StudentTerm__c/fields/FutureTerm__c.field-meta.xml
<CustomField>
    <fullName>FutureTerm__c</fullName>
    <description>The term following the term after the current term.</description>
    <inlineHelpText>Previous → Current → Next → FUTURE TERM</inlineHelpText>
    <label>FutureTerm</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>PeopleSoft_Code__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>[Peoplesoft] - Peoplesoft code</description>
        <externalId>true</externalId>
        <label>PeopleSoft Code</label>
        <length>4</length>
        <type>Text</type>
        <unique>true</unique>
    </fields><fields>
        <fullName>Session_A_C_Close_Date__c</fullName>
        <description>[Peoplesoft] - 21st Day of the Session</description>
        <label>Session A/C Close Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/classes/UpdateTerm.cls
public class UpdateTerm implements Schedulable {
    public void execute(SchedulableContext sc) {
        StudentTerm__c currentTermData = StudentTerm__c.getOrgDefaults();
        Term__c currentTermInfo = [
            SELECT PeopleSoft_Code__c
            FROM Term__c
            WHERE
                Session_A_C_Close_Date__c >= TODAY
                AND (PeopleSoft_Code__c LIKE '%1'
                OR PeopleSoft_Code__c LIKE '%4'
                OR PeopleSoft_Code__c LIKE '%7')
            ORDER BY PeopleSoft_Code__c ASC
            LIMIT 1
        ];

        currentTermData.CurrTerm__c = currentTermInfo.PeopleSoft_Code__c;
        if (currentTermInfo.PeopleSoft_Code__c.right(1) == '1') {
            //spring
            currentTermData.PrevTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) - 4);
            currentTermData.NextTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 3);
            currentTermData.FutureTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 6);
        } else if (currentTermInfo.PeopleSoft_Code__c.right(1) == '4') {
            //summer
            currentTermData.PrevTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) - 3);
            currentTermData.NextTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 3);
            currentTermData.FutureTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 7);
        } else {
            //fall
            currentTermData.PrevTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) - 3);
            currentTermData.NextTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 4);
            currentTermData.FutureTerm__c = String.valueOf(Integer.valueOf(currentTermInfo.PeopleSoft_Code__c) + 7);
        }

        update currentTermData;
    }
}