src/objects/Student_Program_Plan__c.object
<CustomObject><fields>
        <fullName>Career__c</fullName>
        <description>Data sourced from PS_ACAD_CAR_TBL.DESCR</description>
        <label>Career</label>
        <picklist>
            <picklistValues>
                <fullName>Undergraduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>Plan_Code__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.ACAD_PLAN</description>
        <label>Plan Code</label>
        <length>25</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Plan_Description__c</fullName>
        <description>Data sourced from ACAD_PLAN_TBL.DESCR</description>
        <label>Plan Description</label>
        <length>30</length>
        <type>Text</type>
    </fields><fields>
        <fullName>Status__c</fullName>
        <description>Data sourced from PS_ACAD_PROG.ASU_PROGSTATUS1</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active in Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed Program</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discontinued</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic History of student's enrollment. Lists the related College (Program) and Major (Plan) with its current status.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Student Program Plan</label><nameField>
        <displayFormat>{000000}-{YYYY}-{MM}-{DD}</displayFormat>
        <label>Details</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Student Program Plans</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/classes/AutoSubscriberFilterHelper.cls
public with sharing class AutoSubscriberFilterHelper {
    public static Boolean filterProgramPlan(String methodTocall, Student_Program_Plan__c planToCheck) {
        switch on methodToCall {
            when 'Graduate_College' {
                return graduateCollegeForStudentProgramPlan(planToCheck);
            }
            when else {
                return false;
            }
        }
    }

    public static Boolean filterCampaignMember(String methodTocall, CampaignMember memberToCheck) {
        switch on methodToCall {
            when 'Access_Asu' {
                return accessAsuForCampaignMember(memberToCheck);
            }
            when else {
                return false;
            }
        }
    }

    public static Boolean graduateCollegeForStudentProgramPlan(Student_Program_Plan__c planToCheck) {
        if (
            planToCheck.Career__c == 'Graduate' &&
            planToCheck.Status__c == 'Active In Program' &&
            planToCheck.Plan_Code__c != 'PRISEPGR' &&
            planToCheck.Plan_Code__c != 'GRPLUS' &&
            (planToCheck.Plan_Code__c == null || !planToCheck.Plan_Code__c.contains('GERT')) &&
            (planToCheck.Plan_Description__c == null || !planToCheck.Plan_Description__c.contains('UG'))
        ) {
            return true;
        } else {
            return false;
        }
    }

    public static Boolean accessAsuForCampaignMember(CampaignMember memberToCheck) {
        if (
            AutoSubscriberHelper.campaignToRecordTypeName.get(memberToCheck.CampaignId) == 'EOSS Event' &&
            AutoSubscriberHelper.contactToCareer.get(memberToCheck.ContactId) == 'Undergraduate'
        ) {
            return true;
        } else {
            return false;
        }
    }
}