src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Owner_Should_Be__c</fullName>
        <description>On 12/11/17, per conversation with Dawn and Jana, Joy removed the following:
IF(LEFT(Subscription__r.OwnerId,3) = "00G" &amp;&amp; Apex_Private_in_Salesforce_Should_Be__c = "True", Subscription__r.OwnerId, OwnerId)</description>
        <formula>Subscription__r.OwnerId</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays the ID that should exist for the Owner.</inlineHelpText>
        <label>Apex: Owner Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Subscriber_Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Makes this record and associated Contact or Lead Subscriber records only visible to the Users that are members of the Queue listed as this Subscription's Owner. Note that the Subscriber record must be owned by a Queue in order to check this box.</inlineHelpText>
        <label>Subscriber Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubscriberTriggerTest.cls
@isTest
private class SubscriberTriggerTest {
    @isTest
    private static void nonPrivateSubscriptionInsert() {
        List<Subscription__c> subscriptions = TestDataFactory.createTestSubscriptions(1);
        for (Subscription__c subscription : subscriptions) {
            subscription.Subscriber_Private_in_Salesforce__c = false;
        }
        insert subscriptions;

        List<Contact> contacts = ContactService.createTestContacts(5);
        insert contacts;

        List<Subscriber__c> subscribers = TestDataFactory.createTestSubscribers(contacts, subscriptions);
        Test.startTest();
        insert subscribers;
        Test.stopTest();

        for (Subscriber__c subscriber : [SELECT Id, OwnerId, Apex_Owner_Should_Be__c FROM Subscriber__c]) {
            System.assertEquals(
                subscriber.Apex_Owner_Should_Be__c,
                subscriber.OwnerId,
                'OwnerId was not set as expected'
            );
        }
    }

    @isTest
    private static void privateSubscriptionInsert() {
        Group testGroup = TestDataFactory.createTestGroupAndQueue(
            new List<String>{ 'Subscription__c', 'Subscriber__c' }
        );
        List<Subscription__c> subscriptions = TestDataFactory.createTestSubscriptions(1);
        for (Subscription__c subscription : subscriptions) {
            subscription.OwnerId = testGroup.Id;
            subscription.Subscriber_Private_in_Salesforce__c = true;
        }
        insert subscriptions;

        List<Contact> contacts = ContactService.createTestContacts(5);
        insert contacts;

        List<Subscriber__c> subscribers = TestDataFactory.createTestSubscribers(contacts, subscriptions);
        Test.startTest();
        insert subscribers;
        Test.stopTest();

        for (Subscriber__c subscriber : [SELECT Id, OwnerId, Apex_Owner_Should_Be__c FROM Subscriber__c]) {
            System.assertEquals(
                subscriber.Apex_Owner_Should_Be__c,
                subscriber.OwnerId,
                'OwnerId was not set as expected'
            );
        }
    }
}