src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>HashSubscriberId__c</fullName>
        <description>A hashed version of the ID to act as a unique and secret identifier.</description>
        <externalId>true</externalId>
        <label>HashSubscriberId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SubscriberHashUpdateBatch.cls
public class SubscriberHashUpdateBatch implements Database.Batchable<sObject>, Schedulable{
	public final String query;

   public SubscriberHashUpdateBatch(){
       query = 'SELECT Id, HashSubscriberId__c FROM Subscriber__c';
   }

   public Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Subscriber__c> cList = (List<Subscriber__c>) scope;
        for(Integer i = 0; i < cList.size(); i++){
            cList[i].HashSubscriberId__c = hashId(cList[i].Id);
        }     
        update scope;
    }

   public void finish(Database.BatchableContext BC){

   }
    
   public String hashId(String subIdIn) {
       Blob blobId = Blob.valueOf(subIdIn);
       Blob digestId = Crypto.generateDigest('SHA-512', blobId);
       String stringId = EncodingUtil.base64Encode((digestId));
       String encodedId = EncodingUtil.urlEncode(stringId, 'UTF-8');
       return encodedId;
   }
   
   public void execute(SchedulableContext sc) {
       BatchApplySubscriberPrivacy b = new BatchApplySubscriberPrivacy();
       database.executebatch(b, 200);
   }
}