src/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>HashSubscriptionId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>HashSubscriptionId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/SubscriptionHashUpdateBatch.cls
global class SubscriptionHashUpdateBatch implements Database.Batchable<sObject>{
	global final String Query;

   global SubscriptionHashUpdateBatch(){
       Query = 'SELECT Id, HashSubscriptionId__c FROM Subscription__c';
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Subscription__c> cList = (List<Subscription__c>) scope;
        for(Integer i = 0; i < cList.size(); i++){
            cList[i].HashSubscriptionId__c = hashId(cList[i].Id);
        }     
        update scope;
    }

   global void finish(Database.BatchableContext BC){

   }
    
   global String hashId(String subIdIn) {
       Blob blobId = Blob.valueOf(subIdIn);
       Blob digestId = Crypto.generateDigest('SHA-512', blobId);
       String stringId = EncodingUtil.base64Encode((digestId));
       String encodedId = EncodingUtil.urlEncode(stringId, 'UTF-8');
       return encodedId;
   }
}