src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Owner_Should_Be__c</fullName>
        <description>On 12/11/17, per conversation with Dawn and Jana, Joy removed the following:
IF(LEFT(Subscription__r.OwnerId,3) = "00G" &amp;&amp; Apex_Private_in_Salesforce_Should_Be__c = "True", Subscription__r.OwnerId, OwnerId)</description>
        <formula>Subscription__r.OwnerId</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays the ID that should exist for the Owner.</inlineHelpText>
        <label>Apex: Owner Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HashSubscriberId__c</fullName>
        <description>A hashed version of the ID to act as a unique and secret identifier.</description>
        <externalId>true</externalId>
        <label>HashSubscriberId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Available_for_Opt_In__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this Subscription will be made available for ASU constituents to "opt-in" when managing their subscriptions. Please note that selecting this option requires that your team has a plan for engaging newly opted-in subscribers.</inlineHelpText>
        <label>Available for Opt-In</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Parent_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Child Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscriber_Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Makes this record and associated Contact or Lead Subscriber records only visible to the Users that are members of the Queue listed as this Subscription's Owner. Note that the Subscriber record must be owned by a Queue in order to check this box.</inlineHelpText>
        <label>Subscriber Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription_Description__c</fullName>
        <label>Subscription Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <inlineHelpText>Business Unit types are primarily used to store opt-in information 
Area of Interest types store general interests, within a BU (e.g. Financial Aid, Academic Research) 
List types store explicit list (e.g. newsletter, membership)</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Area of Interest</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubscriberTriggerTest.cls
@isTest
private class SubscriberTriggerTest {
    @isTest
    private static void nonPrivateSubscriptionInsert() {
        List<Subscription__c> subscriptions = TestDataFactory.createTestSubscriptions(1);
        for (Subscription__c subscription : subscriptions) {
            subscription.Subscriber_Private_in_Salesforce__c = false;
        }
        insert subscriptions;

        List<Contact> contacts = ContactService.createTestContacts(5);
        insert contacts;

        List<Subscriber__c> subscribers = TestDataFactory.createTestSubscribers(contacts, subscriptions);
        Test.startTest();
        insert subscribers;
        Test.stopTest();

        for (Subscriber__c subscriber : [SELECT Id, OwnerId, Apex_Owner_Should_Be__c FROM Subscriber__c]) {
            System.assertEquals(
                subscriber.Apex_Owner_Should_Be__c,
                subscriber.OwnerId,
                'OwnerId was not set as expected'
            );
        }
    }

    @isTest
    private static void privateSubscriptionInsert() {
        Group testGroup = TestDataFactory.createTestGroupAndQueue(
            new List<String>{ 'Subscription__c', 'Subscriber__c' }
        );
        List<Subscription__c> subscriptions = TestDataFactory.createTestSubscriptions(1);
        for (Subscription__c subscription : subscriptions) {
            subscription.OwnerId = testGroup.Id;
            subscription.Subscriber_Private_in_Salesforce__c = true;
        }
        insert subscriptions;

        List<Contact> contacts = ContactService.createTestContacts(5);
        insert contacts;

        List<Subscriber__c> subscribers = TestDataFactory.createTestSubscribers(contacts, subscriptions);
        Test.startTest();
        insert subscribers;
        Test.stopTest();

        for (Subscriber__c subscriber : [SELECT Id, OwnerId, Apex_Owner_Should_Be__c FROM Subscriber__c]) {
            System.assertEquals(
                subscriber.Apex_Owner_Should_Be__c,
                subscriber.OwnerId,
                'OwnerId was not set as expected'
            );
        }
    }

    @isTest
    private static void retriveSubscriberTest() {
        String fieldsToString;
        List<Subscriber__c> subscriberList = new List<Subscriber__c>();
        List<Id> subscriberIds = new List<Id>();

        Contact con = new Contact(FirstName = 'Joe', LastName = 'Smith', Phone = '415.555.1212');
        List<Contact> conList = new List<Contact>{ con };
        insert con;

        List<Subscriber__c> subscriberCon = [SELECT Name FROM Subscriber__c WHERE Contact__c = :con.Id];

        List<Contact> contacts = ContactService.createTestContacts(5);
        insert contacts;

        Subscription__c parentSubscription = new Subscription__c(
            Subscription_Type__c = 'Business Unit',
            Name = 'ParentSub',
            Subscription_Description__c = 'Parent Sub Description',
            Available_for_Opt_In__c = true,
            Subscriber_Private_in_Salesforce__c = false
        );
        insert parentSubscription;

        List<Subscription__c> subscriptionList = new List<Subscription__c>();
        for (Integer i = 0; i < 1; i++) {
            Subscription__c subscription = new Subscription__c(
                Subscription_Type__c = 'List',
                Name = 'Sub' + i,
                Subscription_Description__c = 'Sub Description' + i,
                Subscriber_Private_in_Salesforce__c = false,
                Parent_Subscription__c = parentSubscription.Id
            );
            subscriptionList.add(subscription);
        }
        insert subscriptionList;

        List<Subscriber__c> subscribers = new List<Subscriber__c>();

        for (Subscription__c subscription : subscriptionList) {
            for (Contact contact : contacts) {
                Subscriber__c subscriber = new Subscriber__c(
                    Subscription__c = subscription.Id,
                    Contact__c = contact.Id,
                    Subscriber_Status__c = 'Subscribed'
                );
                subscribers.add(subscriber);
            }
        }
        for (Subscriber__c sub : subscribers) {
            subscriberIds.add(sub.Id);
            sub.HashSubscriberID__c = null;
        }
        insert subscribers;

        Test.startTest();
        fieldsToString = SubscriberService.subscriberFieldsToString();
        subscriberList = SubscriberService.getSubscribers(con.Id);
        SubscriberService.setHashIdNotFuture(subscriberIds);
        Test.stopTest();

        System.assertEquals(subscriberList.size(), subscriberCon.size());
    }
}