src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Owner_Should_Be__c</fullName>
        <description>On 12/11/17, per conversation with Dawn and Jana, Joy removed the following:
IF(LEFT(Subscription__r.OwnerId,3) = "00G" &amp;&amp; Apex_Private_in_Salesforce_Should_Be__c = "True", Subscription__r.OwnerId, OwnerId)</description>
        <formula>Subscription__r.OwnerId</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays the ID that should exist for the Owner.</inlineHelpText>
        <label>Apex: Owner Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Private_in_Salesforce_Should_Be__c</fullName>
        <formula>IF(Subscription__r.Subscriber_Private_in_Salesforce__c, "True", "False")</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays how the "Private in Salesforce" field should be set.</inlineHelpText>
        <label>Apex: Private in Salesforce Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Subscriptions</relationshipLabel>
        <relationshipName>Contact_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HashSubscriberId__c</fullName>
        <description>A hashed version of the ID to act as a unique and secret identifier.</description>
        <externalId>true</externalId>
        <label>HashSubscriberId</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Lead Subscriptions</relationshipLabel>
        <relationshipName>Lead_Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if the associated Subscription record is marked as Private in Salesforce.</inlineHelpText>
        <label>Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscriber_Status__c</fullName>
        <description>Subscribed - this Lead or Contact has explicitly opted in
Unsubscribed - this Lead or Contact has explicitly opted out
No Preference -  this Lead or Contact is associated with the subscription, and should only be sSubscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unitent messages if they have opted in to a parent Business Unit</description>
        <inlineHelpText>Subscribed - this individual has explicitly opted in
Unsubscribed - this individual has explicitly opted out
No Preference -  this individual should only be sent messages if they are opted in to a parent Business Unit</inlineHelpText>
        <label>Subscriber Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Subscribed</fullName>
                </value>
                <value>
                    <fullName>Unsubscribed</fullName>
                </value>
                <value>
                    <fullName>No Preference</fullName>
                    <default>true</default>
                    <label>No Preference</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Business_Unit__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Unit</label>
        <referenceTo>et4ae5__Business_Unit__c</referenceTo>
        <relationshipLabel>Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Parent_Subscription__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Child Subscriptions</relationshipLabel>
        <relationshipName>Subscriptions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscription_Type__c</fullName>
        <inlineHelpText>Business Unit types are primarily used to store opt-in information 
Area of Interest types store general interests, within a BU (e.g. Financial Aid, Academic Research) 
List types store explicit list (e.g. newsletter, membership)</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Business Unit</fullName>
                </value>
                <value>
                    <fullName>Area of Interest</fullName>
                </value>
                <value>
                    <fullName>List</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/SubscriberService.cls
public without sharing class SubscriberService {
    @TestVisible
    private static Boolean parentSubsSynced = false;

    /**
     * Updates Subscriber OwnerID and Private in Salesforce values to match their corresponding
     * formula field values
     * @param A List of Subscriber records to process
     */
    public static void enforceOwnerPolicies(List<Subscriber__c> subList) {
        for (Subscriber__c sub : subList) {
            if (
                (sub.OwnerId != sub.Apex_Owner_Should_Be__c && sub.Apex_Owner_Should_Be__c != null) ||
                (sub.Apex_Private_in_Salesforce_Should_Be__c != null &&
                sub.Private_in_Salesforce__c != Boolean.valueOf(sub.Apex_Private_in_Salesforce_Should_Be__c))
            ) {
                sub.OwnerId = sub.Apex_Owner_Should_Be__c;
                sub.Private_in_Salesforce__c = sub.Apex_Private_in_Salesforce_Should_Be__c != null
                    ? Boolean.valueOf(sub.Apex_Private_in_Salesforce_Should_Be__c)
                    : false;
            }
        }
    }

    /**
     * Upon opt-in, creates a Subscriber record for the parent Subscription if it does not already exist
     *
     * @param A List of Subscriber records to process
     */

    public static void syncParentSubscribers(List<Subscriber__c> subList) {
        if (parentSubsSynced) {
            return;
        }

        Set<Id> subscriptionIds = new Set<Id>();
        Set<Id> contactAndLeadIds = new Set<Id>();
        for (Subscriber__c sub : subList) {
            if (sub.Subscriber_Status__c == 'Subscribed') {
                subscriptionIds.add(sub.Subscription__c);
                if (sub.Contact__c != null)
                    contactAndLeadIds.add(sub.Contact__c);
                else if (sub.Lead__c != null)
                    contactAndLeadIds.add(sub.Lead__c);
            }
        }
        Map<Id, Subscription__c> subscriptionMap = new Map<Id, Subscription__c>(
            [SELECT Id, Parent_Subscription__c, Subscription_Type__c FROM Subscription__c WHERE Id IN :subscriptionIds]
        );

        Set<id> parentSubIds = new Set<Id>();
        for (Id subId : subscriptionMap.keySet()) {
            if (subscriptionMap.get(subId).Subscription_Type__c != 'Business Unit') {
                parentSubIds.add(subscriptionMap.get(subId).Parent_Subscription__c);
            }
        }

        Map<String, Subscriber__c> buSubAndContactToSubscriberMap = new Map<String, Subscriber__c>();
        for (Subscriber__c sub : [
            SELECT Id, Subscription__c, Subscriber_Status__c, Contact__c, Lead__c
            FROM Subscriber__c
            WHERE
                (Contact__c IN :contactAndLeadIds
                OR Lead__c IN :contactAndLeadIds)
                AND Subscription__c IN :parentSubIds
        ]) {
            if (sub.Contact__c != null) {
                buSubAndContactToSubscriberMap.put(sub.Subscription__c + '|' + sub.Contact__c, sub);
            } else if (sub.Lead__c != null) {
                buSubAndContactToSubscriberMap.put(sub.Subscription__c + '|' + sub.Lead__c, sub);
            }
        }

        List<Subscriber__c> subscribersToUpdate = new List<Subscriber__c>();
        List<Subscriber__c> subscribersToInsert = new List<Subscriber__c>();
        Set<String> itemsProcessed = new Set<String>();
        for (Subscriber__c sub : subList) {
            if (!subscriptionMap.containsKey(sub.Subscription__c)) {
                continue;
            }
            if (sub.Subscriber_Status__c != 'Subscribed') {
                continue;
            }
            if (subscriptionMap.get(sub.Subscription__c).Subscription_Type__c == 'Business Unit') {
                continue;
            }
            String compositeKey;
            if (sub.Contact__c != null) {
                compositeKey = subscriptionMap.get(sub.Subscription__c).Parent_Subscription__c + '|' + sub.Contact__c;
            } else if (sub.Lead__c != null) {
                compositeKey = subscriptionMap.get(sub.Subscription__c).Parent_Subscription__c + '|' + sub.Lead__c;
            }

            if (itemsProcessed.contains(compositeKey)) {
                continue;
            }
            if (buSubAndContactToSubscriberMap.containsKey(compositeKey)) {
                Subscriber__c buSubscriber = buSubAndContactToSubscriberMap.get(compositeKey);
                if (buSubscriber.Subscriber_Status__c != 'Subscribed') {
                    buSubscriber.Subscriber_Status__c = 'Subscribed';
                    subscribersToUpdate.add(buSubscriber);
                }
            } else {
                subscribersToInsert.add(
                    new Subscriber__c(
                        Contact__c = sub.Contact__c,
                        Lead__c = sub.Lead__c,
                        Subscription__c = subscriptionMap.get(sub.Subscription__c).Parent_Subscription__c,
                        Subscriber_Status__c = 'Subscribed'
                    )
                );
            }
            itemsProcessed.add(compositeKey);
        }

        parentSubsSynced = true;

        if (subscribersToUpdate.size() > 0) {
            update subscribersToUpdate;
        }
        if (subscribersToInsert.size() > 0) {
            insert subscribersToInsert;
        }
    }

    /**
     * Returns all the fields on Subscriber in a String
     * @return A string containing all the Subscriber fields
     */
    public static String subscriberFieldsToString() {
        String subscriberFields = null;
        Map<String, SObjectField> subscriberFieldMap = ObjectService.getObjectFieldMap('Subscriber__c');
        subscriberFields = ObjectService.objectFieldsToString(subscriberFieldMap);
        return subscriberFields;
    }

    /**
     * Get a list of Subscribers for the provided Contact Id
     * @param The Id of the Contact to search on
     * @return A list of Subscribers for the provided Contact Id
     */
    public static List<Subscriber__c> getSubscribers(Id contactId) {
        String subFields = subscriberFieldsToString();
        List<Subscriber__c> subs = new List<Subscriber__c>();
        String soql =
            '' +
            'SELECT ' +
            subFields +
            ', Subscription__r.Name, Subscription__r.Subscription_Type__c, ' +
            'Subscription__r.Business_Unit__r.Name ' +
            'FROM Subscriber__c ' +
            'WHERE Contact__c = :contactId ' +
            'ORDER BY Subscription__r.Name ';
        subs = Database.query(soql);
        return subs;
    }

    /**
     * Creates a hash from the Subscriber ID and sets it as a unique identifier
     * @param subIdList the subscriber Id List
     */
    @future
    public static void setHashId(List<Id> subIdList) {
        List<Subscriber__c> subList = new List<Subscriber__c>();
        for (Id subscriberId : subIdList) {
            Subscriber__c subscriberToHash = new Subscriber__c(
                Id = subscriberId,
                HashSubscriberID__c = Hasher.hashId(subscriberId)
            );
            subList.add(subscriberToHash);
        }
        update subList;
    }

    /**
     * Creates a hash from the Subscriber ID and sets it as a unique identifier
     * @param subIdList the list of subscribers
     */
    public static void setHashIdNotFuture(List<Id> subIdList) {
        List<Subscriber__c> subscribersWithHashes = new List<Subscriber__c>();
        for (Subscriber__c subscriber : [SELECT ID, HashSubscriberID__c FROM Subscriber__c WHERE ID IN :subIdList]) {
            if (subscriber.HashSubscriberID__c == null) {
                subscriber.HashSubscriberID__c = Hasher.hashId(subscriber.ID);
                subscribersWithHashes.add(subscriber);
            }
        }
        update subscribersWithHashes;
    }
}