src/objects/Subscriber__c.object
<CustomObject>
    <fields>
        <fullName>Apex_Owner_Should_Be__c</fullName>
        <description>On 12/11/17, per conversation with Dawn and Jana, Joy removed the following:
IF(LEFT(Subscription__r.OwnerId,3) = "00G" &amp;&amp; Apex_Private_in_Salesforce_Should_Be__c = "True", Subscription__r.OwnerId, OwnerId)</description>
        <formula>Subscription__r.OwnerId</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays the ID that should exist for the Owner.</inlineHelpText>
        <label>Apex: Owner Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Apex_Private_in_Salesforce_Should_Be__c</fullName>
        <formula>IF(Subscription__r.Subscriber_Private_in_Salesforce__c, "True", "False")</formula>
        <inlineHelpText>For the Apex code that enforces the Subscriber security model, this field displays how the "Private in Salesforce" field should be set.</inlineHelpText>
        <label>Apex: Private in Salesforce Should Be</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Private_in_Salesforce__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Automatically checked if the associated Subscription record is marked as Private in Salesforce.</inlineHelpText>
        <label>Private in Salesforce</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Subscription__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Subscription</label>
        <referenceTo>Subscription__c</referenceTo>
        <relationshipLabel>Subscribers</relationshipLabel>
        <relationshipName>Subscribers</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <description>Used by the custom Subscription Center and Marketing Cloud - This object stores the person-level details of their preference for a given Subscription. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscriber</label>
    <nameField>
        <displayFormat>SUB-{00000000}</displayFormat>
        <label>Subscriber ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscribers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Subscription__c.object
<CustomObject>
    <fields>
        <fullName>Subscriber_Privacy_Changed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates whether the "Subscriber Private in Salesforce" field was recently changed; used by a scheduled job to set Subscriber records' Owner values</description>
        <inlineHelpText>Indicates whether the "Subscriber Private in Salesforce" field was recently changed</inlineHelpText>
        <label>Subscriber Privacy Changed</label>
        <type>Checkbox</type>
    </fields>
    <description>Business Unit and List subscriptions being used by the Subscription Center and Marketing Cloud. This object stores the list-level details for emails where we need to store a subscriber/contact/lead preference. This object is owned by the Enterprise Marketing Hub and the Marketing Cloud Governance team. Any changes to this object should be approved/reviewed by them.</description>
    <label>Subscription</label>
    <nameField>
        <label>Subscription Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/BatchApplySubscriberPrivacy.cls
public class BatchApplySubscriberPrivacy implements Database.Batchable<sObject>, Database.Stateful {
    private static final Boolean debug = false; // Toggle debug error reporting
    private Set<Id> subscriptionIdSet = new Set<Id>();

    public Database.QueryLocator start(Database.BatchableContext bc) {
        String query =
            'SELECT Id, OwnerId, Apex_Owner_Should_Be__c, Private_in_Salesforce__c, ' +
            'Apex_Private_in_Salesforce_Should_Be__c, Subscription__c ' +
            'FROM Subscriber__c ' +
            'WHERE Subscription__r.Subscriber_Privacy_Changed__c = true';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<sObject> scope) {
        // Check each Subscriber record, and set the Owner and Private_In_Salesforce fields to match the values
        // calculated by their corresponding formula fields if they don't match
        List<Subscriber__c> subUpdateList = new List<Subscriber__c>();
        for (Subscriber__c sub : (List<Subscriber__c>) scope) {
            if (
                sub.OwnerId != sub.Apex_Owner_Should_Be__c ||
                sub.Private_in_Salesforce__c != Boolean.valueOf(sub.Apex_Private_in_Salesforce_Should_Be__c)
            ) {
                sub.OwnerId = sub.Apex_Owner_Should_Be__c;
                sub.Private_in_Salesforce__c = Boolean.valueOf(sub.Apex_Private_in_Salesforce_Should_Be__c);
                subUpdateList.add(sub);
            }
            // Add to the ID set so we can reset the Subscriber_Privacy_Changed flags in the finish method
            subscriptionIdSet.add(sub.Subscription__c);
        }
        if (!subUpdateList.isEmpty()) {
            try {
                update subUpdateList;
            } catch (Exception ex) {
                List<String> vars = new List<String>();
                vars.add(ErrorLogger.convertListToJSON('scope', scope));
                vars.add(ErrorLogger.convertListToJSON('subUpdateList', subUpdateList));
                ErrorLogger.log(ex, vars, debug);
            }
        }
    }

    public void finish(Database.BatchableContext bc) {
        // Reset all of the Subscriber_Privacy_Changed flags to false
        List<Subscription__c> subscriptions = new List<Subscription__c>();
        for (Id subId : subscriptionIdSet) {
            Subscription__c sub = new Subscription__c();
            sub.Id = subId;
            sub.Subscriber_Privacy_Changed__c = false;
            subscriptions.add(sub);
        }
        if (!subscriptions.isEmpty()) {
            try {
                update subscriptions;
            } catch (Exception ex) {
                List<String> vars = new List<String>();
                vars.add(ErrorLogger.convertListToJSON('subscriptions', subscriptions));
                ErrorLogger.log(ex, vars, debug);
            }
        }
    }
}