src/objects/Success_Pod__c.object
<CustomObject>
    <fields>
        <fullName>Committee__c</fullName>
        <description>for import of Advising Committee</description>
        <label>Committee</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Role__c</fullName>
        <label>Resource Role</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Person is available to be assigned Success Students</description>
    <label>Active Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Success_Pod__c.field-meta.xml
<CustomField>
    <fullName>Success_Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child object to Success Pod</description>
    <label>Success Pod</label>
    <referenceTo>Success_Pod__c</referenceTo>
    <relationshipLabel>Success Resources</relationshipLabel>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Resource_Pod_Association__c.object
<CustomObject>
    <fields>
        <fullName>Success_Resource__c</fullName>
        <description>The success resource that is being associated to a success pod</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Resource Pod Associations</relationshipLabel>
        <relationshipName>Success_Resource_Pod_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Success_Pod__c</fullName>
        <description>The success pod to associate a resource to.</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resource Pod Associations</relationshipLabel>
        <relationshipName>Success_Resource_Pod_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Creates a Many-To-Many relationship between Success_Resource__c and Success_Pod__c.</description>
    <label>Success Resource Pod Association</label>
    <nameField>
        <displayFormat>SRPA-{0000000000}</displayFormat>
        <label>Success Resource Pod Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Resource Pod Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/Coaching_Student__c.field-meta.xml
<CustomField>
    <fullName>Coaching_Student__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
    <label>Coaching Student</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that this student is an active Success Student</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Student__c.field-meta.xml
<CustomField>
    <fullName>Student__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Student</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Pod__c.field-meta.xml
<CustomField>
    <fullName>Success_Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This determines which Advisors are assigned to this student.</description>
    <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
    <label>Success Pod</label>
    <referenceTo>Success_Pod__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Resource__c.field-meta.xml
<CustomField>
    <fullName>Success_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>links the Success Student to their Assigned Success Resource</description>
    <label>Success Resource</label>
    <referenceTo>Success_Resource__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/recordTypes/Advisor.recordType-meta.xml
<RecordType>
    <fullName>Advisor</fullName>
    <active>true</active>
    <description>Denotes if the Student is a non-Coaching Student.</description>
    <label>Advisor</label>
</RecordType>

force-app/main/default/classes/AdvisorCaseTransferService.cls
public without sharing class AdvisorCaseTransferService {
    private static final String GRAD_CASE_RECORD_TYPE_NAME = 'ASU_Graduate_Advisor_Portal';

    @AuraEnabled(cacheable=true)
    public static String getTransferOptions(List<String> caseIds, Boolean massTransfer, Boolean grad) {
        if (massTransfer) {
            // Get the user's transfer options
            return JSON.serialize(getTransferToOptionsByUser(UserInfo.getUserId(), grad));
        } else {
            Case c = [SELECT Id, ContactId, RecordType.DeveloperName FROM Case WHERE Id = :caseIds[0]][0];

            grad = (c.RecordType.DeveloperName == GRAD_CASE_RECORD_TYPE_NAME); // grad is set by record id if only one case
            if (String.isEmpty(c.ContactId)) {
                // Get the user's transfer options
                return JSON.serialize(getTransferToOptionsByUser(UserInfo.getUserId(), grad));
            } else {
                // Get the user's transfer options, plus the student's committees
                return JSON.serialize(getTransferToOptionsByUserAndStudent(UserInfo.getUserId(), c.ContactId, grad));
            }
        }
    }

    /**
     * Get all transfer options for this user and student
     * Which is:
     * 1. The user themself
     * 2. The student's committees (or the fallback queue if the student has none)
     * 3. The user's PODs
     * 4. The user's managed PODs
     * 5. The user's subordinates
     */
    public static List<LabelValue> getTransferToOptionsByUserAndStudent(String userId, String contactId, Boolean grad) {
        UserTransferOptionBuilder builder = new UserTransferOptionBuilder(userId, grad);

        List<LabelValue> options = new List<LabelValue>();

        // =+=+=+=+=+=+= Add the current user =+=+=+=+=+=+=
        options.add(builder.getUser());

        // =+=+=+=+=+=+= PODs for this student/contact =+=+=+=+=+=+=
        List<Success_Student__c> students = [
            SELECT Success_Pod__r.OwnerId, Success_Pod__r.Committee__c, Success_Pod__r.Name
            FROM Success_Student__c
            WHERE Student__c = :contactId AND Is_Active__c = TRUE AND Coaching_Student__c = FALSE
        ];
        // Add the student's success pods
        options.add(new LabelValue('--Student Advising Committees--', '004xa000003DIlo'));
        if (!students.isEmpty()) {
            for (Success_Student__c student : students)
                options.add(new LabelValue(generateLabel(student.Success_Pod__r), student.Success_Pod__r.OwnerId));
        } else {
            String defaultGroupName = grad ? 'Grad Advisor Fallback Queue' : 'UG Advisor Fallback Queue';

            List<Group> defaultGroups = [SELECT Id, Name FROM Group WHERE Name = :defaultGroupName AND Type = 'Queue'];
            for (Group defaultGroup : defaultGroups) {
                options.add(new LabelValue(defaultGroup.Name, defaultGroup.Id));
            }
        }

        // =+=+=+=+=+=+= Add the committees this user has a user role in =+=+=+=+=+=+=
        List<LabelValue> podsAsUser = builder.getDirectPods();
        if (!podsAsUser.isEmpty()) {
            options.add(builder.getDirectPodLabel());
            options.addAll(podsAsUser);
        }

        // =+=+=+=+=+=+= Add the committees this user has a manager role in =+=+=+=+=+=+=
        List<LabelValue> podsAsManager = builder.getManagedPods();
        if (!podsAsManager.isEmpty()) {
            options.add(builder.getManagedPodLabel());
            options.addAll(podsAsManager);
        }

        // =+=+=+=+=+=+= Add the user's subordinates (i.e. which users are in pods this user manages) =+=+=+=+=+=+=
        List<LabelValue> subordinates = builder.getSubordinates();
        if (!subordinates.isEmpty()) {
            options.add(builder.getSubordinatesLabel());
            options.addAll(subordinates);
        }

        return options;
    }

    /**
     * Get all transfer options for this user
     * Which is:
     * 1. The user themself
     * 3. The user's PODs
     * 4. The user's managed PODs
     * 5. The user's subordinates
     */
    public static List<LabelValue> getTransferToOptionsByUser(String userId, Boolean grad) {
        UserTransferOptionBuilder builder = new UserTransferOptionBuilder(userId, grad);

        List<LabelValue> options = new List<LabelValue>();

        // =+=+=+=+=+=+= Add the current user =+=+=+=+=+=+=
        options.add(builder.getUser());

        // =+=+=+=+=+=+= Add the committees this user has a user role in =+=+=+=+=+=+=
        List<LabelValue> podsAsUser = builder.getDirectPods();
        if (!podsAsUser.isEmpty()) {
            options.add(builder.getDirectPodLabel());
            options.addAll(podsAsUser);
        }

        // =+=+=+=+=+=+= Add the committees this user has a manager role in =+=+=+=+=+=+=
        List<LabelValue> podsAsManager = builder.getManagedPods();
        if (!podsAsManager.isEmpty()) {
            options.add(builder.getManagedPodLabel());
            options.addAll(podsAsManager);
        }

        // =+=+=+=+=+=+= Add the user's subordinates (i.e. which users are in pods this user manages) =+=+=+=+=+=+=
        List<LabelValue> subordinates = builder.getSubordinates();
        if (!subordinates.isEmpty()) {
            options.add(builder.getSubordinatesLabel());
            options.addAll(subordinates);
        }

        return options;
    }

    @AuraEnabled
    public static void transferMultipleCases(List<String> caseIds, String ownerId) {
        List<Case> updatedCases = new List<Case>();

        // Transfer each case
        for (String caseId : new Set<String>(caseIds))
            updatedCases.add(new Case(Id = caseId, OwnerId = ownerId));

        // And do the transfer
        update updatedCases;
    }

    public class UserTransferOptionBuilder {
        private Id userId;
        private Boolean gradMode = null;

        private User u;
        private List<Success_Resource__c> allResources = new List<Success_Resource__c>();
        private List<Success_Resource_Pod_Association__c> subordinateSrpas = new List<Success_Resource_Pod_Association__c>();

        public UserTransferOptionBuilder(Id userId, Boolean gradMode) {
            this.userId = userId;
            this.gradMode = gradMode;

            // Query to get name and alias of user
            u = [SELECT Id, Name, Alias FROM User WHERE Id = :userId LIMIT 1][0];

            // Get all resources for this user, and the pods they are associated with
            allResources = [
                SELECT
                    Role__c,
                    (
                        SELECT
                            Success_Pod__c,
                            Success_Pod__r.OwnerId,
                            Success_Pod__r.Name,
                            Success_Pod__r.Committee__c,
                            Success_Pod__r.RecordTypeId
                        FROM Success_Resource_Pod_Associations__r
                        ORDER BY Success_Pod__r.Name
                    ),
                    RecordTypeId
                FROM Success_Resource__c
                WHERE Resource__c = :userId AND IsActive__c = TRUE
            ];
            // Filter to just grad or ugrad if needed
            if (gradMode != null) {
                String successPodRecordId, successResourceRecordId;
                if (gradMode == true) {
                    successPodRecordId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad');
                    successResourceRecordId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad');
                } else {
                    successPodRecordId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor');
                    successResourceRecordId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor');
                }

                List<Success_Resource__c> removeRes = new List<Success_Resource__c>();
                for (Success_Resource__c res : allResources) {
                    if (res.RecordTypeId != successResourceRecordId)
                        removeRes.add(res);

                    List<Success_Resource_Pod_Association__c> removeSrpas = new List<Success_Resource_Pod_Association__c>();
                    for (Success_Resource_Pod_Association__c srpa : res.Success_Resource_Pod_Associations__r)
                        if (srpa.Success_Pod__r.RecordTypeId != successPodRecordId)
                            removeSrpas.add(srpa);

                    for (Success_Resource_Pod_Association__c srpa : removeSrpas)
                        res.Success_Resource_Pod_Associations__r.remove(
                            res.Success_Resource_Pod_Associations__r.indexOf(srpa)
                        );
                }

                for (Success_Resource__c sr : removeRes)
                    allResources.remove(allResources.indexOf(sr));
            }

            // Get list of which pods this user is a manager for
            List<Id> podsUserIsAManagerForLs = new List<Id>();
            for (Success_Resource__c res : this.allResources)
                if (res.Role__c == 'College Manager' || res.Role__c == 'Department Manager')
                    for (Success_Resource_Pod_Association__c srpa : res.Success_Resource_Pod_Associations__r)
                        podsUserIsAManagerForLs.add(srpa.Success_Pod__c);

            // Get list of all OTHER users in the pods this user is a manager for
            subordinateSrpas = [
                SELECT
                    Id,
                    Success_Resource__r.Resource__c,
                    Success_Resource__r.Resource__r.Name,
                    Success_Resource__r.Resource__r.Alias,
                    Success_Resource__r.RecordTypeId,
                    Success_Pod__r.RecordTypeId
                FROM Success_Resource_Pod_Association__c
                WHERE
                    Success_Resource__r.IsActive__c = TRUE
                    AND Success_Pod__c IN :podsUserIsAManagerForLs
                    AND Success_Resource__r.Resource__c != :userId
                ORDER BY Success_Resource__r.Resource__r.Name ASC
            ];

            // Filter to just grad or ugrad if needed
            if (gradMode != null) {
                String successPodRecordId, successResourceRecordId;
                if (gradMode == true) {
                    successPodRecordId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad');
                    successResourceRecordId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad');
                } else {
                    successPodRecordId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor');
                    successResourceRecordId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor');
                }

                List<Success_Resource_Pod_Association__c> removeSubordinates = new List<Success_Resource_Pod_Association__c>();
                for (Success_Resource_Pod_Association__c srpa : subordinateSrpas) {
                    if (
                        srpa.Success_Pod__r.RecordTypeId != successPodRecordId ||
                        srpa.Success_Resource__r.RecordTypeId != successResourceRecordId
                    )
                        removeSubordinates.add(srpa);
                }
                for (Success_Resource_Pod_Association__c srpa : removeSubordinates)
                    subordinateSrpas.remove(subordinateSrpas.indexOf(srpa));
            }
        }

        /**
         * Get the LabelValue option for THIS user
         */
        public LabelValue getUser() {
            return new LabelValue(generateLabel(u), userId);
        }

        /**
         * Get the LabelValue option for this user's committees.
         * @return LabelValue for "My Committees"
         */
        public LabelValue getDirectPodLabel() {
            return new LabelValue('--My Committees--', '001xa000003DIlo');
        }
        /**
         * Get all the user's committees where the user is a User and not a manager.
         * @return LabelValue list, one per committee. Alphabetical ordering.
         */
        public List<LabelValue> getDirectPods() {
            List<LabelValue> options = new List<LabelValue>();
            List<Success_Resource__c> resourcesAsAUser = new List<Success_Resource__c>();

            // Find all resources for this user AS a user (not a manager)
            for (Success_Resource__c res : allResources)
                if (res.Role__c == 'User')
                    resourcesAsAUser.add(res);

            // Create LabelValue for each success pod
            Map<String, LabelValue> labelToLVMp = new Map<String, LabelValue>();
            for (Success_Resource__c res : resourcesAsAUser) {
                for (Success_Resource_Pod_Association__c srpa : res.Success_Resource_Pod_Associations__r) {
                    String label = generateLabel(srpa.Success_Pod__r);
                    LabelValue lv = new LabelValue(label, srpa.Success_Pod__r.OwnerId);
                    labelToLVMp.put(lv.label, lv);
                }
            }

            // Add in alphabetical order
            List<String> lvLabelsInSortedOrder = new List<String>(labelToLVMp.keySet());
            lvLabelsInSortedOrder.sort();
            for (String label : lvLabelsInSortedOrder)
                options.add(labelToLVMp.get(label));

            return options;
        }

        /**
         * Get the LabelValue option for the committees this user manages.
         * This depends on if we are in gradMode or not. If we are in ugrad
         * then it also depends on if the user is a College Manager or
         * Department Manager
         * @return LabelValue for managed PODs
         */
        public LabelValue getManagedPodLabel() {
            if (gradMode == true) {
                return new LabelValue('--School Name or Advising Team--', '002xa000003DIlo');
            } else if (gradMode == false)
                for (Success_Resource__c res : allResources) {
                    if (res.Role__c == 'College Manager')
                        return new LabelValue('--College Committees--', '002xa000003DIlo');
                    else if (res.Role__c == 'Department Manager')
                        return new LabelValue('--Department Committees--', '002xa000003DIlo');
                }
            return new LabelValue('--Managed Committees--', '002xa000003DIlo');
        }
        /**
         * Get all the committees that the user is a manager for.
         * @return LabelValue list, one per committee. Alphabetical ordering.
         */
        public List<LabelValue> getManagedPods() {
            List<LabelValue> options = new List<LabelValue>();
            List<Success_Resource__c> resourcesAsManager = new List<Success_Resource__c>();

            // Find all resources for this user AS a user (not a manager)
            for (Success_Resource__c res : allResources)
                if (res.Role__c == 'College Manager' || res.Role__c == 'Department Manager')
                    resourcesAsManager.add(res);

            // Create LabelValue for each success pod
            Map<String, LabelValue> labelToLVMp = new Map<String, LabelValue>();
            for (Success_Resource__c res : resourcesAsManager) {
                for (Success_Resource_Pod_Association__c srpa : res.Success_Resource_Pod_Associations__r) {
                    String label = generateLabel(srpa.Success_Pod__r);
                    LabelValue lv = new LabelValue(label, srpa.Success_Pod__r.OwnerId);
                    labelToLVMp.put(lv.label, lv);
                }
            }

            // Add in alphabetical order
            List<String> lvLabelsInSortedOrder = new List<String>(labelToLVMp.keySet());
            lvLabelsInSortedOrder.sort();
            for (String label : lvLabelsInSortedOrder)
                options.add(labelToLVMp.get(label));

            return options;
        }

        /**
         * Get the LabelValue option for the committees this user manages.
         * This depends on if we are in gradMode or not. If we are in ugrad
         * then it also depends on if the user is a College Manager or
         * Department Manager
         * @return LabelValue for members of managed pods
         */
        public LabelValue getSubordinatesLabel() {
            if (gradMode == true) {
                return new LabelValue('--Program Advisors--', '003xa000003DIlo');
            } else if (gradMode == false)
                for (Success_Resource__c res : allResources) {
                    if (res.Role__c == 'College Manager')
                        return new LabelValue('--College Advisors--', '003xa000003DIlo');
                    else if (res.Role__c == 'Department Manager')
                        return new LabelValue('--Department Advisors--', '003xa000003DIlo');
                }
            return new LabelValue('--Other Advisors--', '003xa000003DIlo');
        }
        /**
         * Get all the other users in the committees this user manages.
         * @return LabelValue list, one per committee. Alphabetical ordering.
         */
        public List<LabelValue> getSubordinates() {
            List<LabelValue> options = new List<LabelValue>();
            Map<String, LabelValue> labelToLVMp = new Map<String, LabelValue>();

            for (Success_Resource_Pod_Association__c srpa : subordinateSrpas) {
                String label = generateLabel(srpa.Success_Resource__r.Resource__r);
                LabelValue lv = new LabelValue(label, srpa.Success_Resource__r.Resource__c);

                labelToLVMp.put(lv.label, lv);
            }

            // Add in alphabetical order
            List<String> lvLabelsInSortedOrder = new List<String>(labelToLVMp.keySet());
            lvLabelsInSortedOrder.sort();
            for (String label : lvLabelsInSortedOrder)
                options.add(labelToLVMp.get(label));

            return options;
        }
    }

    /**
     * Create a label that refers to a user
     * @return A string that is either the "[name]" or "[name] - [alias]" for the user
     */
    private static String generateLabel(User u) {
        String displayName = u.Name;
        if (u.Alias != null && u.Alias != '')
            displayName += ' - ' + u.Alias;
        return displayName;
    }
    /**
     * Create a label that refers to a success pod
     * @return A string that is either the "[name]" or "[name] - [committee]" for the success pod
     */
    private static String generateLabel(Success_Pod__c sucPod) {
        String displayName = sucPod.Name;
        if (sucPod.Committee__c != null && sucPod.Committee__c != '')
            displayName += ' - ' + sucPod.Committee__c;
        return displayName;
    }
}