src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Coach</fullName>
        <active>true</active>
        <label>Coach</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/AgentID__c.field-meta.xml
<CustomField>
    <fullName>AgentID__c</fullName>
    <description>inContact Agent Id</description>
    <label>AgentID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/ASURiteID__c.field-meta.xml
<CustomField>
    <fullName>ASURiteID__c</fullName>
    <description>Formula field that displays the Alias field on the User object</description>
    <formula>Resource__r.Alias</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ASURITE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Resource__r.EmployeeNumber</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

src/objects/Success_Student__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <formula>Student__r.ASURite_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Contact_Preference__c</fullName>
        <description>Coach: How coaching student prefers to be contacted</description>
        <inlineHelpText>How coaching student prefers to be contacted</inlineHelpText>
        <label>Contact Preference</label>
        <picklist>
            <picklistValues>
                <fullName>Unknown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pitch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Engagement__c</fullName>
        <description>Coach: Level of Engagement of Coaching Student</description>
        <inlineHelpText>Level of Engagement of Coaching Student</inlineHelpText>
        <label>Engagement</label>
        <picklist>
            <picklistValues>
                <fullName>Nonresponsive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transactional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coach_Enrollment_Status__c</fullName>
        <description>Student's enrollment status</description>
        <inlineHelpText>New: New, first session
Continuing: Enrolled 2+ consecutive sess
Graduated: Completed program
NDrop: No credit courses
TDrop: No classes, will return
PDrop: Never return
Re-Entry: Out of class for 2-6 sess
Re-Apply: Out 6+ sess, needs new adm ppwk</inlineHelpText>
        <label>Enrollment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Continuing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graduated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PDrop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Entry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Re-Apply</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Student__r.EMPLID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Next_Term_Enrolled__c</fullName>
        <description>Data will be imported, used in Coach Portal List view</description>
        <label>Next Term Enrolled</label>
        <length>16</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Plan, used for assign students to Coaches</description>
        <inlineHelpText>Lookup to Plan, used for assign students to Coaches</inlineHelpText>
        <label>Plan Code</label>
        <referenceTo>Plan__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Pod_Owner_ID__c</fullName>
        <formula>Success_Pod__r.OwnerId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Pod Owner ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to Program, used for assign students to Coaches</description>
        <label>Program Code</label>
        <referenceTo>Program__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource_ID__c</fullName>
        <formula>Success_Resource__r.UserId__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Resource ID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Chat_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is for the beta testing of Rocket Chat, it will be manually checked for the first cohort of students in the test group</description>
        <label>Chat Enabled</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Student__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Used to identify which students will be part of Success Student Coaching. Info will be imported from the lists of new students for the initial cohort and each subsequent cohort as they transition from ITK to ASU. This field can be replaced with a lookup to campus once all online students are coached by ASU.</description>
        <label>Coaching Student</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Indicates that this student is an active Success Student</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Coach_Name__c</fullName>
        <formula>Success_Resource__r.Resource__r.FirstName + ' ' + Success_Resource__r.Resource__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Success Coach Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This determines which Advisors are assigned to this student.</description>
        <inlineHelpText>This determines which Advisors are assigned to this student.</inlineHelpText>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>links the Success Student to their Assigned Success Resource</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Students</relationshipLabel>
        <relationshipName>Success_Students</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Student</label><nameField>
        <displayFormat>SS-{0}</displayFormat>
        <label>Success Student ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Students</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Success_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>UPDATEDBY_USER</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <label>All Success Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Success_Coach_Name__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <columns>Is_Active__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Non_Coaching_Students</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <filters>
            <field>Is_Active__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Non Coaching Students</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_No_EMPLID</fullName>
        <columns>NAME</columns>
        <columns>Is_Active__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>EMPLID__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students - No EMPLID</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Students_with_no_Coach</fullName>
        <columns>NAME</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Student_Name__c</columns>
        <columns>Student__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>EMPLID__c</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Success_Resource__c</field>
            <operation>equals</operation>
        </filters>
        <label>Success Students with no Coach</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Stus_w_Success_Resource</fullName>
        <columns>NAME</columns>
        <columns>Student_Name__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Student__c</columns>
        <columns>Coaching_Student__c</columns>
        <columns>Success_Resource__c</columns>
        <columns>Success_Resource_ID__c</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>Coaching_Student__c</field>
            <operation>equals</operation>
            <value>0</value>
        </filters>
        <label>Success Stus w/o Success Resource</label>
    </listViews></CustomObject>

force-app/main/default/objects/Success_Student__c/fields/ASURiteID__c.field-meta.xml
<CustomField>
    <fullName>ASURiteID__c</fullName>
    <formula>Student__r.ASURite_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ASURITE</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <formula>Student__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that this student is an active Success Student</description>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/fields/Success_Resource__c.field-meta.xml
<CustomField>
    <fullName>Success_Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>links the Success Student to their Assigned Success Resource</description>
    <label>Success Resource</label>
    <referenceTo>Success_Resource__c</referenceTo>
    <relationshipLabel>Success Students</relationshipLabel>
    <relationshipName>Success_Students</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Student__c/recordTypes/Coach.recordType-meta.xml
<RecordType>
    <fullName>Coach</fullName>
    <active>true</active>
    <description>Used to denote if the student is a Coaching Student for Ed Plus Success Coaches.</description>
    <label>Coach</label>
</RecordType>

src/objects/User.object
<CustomObject><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><enableFeeds>true</enableFeeds><externalSharingModel>Private</externalSharingModel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User/fields/EmplId__c.field-meta.xml
<CustomField>
    <fullName>EmplId__c</fullName>
    <description>[PeopleSoft] - EMPLID
[DW: sfe_user]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/classes/apiSSC_MyASUCoachesController.cls
@RestResource(urlMapping='/MyASUCoaches')
global with sharing class apiSSC_MyASUCoachesController {

  @HttpGet  
  global static List<Success_Student__c> getAllCoaches() {
     List<Success_Student__c> students = new List<Success_Student__c>();
     String coachResourceRecordTypeId;
     List<RecordType> rectype = [SELECT Id FROM RecordType WHERE DeveloperName = 'Coach' AND SobjectType = 'Success_Resource__c'];
     if(rectype.size()>0)coachResourceRecordTypeId=rectype[0].Id;
     students = [SELECT Id, ASURiteID__c,EmplId__c,Success_Resource__r.Resource__r.Name,
                 Success_Resource__r.Resource__r.Email, Success_Resource__r.Resource__r.Phone, 
                 Success_Resource__r.Resource__r.Title, Success_Resource__r.Resource__r.TimeZoneSidKey,
                 Success_Resource__r.Resource__r.Alias,Success_Resource__r.Resource__r.EmployeeNumber,
                 Success_Resource__r.AgentID__c
                 FROM Success_Student__c 
                 WHERE Is_Active__c = true 
                 AND Success_Resource__r.RecordTypeId =: coachResourceRecordTypeId
                 ORDER BY ASURiteID__c ASC];

    return students;
  }
}