src/objects/Success_Pod__c.object
<CustomObject>
    <fields>
        <fullName>Committee__c</fullName>
        <description>for import of Advising Committee</description>
        <label>Committee</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <description>Used to allow grouping of Success Resources.</description>
    <label>Success Pod</label>
    <nameField>
        <label>Success Pod ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Success Pods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <description>This is an advisor record type.</description>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><fields>
        <fullName>Role__c</fullName>
        <label>Resource Role</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Admin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Outreach</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Provost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Department Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>College Manager</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Person is available to be assigned Success Students</description>
    <label>Active Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Success_Pod__c.field-meta.xml
<CustomField>
    <fullName>Success_Pod__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Child object to Success Pod</description>
    <label>Success Pod</label>
    <referenceTo>Success_Pod__c</referenceTo>
    <relationshipLabel>Success Resources</relationshipLabel>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Success_Resource_Pod_Association__c.object
<CustomObject>
    <fields>
        <fullName>Success_Resource__c</fullName>
        <description>The success resource that is being associated to a success pod</description>
        <label>Success Resource</label>
        <referenceTo>Success_Resource__c</referenceTo>
        <relationshipLabel>Success Resource Pod Associations</relationshipLabel>
        <relationshipName>Success_Resource_Pod_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Success_Pod__c</fullName>
        <description>The success pod to associate a resource to.</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resource Pod Associations</relationshipLabel>
        <relationshipName>Success_Resource_Pod_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <description>Creates a Many-To-Many relationship between Success_Resource__c and Success_Pod__c.</description>
    <label>Success Resource Pod Association</label>
    <nameField>
        <displayFormat>SRPA-{0000000000}</displayFormat>
        <label>Success Resource Pod Association Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Success Resource Pod Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
    <recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
    </recordTypes>
</CustomObject>

force-app/main/default/classes/AdvisorPortalTopLevelFilterTest.cls
/**
 * @author Mathew Ruff, Sierra-Cedar
 * @date 2019-04-11
 *
 * Unit Tests for AdvisorPortalTopLevelFilter.cls
 */
@IsTest
private class AdvisorPortalTopLevelFilterTest {
    public static final String testUserAlias1 = 'testUsr1';
    public static final String testUserAlias2 = 'testUsr2';
    public static final String testUserAlias3 = 'testUsr3';
    public static final String testUserAlias4 = 'testUsr4';
    public static final String testUserAlias5 = 'testUsr5';
    public static final String testUserAlias6 = 'testUsr6';
    public static final String testUserAlias7 = 'testUsr7';
    public static final String testUserAlias8 = 'testUsr8';

    @TestSetup
    static void setup() {
        // Setup objects diagram:  https://asudev.jira.com/wiki/spaces/SFD/pages/2815590423/AdvisorPortalTopLevelFilterTest+Setup+Objects
        User runAsUser = new User(Id = UserInfo.getUserId());

        // Create all the users
        User testUser1 = createUser(testUserAlias1, '1');
        User testUser2 = createUser(testUserAlias2, '2');
        User testUser3 = createUser(testUserAlias3, '3');
        User testUser4 = createUser(testUserAlias4, '4');
        User testUser5 = createUser(testUserAlias5, '5');
        User testUser6 = createUser(testUserAlias6, '6');
        User testUser7 = createUser(testUserAlias7, '7');
        User testUser8 = createUser(testUserAlias8, '8');
        System.runAs(runAsUser) {
            insert new List<User>{
                testUser1,
                testUser2,
                testUser3,
                testUser4,
                testUser5,
                testUser6,
                testUser7,
                testUser8
            };
        }

        // And some groups to own the success pods
        Group group1 = createGroup('1');
        Group group2 = createGroup('2');
        Group group3 = createGroup('3');
        Group group4 = createGroup('4');
        System.runAs(runAsUser) {
            insert new List<Group>{ group1, group2, group3, group4 };
        }

        // Make the success resource for each user
        String sucResrcUgradRecordTypeId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor');
        String sucResrcGradRecordTypeId = RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad');
        Success_Resource__c sucRes1 = createSuccessResource(testUser1, 'User', sucResrcUgradRecordTypeId);
        Success_Resource__c sucRes2 = createSuccessResource(testUser2, 'User', sucResrcUgradRecordTypeId);
        Success_Resource__c sucRes3 = createSuccessResource(testUser3, 'College Manager', sucResrcUgradRecordTypeId);
        Success_Resource__c sucRes4 = createSuccessResource(testUser4, 'Department Manager', sucResrcUgradRecordTypeId);
        Success_Resource__c sucRes5 = createSuccessResource(testUser5, 'User', sucResrcGradRecordTypeId);
        Success_Resource__c sucRes6 = createSuccessResource(testUser6, 'User', sucResrcGradRecordTypeId);
        Success_Resource__c sucRes7 = createSuccessResource(testUser7, 'College Manager', sucResrcGradRecordTypeId);
        Success_Resource__c sucRes8 = createSuccessResource(testUser8, 'Department Manager', sucResrcGradRecordTypeId);
        Success_Resource__c sucRes9 = createSuccessResource(testUser8, 'Department Manager', sucResrcUgradRecordTypeId);
        System.runAs(runAsUser) {
            insert new List<Success_Resource__c>{
                sucRes1,
                sucRes2,
                sucRes3,
                sucRes4,
                sucRes5,
                sucRes6,
                sucRes7,
                sucRes8,
                sucRes9
            };
        }

        // Queue objects
        QueueSobject queue1 = createQueueSObject(group1.Id);
        QueueSobject queue2 = createQueueSObject(group2.Id);
        QueueSobject queue3 = createQueueSObject(group3.Id);
        QueueSobject queue4 = createQueueSObject(group4.Id);
        System.runAs(runAsUser) {
            insert new List<QueueSobject>{ queue1, queue2, queue3, queue4 };
        }

        // Success pods
        String sucPodUgradRecordTypeId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor');
        String sucPodGradRecordTypeId = RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad');
        Success_Pod__c sucPod1 = createSuccessPod(group1.Id, sucPodUgradRecordTypeId, '1');
        Success_Pod__c sucPod2 = createSuccessPod(group2.Id, sucPodUgradRecordTypeId, '2');
        Success_Pod__c sucPod3 = createSuccessPod(group3.Id, sucPodGradRecordTypeId, '3');
        Success_Pod__c sucPod4 = createSuccessPod(group4.Id, sucPodGradRecordTypeId, '4');
        System.runAs(runAsUser) {
            insert new List<Success_Pod__c>{ sucPod1, sucPod2, sucPod3, sucPod4 };
        }

        // Success Resource Pod Associations
        Success_Resource_Pod_Association__c sr1p1a = createSRPA(sucRes1, sucPod1);
        Success_Resource_Pod_Association__c sr2p2a = createSRPA(sucRes2, sucPod2);
        Success_Resource_Pod_Association__c sr3p2a = createSRPA(sucRes3, sucPod2);
        Success_Resource_Pod_Association__c sr4p2a = createSRPA(sucRes4, sucPod2);
        Success_Resource_Pod_Association__c sr9p2a = createSRPA(sucRes9, sucPod2);
        Success_Resource_Pod_Association__c sr5p3a = createSRPA(sucRes5, sucPod3);
        Success_Resource_Pod_Association__c sr6p4a = createSRPA(sucRes6, sucPod4);
        Success_Resource_Pod_Association__c sr7p3a = createSRPA(sucRes7, sucPod3);
        Success_Resource_Pod_Association__c sr7p4a = createSRPA(sucRes7, sucPod4);
        Success_Resource_Pod_Association__c sr8p4a = createSRPA(sucRes8, sucPod4);
        System.runAs(runAsUser) {
            insert new List<Success_Resource_Pod_Association__c>{
                sr1p1a,
                sr2p2a,
                sr3p2a,
                sr4p2a,
                sr9p2a,
                sr5p3a,
                sr6p4a,
                sr7p3a,
                sr7p4a,
                sr8p4a
            };
        }
    }

    @isTest
    private static void testUser1() {
        // Test user 1 should see themself and their single pod
        User testUser = [SELECT Id FROM User WHERE Alias = :testUserAlias1];
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(false);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, groupIds, null, null);
    }

    @isTest
    private static void testUser2() {
        // Test user 2 should see themself and their single pod
        User testUser = [SELECT Id FROM User WHERE Alias = :testUserAlias2];
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(false);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, groupIds, null, null);
    }

    @isTest
    private static void testUser3() {
        // Test user 3 should see themself, their managed pod, and users 2, 4, and 8
        List<User> users = [
            SELECT Id, Alias
            FROM User
            WHERE Alias IN (:testUserAlias2, :testUserAlias3, :testUserAlias4, :testUserAlias8)
        ];
        User testUser;
        for (User u : users) {
            if (u.Alias == testUserAlias3) {
                testUser = u;
                break;
            }
        }
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(false);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        List<String> subordinateUserIds = new List<String>();
        for (User u : users) {
            if (u.Id == testUser.Id)
                continue;
            subordinateUserIds.add(u.Id);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, groupIds, subordinateUserIds);
    }

    @isTest
    private static void testUser4Ugrad() {
        // Test user 4 (in ugrad mode) should see themself, their managed pod, and users 2, 3, and 8
        List<User> users = [
            SELECT Id, Alias
            FROM User
            WHERE Alias IN (:testUserAlias2, :testUserAlias3, :testUserAlias4, :testUserAlias8)
        ];
        User testUser;
        for (User u : users) {
            if (u.Alias == testUserAlias4) {
                testUser = u;
                break;
            }
        }
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(false);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        List<String> subordinateUserIds = new List<String>();
        for (User u : users) {
            if (u.Id == testUser.Id)
                continue;
            subordinateUserIds.add(u.Id);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, groupIds, subordinateUserIds);
    }

    @isTest
    private static void testUser4Grad() {
        // Test user 4 (in grad mode) should see themself
        User testUser = [SELECT Id, Alias FROM User WHERE Alias = :testUserAlias4];
        List<Success_Resource_Pod_Association__c> underGradSRPAs = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(true);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, null, null);
    }

    @isTest
    private static void testUser5() {
        // Test user 5 should see themself and their single pod
        User testUser = [SELECT Id FROM User WHERE Alias = :testUserAlias5];
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(true);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, groupIds, null, null);
    }

    @isTest
    private static void testUser6() {
        // Test user 6 should see themself and their single pod
        User testUser = [SELECT Id FROM User WHERE Alias = :testUserAlias6];
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(true);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, groupIds, null, null);
    }

    @isTest
    private static void testUser7() {
        // Test user 7 should see themself, pods 3 and 4, and test users 5, 6, and 8
        List<User> users = [
            SELECT Id, Alias
            FROM User
            WHERE Alias IN (:testUserAlias7, :testUserAlias5, :testUserAlias6, :testUserAlias8)
        ];
        User testUser;
        for (User u : users) {
            if (u.Alias == testUserAlias7) {
                testUser = u;
                break;
            }
        }
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(true);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        List<String> subordinateUserIds = new List<String>();
        for (User u : users) {
            if (u.Id == testUser.Id)
                continue;
            subordinateUserIds.add(u.Id);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, groupIds, subordinateUserIds);
    }

    @isTest
    private static void testUser8Ugrad() {
        // Test user 8 (in ugrad mode) should see themself, pod 2, and test users 2, 3, 4
        List<User> users = [
            SELECT Id, Alias
            FROM User
            WHERE Alias IN (:testUserAlias8, :testUserAlias2, :testUserAlias3, :testUserAlias4)
        ];
        User testUser;
        for (User u : users) {
            if (u.Alias == testUserAlias8) {
                testUser = u;
                break;
            }
        }
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Advisor')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Advisor')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(false);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        List<String> subordinateUserIds = new List<String>();
        for (User u : users) {
            if (u.Id == testUser.Id)
                continue;
            subordinateUserIds.add(u.Id);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, groupIds, subordinateUserIds);
    }

    @isTest
    private static void testUser8Grad() {
        // Test user 8 (in grad mode) should see themself, pod 4, and users 6 and 7
        List<User> users = [
            SELECT Id, Alias
            FROM User
            WHERE Alias IN (:testUserAlias8, :testUserAlias6, :testUserAlias7)
        ];
        User testUser;
        for (User u : users) {
            if (u.Alias == testUserAlias8) {
                testUser = u;
                break;
            }
        }
        List<Success_Resource_Pod_Association__c> srpas = [
            SELECT Success_Pod__r.OwnerId
            FROM Success_Resource_Pod_Association__c
            WHERE
                Success_Resource__r.Resource__c = :testUser.Id
                AND Success_Resource__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Resource__c', 'Grad')
                AND Success_Pod__r.RecordTypeId = :RecordIdHelper.getRecordTypeId('Success_Pod__c', 'Grad')
        ];

        // Get options
        String viewAsOptionListStr;
        List<OrderedMapStringToString.LabelValue> viewAsOptionList;
        System.runAs(testUser) {
            viewAsOptionListStr = AdvisorPortalTopLevelFilterController.viewAsOptions(true);
        }
        viewAsOptionList = (List<OrderedMapStringToString.LabelValue>) JSON.deserialize(
            viewAsOptionListStr,
            List<OrderedMapStringToString.LabelValue>.class
        );
        OrderedMapStringToString viewAsOptionMap = new OrderedMapStringToString(viewAsOptionList);

        List<String> groupIds = new List<String>();
        for (Success_Resource_Pod_Association__c srpa : srpas) {
            groupIds.add(srpa.Success_Pod__r.OwnerId);
        }
        List<String> subordinateUserIds = new List<String>();
        for (User u : users) {
            if (u.Id == testUser.Id)
                continue;
            subordinateUserIds.add(u.Id);
        }
        assertContainsAllOptionsInProperOrder(viewAsOptionList, testUser.Id, null, groupIds, subordinateUserIds);
    }

    private static void assertContainsAllOptionsInProperOrder(
        List<OrderedMapStringToString.LabelValue> optionsList,
        String userId,
        List<String> ownersOfPods,
        List<String> ownersOfManagedPods,
        List<String> subordinateIds
    ) {
        Boolean atStart = true, inPodsSection = false, inManagedPodsSection = false, inSubordinateSection = false;
        Boolean foundSelf = false,
            foundPodsHeader = false,
            foundManagedPodsHeader = false,
            foundSubordinateHeader = false;
        Integer podCount = 0, managedPodsCount = 0, subordinateCount = 0;

        if (ownersOfPods == null)
            ownersOfPods = new List<String>();
        if (ownersOfManagedPods == null)
            ownersOfManagedPods = new List<String>();
        if (subordinateIds == null)
            subordinateIds = new List<String>();

        for (OrderedMapStringToString.LabelValue labelValue : optionsList) {
            String label = labelValue.label;
            String value = labelValue.value;

            // Mvoe from section to section
            if (label == '--My Committees--') {
                atStart = false;
                inPodsSection = true;
                inManagedPodsSection = false;
                inSubordinateSection = false;
                foundPodsHeader = true;
                continue;
            } else if (
                label == '--Department Committees--' ||
                label == '--College Committees--' ||
                label == '--School Name or Advising Team--'
            ) {
                atStart = false;
                inPodsSection = false;
                inManagedPodsSection = true;
                inSubordinateSection = false;
                foundManagedPodsHeader = true;
                continue;
            } else if (
                label == '--Department Advisors--' ||
                label == '--College Advisors--' ||
                label == '--Program Advisors--'
            ) {
                atStart = false;
                inPodsSection = false;
                inManagedPodsSection = false;
                inSubordinateSection = true;
                foundSubordinateHeader = true;
                continue;
            }

            if (atStart) {
                // First should be the user themself, ALWAYS
                foundSelf = value == userId;
                atStart = false;
            } else if (inPodsSection) {
                // These are all pods the user is in
                podCount += ownersOfPods.contains(value) ? 1 : 0;
            } else if (inManagedPodsSection) {
                // There are all pods the user manages
                managedPodsCount += ownersOfManagedPods.contains(value) ? 1 : 0;
            } else if (inSubordinateSection) {
                // All subordinates
                subordinateCount += subordinateIds.contains(value) ? 1 : 0;
            }
        }

        System.debug('==================');

        for (OrderedMapStringToString.LabelValue labelValue : optionsList) {
            System.debug(labelValue);
        }
        System.debug('---');
        System.debug(foundSelf);
        System.debug(ownersOfPods);
        System.debug(foundPodsHeader);
        System.debug(podCount);
        System.debug(ownersOfManagedPods);
        System.debug(foundManagedPodsHeader);
        System.debug(managedPodsCount);
        System.debug(subordinateIds);
        System.debug(foundSubordinateHeader);
        System.debug(subordinateCount);
        System.debug('==================');

        System.assert(foundSelf, 'The user themself should ALWAYS be the first option in the list');
        System.assertEquals(
            !ownersOfPods.isEmpty(),
            foundPodsHeader,
            'If-and-only-if there some pods specified should the header be included'
        );
        System.assertEquals(ownersOfPods.size(), podCount);
        System.assertEquals(
            !ownersOfManagedPods.isEmpty(),
            foundManagedPodsHeader,
            'If-and-only-if there some pods specified should the header be included'
        );
        System.assertEquals(ownersOfManagedPods.size(), managedPodsCount);
        System.assertEquals(
            !subordinateIds.isEmpty(),
            foundSubordinateHeader,
            'If-and-only-if there some subordinates specified should the header be included'
        );
        System.assertEquals(subordinateIds.size(), subordinateCount);
    }

    private static User createUser(String alias, String indx) {
        return new User(
            FirstName = 'Test-' + indx,
            LastName = 'User',
            Username = 'test-' + indx + '.user@test.test',
            Email = 'test-' + indx + '.user@test.test',
            Alias = alias,
            CommunityNickname = alias,
            TimeZoneSidKey = 'America/Phoenix',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'ISO-8859-1',
            LanguageLocaleKey = 'en_US',
            ProfileId = RecordIdHelper.getProfileId('Standard User')
        );
    }

    private static Group createGroup(String indx) {
        return new Group(Name = 'TestGroup-' + indx, Email = 'test-' + indx + '.group@test.test', Type = 'Queue');
    }

    private static Success_Resource__c createSuccessResource(User u, String role, String recordTypeId) {
        return new Success_Resource__c(
            Role__c = role,
            Resource__c = u.Id,
            IsActive__c = true,
            RecordTypeId = recordTypeId
        );
    }

    private static QueueSobject createQueueSObject(String groupId) {
        return new QueueSobject(QueueId = groupId, SobjectType = 'Success_Pod__c');
    }

    private static Success_Pod__c createSuccessPod(String ownerId, String recordTypeId, String indx) {
        return new Success_Pod__c(
            OwnerId = ownerId,
            RecordTypeId = recordTypeId,
            Name = 'Test Pod ' + indx,
            Committee__c = 'tp-' + indx
        );
    }

    private static Success_Resource_Pod_Association__c createSRPA(Success_Resource__c sucRes, Success_Pod__c sucPod) {
        return new Success_Resource_Pod_Association__c(Success_Resource__c = sucRes.Id, Success_Pod__c = sucPod.Id);
    }
}