src/objects/Success_Resource__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Committee_Code__c</fullName>
        <formula>Success_Pod__r.Committee__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Committee Code</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Person is available to be assigned Success Students</description>
        <label>Active Resource</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Messaging_Account_Created__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Messaging Account Created</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Military_Coach__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this field identifies the Success Resource assigned to Coaching Military Students</description>
        <label>Military Coach</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Phone__c</fullName>
        <label>Primary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Email__c</fullName>
        <label>Secondary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Secondary_Phone__c</fullName>
        <label>Secondary Phone</label>
        <type>Phone</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>ASURiteID__c</fullName>
        <description>Formula field that displays the Alias field on the User object</description>
        <formula>Resource__r.Alias</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ASURITE</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>AgentID__c</fullName>
        <description>inContact Agent Id</description>
        <label>AgentID</label>
        <length>50</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Delegated Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources1</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Delegated_UserId__c</fullName>
        <formula>Delegated_Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Delegated UserId</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>EMPLID__c</fullName>
        <formula>Resource__r.EmployeeNumber</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>EMPLID</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Plan_Code__c</fullName>
        <label>Plan Code</label>
        <picklist>
            <picklistValues>
                <fullName>ARPUPBSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSFPBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASPGSMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABDABS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSBABA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSCBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSFIMBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSGLBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSRBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSSBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BABUSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BACMRMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAFIMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMGTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BAMKTBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSBSJMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSMCMSTBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRCBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRDMS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ECNTRMBS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDDCIMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDESLMA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSLSTBAE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDSPEGRCA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EDTECHMED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESCONSTMS</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Primary_Email__c</fullName>
        <label>Primary Email</label>
        <type>Email</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Program_Code__c</fullName>
        <description>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</description>
        <inlineHelpText>Used to tie an Advisor Manager to multiple PODs (Queues) for viewing as access. One of these values must match a value in a POD's Program__c field.</inlineHelpText>
        <label>Program Code</label>
        <picklist>
            <picklistValues>
                <fullName>UGAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGCS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGES</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGFA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGLS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNH</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGNU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGPP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGSU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGTE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UGHI</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource_Name__c</fullName>
        <formula>Resource__r.FirstName &amp; ' ' &amp; Resource__r.LastName</formula>
        <label>Resource Name</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Resource__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Pod__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Child object to Success Pod</description>
        <label>Success Pod</label>
        <referenceTo>Success_Pod__c</referenceTo>
        <relationshipLabel>Success Resources</relationshipLabel>
        <relationshipName>Success_Resources</relationshipName>
        <type>Lookup</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>UserId__c</fullName>
        <formula>Resource__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UserId</label>
        <type>Text</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableEnhancedLookup>true</enableEnhancedLookup><enableFeeds>false</enableFeeds><enableHistory>true</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Success Resource</label><nameField>
        <displayFormat>SR-{0}</displayFormat>
        <label>Success Resource ID</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Success Resources</pluralLabel><recordTypeTrackHistory>false</recordTypeTrackHistory><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>AgentID__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Primary_Email__c</columns>
        <columns>Primary_Phone__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Resource__c</columns>
        <columns>Role__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>UserId__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All_Resources_with_Details</fullName>
        <columns>NAME</columns>
        <columns>Success_Pod__c</columns>
        <columns>Resource__c</columns>
        <columns>IsActive__c</columns>
        <columns>CREATED_DATE</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <label>All Resources with Details</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Active_Advisors</fullName>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Role__c</columns>
        <columns>RECORDTYPE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Advisor</value>
        </filters>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
        </filters>
        <label>Success Resources - Active Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Advisors</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Committee_Code__c</columns>
        <columns>Success_Pod__c</columns>
        <filterScope>Everything</filterScope>
        <label>Success Resources - Advisors</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_Coaches</fullName>
        <columns>NAME</columns>
        <columns>IsActive__c</columns>
        <columns>Resource__c</columns>
        <columns>AgentID__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Role__c</columns>
        <columns>Program_Code__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <columns>CREATEDBY_USER</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <label>Success Resources - Coaches</label>
    </listViews><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Success_Resources_DelegatedCoaches</fullName>
        <columns>NAME</columns>
        <columns>Resource__c</columns>
        <columns>Delegated_Resource__c</columns>
        <columns>Plan_Code__c</columns>
        <columns>Military_Coach__c</columns>
        <columns>Success_Pod__c</columns>
        <columns>OWNER.ALIAS</columns>
        <columns>CREATED_DATE</columns>
        <filterScope>Everything</filterScope>
        <filters>
            <field>RECORDTYPE</field>
            <operation>equals</operation>
            <value>Success_Resource__c.Coach</value>
        </filters>
        <filters>
            <field>Delegated_Resource__c</field>
            <operation>notEqual</operation>
        </filters>
        <filters>
            <field>IsActive__c</field>
            <operation>equals</operation>
            <value>1</value>
        </filters>
        <label>Success Resources - DelegatedCoaches</label>
    </listViews><recordTypes>
        <fullName>Advisor</fullName>
        <active>true</active>
        <label>Advisor</label>
        
        
    </recordTypes></CustomObject>

force-app/main/default/objects/Success_Resource__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Person is available to be assigned Success Students</description>
    <label>Active Resource</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Success_Resource__c/fields/Resource__c.field-meta.xml
<CustomField>
    <fullName>Resource__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Coach's Name. Probable future use for other Portal Users.</description>
    <label>Resource</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Success_Resources</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AdvisorPortalFilterSavingService.cls
public class AdvisorPortalFilterSavingService {
    @AuraEnabled(cacheable=true)
    public static AdvisorPortalFilter getDefaultFilter() {
        AdvisorPortalFilter filter = null;
        List<Success_Resource__c> activeResources = [
            SELECT Default_Filter__c
            FROM Success_Resource__c
            WHERE Resource__c = :UserInfo.getUserId() AND IsActive__c = TRUE
        ];

        if (!activeResources.isEmpty()) {
            String json = activeResources[0].Default_Filter__c;

            if (String.isNotBlank(json)) {
                try {
                    filter = AdvisorPortalFilter.deserialize(json);
                    // and upgrade, since saved filter may be an older version of the filter object
                    filter.upgradeToMostRecentVersion();
                } catch (Exception ex) {
                    throw new AdvisorPortalFilterCannotGetDefaultCorruptedException(
                        'This user has a filter - but it\'s format is corrupted'
                    );
                }
            }
        }

        // If they don't have a saved filter, we should just apply some default values depending on the user's roles/access
        if (filter == null) {
            filter = new AdvisorPortalFilter();
        }

        // Default values
        if (String.isBlank(filter.caseTypeState))
            filter.caseTypeState = 'ProactiveCasesState';
        if (String.isBlank(filter.career))
            filter.career = 'UGRD';

        if (ProfileHelper.currentUserHasProfile('System Administrator')) {
            // Sys admin - leave it alone
        } else if (
            PermissionSetHelper.currentUserHasPermissionSet('Role_Academic_Advisor_Portal_Service_Users') &&
            PermissionSetHelper.currentUserHasPermissionSet('Role_Graduate_Academic_Advisor_Portal_Service_Users')
        ) {
            // Have both perms - leave it alone
        } else if (
            !PermissionSetHelper.currentUserHasPermissionSet('Role_Academic_Advisor_Portal_Service_Users') &&
            PermissionSetHelper.currentUserHasPermissionSet('Role_Graduate_Academic_Advisor_Portal_Service_Users')
        ) {
            // Only can access GRD - force it to GRD
            filter.career = 'GRD';
        } else if (
            !PermissionSetHelper.currentUserHasPermissionSet('Role_Graduate_Academic_Advisor_Portal_Service_Users') &&
            PermissionSetHelper.currentUserHasPermissionSet('Role_Academic_Advisor_Portal_Service_Users')
        ) {
            // Only can access UGRD - force it to UGRD
            filter.career = 'UGRD';
        } else {
            throw new AdvisorPortalFilterCannotGetDefaultPermissionsException(
                'The current user, userid=' +
                    UserInfo.getUserId() +
                    ' does not have the Role_Academic_Advisor_Portal_Service_Users or Role_Graduate_Academic_Advisor_Portal_Service_Users permission set. The advisor portal will not work properly without one of these permission sets.'
            );
        }

        return filter;
    }

    @AuraEnabled
    public static void setDefaultFilter(String json) {
        if (json.length() > Schema.SObjectType.Success_Resource__c.fields.Default_Filter__c.getLength()) {
            throw new AdvisorPortalFilterCannotSaveDefaultException(
                'Filter too large. Filter is ' +
                    json.length() +
                    ' bytes long, but it must be, at most ' +
                    Schema.SObjectType.Success_Resource__c.fields.Default_Filter__c.getLength() +
                    'bytes. Try selecting fewer filters.'
            );
        }
        List<Success_Resource__c> activeResources = [
            SELECT Id, Default_Filter__c
            FROM Success_Resource__c
            WHERE Resource__c = :UserInfo.getUserId() AND IsActive__c = TRUE
        ];
        for (Success_Resource__c sr : activeResources) {
            sr.Default_Filter__c = json;
        }
        if (!activeResources.isEmpty())
            update activeResources;
        else
            throw new AdvisorPortalFilterCannotSaveDefaultException(
                'This user doesn\'t have a success resource and can\'t use the save filters feature'
            );
    }

    @AuraEnabled
    public static void clearDefaultFilter() {
        List<Success_Resource__c> activeResources = [
            SELECT Id, Default_Filter__c
            FROM Success_Resource__c
            WHERE Resource__c = :UserInfo.getUserId() AND IsActive__c = TRUE
        ];
        for (Success_Resource__c sr : activeResources) {
            sr.Default_Filter__c = null;
        }
        if (!activeResources.isEmpty())
            update activeResources;
        else
            throw new AdvisorPortalFilterCannotSaveDefaultException(
                'This user doesn\'t have a success resource and can\'t use the save filters feature'
            );
    }

    public class AdvisorPortalFilterCannotSaveDefaultException extends Exception {
    }
    public class AdvisorPortalFilterCannotGetDefaultPermissionsException extends Exception {
    }
    public class AdvisorPortalFilterCannotGetDefaultCorruptedException extends Exception {
    }
}