src/objects/Territory_Assignment_Rule__c.object
<CustomObject><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Follow</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>List</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>New</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>SaveEdit</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>Tab</actionName>
        <type>Default</type>
    </actionOverrides><actionOverrides xmlns="http://soap.sforce.com/2006/04/metadata">
        <actionName>View</actionName>
        <type>Default</type>
    </actionOverrides><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_By_State__c</fullName>
        <label>Assignment By State</label>
        <picklist>
            <picklistValues>
                <fullName>Alabama</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alaska</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arizona</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arkansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armed Forces Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>California</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Colorado</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Connecticut</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Delaware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>District of Columbia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federated States of Micronesia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Florida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Georgia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Guam</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hawaii</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Idaho</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illinois</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Indiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Iowa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kansas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Kentucky</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Louisiana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marshall Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maryland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Massachusetts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Michigan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Minnesota</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mississippi</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Assignment_by_Country__c</fullName>
        <description>For International Territory Assignment</description>
        <label>Assignment by Country</label>
        <picklist>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aland Islands</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antarctica</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia, Plurinational State of</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bonaire, Sint Eustatius and Saba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia and Herzegovina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bouvet Island</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Campus__c</fullName>
        <label>Campus</label>
        <picklist>
            <picklistValues>
                <fullName>Downtown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tempe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Defer_Territory_Assignment__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer Territory Assignment</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Geomarket__c</fullName>
        <label>Geomarket</label>
        <length>10</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>International__c</fullName>
        <defaultValue>false</defaultValue>
        <label>International</label>
        <type>Checkbox</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Lake Havasu</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>National_Scholarship__c</fullName>
        <label>National Scholarship</label>
        <picklist>
            <picklistValues>
                <fullName>National Achievement Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Achievement Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Hispanic Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Finalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>National Merit Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gammage Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Designate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Semifinalist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Flinn Finalist</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Opportunity_Type__c</fullName>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Graduate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Law</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>First Time Freshman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Non-Degree</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Readmission</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Previous_User_ID__c</fullName>
        <label>Previous User ID</label>
        <length>18</length>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_End__c</fullName>
        <inlineHelpText>Based on opportunities numbered 1-100, opportunities will be assigned ending at this number (MAX = 100)</inlineHelpText>
        <label>Range End</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Range_Start__c</fullName>
        <description>Based on opportunities numbered 1-100, opportunities in countries that are split will be assigned starting at this number.</description>
        <label>Range Start</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Key__c</fullName>
        <formula>If (TEXT(Rule_Type__c) = 'Freshman Scholar',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International Admitted - Conditional',TEXT(Rule_Type__c), 
If (TEXT(Rule_Type__c) = 'International',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_by_Country__c), 
If (TEXT(Rule_Type__c) = 'Location',TEXT(Rule_Type__c)+'|'+TEXT(Location__c), 
If (TEXT(Rule_Type__c) = 'Geomarket',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + Geomarket__c, 
If (TEXT(Rule_Type__c) = 'State',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c) + '|' + TEXT(Assignment_By_State__c), 
If (TEXT(Rule_Type__c) = 'Default User',TEXT(Rule_Type__c)+'|'+TEXT(Opportunity_Type__c),'') 
))))))</formula>
        <label>Rule Key</label>
        <type>Text</type>
    </fields><fields xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>Rule_Type__c</fullName>
        <label>Rule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Freshman Scholar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Location</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geomarket</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Default User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International Admitted - Conditional</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields><fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Assign to?</inlineHelpText>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Auto_Territory_Assignment_Rules</relationshipName>
        <type>Lookup</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>This object is used to define the rules for recruitment auto territory assignment.</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>true</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>ReadWrite</externalSharingModel><label>Territory Assignment Rule</label><nameField>
        <displayFormat>Rule-{0000}</displayFormat>
        <label>Auto Territory Assignment Rule Name</label>
        <type>AutoNumber</type>
    </nameField><pluralLabel>Territory Assignment Rules</pluralLabel><sharingModel>ReadWrite</sharingModel><listViews xmlns="http://soap.sforce.com/2006/04/metadata">
        <fullName>All</fullName>
        <columns>NAME</columns>
        <columns>Opportunity_Type__c</columns>
        <columns>Rule_Type__c</columns>
        <columns>User__c</columns>
        <columns>Assignment_by_Country__c</columns>
        <columns>Assignment_By_State__c</columns>
        <columns>Campus__c</columns>
        <columns>Defer_Territory_Assignment__c</columns>
        <columns>Geomarket__c</columns>
        <columns>International__c</columns>
        <columns>Location__c</columns>
        <columns>National_Scholarship__c</columns>
        <filterScope>Everything</filterScope>
        <label>All</label>
    </listViews></CustomObject>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Defer_Territory_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Defer_Territory_Assignment__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Defer Territory Assignment</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Territory_Assignment_Rule__c/fields/Previous_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Previous_User_ID__c</fullName>
    <label>Previous User ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TerritoryAssignmentRule.cls
public without sharing class TerritoryAssignmentRule {
    public static Boolean assignTerritoryDone = false;

    public void assignTerritory() {
        if (assignTerritoryDone) {
            return;
        }

        if (Trigger.isBefore && Trigger.isUpdate) {
            Map<ID, Territory_Assignment_Rule__c> tarOldMap = (Map<ID, Territory_Assignment_Rule__c>) Trigger.oldMap;

            for (Territory_Assignment_Rule__c tar : (List<Territory_Assignment_Rule__c>) Trigger.New) {
                if (tar.User__c != null && tarOldMap.get(tar.Id).User__c != tar.User__c) {
                    tar.Defer_Territory_Assignment__c = true;
                    tar.Previous_User_ID__c = tarOldMap.get(tar.Id).User__c;
                }
            }
        }

        assignTerritoryDone = true;
    }
}