force-app/main/default/objects/Object_Tag__c/Object_Tag__c.object-meta.xml
<CustomObject>
    <description>The object provides information on the tags that are associated with various objects.</description>
    <label>Object Tag</label>
    <nameField>
        <label>Object Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Object Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Tag__c/fields/Tag__c.field-meta.xml
<CustomField>
    <fullName>Tag__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field is a Look-up to Tag that the object tag is for.</description>
    <inlineHelpText>This field is a Look-up to Tag that the object tag is for.</inlineHelpText>
    <label>Tag</label>
    <referenceTo>Tag__c</referenceTo>
    <relationshipLabel>Contact Tags</relationshipLabel>
    <relationshipName>Contact_Tags</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tag__c/Tag__c.object-meta.xml
<CustomObject>
    <description>[Alteryx/Manual] - Provides list on the tag that are available to apply to Contacts and other objects.</description>
    <label>Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tags</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/TagBatchUpdateRecordType.cls
public class TagBatchUpdateRecordType implements Database.Batchable<sObject> {
    public final String QUERY;
    public final String RTID;

    public TagBatchUpdateRecordType(String newRecordType, Id tagId) {
        QUERY = 'SELECT Id FROM Object_Tag__c WHERE Tag__c = \'' + tagId + '\'';
        RTID = (String) Schema.SObjectType.Object_Tag__c.getRecordTypeInfosByDeveloperName()
            .get(newRecordType)
            .getRecordTypeId();
    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<Object_Tag__c> objectTagsToUpdate = (List<Object_Tag__c>) scope;

        for (Object_Tag__c ot : objectTagsToUpdate) {
            ot.RecordTypeId = RTID;
        }

        update scope;
    }

    public void finish(Database.BatchableContext BC) {
    }
}