force-app/main/default/objects/ASU_Alert_Messages__mdt/ASU_Alert_Messages__mdt.object-meta.xml
<CustomObject>
    <description>Configurable messages that can display alerts at the top of various pages.

Currently on used on the Help Tab</description>
    <label>ASU Alert Messages</label>
    <pluralLabel>ASU Alert Messages</pluralLabel>
</CustomObject>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Display_Message__c.field-meta.xml
<CustomField>
    <fullName>Display_Message__c</fullName>
    <businessOwnerGroup>Data_Owner_SSI</businessOwnerGroup>
    <description>The message that will be displayed on the page</description>
    <inlineHelpText>The message that will be displayed on the page.</inlineHelpText>
    <label>Display_Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/End_Time__c.field-meta.xml
<CustomField>
    <fullName>End_Time__c</fullName>
    <description>The end time for the message to be displayed.</description>
    <inlineHelpText>The end time for the message to be displayed.</inlineHelpText>
    <label>End Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Is_Active__c.field-meta.xml
<CustomField>
    <fullName>Is_Active__c</fullName>
    <businessOwnerGroup>Data_Owner_SSI</businessOwnerGroup>
    <defaultValue>false</defaultValue>
    <description>Whether the message will display or not</description>
    <inlineHelpText>Include or exclude message from display. Check to Include the message</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <businessOwnerGroup>Data_Owner_SSI</businessOwnerGroup>
    <description>The display order for the messages</description>
    <inlineHelpText>Enter a number for priority sorting. Message with the lower number will sort higher on the page.</inlineHelpText>
    <label>Priority</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Start_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Time__c</fullName>
    <description>The start time for the message to be displayed.</description>
    <inlineHelpText>The start time for the message to be displayed.</inlineHelpText>
    <label>Start Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <description>Title of alert. This is shown in bold before the main body of the alert.</description>
    <inlineHelpText>Title of alert. This is shown in bold before the main body of the alert.</inlineHelpText>
    <label>Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <businessOwnerGroup>Data_Owner_SSI</businessOwnerGroup>
    <defaultValue>"warning"</defaultValue>
    <description>What type of alert message to show?  This controls the background color and icon for the alert.</description>
    <inlineHelpText>This controls the background color and icon for the alert. Warning = Orange background with a message bell icon; Info = Blue background with a info icon; Fatal = Red background with a error triangle icon; Confirm = Green background with a check mark icon; None = Orange background with a message bell icon.</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>warning</fullName>
                <default>true</default>
                <label>warning</label>
            </value>
            <value>
                <fullName>info</fullName>
            </value>
            <value>
                <fullName>fatal</fullName>
            </value>
            <value>
                <fullName>confirm</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ASU_Alert_Messages__mdt/fields/Url__c.field-meta.xml
<CustomField>
    <fullName>Url__c</fullName>
    <businessOwnerGroup>Data_Owner_SSI</businessOwnerGroup>
    <description>A url to link people to in the message</description>
    <inlineHelpText>Optional Url for detailed information; Make sure to include http://</inlineHelpText>
    <label>Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case.object
<CustomObject>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Ed_Plus</businessOwnerGroup>
    <description>Lookup to the Contact EMPLID
[DW: sfe_case]</description>
    <formula>Contact.EMPLID__c</formula>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/objects/Case_Classification__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <description>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</description>
        <inlineHelpText>If marked true, this record will be available for use on cases. If marked false, this record cannot be used for case creation or edits.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <description>An object used for classifying cases for some fields such as Functional Group, Category and Sub Category.</description>
    <label>Case Classification</label>
    <nameField>
        <label>Case Classification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Case Classifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <label>Category</label>
    </recordTypes>
</CustomObject>

force-app/main/default/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ASURite_ID__c</fullName>
        <description>[Peoplesoft] - Student alias; also used for student email account</description>
        <label>ASURITE ID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>EMPLID__c</fullName>
        <description>[Peoplesoft] - PeopleSoft unique ID</description>
        <externalId>true</externalId>
        <label>EMPLID</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/Live_Agent_Button_Setting__mdt.object-meta.xml
<CustomObject>
    <description>These records map the live agent buttons in our org to the necessary chat endpoint, org id, and deployment id.

They also are able to be shown in the MyASU Help Tab, and when used in the Help Tab, can be configured to send the user to a chatbot rather than starting a conversation with a live agent.</description>
    <label>Live Agent Button Setting</label>
    <pluralLabel>Live Agent Button Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Chat_Button_Id__c.field-meta.xml
<CustomField>
    <fullName>Chat_Button_Id__c</fullName>
    <description>Button Id for specific Chat</description>
    <inlineHelpText>Button Id for specific Chat</inlineHelpText>
    <label>Chat Button Id</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Chat_Deployment__c.field-meta.xml
<CustomField>
    <fullName>Chat_Deployment__c</fullName>
    <description>The unique ID of your Chat deployment. To get this value, from Setup, select Chat | Deployments. The script at the bottom of the page contains a call to the liveagent.init function with the pod, the deploymentId, and orgId as arguments. Copy the deploymentId value.</description>
    <inlineHelpText>The unique ID of your Chat deployment. To get this value, from Setup, select Chat | Deployments. The script at the bottom of the page contains a call to the liveagent.init function with the pod, the deploymentId, and orgId as arguments. Copy the deploymentId value.</inlineHelpText>
    <label>Chat Deployment</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Chat_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Chat_Endpoint__c</fullName>
    <description>The hostname for the Chat endpoint that your organization has been assigned. To get this value, from Setup, search for Chat Settings and copy the hostname from the API Endpoint.</description>
    <inlineHelpText>The hostname for the Chat endpoint that your organization has been assigned. To get this value, from Setup, search for Chat Settings and copy the hostname from the API Endpoint.</inlineHelpText>
    <label>Chat Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Chatbot_URL__c.field-meta.xml
<CustomField>
    <fullName>Chatbot_URL__c</fullName>
    <description>This is used when this button is display on the Help tab.  When a user clicks on this button, they are sent to the chatbot rather than starting a live agent chat with a person.</description>
    <inlineHelpText>This is used when this button is display on the Help tab.  When a user clicks on this button, they are sent to the chatbot rather than starting a live agent chat with a person.</inlineHelpText>
    <label>Chatbot URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <description>When shown on the MyASU Help Tab, this control the order the buttons appear in.  Lower numbers appear first.</description>
    <inlineHelpText>When shown on the MyASU Help Tab, this control the order the buttons appear in.  Lower numbers appear first.</inlineHelpText>
    <label>Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Org_Id__c.field-meta.xml
<CustomField>
    <fullName>Org_Id__c</fullName>
    <description>The Salesforce org ID. To get this value, from Setup, search for Company Information and copy the Salesforce Organization ID.</description>
    <inlineHelpText>The Salesforce org ID. To get this value, from Setup, search for Company Information and copy the Salesforce Organization ID.</inlineHelpText>
    <label>Org Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Live_Agent_Button_Setting__mdt/fields/Show_on_Help_Tab__c.field-meta.xml
<CustomField>
    <fullName>Show_on_Help_Tab__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Controls whether this button appears on the MyASU Help Tab.</description>
    <inlineHelpText>Controls whether this button appears on the MyASU Help Tab.</inlineHelpText>
    <label>Show on Help Tab</label>
    <type>Checkbox</type>
</CustomField>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Term__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>[peoplesoft] - Picklist with the term</description>
        <label>Term</label>
        <referenceTo>Term__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/EMPLID__c.field-meta.xml
<CustomField>
    <fullName>EMPLID__c</fullName>
    <businessOwnerGroup>Data_Owner_Campus_Community</businessOwnerGroup>
    <complianceGroup>FERPA</complianceGroup>
    <description>Lookup to the EMPLID in the Contact Object
[Peoplesoft] - PeopleSoft unique ID
[MDM] - Read/Write - Critical to MDM
[DW: sfe_contact]</description>
    <formula>Contact__r.EMPLID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>EMPLID</inlineHelpText>
    <label>EMPLID</label>
    <type>Text</type>
</CustomField>

src/objects/Term__c.object
<CustomObject><fields>
        <fullName>Session_A_C_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin</description>
        <label>Session A/C Start Date</label>
        <type>Date</type>
    </fields><fields>
        <fullName>Session_B_Start_Date__c</fullName>
        <description>[Peoplesoft] - Day classes begin for Session B</description>
        <label>Session B Start Date</label>
        <type>Date</type>
    </fields><allowInChatterGroups>false</allowInChatterGroups><compactLayoutAssignment>SYSTEM</compactLayoutAssignment><deploymentStatus>Deployed</deploymentStatus><description>Academic term</description><enableActivities>false</enableActivities><enableBulkApi>true</enableBulkApi><enableFeeds>false</enableFeeds><enableHistory>false</enableHistory><enableReports>false</enableReports><enableSearch>true</enableSearch><enableSharing>true</enableSharing><enableStreamingApi>true</enableStreamingApi><externalSharingModel>Private</externalSharingModel><label>Term</label><nameField>
        <label>Term Name</label>
        <type>Text</type>
    </nameField><pluralLabel>Terms</pluralLabel><sharingModel>Read</sharingModel></CustomObject>

force-app/main/default/objects/User.object
<CustomObject>
    <fields>
        <fullName>ASURITE_Id__c</fullName>
        <description>[??] - ASURITE ID</description>
        <formula>Contact.ASURite_ID__c</formula>
        <label>ASURITE Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmplId__c</fullName>
        <description>[PeopleSoft] - EMPLID</description>
        <formula>Contact.EMPLID__c</formula>
        <label>EMPLID</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/MyASUHelpController.cls
public with sharing class MyASUHelpController {
    public String siteTitleName { get; set; }
    public String siteTitleUrl { get; set; }
    private static final Date EMAILVISIBILITYDATE = Date.newInstance(2015, 4, 6);
    private Id caseId;
    private Date today;
    private Term__c termcAC;
    private Term__c termcB;
    public AlertHandler alertHandler { get; set; } // Use the custom alerting component
    private MyASUHelpViewAsService viewAsService;
    public List<Opportunity> oppList;
    public Boolean viewingAs { get; set; }
    public Case suggestAnArticle { get; set; }
    public String suggestedArticleDescription { get; set; }
    public Case newCase { get; set; }

    public Contact userContact;
    public String firstName { get; set; }
    public String lastName { get; set; }
    public String emplId { get; set; }
    public String masqScopeIdCookie { get; set; }
    public String stopViewAsUrl { get; set; }
    public String viewAsUrl { get; set; }
    public String asurite { get; set; }
    public String userAsurite;

    public String functionalGroup { get; set; }
    public Boolean isSearchingWithFunctionalGroup { get; set; }
    public List<FAQ__kav> allFinancialArticles;
    public List<FAQ__kav> topThreeFinancialArticles;
    public List<FAQ__kav> allTechnicalArticles;
    public List<FAQ__kav> topThreeTechnicalArticles;
    public List<FAQ__kav> allHousingArticles;
    public List<FAQ__kav> topThreeHousingArticles;
    public String viewAllArticlesUrl;
    public String viewAllFinanceArticlesUrl;
    public String viewAllTechnicalArticlesUrl;
    public String viewAllHousingArticlesUrl;

    public String orgId { get; set; }
    public String chatEndpoint { get; set; }
    public String scriptEndpointUrl { get; set; }
    public String deploymentId { get; set; }
    public List<Live_Agent_Button_Setting__mdt> livechatButtons { get; set; }
    @TestVisible
    private static List<Live_Agent_Button_Setting__mdt> TEST_BUTTONS;

    public MyASUHelpController() {
        setSiteTitleInformation();
        instantiateControllerVariables();
        setLiveAgentSettings();

        checkForViewAs();
        popUserContact();
        popTerms();

        checkForFunctionalGroup();
        setAllFinancialArticles();
        setAllTechnicalArticles();
        setAllHousingArticles();
        setViewAllArticlesLinks();
    }

    private void setSiteTitleInformation() {
        siteTitleName = 'My ASU';
        siteTitleUrl = System.Label.MyASU_Help_Base_URL + '/myasu/student';
    }

    private void instantiateControllerVariables() {
        suggestAnArticle = new Case();
        newCase = new Case();
        viewingAs = false;
        functionalGroup = null;
        isSearchingWithFunctionalGroup = false;
        alertHandler = new AlertHandler();
        loadStudentSCAlerts(); // Do before standard alerts to appear above standard alerts
        alertHandler.loadStandardAlertsFromMap(ApexPages.currentPage().getParameters());
    }

    private void loadStudentSCAlerts() {
        // Only loaded on studentSC page
        if (ApexPages.currentPage().getUrl().toLowerCase().contains(Page.studentSC.getUrl().toLowerCase())) {
            List<ASU_Alert_Messages__mdt> alertMessages;

            if (CustomMetadataHelper.isNotTest()) {
                alertMessages = [
                    SELECT Display_Message__c, Url__c, Priority__c, Type__c, Title__c, Start_Time__c, End_Time__c
                    FROM ASU_Alert_Messages__mdt
                    WHERE Is_Active__c = TRUE
                    ORDER BY Priority__c
                ];
            } else {
                alertMessages = (List<ASU_Alert_Messages__mdt>) CustomMetadataHelper.getFakeRecords(
                    'ASU_Alert_Messages__mdt$$ASUHelpTab$$Active'
                );
            }

            processAlerts(alertMessages);
        }
    }

    private void processAlerts(List<ASU_Alert_Messages__mdt> alertMessages) {
        for (ASU_Alert_Messages__mdt message : alertMessages) {
            // If has not started yet or if has already ended - then skip
            // this cannot be part of the SOQL query due to SF not supporting OR disjunctions for custom metadata
            if (message.Start_Time__c != null && message.Start_Time__c > System.now())
                continue;
            if (message.End_Time__c != null && message.End_Time__c < System.now())
                continue;

            // Setup required fields
            String alertType = customAlert.WARNING;
            String alertTitle = message.Title__c != null ? message.Title__c : ' ';
            String alertMessage = message.Display_Message__c;
            String alertUrl = message.Url__c;

            // Set the message type
            if (message.Type__c != null) {
                if (message.Type__c.equalsIgnoreCase(customAlert.FATAL))
                    alertType = customAlert.FATAL;
                else if (message.Type__c.equalsIgnoreCase(customAlert.INFO))
                    alertType = customAlert.INFO;
                else if (message.Type__c.equalsIgnoreCase(customAlert.WARNING))
                    alertType = customAlert.WARNING;
                else if (message.Type__c.equalsIgnoreCase(customAlert.CONFIRM))
                    alertType = customAlert.CONFIRM;
            }

            // Add the alert to the list
            alertHandler.newAlert(alertType, alertTitle, alertMessage, alertUrl);
        }
    }

    private void setLiveAgentSettings() {
        // Get all chat buttons
        livechatButtons = [
            SELECT
                Label,
                DeveloperName,
                Chat_Button_Id__c,
                Chat_Deployment__c,
                Chat_Endpoint__c,
                Org_Id__c,
                Chatbot_URL__c,
                Order__c
            FROM Live_Agent_Button_Setting__mdt
            WHERE Show_on_Help_Tab__c = TRUE
            ORDER BY Order__c ASC
        ];

        // Test override
        if (Test.isRunningTest() && TEST_BUTTONS != null)
            livechatButtons = TEST_BUTTONS;

        // Handle when all are disabled
        if (livechatButtons.isEmpty()) {
            orgId = '';
            chatEndpoint = '';
            scriptEndpointUrl = '';
            deploymentId = '';
            return;
        }

        // Get common scripts/metadata
        orgId = livechatButtons[0].Org_Id__c;
        chatEndpoint = livechatButtons[0].Chat_Endpoint__c;
        scriptEndpointUrl = chatEndpoint.replace('https://d', 'https://c').replace('/chat', '');
        deploymentId = livechatButtons[0].Chat_Deployment__c;
    }

    public void checkForViewAs() {
        if (
            ApexPages.currentPage().getParameters().get('masqScopeIdCookie') != null &&
            ApexPages.currentPage().getParameters().get('masqScopeIdCookie') != ''
        ) {
            masqScopeIdCookie = ApexPages.currentPage().getParameters().get('masqScopeIdCookie');
            userAsurite = [SELECT ASURite_Id__c FROM User WHERE Id = :UserInfo.getUserId()].ASURite_Id__c;

            viewAsService = new MyASUHelpViewAsService(masqScopeIdCookie, userAsurite);
        } else {
            viewingAs = false;
        }
    }

    public void checkForFunctionalGroup() {
        if (ApexPages.currentPage().getParameters().get('category') != null) {
            String functionalGroupKey = ApexPages.currentPage().getParameters().get('category');
            if (functionalGroupKey.equals('finance')) {
                functionalGroup = 'Financial Aid';
            } else if (functionalGroupKey.equals('technical')) {
                functionalGroup = '%Technical Resources%';
            } else if (functionalGroupKey.equals('housing')) {
                functionalGroup = 'Housing';
            }

            if (functionalGroup != null) {
                isSearchingWithFunctionalGroup = true;
            }
        }
    }

    public void popUserContact() {
        if (viewAsService != null && viewAsService.hasViewAsRights) {
            userContact = viewAsService.getContact(viewAsService.getResponseValueFromMap('effectiveAsurite'));
            stopViewAsUrl = viewAsService.getResponseValueFromMap('stopViewAsUrl');
            viewAsUrl = viewAsService.getResponseValueFromMap('viewAsUrl');
            viewingAs = true;
        } else {
            userContact = ContactService.getLoggedInContact();
        }
        firstName = userContact.FirstName;
        lastName = userContact.LastName;
        emplId = userContact.EMPLID__c;
        asurite = userContact.ASURite_ID__c;
    }

    public void popTerms() {
        today = date.today();

        termcAC = [
            SELECT Session_A_C_Start_Date__c
            FROM Term__c
            WHERE session_A_C_Start_Date__c > :System.today()
            LIMIT 1
        ];

        termcB = [SELECT Session_B_Start_Date__c FROM Term__c WHERE session_B_Start_Date__c > :System.today() LIMIT 1];

        oppList = [
            SELECT Career__c, Term__c, StageName, Admitted_Session__c
            FROM Opportunity
            WHERE Contact__c = :userContact.Id
        ];
    }

    private void setAllFinancialArticles() {
        allFinancialArticles = [
            SELECT Id, Functional_Group__c, KnowledgeArticleId, Title, UrlName
            FROM FAQ__kav
            WHERE IsDeleted = FALSE AND PublishStatus = 'Online' AND Functional_Group__c = 'Financial Aid'
            ORDER BY ArticleTotalViewCount DESC
            LIMIT 200
        ];
        topThreeFinancialArticles = new List<FAQ__kav>();

        if (allFinancialArticles != null && !allFinancialArticles.isEmpty()) {
            if (allFinancialArticles[0].Id != null) {
                topThreeFinancialArticles.add(allFinancialArticles[0]);
            }
            if (allFinancialArticles[1].Id != null) {
                topThreeFinancialArticles.add(allFinancialArticles[1]);
            }
            if (allFinancialArticles[2].Id != null) {
                topThreeFinancialArticles.add(allFinancialArticles[2]);
            }
        }
    }

    public List<FAQ__kav> getAllFinancialArticles() {
        return allFinancialArticles;
    }

    public List<FAQ__kav> getTopThreeFinancialArticles() {
        return topThreeFinancialArticles;
    }

    private void setAllTechnicalArticles() {
        allTechnicalArticles = [
            SELECT Id, Functional_Group__c, KnowledgeArticleId, Title, UrlName
            FROM FAQ__kav
            WHERE IsDeleted = FALSE AND PublishStatus = 'Online' AND Functional_Group__c LIKE '%Technical Resources%'
            ORDER BY ArticleTotalViewCount DESC
            LIMIT 200
        ];
        topThreeTechnicalArticles = new List<FAQ__kav>();

        if (allTechnicalArticles != null && !allTechnicalArticles.isEmpty()) {
            if (allTechnicalArticles[0].Id != null) {
                topThreeTechnicalArticles.add(allTechnicalArticles[0]);
            }
            if (allTechnicalArticles[1].Id != null) {
                topThreeTechnicalArticles.add(allTechnicalArticles[1]);
            }
            if (allTechnicalArticles[2].Id != null) {
                topThreeTechnicalArticles.add(allTechnicalArticles[2]);
            }
        }
    }

    public List<FAQ__kav> getAllTechnicalArticles() {
        return allTechnicalArticles;
    }

    public List<FAQ__kav> getTopThreeTechnicalArticles() {
        return topThreeTechnicalArticles;
    }

    private void setAllHousingArticles() {
        allHousingArticles = [
            SELECT Id, Functional_Group__c, KnowledgeArticleId, Title, UrlName
            FROM FAQ__kav
            WHERE IsDeleted = FALSE AND PublishStatus = 'Online' AND Functional_Group__c = 'Housing'
            ORDER BY ArticleTotalViewCount DESC
            LIMIT 200
        ];
        topThreeHousingArticles = new List<FAQ__kav>();

        if (allHousingArticles != null && !allHousingArticles.isEmpty()) {
            if (allHousingArticles[0].Id != null) {
                topThreeHousingArticles.add(allHousingArticles[0]);
            }
            if (allHousingArticles[1].Id != null) {
                topThreeHousingArticles.add(allHousingArticles[1]);
            }
            if (allHousingArticles[2].Id != null) {
                topThreeHousingArticles.add(allHousingArticles[2]);
            }
        }
    }

    public List<FAQ__kav> getAllHousingArticles() {
        return allHousingArticles;
    }

    public List<FAQ__kav> getTopThreeHousingArticles() {
        return topThreeHousingArticles;
    }

    public String getViewAllArticlesLink() {
        return viewAllArticlesUrl;
    }

    private void setViewAllArticlesLinks() {
        viewAllArticlesUrl = '/viewAllArticles';
        viewAllFinanceArticlesUrl = viewAllArticlesUrl + '?category=finance';
        viewAllTechnicalArticlesUrl = viewAllArticlesUrl + '?category=technical';
        viewAllHousingArticlesUrl = viewAllArticlesUrl + '?category=housing';
    }

    public String getViewAllFinancialArticlesLink() {
        return viewAllFinanceArticlesUrl;
    }

    public String getViewAllTechnicalArticlesLink() {
        return viewAllTechnicalArticlesUrl;
    }

    public String getViewAllHousingArticlesLink() {
        return viewAllHousingArticlesUrl;
    }

    public PageReference suggestAnArticleSubmit() {
        if (viewingAs) {
            PageReference go = new PageReference(ApexPages.currentPage().getUrl());
            go.getParameters().put('masqScopeIdCookie', masqScopeIdCookie);
            go.setRedirect(true);
            return go;
        }

        suggestAnArticle.Subject = 'Suggest An Article';
        if (suggestedArticleDescription != null) {
            suggestAnArticle.Description = suggestedArticleDescription;
        }
        suggestAnArticle.ContactId = userContact.Id;

        List<Case_Classification__c> funcGroupList;
        funcGroupList = [
            SELECT Id
            FROM Case_Classification__c
            WHERE RecordType.Name = 'Functional Group' AND Active__c = TRUE AND Name = 'Student Success Innovations'
            LIMIT 1
        ];
        if (!funcGroupList.isEmpty() && funcGroupList[0].Id != null) {
            suggestAnArticle.CC_Functional_Group__c = funcGroupList[0].Id;
        }

        List<Case_Classification__c> catList;
        catList = [
            SELECT Id
            FROM Case_Classification__c
            WHERE
                RecordType.Name = 'Category'
                AND Active__c = TRUE
                AND Name = 'Knowledge'
                AND Parent__c = :suggestAnArticle.CC_Functional_Group__c
            LIMIT 1
        ];
        if (!catList.isEmpty() && catList[0].Id != null) {
            suggestAnArticle.CC_Category__c = catList[0].Id;
        }

        suggestAnArticle.Origin__c = 'My ASU';
        suggestAnArticle.Visible_by_Contact__c = false;
        suggestAnArticle.OwnerId = [
            SELECT Id
            FROM Group
            WHERE Name = 'Student Success Innovations (Case)' AND Type = 'Queue'
        ]
        .Id;

        insert suggestAnArticle;

        return redirectWithParams(ApexPages.currentPage(), 'Suggest', 'yes');
    }

    public String getSource() {
        String source = ApexPages.currentPage().getParameters().get('source');

        if (source == null) {
            source = 'studentSC';
        } else if (source.equals('viewAllCases')) {
            source = 'viewAllCases?source=studentSC';
        }

        return source;
    }

    public Boolean getNormalPhone() {
        return (userContact.CAP__c == null) ? true : false;
    }

    public Boolean getRoverPhone() {
        return (userContact.CAP__c != null) ? true : false;
    }

    public Boolean getHelpBox() {
        if ((oppList == null && userContact != null) || (oppList.size() == 0 && userContact != null)) {
            return true;
        } else if (
            (oppList[0].StageName == 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            oppList[0].Admitted_Session__c == 'A/C') && today < date.valueOf(termcAC.Session_A_C_Start_Date__c)
        ) {
            return false;
        } else if (
            (oppList[0].StageName == 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            oppList[0].Admitted_Session__c == 'B') && today < date.valueOf(termcB.Session_B_Start_Date__c)
        ) {
            return false;
        } else if (
            oppList[0].StageName != 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            (userContact.Affiliation_Student__c == 'Current' ||
            userContact.Affiliation_Alumni__c == 'Current' ||
            userContact.Affiliation_Courtesy_Affiliate__c == 'Current' ||
            userContact.Affiliation_Employee__c == 'Current') &&
            today < date.valueOf(termcB.Session_B_Start_Date__c)
        ) {
            return false;
        } else {
            return true;
        }
    }

    public List<Case> getMyCases() {
        List<Contact> contacts = new List<Contact>{ userContact };
        Map<Id, List<Case>> openCaseMap;
        if (viewAsService != null) {
            openCaseMap = viewAsService.getOpenCases(contacts, 5);
        } else {
            openCaseMap = CaseService.getVisibleOpenCases(contacts, 5);
        }

        return (openCaseMap.get(userContact.Id) == null) ? new List<Case>() : openCaseMap.get(userContact.Id);
    }

    public List<Case> getClosedCases() {
        List<Case> closedCases = new List<Case>();
        List<Contact> contacts = new List<Contact>{ userContact };
        Map<Id, List<Case>> closedCaseMap;

        if (viewAsService != null) {
            closedCaseMap = viewAsService.getClosedCases(contacts, 5);
        } else {
            closedCaseMap = CaseService.getVisibleClosedCases(contacts, 5);
        }

        return (closedCaseMap.get(userContact.Id) == null) ? new List<Case>() : closedCaseMap.get(userContact.Id);
    }

    public Boolean getMyCasesBox() {
        if ((oppList == null && userContact != null) || (oppList.size() == 0 && userContact != null)) {
            return true;
        } else if (
            (oppList[0].StageName == 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            oppList[0].Admitted_Session__c == 'A/C') && today < date.valueOf(termcAC.Session_A_C_Start_Date__c)
        ) {
            return false;
        } else if (
            (oppList[0].StageName == 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            oppList[0].Admitted_Session__c == 'B') && today < date.valueOf(termcB.Session_B_Start_Date__c)
        ) {
            return false;
        } else if (
            oppList[0].StageName != 'Enrolled' &&
            oppList[0].Career__c == 'Undergraduate' &&
            (userContact.Affiliation_Student__c == 'Current' ||
            userContact.Affiliation_Alumni__c == 'Current' ||
            userContact.Affiliation_Courtesy_Affiliate__c == 'Current' ||
            userContact.Affiliation_Employee__c == 'Current') &&
            today < date.valueOf(termcB.Session_B_Start_Date__c)
        ) {
            return false;
        } else {
            return true;
        }
    }

    public PageReference redirectWithParams(PageReference page, String param, String value) {
        PageReference redirect = page;
        redirect.getParameters().put(param, value);
        redirect.setRedirect(true);
        return redirect;
    }

    public PageReference viewCase() {
        caseId = ApexPages.currentPage().getParameters().get('caseId');
        String current = ApexPages.currentPage().getUrl();
        current = current.split('apex/')[1];
        PageReference viewCasePage = new PageReference('/viewcase');
        viewCasePage.getParameters().put('id', caseId);
        viewCasePage.getParameters().put('source', current);

        if (viewingAs) {
            viewCasePage.getParameters().put('masqScopeIdCookie', masqScopeIdCookie);
        }

        return viewCasePage;
    }

    public PageReference submitCase() {
        Boolean isCaseCreated = true;
        PageReference confirmPage;
        if (viewingAs) {
            PageReference go = new PageReference(ApexPages.currentPage().getUrl());
            go.getParameters().put('masqScopeIdCookie', masqScopeIdCookie);
            go.setRedirect(true);
            return go;
        }

        Case createdCase = MyASUHelpEmailService.submitCase(newCase, userContact);

        if (createdCase.Id != null) {
            ApexPages.currentPage().getParameters().put('caseId', newCase.Id);
            confirmPage = viewCase();
            confirmPage.setRedirect(true);
            return confirmPage;
        } else {
            return null;
        }
    }
}